tier4/autoware_universe

planning/behavior_velocity_crosswalk_module/CMakeLists.txt, planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_crosswalk_module/package.xml, planning/behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_crosswalk_module/src/occluded_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/occluded_crosswalk.hpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6122 (not merged yet).
=> feat(crosswalk): add option to slowdown at occluded crosswalks (#6122)

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml, planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml, planning/behavior_velocity_planner/package.xml, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/src/node.hpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/util.hpp, planning/behavior_velocity_planner_common/package.xml, planning/behavior_velocity_traffic_light_module/config/traffic_light.param.yaml, planning/behavior_velocity_traffic_light_module/src/manager.cpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp, planning/behavior_velocity_traffic_light_module/src/scene.hpp
Cherry-pick these commits to use the remaining time information from V2I in planning module.
- https://github.com/tier4/autoware.universe/pull/941
- https://github.com/tier4/autoware.universe/pull/1030
- https://github.com/tier4/autoware.universe/pull/1083
Conducted tests in simple planning simulator.
https://github.com/tier4/autoware.universe/assets/11865769/c3cbe150-b4c0-41f1-a56f-1daaec168079
In this situation, stop point is inserted though the signal is GREEN. This is because the planning module uses the remaining time information from V2I.
After all checkboxes are …
=> feat(behavior_velocity_planner.traffic_light): use v2i in planning

sensing/pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp
* fix: blockage_range_angle bug
* chore: refactor
* Revert "chore: refactor"
This reverts commit fc430946f1a9075bee36402a36180965e3b028a1.
---------
- Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6445
=> fix(blockage_diag): output blockage angle range bug fix (#6445)

perception/multi_object_tracker/include/multi_object_tracker/tracker/model/bicycle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/big_vehicle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/normal_vehicle_tracker.hpp, perception/multi_object_tracker/models.md, perception/multi_object_tracker/src/data_association/data_association.cpp, perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp, perception/tracking_object_merger/src/utils/utils.cpp
cherry-picks of multi_object_tracking
https://github.com/autowarefoundation/autoware.universe/pull/6082
https://github.com/autowarefoundation/autoware.universe/pull/6337
https://github.com/autowarefoundation/autoware.universe/pull/6343
cherry-pick of tracking_object_merger
https://github.com/autowarefoundation/autoware.universe/pull/6457
fix for following issues
https://tier4.atlassian.net/browse/RT1-4914
https://tier4.atlassian.net/browse/RT1-5207
https://tier4.atlassian.net/browse/RT1-5343
https://tier4.atlassian.net/browse/RT1-5257
After all checkboxes are checked, anyone who has …
=> fix(multi_object_tracking): mot bicycle model revision, tracking_object_merger bugfix

perception/traffic_light_arbiter/CMakeLists.txt, perception/traffic_light_arbiter/README.md, perception/traffic_light_arbiter/config/traffic_light_arbiter.param.yaml, perception/traffic_light_arbiter/include/traffic_light_arbiter/signal_match_validator.hpp, perception/traffic_light_arbiter/include/traffic_light_arbiter/traffic_light_arbiter.hpp, perception/traffic_light_arbiter/src/signal_match_validator.cpp, perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
Cherry-pick this PR to enable the feature that validates the result of perception and external (V2I).
- https://github.com/autowarefoundation/autoware.universe/pull/6423
PR for launch
- https://github.com/tier4/autoware_launch.x2/pull/579
[TIER IV INTERNAL JIRA LINK](https://tier4.atlassian.net/browse/RT0-29986)
See https://github.com/autowarefoundation/autoware.universe/pull/6423
If the traffic light recognition result and V2I result are not equivalent, it is published as UNKNOWN and the ego stops.
This feature is enabled by setting `enable_signal_matching` to true.
After all …
=> feat(traffic_light_arbiter): add signal match validator (#6423)

localization/ndt_scan_matcher/include/ndt_scan_matcher/map_update_module.hpp, localization/ndt_scan_matcher/src/map_update_module.cpp
Fixed an issue where processing speed was slow when using a single map.
* https://github.com/autowarefoundation/autoware.universe/pull/6480
* https://github.com/autowarefoundation/autoware.universe/pull/6502
See 
* https://github.com/autowarefoundation/autoware.universe/pull/6480
* https://github.com/autowarefoundation/autoware.universe/pull/6502
Fixed an issue where processing speed was slow when using a single map.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …
=> fix(ndt_scan_matcher): fixed an issue where processing speed was slow when using a single map

planning/behavior_path_avoidance_module/config/avoidance.param.yaml, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp, planning/behavior_path_avoidance_module/src/scene.cpp
Original PR: https://github.com/autowarefoundation/autoware.universe/pull/6501
Realted PR: https://github.com/tier4/autoware_launch.xx1/pull/793
Realted Ticket: https://tier4.atlassian.net/browse/RT1-5327
=> feat(avoidance): wait next shift approval until the ego reaches shift length threshold (#6501)

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/boost_geometry.hpp, control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp, planning/behavior_path_planner_common/package.xml, planning/behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/geometric_pull_out.hpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_start_planner_module/src/geometric_pull_out.cpp, planning/behavior_path_start_planner_module/src/shift_pull_out.cpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
Original PR: https://github.com/autowarefoundation/autoware.universe/pull/6366
Related Ticket: https://tier4.atlassian.net/browse/RT1-5194
PSim 
=> feat(lane_departure_checker,start_planner): add check for path within lanes for bvspm (autowarefoundation#6366)

planning/behavior_velocity_intersection_module/src/decision_result.cpp, planning/behavior_velocity_intersection_module/src/decision_result.hpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/manager.hpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
=> feat(intersection): add traffic signal info publisher and detailed occlusion diagnosis  (#6491)

.github/workflows/sync-awf-latest.yaml
The `sync-awf-latest` workflow may modify the `.github/workflows` directory since it force-pushes the commits of awf/autoware.universe directly.
Since the workflow cannot modify the directory by default, the workflow sometimes fails as follows.
https://github.com/tier4/autoware.universe/actions/runs/8096410145/job/22125118729
To fix this issue, this PR added a token in the workflow file to permit the modification. This token was generated by the TIER IV's github admin and registered to the secret variable in tier4/autoware.universe by @tkimura4 
just run a sync-awf-latest without further testing
https://github.com/tier4/autoware.universe/actions/runs/8115389770
`sync-awf-latest` will not fail when it modifies the workflow directory.
The PR author **must** check the checkboxes below when …
=> feat(workflow): modify workflow from sync-awf-latest workflow

perception/traffic_light_multi_camera_fusion/src/node.cpp
Cherry-pick this PR to avoid mistrial resulted from low-confidence misdetection.
https://github.com/autowarefoundation/autoware.universe/pull/6267
https://tier4.atlassian.net/browse/RT1-4749
see https://github.com/autowarefoundation/autoware.universe/pull/6267 …
=> feat(traffic_light_multi_camera_fusion): take confidence into consideration(#6267)

planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp
Cherry-pick this PR.
- https://github.com/autowarefoundation/autoware.universe/pull/6468
Now, if a signal message is received but a subsequent traffic signal message is not, the ego vehicle will stop.
See https://github.com/autowarefoundation/autoware.universe/pull/6468
I also conducted tests on beta/v0.19.1
https://github.com/tier4/autoware.universe/assets/11865769/16385273-dc0e-4d7f-8b60-bdfbb00db5e1
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/mai …
=> feat(behavior_velocity_traffic_light): ensure stopping if a signal, once received, is not received again (autowarefoundation#6468)

planning/behavior_path_start_planner_module/README.md, planning/behavior_path_start_planner_module/config/start_planner.param.yaml, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_parameters.hpp, planning/behavior_path_start_planner_module/src/manager.cpp, planning/behavior_path_start_planner_module/src/shift_pull_out.cpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
Original PR: https://github.com/tier4/autoware.universe/pull/1165
Ticket:  https://tier4.atlassian.net/browse/RT1-5046
=> feat(start_planner): override lane departure check

planning/obstacle_cruise_planner/README.md, planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/src/node.cpp
Add yield function to obstacle cruise planner
Ticket: https://tier4.atlassian.net/jira/software/c/projects/RT1/issues/RT1-3025?filter=doneissues&jql=project%20%3D%20%22%5BR%26D%5D%20Autonomous%20Driving%20Components%22%0Aand%20statusCategory%20%3D%20%22Done%22%0Aand%20assignee%20%3D%20712020%3A7d8589d1-64d7-4a6d-8162-863204d3efe2%0Aand%20status%20%3D%20Done%0AORDER%20BY%20created%20DESC
Universe PR: https://github.com/autowarefoundation/autoware.universe/pull/6242
---------
**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.
Click the `Preview` tab and select a PR template:
- [Standard change](?expand=1&template=standard-change.md)
- [Small …
=> feat(obstacle_cruise_planner): yield function for ocp (#6242)

planning/behavior_path_start_planner_module/README.md, planning/behavior_path_start_planner_module/config/start_planner.param.yaml, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_parameters.hpp, planning/behavior_path_start_planner_module/src/manager.cpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
Cherry pick change path generation logic based on object class
https://github.com/autowarefoundation/autoware.universe/pull/6370
**launcher change [PR](https://github.com/tier4/autoware_launch.xx1/compare/v0.44.3.0+PR902?expand=1) shold be merged at the same time**
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pul …
=> feat(start_planner): cherry pick

planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/6558
=> fix(start_planner): consider backward completion before preparing blinker (#6558)

planning/route_handler/src/route_handler.cpp
https://github.com/autowarefoundation/autoware.universe/pull/6567
=> fix(route_handler): query shoulder lane in getLaneletSequence() if only_route_lanes is false and the arg is shoulder type (#6567)

planning/behavior_velocity_planner/src/node.cpp
※この変更はV2Iの残り時間情報を使うuniverse versionでのみ有効なため、beta/v0.19.1に変更を加えている
Related link: [TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-30742)
Handled the case when the remaining time is unavailable.
`has_max_rest_time` is false or `has_min_rest_time` is false
NOTE:
This PR should be merged after this PR
I will rebase after following PR has been merged.
-> **DONE**
- https://github.com/tier4/autoware.universe/pull/1171 …
=> feat(behavior_velocity_traffic_light): check if remaining time is available

planning/behavior_velocity_traffic_light_module/src/scene.cpp, planning/behavior_velocity_traffic_light_module/src/scene.hpp
I fixed the issue that the ego vehicle doesn't stop even if the signal is UNKNOWN when using the V2I remaining time information.
Related links: 
- [TIER IV INTERNAL JIRA](https://tier4.atlassian.net/browse/RT0-29986)
- [TIER IV INTERNAL Confluence](https://tier4.atlassian.net/wiki/spaces/~283541267/pages/2976122841/X2+V2I)
V2Iの残り時間情報を使う場合に、信号機がUNKNOWNでも停止線で停止しない問題を修正
※この問題はV2Iの残り時間情報を使うuniverse versionでのみ発生するため、beta/v0.19.1に変更を加えている
This PR should be merged after this PR
I will rebase after following PR has been merged.
-> **DONE**
- https://github.com/tier4/autoware.universe/pull/1171
Simple planning simulator.
A stop line is not inserted even if the signal is UNKNOWN because the module only checks the remaining time to the RED. …
=> feat(behavior_velocity_traffic_light): stop when the signal is unknown or timed out

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_start_planner_module/src/shift_pull_out.cpp
Universe PR: https://github.com/autowarefoundation/autoware.universe/pull/6588
Ticket: https://tier4.atlassian.net/browse/RT1-5672
Fixes an issue were the start planner's output path is incomplete and the ego vehicle cannot engage.
* fix union sometimes returning empty polygon
* fix union of polygons
* fix back launcher
---------
https://github.com/autowarefoundation/autoware.universe/pull/6588
[pull …
=> fix(lane_departure_checker): empty lanelet polygon (#6588)

system/diagnostic_graph_aggregator/CMakeLists.txt, system/diagnostic_graph_aggregator/script/dump.py
This PR adds the debug tool for diagnostic_graph_aggregator.
- https://github.com/autowarefoundation/autoware.universe/pull/6427
Run simple planning simulator and dump tool.
```
$ ros2 run diagnostic_graph_aggregator dump
| ----- | ----- | -------------------------------------------------------- | ----------------------------------------------------------- |
| index | level | name                                                     | links                                                       |
| ----- | ----- | -------------------------------------------------------- | ----------------------------------------------------------- |
| 0     | STALE | /sensing/lidar/rear_upper/temperature                    |                                                             |
| 1     | STALE | …
```
=> feat(diagnostic_graph_aggregator): add dump tool (#6427)

planning/behavior_path_avoidance_by_lane_change_module/config/avoidance_by_lane_change.param.yaml, planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp, planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_avoidance_module/config/avoidance.param.yaml, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp, planning/behavior_path_avoidance_module/src/debug.cpp, planning/behavior_path_avoidance_module/src/manager.cpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_avoidance_module/src/shift_line_generator.cpp, planning/behavior_path_avoidance_module/src/utils.cpp, planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6520
- https://github.com/autowarefoundation/autoware.universe/pull/6566
- https://github.com/autowarefoundation/autoware.universe/pull/6565
- https://github.com/autowarefoundation/autoware.universe/pull/6601
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …
=> fix(avoidance): cherry pick PRs for avoidance module

planning/behavior_velocity_dynamic_obstacle_stop_module/README.md, planning/behavior_velocity_dynamic_obstacle_stop_module/config/dynamic_obstacle_stop.param.yaml, planning/behavior_velocity_dynamic_obstacle_stop_module/src/manager.cpp, planning/behavior_velocity_dynamic_obstacle_stop_module/src/object_filtering.cpp, planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.cpp, planning/behavior_velocity_dynamic_obstacle_stop_module/src/types.hpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6594
Also need the launch PR: https://github.com/tier4/autoware_launch.xx1/pull/813
=> feat(dynamic_obstacle_stop): add option to ignore unavoidable collisions

planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6608
- https://github.com/autowarefoundation/autoware.universe/pull/6585
の盛り込みです．スプレッドシートに書きましたが効くシーンはそんなにないと思います．
=> Cherry pick/pr6608+6585

system/hazard_status_converter/CMakeLists.txt, system/hazard_status_converter/launch/hazard_status_converter.launch.xml, system/hazard_status_converter/package.xml, system/hazard_status_converter/src/converter.cpp, system/hazard_status_converter/src/converter.hpp
This PR adds hazard_status_converter.
- https://github.com/autowarefoundation/autoware.universe/pull/6428
=> feat(hazard_status_converter): add package (#6428)

planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp, planning/behavior_path_avoidance_module/config/avoidance.param.yaml, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp, planning/behavior_path_avoidance_module/src/debug.cpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_avoidance_module/src/utils.cpp
See https://github.com/autowarefoundation/autoware.universe/pull/6631.
=> feat(avoidance): wait and see ambiguous stopped vehicle (#6631)

planning/behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/parameters.hpp
Cherry picking https://github.com/autowarefoundation/autoware.universe/pull/6615
to v0.20.1.5
Lane change max velocity computation currently doesn't consider the parameterized input from `common.max_vel`. The result is that it causes the prepare path to be much longer than anticipated, plus, the results also affects the safety check, where the expected velocity is different from the actual velocity, which causes many safety check issues. 
This PR aims to solve this by including the max_vel parameter
Prepare path is long, plus safety check is difficult to be approved.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/79d9c978-9830-40fe-98f7-5fe3e371a8e6
Safety check is much simpler to be approved.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/ …
=> fix(lane_change): consider max velocity during path planning (#6615)

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
* fix(motion_utils): check size after overlap points removal
* change implementation to not return warning
* fix comparison sign
---------
```shell
terminate called after throwing an instance of 'std::out_of_range'
what():  vector::_M_range_check: __n (which is 54) >= this->size() (which is 54)
Thread 1 "behavior_path_p" received signal SIGABRT, Aborted.
0x00007ffff74969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff74969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7442476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff74287f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff78a2b9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff78ae20c in ?? () from …
```
=> fix(motion_utils): check size after overlap points removal (#6653)

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml, planning/behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/launch/behavior_path_planner.launch.xml, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/parameters.hpp
https://github.com/tier4/autoware.universe/pull/1203
Related pull request. Previous cherry pick couldn't work, due to common param is still not yet adopting new parameter. Therefore, in addition to cherry  picking, this PR also temporarily subscribe from motion velocity smoother's param. …
=> fix(lane_change): consider max velocity during path planning

launch/tier4_control_launch/launch/control.launch.py
Enable multithreading for control container
https://github.com/autowarefoundation/autoware.universe/pull/6666
=> feat(tier4_control_launch): enable multithreading for the control container

planning/behavior_velocity_out_of_lane_module/src/footprint.cpp, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.hpp, planning/behavior_velocity_out_of_lane_module/src/overlapping_range.cpp, planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
This PR adds the hotfix of out_of_lane module to prevent unnecessary stops during lane change.
- https://github.com/autowarefoundation/autoware.universe/pull/6334
- https://github.com/autowarefoundation/autoware.universe/pull/6600
Related link:
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-30803)
PSim
https://github.com/tier4/autoware.universe/assets/11865769/eebde842-8b84-4c3b-abd2-ed91266d1874 …
=> fix(out_of_lane): cherry-pick hotfix

planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.hpp
This PR adds the hotfix of out_of_lane module to prevent unnecessary stops during lane change.
- https://github.com/autowarefoundation/autoware.universe/pull/6600
Related link:
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-30803)
https://github.com/tier4/autoware.universe/assets/11865769/584ef0dc-7262-4fc5-ba21-450b781e7cde
PSim …
=> fix(out_of_lane): calculate path lanelets that we can miss during a lane change

planning/planning_validator/include/planning_validator/utils.hpp, planning/planning_validator/src/planning_validator.cpp, planning/planning_validator/src/utils.cpp
Cherry-pick from https://github.com/autowarefoundation/autoware.universe/pull/6679
Related JIRA Ticket:  https://tier4.atlassian.net/browse/RT0-29352
In the planning validator, among other checks, the max lateral acceleration is calculated and checked whether it is larger than 1G [m/s^2] or not from an input of trajectory. The lateral accelerations are calculated from longitudinal velocities and curvatures at every trajectory points.
The validation function in the planning validator includes two internal trajectory variables, namely `trajectory`, an input from the motion velocity smoother which is densely sampled near the ego and sparsely sampled otherwise with the policy explained [here](https://autowarefoundation.github.io/autoware.universe/main/planning/motion_velocity_smoother/#resampl …
=> fix(planning_validator): cherry-pick numerically safe calculation of max lateral acceleration for MRM check

planning/planning_validator/src/planning_validator.cpp
Cherry-pick the fix of lateral acceleration calculation in planning_validator.
- https://github.com/autowarefoundation/autoware.universe/pull/6679
=> fix(planning_validator): calculate max lateral acceleration after resampling trajectory (autowarefoundation#6679)

perception/map_based_prediction/src/map_based_prediction_node.cpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/bicycle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/big_vehicle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/normal_vehicle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/tracker_base.hpp, perception/multi_object_tracker/models.md, perception/multi_object_tracker/src/data_association/data_association.cpp, perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/multiple_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/pedestrian_and_bicycle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp, perception/multi_object_tracker/src/tracker/model/tracker_base.cpp, perception/tracking_object_merger/src/utils/utils.cpp
自転車の挙動に関するPRです。
- tracker挙動改善
- 歩行者自転車の追従性能向上
- Unknown検知を歩行者自転車のTrackletへと対応付け可能にする（デグレ注意）  
- predictionによる走行レーン内歩行者のPath算出方法の変更
https://tier4.atlassian.net/browse/RT0-30816
- tickets
1. https://tier4.atlassian.net/browse/RT0-30816 :heavy_check_mark: 
2. https://tier4.atlassian.net/browse/RT0-30812 :heavy_check_mark:  …
=> feat: fix lv4 bicycle pedestrian prediction issue

sensing/pointcloud_preprocessor/CMakeLists.txt, sensing/pointcloud_preprocessor/config/blockage_diagnostics_param_file.yaml, sensing/pointcloud_preprocessor/docs/blockage_diag.md, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/blockage_diag/blockage_diag_nodelet.hpp, sensing/pointcloud_preprocessor/launch/blockage_diag.launch.xml, sensing/pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp
- To enable dust_detection eable option for blockage_diag, this cherry-picks:
- https://github.com/autowarefoundation/autoware.universe/pull/5932
- https://github.com/autowarefoundation/autoware.universe/pull/6645 
- Need to merge with: https://github.com/tier4/aip_launcher/pull/228
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/mai …
=> fix(blockage_diag): add dust detection enable option pr5932+6645

launch/tier4_system_launch/launch/system.launch.xml, system/hazard_status_converter/launch/hazard_status_converter.launch.xml, system/hazard_status_converter/src/converter.cpp
This PR adds the option to launch mrm handler.
Cherry-pick following PR.
- https://github.com/autowarefoundation/autoware.universe/pull/6660
- https://github.com/autowarefoundation/autoware.universe/pull/6700
Related links:
- [TIER IV INTERNAL JIRA](https://tier4.atlassian.net/browse/RT0-30509)
- PR for launch: https://github.com/tier4/autoware_launch.x2/pull/605
planning simulator
I confirmed Emergency Stop and Comfortable Stop was performed when corresponding diagnostics was published.
https://github.com/tier4/autoware.universe/assets/11865769/29a58cef-7959-437f-8b0b-9682e0703795
https://github.com/tier4/autoware.universe/assets/11865769/2ed2f526-7b9a-4e61-8f66-a556da8ac2eb
The PR reviewers **must** …
=> feat(tier4_system_launch): add option to launch mrm handler (#6660)

planning/mission_planner/src/mission_planner/mission_planner.cpp, planning/mission_planner/src/mission_planner/mission_planner.hpp
=> fix(mission_planner): find the first common interval naively for main/mrm reroute check (#6504)

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
Record avoidance start/finish time stamp by using steering factor.
- start time: `status = 100`
- end time `status = 200`
Time stamp is recorded only when the avoidance path straddles lane border line.
https://github.com/tier4/autoware.universe/assets/44889564/1a53fd41-94f1-4c1e-9d41-43813732f6c4
start avoidance maneuver.
end avoidance maneuver.
[pull request …
=> feat(avoidance): (TEMPORARY) steering factor for avoidance maneuver

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/boost_geometry.hpp, control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp, planning/behavior_path_planner_common/package.xml, planning/behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/geometric_pull_out.hpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_start_planner_module/src/geometric_pull_out.cpp, planning/behavior_path_start_planner_module/src/shift_pull_out.cpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
(cherry pick 8bdb5422c68 and 0042c2086d9) to solve https://tier4.atlassian.net/browse/RT0-31009
After this is merged, lane departure check should be enabled by default: https://github.com/tier4/autoware_launch.x2/pull/610/files
=> feat(lane departure check,start planner): update lane departure check (cherry pick 8bdb5422c68 and 0042c2086d9)

perception/multi_object_tracker/include/multi_object_tracker/debugger.hpp, perception/multi_object_tracker/include/multi_object_tracker/multi_object_tracker_core.hpp, perception/multi_object_tracker/src/debugger.cpp, perception/multi_object_tracker/src/multi_object_tracker_core.cpp
cherry-pick for mot timer bug fix + latency reduction
timer bug fix
PR https://github.com/autowarefoundation/autoware.universe/pull/6757
PR https://github.com/autowarefoundation/autoware.universe/pull/6775
latency reduction
PR https://github.com/autowarefoundation/autoware.universe/pull/6710
https://evaluation.tier4.jp/evaluation/reports/b0d4a760-d580-5cf4-901c-e44654c59fb4?project_id=prd_jt
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …
=> fix(multi_object_tracker): mot timer cherrypicks

planning/behavior_velocity_out_of_lane_module/config/out_of_lane.param.yaml, planning/behavior_velocity_out_of_lane_module/package.xml, planning/behavior_velocity_out_of_lane_module/src/decisions.cpp, planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.cpp, planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.hpp, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.hpp, planning/behavior_velocity_out_of_lane_module/src/manager.cpp, planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp, planning/behavior_velocity_out_of_lane_module/src/types.hpp
Cherry-pick the following PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/6478
- https://github.com/autowarefoundation/autoware.universe/pull/6630
- https://github.com/autowarefoundation/autoware.universe/pull/6600
=> feat(out_of_lane): cherry-pick lane change bug fix + cut pred paths at red light

vehicle/raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml, vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml, vehicle/raw_vehicle_cmd_converter/schema/raw_vehicle_cmd_converter.schema.json
…(#6476)
accel_map.csv, brake_map.csv, steer_map.csvのパス設定はyamlファイルに移動した。
autowarefoundation/autoware.universe側のPRをcherry-pickしました。
https://github.com/autowarefoundation/autoware.universe/pull/6476
ros2 launch j6_gen1_launch vehicle_interface.launch.xml で起動すると、map_pathが正しく読み込んでいることは確認できました。
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-reque …
=> fix(raw_vehicle_cmd_converter): csv paths are resolved in param.yaml

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
launcher https://github.com/tier4/autoware_launch.x2/pull/573
cherry-pick this PR
[feat(avoidance): keep stopping until all shift lines are registered by satoshi-ota · Pull Request #5658 · autowarefoundation/autoware.universe](https://github.com/autowarefoundation/autoware.universe/pull/5658)
https://tier4.atlassian.net/browse/RT1-4491
PSim …
=> feat: keep stop policy v0.11.2 (reopen)

launch/tier4_planning_launch/launch/planning.launch.xml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving.launch.xml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp
Cherry pick following PRs.
The ego vehicle will stop at the traffic light stop line if no signal messages were received.
- https://github.com/autowarefoundation/autoware.universe/pull/6468
- https://github.com/autowarefoundation/autoware.universe/pull/6498
PR for launch
- https://github.com/tier4/autoware_launch.x2/pull/622
PSim …
=> feat(behavior_velocity_traffic_light): ensure stopping if a signal is not received

system/diagnostic_graph_aggregator/src/common/graph/graph.cpp, system/diagnostic_graph_aggregator/src/common/graph/units.cpp, system/diagnostic_graph_aggregator/src/common/graph/units.hpp
Report the highest error level.
Use fault injection tools.
=> feat(diagnostic_graph_aggregator): report the highest error level

planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/6011
https://tier4.atlassian.net/browse/RT0-30692
=> fix(obstacle_avoidance_planner): use update_bounds instead of update_lower/upper_bounds (#6011)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/5905
Related ticket: https://tier4.atlassian.net/browse/RT0-30848
=> fix(avoidance): same as feat(avoidance): suppress unnatural turn signal #5905

planning/behavior_velocity_traffic_light_module/src/scene.cpp
Related: https://tier4.atlassian.net/browse/RT0-30814
:information_source: This fix has been applied only to the beta/v0.19.1 branch, as the use of remaining time data is only implemented in this branch.
I fixed the following bugs:
- The planner failed to insert a point when the signal was outdated
- https://github.com/tier4/autoware.universe/pull/1259/commits/cbc7016c767cf24e9224ccc3823db55aa95f3f09
- The pass judgment did not function correctly because prev_state_stop_ was not updated when using time to red signal
- https://github.com/tier4/autoware.universe/pull/1259/commits/6b99e3940a7fff75da6a6ed01b852721a37f624d
[Scenario simulator](https://evaluation.tier4.jp/evaluation/reports/05d99f4a-947b-5a85-a78d-175c9a50d5c0/tests/6559f711-adb6-5e70-9639-7bdaccdc63b3?project_id=x2_dev)
No …
=> fix(behavior_velocity_traffic_light): stop for outdated signals and set prev_state_stop when using time to red signal

sensing/gnss_poser/README.md, sensing/gnss_poser/config/gnss_poser.param.yaml, sensing/gnss_poser/include/gnss_poser/gnss_poser_core.hpp, sensing/gnss_poser/schema/gnss_poser.schema.json, sensing/gnss_poser/src/gnss_poser_core.cpp
Cherry-pick bug fixes for `gnss_poser`
- https://github.com/autowarefoundation/autoware.universe/pull/6116
- https://github.com/autowarefoundation/autoware.universe/pull/6404
- https://tier4.atlassian.net/browse/RT0-31338
- https://github.com/tier4/aip_launcher/pull/234
Checked param and topics
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …
=> fix(gnss_poser): cherry pick

perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp
- This is a temporal change for compare map filter to retain the obstacle pointcloud of low height objects. 
TIER IV INTERNAL LINK: [ticket 1](https://tier4.atlassian.net/browse/RT1-5185) and [ticket 2](https://tier4.atlassian.net/browse/RT0-31059)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideli …
=> fix(compare_map_segmentation): vertical check adjust for low height object detection

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/polygon_utils.cpp
ignore near beside objects
https://github.com/autowarefoundation/autoware.universe/pull/6754
=> feat(obstacle_cruise): ignore right beside objects (#6754)

planning/behavior_path_planner/src/turn_signal_decider.cpp
実証実験中に、経路から外れる時に、behavior path plannerが死ぬため、以下のPRを取り込む。
https://github.com/autowarefoundation/autoware.universe/pull/2382
[チケット](https://tier4.atlassian.net/browse/RT0-31302)
=> fix(behavior_path_planner): node died when change ego behavior

launch/tier4_perception_launch/launch/perception.launch.xml, launch/tier4_simulator_launch/launch/simulator.launch.xml
cherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/6861
=> feat(perception_online_evaluator): add use_perception_online_evaluator option and disable it by default (#6861)

system/diagnostic_graph_aggregator/script/dump.py
Resolve pre-commit.ci error
```
flake8 ros...............................................................Failed
- hook id: flake8-ros
- exit code: 1
system/diagnostic_graph_aggregator/script/dump.py:34:37: E231 missing whitespace after ':'
line = map(lambda v, w: f"{v:{w}}", line, widths)
^
1     E231 missing whitespace after ':'
```
https://results.pre-commit.ci/run/github/438106587/1714613670.K3nwJB10QBmgl0y_WPd6RQ …
=> fix: pre-commit.ci error

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6904
=> feat(crosswalk)!: change ego min assumed speed (#6904)

system/dummy_diag_publisher/include/dummy_diag_publisher/dummy_diag_publisher_core.hpp, system/dummy_diag_publisher/src/dummy_diag_publisher_core.cpp
- diagnostic_updaterを使用するとdiagのnameにノード名が入ってしまうため、自前でpublishする形に変更する
- param callbackを削除する
- 正常に動いていなかったため、
- パラメータでdefaultを設定する都合上、正常に動いたとしてもdefault指定の場合はパラメータを変更できないため
https://tier4.atlassian.net/browse/RT0-31356
https://github.com/tier4/autoware_launch.x2/pull/641 と一緒に確認する …
=> fix(dummy_diag_publisher): not use diagnostic_updater and param callback

common/tier4_system_rviz_plugin/src/mrm_summary_overlay_display.cpp
:warning: This modification is only applied to this branch.
MRM Summary was not displayed when using the diagnostic graph aggregator because the hazard status message has no hardware_id.
So I fixed to display the hazard_status that has no hardware_id.
PSim
=> chore: display hazard status that has no hardware_id

planning/behavior_velocity_out_of_lane_module/config/out_of_lane.param.yaml, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/behavior_velocity_out_of_lane_module/src/manager.cpp, planning/behavior_velocity_out_of_lane_module/src/types.hpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6991
Fix https://tier4.atlassian.net/browse/RT0-31440
Psim, bag replay, and pilot-auto evaluator
`out_of_lane` module should no longer trigger stops during avoidance where the ego vehicle overlaps another lane.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guid …
=> feat(out_of_lane): add option to ignore overlaps in lane changes (#6991)

.pre-commit-config.yaml, common/tier4_debug_tools/package.xml
pre-commit.ciがflake8が、failする問題を解決するPRとなります。
今回の問題は、flake8のバージョンが古い事が問題となっており、
v4.0.1からv6.0.0に変更される事で解決しました。
バージョン更新に伴い、他のリポジトリでpre-commit.ciがpassしている方法と同じ実装を対策として実施。
https://github.com/tier4/autoware_launch.x1.eve/blob/e8430668eea3cd57ba231aa1027518828cf89456/.pre-commit-config.yaml#L36-L44
pre-commit.ciがpassする事を確認済み
https://results.pre-commit.ci/run/github/438106587/1715598146.hX5oIshYRT2lKSQdPEDIkA
特にありません
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …
=> fix(pre-commit): add flake8-ros

common/tier4_calibration_rviz_plugin/src/accel_brake_map_calibrator_button_panel.cpp, common/tier4_calibration_rviz_plugin/src/accel_brake_map_calibrator_button_panel.hpp, planning/planning_debug_tools/scripts/perception_replayer/utils.py, vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp
以下をbackport
https://github.com/autowarefoundation/autoware.universe/pull/6973
https://github.com/autowarefoundation/autoware.universe/pull/6992
=> chore: backport autowarefoundation#6973 and #6992

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/6935
https://tier4.atlassian.net/browse/RT1-5675
=> feat(goal_planner): reject candidate path whose start pose direction is not aligned with ego path (#6935)

planning/obstacle_cruise_planner/src/node.cpp
地図にないpolygonIDを指定すると例外をキャッチできずノードが死ぬ問題の修正です。
適当な番号999999とかをいれたり、お台場の地図で動かして、弾けることを確認しました。
また、作動してほしい場所での動作に影響がないことを確認しました。
=> fix(pseudo occulusion): fix out of range access

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
-  To add timeout in cases multi-additional lidars used for ground_segmentation
- Related PR: https://github.com/tier4/aip_launcher/pull/215/files
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5185?focusedCommentId=165666)
- Tested on X2 bench hardware: `/perception/obstacle_segmentation/concatenate_data` output (`/perception/obstacle_segmentation/single_frame/pointcloud_raw`) rate:  7.2hz -> 10hz
| Before | After |
| --- | --- |
|![Screenshot from 2024-05-02 11-34-36](https://github.com/tier4/autoware.universe/assets/94814556/64b17091-cb4e-4f66-9581-a2fe883dafd8) | ![Screenshot from 2024-05-02 09-03-38](https://github.com/tier4/autoware.universe/assets/94814556/92b38ad1-8ecb-4e0c-b818-d46bf9715584)|
The PR author **must** check the checkboxes below when …
=> fix(ground_segmentation launch): fix ground segmentation concatenate node and timeout

control/autonomous_emergency_braking/README.md, control/autonomous_emergency_braking/config/autonomous_emergency_braking.param.yaml, control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp, control/autonomous_emergency_braking/src/node.cpp, evaluator/control_evaluator/CMakeLists.txt, evaluator/control_evaluator/README.md, evaluator/control_evaluator/include/control_evaluator/control_evaluator_node.hpp, evaluator/control_evaluator/launch/control_evaluator.launch.xml, evaluator/control_evaluator/package.xml, evaluator/control_evaluator/param/control_evaluator.defaults.yaml, evaluator/control_evaluator/src/control_evaluator_node.cpp, launch/tier4_control_launch/launch/control.launch.py, launch/tier4_control_launch/package.xml
Update AEB module and add control evaluator for AEB monitoring: 
cherry-picked PRs: 
https://github.com/autowarefoundation/autoware.universe/pull/6966  (AEB update)
https://github.com/autowarefoundation/autoware.universe/pull/6875  (AEB update)
https://github.com/autowarefoundation/autoware.universe/pull/6912 (AEB update)
https://github.com/tier4/autoware.universe/commit/c66d5769e1776bb9855e8cb2efa633f38584c3b6 (Param update with rqt_reconfigure for AEB)
https://github.com/autowarefoundation/autoware.universe/pull/6959 (Add control evaluator node)
Requires launch changes: https://github.com/tier4/autoware_launch.xx1/pull/853
PSim
The …
=> feat(aeb): update aeb module and add control evaluator

planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_traffic_light_module/package.xml, planning/behavior_velocity_traffic_light_module/src/manager.cpp, planning/behavior_velocity_traffic_light_module/src/manager.hpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp, planning/behavior_velocity_traffic_light_module/src/scene.hpp
https://github.com/autowarefoundation/autoware.universe/pull/7044
https://tier4.atlassian.net/browse/RT0-31341
=> feat(behavior_velocity_traffic_light): do not overwrite unknown with past known color (#7044)

planning/obstacle_cruise_planner/include/obstacle_cruise_planner/polygon_utils.hpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/polygon_utils.cpp
reduce computation cost
https://github.com/autowarefoundation/autoware.universe/pull/7040
=> feat(obstacle cruise): reduce computation cost (#7040)

planning/behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_lane_change_module/src/scene.cpp
cherry-pick disable terminal paths commits
=> fix(lane_change): cherry-pick disable terminal path

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_avoidance_module/config/avoidance.param.yaml, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/debug.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/shift_line_generator.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/type_alias.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp, planning/behavior_path_avoidance_module/schema/avoidance.schema.json, planning/behavior_path_avoidance_module/src/debug.cpp, planning/behavior_path_avoidance_module/src/manager.cpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_avoidance_module/src/shift_line_generator.cpp, planning/behavior_path_avoidance_module/src/utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6913
- https://github.com/autowarefoundation/autoware.universe/pull/6947
- https://github.com/autowarefoundation/autoware.universe/pull/6911
- https://github.com/autowarefoundation/autoware.universe/pull/7097
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …
=> fix: cherry pick avoidance PRs

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_nodelet.hpp, sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
- stopped using diagnostics_updater to control /diagnostics publish timing
- Changed to publish diagnostics in WARN only when concat fails for more than 2 consecutive frames
- changed the node name of segmentation to distinguish between sensing concat and segmentation concat
- Confirmed by actual vehicle
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …
=> feat(pointcloud preprocessor): add hysteresis to diag

sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
In https://github.com/tier4/autoware.universe/pull/1309, `consecutive_concatenate_failures_` should be `consecutive_concatenate_failures`
=> fix(pointcloud_preprocessor): typo consecutive_concatenate_failures

planning/behavior_velocity_blind_spot_module/CMakeLists.txt, planning/behavior_velocity_blind_spot_module/config/blind_spot.param.yaml, planning/behavior_velocity_blind_spot_module/src/debug.cpp, planning/behavior_velocity_blind_spot_module/src/decisions.cpp, planning/behavior_velocity_blind_spot_module/src/manager.cpp, planning/behavior_velocity_blind_spot_module/src/scene.cpp, planning/behavior_velocity_blind_spot_module/src/scene.hpp
https://github.com/tier4/autoware.universe/pull/1312
=> chore(blind_spot): PR7110 and PR7164

perception/multi_object_tracker/CMakeLists.txt, perception/multi_object_tracker/include/multi_object_tracker/debugger.hpp, perception/multi_object_tracker/include/multi_object_tracker/multi_object_tracker_core.hpp, perception/multi_object_tracker/include/multi_object_tracker/processor/processor.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/bicycle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/big_vehicle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/normal_vehicle_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/pedestrian_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/tracker_base.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/model/unknown_tracker.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/motion_model/bicycle_motion_model.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/motion_model/ctrv_motion_model.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/motion_model/cv_motion_model.hpp, perception/multi_object_tracker/include/multi_object_tracker/tracker/motion_model/motion_model_base.hpp, perception/multi_object_tracker/include/multi_object_tracker/utils/utils.hpp, perception/multi_object_tracker/launch/multi_object_tracker.launch.xml, perception/multi_object_tracker/package.xml, perception/multi_object_tracker/src/debugger.cpp, perception/multi_object_tracker/src/multi_object_tracker_core.cpp, perception/multi_object_tracker/src/processor/processor.cpp, perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp, perception/multi_object_tracker/src/tracker/model/unknown_tracker.cpp, perception/multi_object_tracker/src/tracker/motion_model/bicycle_motion_model.cpp, perception/multi_object_tracker/src/tracker/motion_model/ctrv_motion_model.cpp, perception/multi_object_tracker/src/tracker/motion_model/cv_motion_model.cpp, perception/multi_object_tracker/src/tracker/motion_model/motion_model_base.cpp
Catch-up of old PRs, cherry-pick of the fix https://github.com/autowarefoundation/autoware.universe/pull/7159
Bug ticket: https://tier4.atlassian.net/browse/RT0-31411
Want to be checked in X2 environment.
=> fix(multi_object_tracker): huge tracking object bug fix for x2

perception/multi_object_tracker/src/debugger.cpp
I fixed the calculation of detection delay diagnostics.
Related PR:
- https://github.com/tier4/autoware.universe/pull/1314
Related JIRA:
https://tier4.atlassian.net/browse/RT0-31411
I tested on simple planning simulator.
=> fix(multi_object_tracker): calculation of detection delay diagnostics

perception/multi_object_tracker/include/multi_object_tracker/utils/utils.hpp
cherry-pick of the fix https://github.com/autowarefoundation/autoware.universe/pull/7159
Bug ticket: https://tier4.atlassian.net/browse/RT0-31411
=> fix(multi_object_tracker): mot convexhull to bbox convert bug

planning/obstacle_avoidance_planner/src/utils.cpp
走行中に、motion_planning_containerが落ちることによって、EMが発生する問題の対策PRとなる。
今回の対策によって、稼働を継続できる条件において、EMが発生せずに、稼働を継続する。
空データに対してスプライン補間をした場合に例外が発生する事が分かった。
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140599944683328)
at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140599944683328)
at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140599944683328, signo=signo@entry=6)
at ./nptl/pthread_kill.c:89
#3  0x00007fdff9f21476 in __GI_raise (sig=sig@entry=6)
at ../sysdeps/posix/raise.c:26
#4  0x00007fdff9f077f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fdffa1ccb9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fdffa1d820c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fdffa1d8277 in std::terminate() ()
from …
```
=> fix(obstacle_avoidance_planner): add empty check

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/utils.hpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/planner_interface.cpp, planning/obstacle_cruise_planner/src/utils.cpp
https://tier4.atlassian.net/browse/RT1-6338 への対応PRです。
https://github.com/autowarefoundation/autoware.universe/pull/7230 とその前提PRをcherry-pickしています。
挙動はlaunch側で説明します。
launch PR: https://github.com/tier4/autoware_launch.xx1/pull/868
=> feat(obstacle_cruise)!: type specified stop deccel limit and enabling abandon to stop

planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp, planning/motion_velocity_smoother/include/motion_velocity_smoother/smoother/smoother_base.hpp, planning/motion_velocity_smoother/package.xml, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp, planning/motion_velocity_smoother/src/smoother/smoother_base.cpp
Add FOA cooperated force acceleration function.
PSim + Experimental vehicle
Accelerates depending on safety operator operation
Added service in motion_velocity_smoother to communicate with FOA.
=> feat(motion_velocity_smoother)!: added force acceleration

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/src/node.cpp
cherr-pick https://github.com/autowarefoundation/autoware.universe/pull/7177 with small conflict resolve
=> feat(obstacle_cruise_planner)!: ignore to garze against unknwon objects (#7177)

perception/detected_object_validation/config/object_lanelet_filter.param.yaml, perception/detected_object_validation/config/obstacle_pointcloud_based_validator.param.yaml, perception/detected_object_validation/config/occupancy_grid_based_validator.param.yaml, perception/detected_object_validation/include/detected_object_validation/detected_object_filter/object_lanelet_filter.hpp, perception/detected_object_validation/include/detected_object_validation/detected_object_filter/object_position_filter.hpp, perception/detected_object_validation/launch/obstacle_pointcloud_based_validator.launch.xml, perception/detected_object_validation/launch/occupancy_grid_based_validator.launch.xml, perception/detected_object_validation/package.xml, perception/detected_object_validation/src/object_lanelet_filter.cpp, perception/detected_object_validation/test/test_utils.cpp, sensing/pointcloud_preprocessor/CMakeLists.txt, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/utility/utilities.hpp, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/vector_map_filter/vector_map_inside_area_filter.hpp, sensing/pointcloud_preprocessor/src/utility/utilities.cpp, sensing/pointcloud_preprocessor/src/vector_map_filter/vector_map_inside_area_filter.cpp, sensing/pointcloud_preprocessor/test/test_utilities.cpp
AWFに追加済みのUnknownの除去ロジックの一部をcherry-pickします。
これが入ることでロータリのカーブの縁石Unknownが正しく除去できるようになります。
追加される機能一覧
- object_lanelet_filter:
- Lane外の点群のみで構成されたUnknownがLanelet Filterで弾けない問題を解決
- vector_map_inside_area_filter:
- mapに設定した領域内の点群を除去するフィルタにて高さを考慮できるように変更（非低層点群を誤って消さないようにする）
- このPR単体では全体としては不使用
関連するPR
- autoware_launcherの変更：https://github.com/tier4/autoware_launch.x2/pull/672
- X2限定の変更（vector_map_inside_area_filter）の実装 : https://github.com/tier4/autoware.universe/pull/1330 …
=> feat(object_lanelet_filter, vector_map_inside_area_filter): cherry-pick unknown removal feature from awf

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/package.xml, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
is_mrm_recoverableをTrueにした場合、autowareを再起動しないとMRMから復帰できない。  
ソフトウェアの仕様としては正しいが、実験する上で可用性が低いため、
is_mrm_recoverableパラメータを動的に変更することを許可する。
MRMからの復帰
`ros2 param set /system/mrm_handler is_mrm_recoverable True`
https://github.com/tier4/autoware.universe/assets/19224532/b8f57bad-bd2b-4cec-8eae-3be68ee84667
Psimで実験した。
走行開始→Emergency発生→MRMによる緊急停止→Emergency解除（MRM復帰せず）→is_mrm_recoverableをTrueに変更→再発進 …
=> feat: daynamic reconfigurable is_mrm_recoverable parameter

planning/behavior_path_start_planner_module/src/shift_pull_out.cpp
cherry-pick [PR](https://github.com/autowarefoundation/autoware.universe/pull/7401)
=> fix(start_planner): set minimum velocity to avoid high curvature in trajectroy

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6898
=> feat(avoidance): keep enough distance to avoid object in front of red signal (#6898)

control/control_validator/config/control_validator.param.yaml, control/control_validator/include/control_validator/control_validator.hpp, control/control_validator/src/control_validator.cpp
checking
Add min velocity for max distance deviation checking.
https://tier4.atlassian.net/browse/RT0-31622
Checked on Psim.
=> feat(control_validator): add min velocity for max distance deviation checking

system/topic_state_monitor/src/topic_state_monitor_core.cpp
Cherry-pick from https://github.com/autowarefoundation/autoware.universe/pull/7236
Run psim in awf's PR.
A logging message will appear when the required topic is lost.
None
=> chore(topic_state_monitor): enrich error log message (#7236)

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/6037 のbackport
engage_velocity適用判定で使用するstop_distの計算において、経路終端が0になっているのが前提だが0になっておらずdouble::max()が常に出力されていたのを修正
https://github.com/tier4/autoware.universe/blob/fed4253d5b8c27f149dc2223e62c5f1a73476c3c/planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp#L777
https://tier4.atlassian.net/browse/VEH-1001
psimにおいて、engage_velocity適用判定で使用するstop_distをデバッグコードを仕込んで出力できるようにし、正常な値が計算されていることを確認した
また、これまで停止際にengage_velocityが入力されていたが、入力されないことも確認した
After all checkboxes are checked, anyone who has write access can merge the …
=> fix(motion_velocity_smoother): make stopping_distance and stopping_velocity be able to work (#6037)

planning/behavior_path_side_shift_module/include/behavior_path_side_shift_module/scene.hpp, planning/behavior_path_side_shift_module/src/scene.cpp
Related to [issue](https://tier4.atlassian.net/browse/RT1-6473) in odaiba reference drive.
This PR would make an appropriate side shift path; the path would be inside the driving area (specially behind the ego vehicle).
PSim
Before
[Screencast from 2024年06月20日 14時32分48秒.webm](https://github.com/tier4/autoware.universe/assets/12757369/2f2dc5b5-1e82-41e1-bd19-d8ca6e783d20)
After
[Screencast from 2024年06月20日 14時43分57秒.webm](https://github.com/tier4/autoware.universe/assets/12757369/b2e8ab46-4bc8-4dbd-b88e-2228bba61541)
After all checkboxes are checked, anyone who has …
=> perf(side_shift): fix unupdated prev path

system/diagnostic_graph_utils/CMakeLists.txt, system/diagnostic_graph_utils/launch/logging.launch.xml, system/diagnostic_graph_utils/src/node/logging.cpp, system/diagnostic_graph_utils/src/node/logging.hpp
Same as https://github.com/tier4/autoware.universe/pull/1346
=> feat(diagnostic_graph_utils): add logging tool

system/default_ad_api/src/operation_mode.cpp
Same as https://github.com/tier4/autoware.universe/pull/1347
=> feat(default_ad_api): add log when operation mode change fails

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
fix(lane_change): prevent empty path when routing
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/7717
- psim and evaluator in main
- build in this branch
=> fix(lane_change): prevent empty path when rerouting (#7717)

planning/behavior_velocity_detection_area_module/src/scene.cpp, planning/behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/arc_lane_util.hpp, planning/behavior_velocity_planner_common/test/src/test_arc_lane_util.cpp, planning/behavior_velocity_stop_line_module/src/scene.cpp, planning/behavior_velocity_virtual_traffic_light_module/src/scene.cpp
Signed-off-by: Y.Hisaki <yhisaki31@gmail.com>
https://github.com/autowarefoundation/autoware.universe/pull/7710
https://tier4.atlassian.net/browse/RT0-30839
https://evaluation.ci.tier4.jp/evaluation/reports/6f5f6e7c-1d11-5ca3-b5cd-f89ac8fca216?project_id=prd_jt
None.
None.
None.
=> fix(autoware_behavior_velocity_planner_common): remove lane_id check from arc_lane_util

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker_node.hpp, control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/footprint.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/package.xml, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/7730 https://github.com/autowarefoundation/autoware.universe/pull/7732 #7683 and #7633
Psim and perception replayer.
Performance of the `out_of_lane` (most heavy module) on a rosbag with many dynamic objects:
- Without the PR: ~50ms runtime with peaks at 80ms.
- With the PR: ~15ms runtime with peaks at 25ms
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/con …
=> perf(motion_velocity_planner): resample trajectory and build rtree with packing algorithm

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
This PR changes that mrm_handler does not use MrmState.msg in autowqare_adapi_v1_msgs, but use in tier4_system_msgs.
=> feat: change MrmState.msg to internal one

simulator/simple_planning_simulator/CMakeLists.txt, system/control_cmd_switcher/CMakeLists.txt, system/control_cmd_switcher/README.md, system/control_cmd_switcher/config/control_cmd_switcher.yaml, system/control_cmd_switcher/launch/control_cmd_switcher.launch.xml, system/control_cmd_switcher/package.xml, system/control_cmd_switcher/src/control_cmd_switcher/control_cmd_switcher.cpp, system/control_cmd_switcher/src/control_cmd_switcher/control_cmd_switcher.hpp, system/control_cmd_switcher/tool/rely_trajectry.py
This PR adds control cmd siwthcher node and rely trajectry script for MRMv0.6 one host test.
Confirm that the node switches main control_cmd and sub control_cmd according to selected path_info.
=> feat: add control cmd switcher

localization/pose_instability_detector/src/pose_instability_detector.cpp, localization/pose_instability_detector/test/test.cpp
Cherry-pick of the following PR
* https://github.com/autowarefoundation/autoware.universe/pull/7681
This seems to occur when performing initial position estimation twice, as the EKF is lost during the second iteration.
Error
```
1719899212.4359140 [ERROR] [pose_instability_detector_node-77]: process has died [pid 97654, exit code -6, cmd '/home/autoware/pilot-auto.xx1/install/pose_instability_detector/lib/pose_instability_detector/pose_instability_detector_node --ros-args -r __node:=pose_instability_detector -r __ns:=/localization/pose_twist_fusion_filter -p use_sim_time:=False -p wheel_radius:=0.31 -p wheel_width:=0.18 -p wheel_base:=2.75 -p wheel_tread:=1.485 -p front_overhang:=0.8 -p rear_overhang:=0.85 -p left_overhang:=0.105 -p right_overhang:=0.105 -p vehicle_height:=2.5 -p …
```
=> fix(pose_instability_detector): fix a crash bug in pose_instability_detector

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
For the simulation test, all of the scenario tests will be failed. Let me cherry-pick this PR, that has been merged in awf/autoware.universe.
We had talked about it in [slack](https://star4.slack.com/archives/C04TZBEABDM/p1719885974285699?thread_ts=1719815589.540119&cid=C04TZBEABDM)
PR: https://github.com/autowarefoundation/autoware.universe/pull/7784
=> feat(mrm_handler): operate mrm only when autonomous operation mode

sensing/image_transport_decompressor/CMakeLists.txt
yoloxで使用するimage_tranport_decomposerが参照するconfigがビルド対象に含まれておらず、roscube側で起動時即死します。
https://github.com/autowarefoundation/autoware.universe/pull/7615
=> fix(image_transport_decompressor): missing config setting (#7615)

system/leader_election_converter/CMakeLists.txt, system/leader_election_converter/README.md, system/leader_election_converter/config/leader_election_converter.param.yaml, system/leader_election_converter/launch/leader_election_converter.launch.xml, system/leader_election_converter/package.xml, system/leader_election_converter/schema/leader_election_converter.schema.json, system/leader_election_converter/src/common/converter/availability_converter.cpp, system/leader_election_converter/src/common/converter/availability_converter.hpp, system/leader_election_converter/src/common/converter/log_converter.cpp, system/leader_election_converter/src/common/converter/log_converter.hpp, system/leader_election_converter/src/common/converter/mrm_converter.cpp, system/leader_election_converter/src/common/converter/mrm_converter.hpp, system/leader_election_converter/src/common/converter/udp_receiver.hpp, system/leader_election_converter/src/common/converter/udp_sender.hpp, system/leader_election_converter/src/node/leader_election_converter.cpp, system/leader_election_converter/src/node/leader_election_converter.hpp
This PR adds leader_election_converter which is for mrm v0.6 function.
=> feat(leader_election_converter): mrm v0.6 add leader election converter based on x2 v3.0.0

simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
This PR changes initial control mode value in simple_planning_simulator.
=> feat: change initial control mode

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
This PR change mrm state type adapi_v1_msg to internal type tier4_system_msgs.
=> feat: change mrm state type to internal one

control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp, control/trajectory_follower_node/test/test_controller_node.cpp
fix of https://github.com/tier4/autoware.universe/pull/1404
- Link
None.
None.
None.
=> fix(pid_longitudinal_controller): fix cherry-pick

system/system_diagnostic_monitor/config/control.yaml, vehicle/autoware_external_cmd_converter/src/node.cpp
Cherry-pick to use local mode:
https://github.com/autowarefoundation/autoware.universe/pull/7921
https://github.com/autowarefoundation/autoware.universe/pull/7532
- Link
https://github.com/autowarefoundation/autoware.universe/pull/7921
https://github.com/autowarefoundation/autoware.universe/pull/7532
None.
None.
None.
=> fix(autoware_external_cmd_converter, system_diagnostic_monitor): fix check_topic_state and local mode config

planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
This PR adds a force slow driving function to the motion_velocity_smoother node. The function is activated when there is a trigger from the FOA. It can only be activated when the ego velocity is lower than the threshold.
ex. Use when start/goal planner is stuck
[launch](https://github.com/tier4/autoware_launch.xx1/pull/899)
Vehicle experiment + PSim
This is a temporary function.
None.
None.
=> feat(motion_velocity_smoother): force slow driving

system/duplicated_node_checker/config/duplicated_node_checker.param.yaml, system/duplicated_node_checker/include/duplicated_node_checker/duplicated_node_checker_core.hpp, system/duplicated_node_checker/src/duplicated_node_checker_core.cpp
https://github.com/autowarefoundation/autoware.universe/pull/7959
( https://github.com/autowarefoundation/autoware_launch/pull/1070 )
Hotfix to beta/v0.29.0
=> feat(duplicated_node_checker): add duplicate nodes to ignore (#7959)

planning/behavior_velocity_blind_spot_module/src/scene.cpp
Equivalent change to
https://github.com/autowarefoundation/autoware.universe/pull/7925
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-32251)
None.
None.
None.
=> feat(blind_spot): consider road_shoulder if exist

planning/behavior_path_planner/config/behavior_path_planner.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/planner_manager.cpp
original [PR](https://github.com/autowarefoundation/autoware.universe/pull/7881)
laucher change in this [PR](https://github.com/tier4/autoware_launch.xx1/pull/902) should be merged first 
- Link
None.
None.
None.
=> feat(autoware_behavior_path_planner): remove max_iteration_num parameter

system/dummy_diag_publisher/src/dummy_diag_publisher_core.cpp
I did wrong commit in [PR1414](https://github.com/tier4/autoware.universe/pull/1414).
This PR fix build issue of this PR. Sorry for inconvenient.
- Link
None.
None.
None.
=> fix: resolve build error of dummy diag publisher

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp, common/motion_utils/src/trajectory/trajectory.cpp, planning/behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_parameters.hpp, planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/pull_over_planner_base.hpp, planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_goal_planner_module/src/manager.cpp, planning/behavior_path_goal_planner_module/src/shift_pull_over.cpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/data_structs.hpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_start_planner_module/src/shift_pull_out.cpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
- goal plannerで曲率の高い経路の優先度を下げる
- start plannerで後方車両への過剰な安全判定を修正
- start/goal plannerでのutilsでの曲率計算を修正
- 
- Link
None.
None.
None.
=> fix(start/goal_planner): improve start/goal planner

common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp, common/autoware_motion_utils/src/trajectory/trajectory.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_parameters.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/shift_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
- goal plannerで曲率の高い経路の優先度を下げる
- start plannerで後方車両への過剰な安全判定を修正
- start/goal plannerでのutilsでの曲率計算を修正
- Link
https://evaluation.tier4.jp/evaluation/reports/466a4830-cd49-5899-bf57-0e9d0e47250c?project_id=prd_jt
None.
None.
None.
=> fix(star/goal_planner): improve start/goal planner

perception/detected_object_validation/include/detected_object_validation/detected_object_filter/object_lanelet_filter.hpp, perception/detected_object_validation/src/object_lanelet_filter.cpp
Cherry pick https://github.com/autowarefoundation/autoware.universe/pull/8109
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1721631074035729?thread_ts=1719913008.443889&cid=C03S84LDJGG)
- Link
I tested by Lsim.
The CPU usage is better than before. (approximately 23% -> 19% )
None.
None.
None.
=> fix(detected_object_validation): use search for searching intersected lanelet

common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/include/signal_display.hpp, common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/include/traffic_display.hpp, common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/signal_display.cpp, common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/traffic_display.cpp
Cherry-pick following PR to fix RViz plugin.
- https://github.com/autowarefoundation/autoware.universe/pull/8098
- Link
PSim
None.
None.
None.
=> fix(autoware_overlay_rviz_plugin): topic type of traffic light (#8098)

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/node.hpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/type_alias.hpp, planning/autoware_obstacle_cruise_planner/src/node.cpp, planning/autoware_path_optimizer/include/autoware/path_optimizer/node.hpp, planning/autoware_path_optimizer/src/node.cpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp, planning/autoware_velocity_smoother/src/node.cpp
https://star4.slack.com/archives/C03QW0GU6P7/p1721696047974389
Cherry-pick of
- https://github.com/autowarefoundation/autoware.universe/pull/8160
- https://github.com/autowarefoundation/autoware.universe/pull/8161
- Link
None.
None.
None.
=> fix: all the processing_time publishing of the planning works as expected

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
Resolve those build errors accompanied by https://github.com/tier4/autoware.universe/pull/1419
```
/home/shmpwk/xx1/pilot-auto.xx1.v0.45.0.0/src/autoware/universe/planning/behavior_path_start_planner_module/src/start_planner_module.cpp: In member function ‘bool behavior_path_planner::StartPlannerModule::isPreventingRearVehicleFromPassingThrough() const’:
/home/shmpwk/xx1/pilot-auto.xx1.v0.45.0.0/src/autoware/universe/planning/behavior_path_start_planner_module/src/start_planner_module.cpp:369:5: error: ‘autoware’ has not been declared
369 |     autoware::behavior_path_planner::utils::parking_departure::calcFeasibleDecelDistance(
|     ^~~~~~~~
/home/shmpwk/xx1/pilot-auto.xx1.v0.45.0.0/src/autoware/universe/planning/behavior_path_start_planner_module/src/start_planner_module.cpp: In lambda …
```
=> fix(start/goal_planner): bug of autoware prefix and current_pose

perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/8176
- Link
None.
None.
None.
=> feat(map_based_prediction): add time_keeper (#8176)

planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp
dynamic avoidanceの処理負荷削減
* decrease computation cost
* remove TODO
* fix
https://github.com/autowarefoundation/autoware.universe/pull/7986
---------
- Link
None.
None.
None.
=> perf(dynamic_obstacle_avoidance): decrease the computation time with time_keeper (#7986)

perception/detected_object_validation/include/detected_object_validation/detected_object_filter/object_lanelet_filter.hpp, perception/detected_object_validation/src/object_lanelet_filter.cpp
* add local r-tree for fast searching
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/8240
https://tier4.atlassian.net/browse/RT1-7219
None.
None.
None.
=> perf(autoware_detected_object_validation): reduce lanelet_filter processing time  (#8240)

perception/multi_object_tracker/include/multi_object_tracker/multi_object_tracker_core.hpp, perception/multi_object_tracker/src/multi_object_tracker_core.cpp
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/8277
- Link
None.
None.
None.
=> fix(autoware_multi_object_tracker): revert latency reduction logic and bring back to timer trigger #8277

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/7891
- Link
None.
None.
None.
=> feat(out_of_lane): ignore objects coming from behind ego (#7891)

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/7918
- Link
None.
None.
None.
=> feat(out_of_lane): also apply lat buffer between the lane and stop pose

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light_node_container.launch.py
We need this PR if use [this commit](https://github.com/autowarefoundation/autoware.universe/pull/8157)
- https://github.com/autowarefoundation/autoware.universe/pull/8315
None.
None.
None.
=> fix(tier4_perception_launch): set `use_image_transport` in launch #8315

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/8344
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): remove invalid small shift lines

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
fix cherry-pick from https://github.com/autowarefoundation/autoware.universe/pull/6015
https://tier4.atlassian.net/browse/RT0-30867
- Link
None.
None.
None.
=> fix(crosswalk): fix cherry-pick from autowarefoundation#6015

planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/smoother_base.hpp, planning/autoware_velocity_smoother/package.xml, planning/autoware_velocity_smoother/src/node.cpp, planning/autoware_velocity_smoother/src/smoother/smoother_base.cpp
Cherry-pick force acceleration and slow driving
https://github.com/tier4/autoware.universe/pull/1329
https://github.com/tier4/autoware.universe/pull/1409
https://github.com/tier4/FieldOperatorApplication/pull/701
https://github.com/tier4/autoware_launch/pull/529
None
None.
| Added | Srv | `/planning/scenario_planning/velocity_smoother/adjust_common_param` | `std_srvs::srv::SetBool`   | Change parameter for force acceleration |
|Added | Srv | `/planning/scenario_planning/velocity_smoother/slow_driving` | `std_srvs::srv::SetBool` | Set velocity limit for slow driving |
None.
=> feat(motion_velocity_smoother): cherry pick force acceleration and slow driving

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
I have modified the lane change module so that it can utilize `current_lanes` even if `target_lanes` is empty.
When driving manually with Autoware activated, sometimes `target_lanes` would be empty, which would cause `current_lanes` to be empty as well. 
If current_lanes is empty, an error occurs in the `current_lanes.back()` that is called afterwards.
Specifically, I encountered the error at [utils::lane_change::calcMinimumLaneChangeLength(
route_handler, current_lanes.back(), *lane_change_parameters_, direction_);](https://github.com/tier4/autoware.universe/blob/57a0c2890d87da473f6fa750467275fcf4fdb4f9/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp#L1128])
- Nothing
- [TIER IV internal ticket …
=> fix(autoware_behavior_path_lane_change_module): avoid empty current lanes

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
Reduce computational cost.
- See https://github.com/autowarefoundation/autoware.universe/pull/8344
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): remove invalid small shift lines (#8344)

control/autoware_mpc_lateral_controller/src/mpc.cpp
add timestamp and frame ID to published trajectory
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/8164
- Link
None.
None.
None.
=> fix(autoware_mpc_lateral_controller): add timestamp and frame ID to published trajectory (#8164)

launch/tier4_perception_launch/launch/object_recognition/detection/filter/radar_filter.launch.xml
Radar_lanelet_filtering_range_param is not passed properly.
We need to merge this PR after [launcher PR 522](https://github.com/tier4/autoware_launch/pull/522) is merged.
- Link
None.
None.
None.
=> fix(tier4_perception_launch): radar_lanelet_filtering_range_param_path

perception/traffic_light_classifier/src/nodelet.cpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/8412
https://github.com/autowarefoundation/autoware.universe/pull/8412
None.
None.
None.
=> fix(traffic_light_classifier): fix traffic light monitor warning (#8412)

common/autoware_universe_utils/include/autoware/universe_utils/system/time_keeper.hpp, common/autoware_universe_utils/src/system/time_keeper.cpp
same as https://github.com/autowarefoundation/autoware.universe/pull/8425
This PR would fix the memory problem with map_based_prediction.
https://star4.slack.com/archives/C03S84LDJGG/p1723189282452959?thread_ts=1723082650.906059&cid=C03S84LDJGG
- Link
None.
None.
None.
=> fix(autoware_universe_utils): fix memory leak of time_keeper

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/8432
- Link
None.
None.
None.
=> perf(static_obstacle_avoidance): improve logic to reduce computational cost (#8432)

common/autoware_universe_utils/examples/example_lru_cache.cpp, common/autoware_universe_utils/include/autoware/universe_utils/system/lru_cache.hpp, common/autoware_universe_utils/test/src/system/test_lru_cache.cpp, perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp, perception/autoware_map_based_prediction/src/path_generator.cpp
Improve performance of map_based_prediction.
* autoware_map_based_prediction
https://github.com/autowarefoundation/autoware.universe/pull/8031
https://github.com/autowarefoundation/autoware.universe/pull/8403
https://github.com/autowarefoundation/autoware.universe/pull/8406
https://github.com/autowarefoundation/autoware.universe/pull/8416
https://github.com/autowarefoundation/autoware.universe/pull/8427
https://github.com/autowarefoundation/autoware.universe/pull/8413
https://github.com/autowarefoundation/autoware.universe/pull/8461
https://github.com/autowarefoundation/autoware.universe/pull/8467
* autoware_universe_utils
https://github.com/autowarefoundation/autoware.universe/pull/8456
- Link
None.
None.
None.
=> perf(autoware_map_based_prediction autoware_universe_utils): improve performance of map_based_prediction

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/data_manager.hpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/turn_signal_decider.hpp, planning/behavior_path_planner_common/src/turn_signal_decider.cpp
Cherry-pick the modification into beta branches.
- https://github.com/autowarefoundation/autoware.universe/pull/8463#issuecomment-2288109965
None.
None.
None.
=> fix(turn_signal, lane_change, goal_planner): add optional to tackle lane change turn signal and pull over turn signal

perception/autoware_map_based_prediction/config/map_based_prediction.param.yaml, perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/include/map_based_prediction/path_generator.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp, perception/autoware_map_based_prediction/src/path_generator.cpp
cherry pick of
https://github.com/autowarefoundation/autoware.universe/pull/8462
https://github.com/autowarefoundation/autoware_launch/pull/1118
this PR should be merged first
https://github.com/tier4/autoware_launch/pull/545
=> chore(map_based_prediction): debug options

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/8471
* fix(autoware_map_based_prediction): use surrounding_crosswalks instead of external_surrounding_crosswalks
* perf(autoware_map_based_prediction): enhance speed by removing unnecessary calculation
- Link
None.
None.
None.
=> perf(autoware_map_based_prediction): enhance speed by removing unnecessary calculation

sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp
Perceptionのチラツキ問題のFix
https://tier4.atlassian.net/browse/RT0-32401
- Link
None.
None.
None.
=> fix(ring_outlier_filter): bugfix for large delay in perception in xx1 release

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
cherry-pick of https://github.com/tier4/autoware.universe/pull/1469
- Link
None.
None.
None.
=> perf(autoware_map_based_prediction): removed duplicate findNearest calculations (#8490)

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp
cherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/8326
据え切り発進(停車)で経路歪む問題を修正
- Link
None.
None.
None.
=> fix(start/goal_planner): align geometric parall parking start pose with center line (#8326)

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/freespace_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/geometric_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/shift_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
goal planner高速化・タイムキーパー追加
- https://github.com/autowarefoundation/autoware.universe/pull/8194
- https://github.com/autowarefoundation/autoware.universe/pull/8193
- https://github.com/autowarefoundation/autoware.universe/pull/8195
- Link
wip: 2024/08/08 https://evaluation.tier4.jp/evaluation/reports/d0a8712f-68b2-5441-8bc5-fe732a1d142c/?project_id=prd_jt
None.
None.
None.
=> perf(goal_planner): reduce processing time

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/test/test_filter_predicted_objects.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/8439
Should greatly reduce performance issues with the `out_of_lane` module.
- Link
None.
None.
None.
=> perf(out_of_lane): use rtree to get stop lines and trajectory lanelets

planning/trajectory_repeater/src/trajectory_repeater.cpp, planning/trajectory_repeater/src/trajectory_repeater.hpp, system/leader_election_converter/README.md, system/leader_election_converter/src/common/converter/log_converter.hpp, system/leader_election_converter/src/common/converter/mrm_converter.cpp, system/leader_election_converter/src/common/converter/mrm_converter.hpp
This PR exchanges mrm_state to adapi's one in leader_election_converter.
- Link
None.
None.
None.
=> fix(leader_election_converter): use adapi mrm state

system/mrm_stop_operator/package.xml, system/mrm_stop_operator/src/mrm_stop_operator.cpp, system/mrm_stop_operator/src/mrm_stop_operator.hpp
This PR exchanges mrm_state to adapi's one in mrm_stop_operator.
- Link
None.
None.
None.
=> fix(mrm_stop_operator): use adapi mrm state

launch/tier4_system_launch/launch/system.main.mrm-v0.6.tmp.launch.xml
This PR changes `/system/fail_safe/mrm_state/tmp` to `/system/fail_safe/mrm_state`
- Link
None.
None.
None.
=> fix(tier4_system_launch): change mrm state name

perception/lidar_transfusion/CMakeLists.txt, perception/lidar_transfusion/README.md, perception/lidar_transfusion/config/transfusion.param.yaml, perception/lidar_transfusion/include/lidar_transfusion/preprocess/pointcloud_densification.hpp, perception/lidar_transfusion/include/lidar_transfusion/preprocess/preprocess_kernel.hpp, perception/lidar_transfusion/include/lidar_transfusion/preprocess/voxel_generator.hpp, perception/lidar_transfusion/include/lidar_transfusion/ros_utils.hpp, perception/lidar_transfusion/include/lidar_transfusion/transfusion_config.hpp, perception/lidar_transfusion/include/lidar_transfusion/utils.hpp, perception/lidar_transfusion/lib/preprocess/pointcloud_densification.cpp, perception/lidar_transfusion/lib/preprocess/preprocess_kernel.cu, perception/lidar_transfusion/lib/preprocess/voxel_generator.cpp, perception/lidar_transfusion/package.xml, perception/lidar_transfusion/schema/transfusion.schema.json, perception/lidar_transfusion/src/lidar_transfusion_node.cpp, perception/lidar_transfusion/test/test_detection_class_remapper.cpp, perception/lidar_transfusion/test/test_nms.cpp, perception/lidar_transfusion/test/test_postprocess_kernel.cpp, perception/lidar_transfusion/test/test_postprocess_kernel.hpp, perception/lidar_transfusion/test/test_preprocess_kernel.cpp, perception/lidar_transfusion/test/test_preprocess_kernel.hpp, perception/lidar_transfusion/test/test_ros_utils.cpp, perception/lidar_transfusion/test/test_voxel_generator.cpp, perception/lidar_transfusion/test/test_voxel_generator.hpp
cherry-pick 
https://github.com/autowarefoundation/autoware.universe/pull/7745
https://github.com/autowarefoundation/autoware.universe/pull/7890
- Link
None.
None.
None.
=> feat(lidar_transfusion): update TransFusion-L model

common/qp_interface/include/qp_interface/osqp_csc_matrix_conv.hpp, common/qp_interface/include/qp_interface/osqp_interface.hpp, common/qp_interface/include/qp_interface/proxqp_interface.hpp, common/qp_interface/include/qp_interface/qp_interface.hpp, common/qp_interface/src/osqp_csc_matrix_conv.cpp, common/qp_interface/src/osqp_interface.cpp, common/qp_interface/src/proxqp_interface.cpp, common/qp_interface/src/qp_interface.cpp, common/qp_interface/test/test_csc_matrix_conv.cpp, common/qp_interface/test/test_osqp_interface.cpp, common/qp_interface/test/test_proxqp_interface.cpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/node.hpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/type_alias.hpp, planning/autoware_obstacle_cruise_planner/src/node.cpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/jerk_filtered_smoother.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/l2_pseudo_jerk_smoother.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/linf_pseudo_jerk_smoother.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/smoother_base.hpp, planning/autoware_velocity_smoother/package.xml, planning/autoware_velocity_smoother/src/node.cpp, planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp, planning/autoware_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp, planning/autoware_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp, planning/autoware_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/trajectory_utils.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
cherry-pick several changes for the performance improvement of velocity_smoother
- https://github.com/autowarefoundation/autoware.universe/pull/8028
- https://github.com/autowarefoundation/autoware.universe/pull/8030
not related changes
- https://github.com/autowarefoundation/autoware.universe/pull/8161
- https://github.com/autowarefoundation/autoware.universe/pull/8029
- Link
None.
None.
None.
=> perf(velocity_smoother): decrease the processing time

control/autoware_vehicle_cmd_gate/README.md, control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
cherry-pick: 
https://github.com/autowarefoundation/autoware.universe/pull/8479
https://github.com/autowarefoundation/autoware.universe/pull/8084
- Link
None.
None.
None.
=> feat(autoware_vehicle_cmd_gate): check the timestamp of input topics to avoid using old topics

localization/stop_filter/config/stop_filter.param.yaml
RoboShuttleは速度の分解能が0.001m/sまであるが、stop_filterは0.1m/sで0にしてしまうため、しきい値を変更する
現在stop_filterのconfigがlauncherに存在しないため、暫定的にこのファイルを修正する
[CompanyName internal link](https://tier4.atlassian.net/browse/VEH-1001)
0.01m/sを下回らないと0m/sにならないことが確認できた
None.
None.
None.
=> fix: change stop_filter vx 0.1 -> 0.01 

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
ノード死を修正
https://star4.slack.com/archives/CEV8XMJBV/p1724647690745749?thread_ts=1724404193.762779&cid=CEV8XMJBV
https://github.com/autowarefoundation/autoware.universe/pull/8610
- Link
None.
None.
None.
=> fix(goal_planner): remove time keeper in non main thread (#8610)

sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
https://github.com/autowarefoundation/autoware.universe/pull/8525 のbackport
- Link
https://star4.slack.com/archives/C076E8EBJTG/p1724036108812549
None.
None.
None.
=> chore(autoware_pointcloud_preprocessor): change unnecessary warning message to debug (backport #8525)

planning/autoware_rtc_interface/include/autoware/rtc_interface/rtc_interface.hpp, planning/autoware_rtc_interface/src/rtc_interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
With this PR force execution and force cancel is enabled via FOA for xx1.
Easy explanation about the functions in FOA.
[FOAによる介入手法一覧](https://tier4.atlassian.net/wiki/spaces/~712020d58fded3c3c64c03944f9854862e9ca6/pages/3260219764/FOA)
https://github.com/tier4/autoware_launch/pull/538
Could engage in PSim.
None.
| Change type   | Parameter Name | Type     | Default Value | Description       |
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added| `cancel.force.duration`   | `double` | `2.0`         | Time until avoidance path is regenerated |
None.
=> feat(lane_change, avoidance): add force execution and cancel

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
- See https://github.com/autowarefoundation/autoware.universe/pull/8433.
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): change avoidance condition (#8433)

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/type_alias.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Cherry pick https://github.com/autowarefoundation/autoware.universe/pull/8545 https://github.com/autowarefoundation/autoware.universe/pull/8551
https://github.com/tier4/autoware_launch/pull/569
PSim
None.
None.
None.
=> fix(static_obstacle_avoidance): cherry-pick AWF #8545, #8551

vehicle/autoware_accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/8593
- Link
None.
None.
None.
=> feat(autoware_accel_brake_map_calibrator): conditional actuation data processing based on source

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/launch/mrm_handler.launch.xml, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/8080
---------
- Link
None.
None.
None.
=> feat(mrm_handler): input gear command (#8080)

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp
- cherry pick: https://github.com/autowarefoundation/autoware.universe/pull/8720
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): use wrong parameter (#8720)

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.hpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_external_request_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/include/autoware/behavior_path_sampling_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/include/autoware/behavior_path_sampling_planner_module/sampling_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
- cherry pick: https://github.com/autowarefoundation/autoware.universe/pull/8675
[BACKGROUND](https://star4.slack.com/archives/C03QW0GU6P7/p1724664201319669)
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-33328)
None.
None.
None.
=> fix(bpp): use common steering factor interface for same scene modules (#8675)

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp
* modify lane change requested condition
* Update planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp
* style(pre-commit): autofix
* fix docstring
---------
- Link
None.
None.
None.
=> fix(lane_change): modify lane change requested condition (#8510)

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/type_alias.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Cherry pick https://github.com/autowarefoundation/autoware.universe/pull/8545 https://github.com/autowarefoundation/autoware.universe/pull/8551 to stabilize the envelope polygon for avoidance target objects.
https://github.com/tier4/autoware_launch.x2/pull/771
PSim + Perception Reproducer.
For detail look at the JIRA tickets as below:
・https://tier4.atlassian.net/browse/RT0-33018
・https://tier4.atlassian.net/browse/RT0-33293
・https://tier4.atlassian.net/browse/RT0-33348
None.
None.
None.
=> fix(static_obstacle_avoidance): cherry-pick #8545, #8551

control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
https://tier4.atlassian.net/browse/RT0-33317 の修正PRです。
不具合は速度制御の勾配計算部分において発生しており、
same pointによる nanやゼロ割が発生し、その結果lpfがバグって復帰できない状態となっていました。
この修正により、当該rosbagで再現しないことと、無印でのシナリオテストに問題がないことを確認しました。
無印側修正 PR https://github.com/autowarefoundation/autoware.universe/pull/8758
- Link
None.
None.
None.
=> fix(pid_longitudinal_controller): fix the same point error (#8758)

planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp
The motion_velocity_planner node implements two publishers with the same topic name.
https://github.com/tier4/autoware.universe/blob/c1011857f1f31ccdff9ede41b51f004889c51786/planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp#L85-L86
https://github.com/tier4/autoware.universe/blob/c1011857f1f31ccdff9ede41b51f004889c51786/planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp#L102
This will result in the following error when starting Autoware.
~~~bash
1725517904.5326092 [ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'motion_velocity_planner' of type 'autoware::motion_velocity_planner::MotionVelocityPlannerNode' in container '/planning/scenario_planning/lane_driving/motion_planning/motion_planning_container …
=> fix(motion_velocity_planner): fix duplicated topic name

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
https://star4.slack.com/archives/C03QW0GU6P7/p1725585793943889
の修正。
cherry-pick 
- https://github.com/autowarefoundation/autoware.universe/pull/8714
- 物体検出エリアが狭くなる問題(lane boundが2点のみのとき) 
- https://github.com/autowarefoundation/autoware.universe/pull/8780
- time keeperをマルチスレッドで不適切に利用したためノード死  
- Link
None.
None.
None.
=> fix(goal planner): fix scenario fail and data race beta/v0.34

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
We implement a service to reset MRM behavior.
> service name: /system/clear_mrm
service type: std_srvs/Trigger
- Link
None.
None.
None.
=> feat: implement service for clear MRM behavior

common/autoware_motion_utils/src/resample/resample.cpp, common/autoware_motion_utils/test/src/resample/test_resample.cpp
Cherry pick of https://github.com/autowarefoundation/autoware.universe/pull/8768 for v0.29.0
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-7712?atlOrigin=eyJpIjoiYjVkY2IzOTkzOTVhNDM2Nzk5MWJmY2UzYmMyMDIxZGYiLCJwIjoiaiJ9)
PSim test and Evaluator test were performed.
None.
None.
None.
=> feat(autoware_motion_utils): set zero velocity after stop in resample trajectory

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
LC module kept rtc cooperateStatus as `RUNNING`, where it needed to be `FAILED`. This caused many LC module appearing on the FOA screen.
It can be easily reproduced in PSim as below:
[Screencast from 2024年09月09日 16時54分38秒.webm](https://github.com/user-attachments/assets/7be75bde-320e-4550-b768-9ab8d8f06e08)
This PR solves the problem by appropriately transiting the RTC cooperateStatus. 
None
PSim
[Screencast from 2024年09月09日 17時00分58秒.webm](https://github.com/user-attachments/assets/b1583af1-737e-4a00-b8d5-de5fc7732954)
None.
None.
None.
=> fix(lane_change): transit rtc status to failure for some condition

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/8817
https://star4.slack.com/archives/C074CCKN35E/p1724808429233129
None.
None.
None.
=> feat: crosswalk keep stopping v0.19.1.1

perception/image_projection_based_fusion/include/image_projection_based_fusion/pointpainting_fusion/pointpainting_trt.hpp, perception/lidar_centerpoint/include/lidar_centerpoint/centerpoint_trt.hpp
This PR increases CAPACITY_POINT to avoid crashing due to the large number of points.
⚠️ This is a temporary workaround for this branch.
Since the following PR also addresses this issue, I tried to cherry-pick it, but there were too many conflicts.
Therefore, I directly changed the CAPACITY_POINT in the current code.
- https://github.com/autowarefoundation/autoware.universe/pull/7936
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-31777)
I confirmed node doesn't crash on the bench environment.
None.
None.
None.
=> fix(lidar_centerpoint, pointpainting): increase CAPACITY_POINT to avoid crashing

control/autoware_mpc_lateral_controller/CMakeLists.txt, control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/vehicle_model/vehicle_model_adt_kinematics.hpp, control/autoware_mpc_lateral_controller/src/mpc.cpp, control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp, control/autoware_mpc_lateral_controller/src/vehicle_model/vehicle_model_adt_kinematics.cpp, simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/articulate/sim_model_delay_articulate_acc_geared.cpp
MPC Lateral ControllerのVehicleModle用のADTモデルを作成した。
ステアリング角の微分項は未実装。
- Link
None.
None.
None.
=> feat(autoware_mpc_lateral_controller): create ADT model as vehicle model for mpc

system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
This patch fixes an issue that causes the hazard light to NOT activate when an emergency stop is issued.
Evidence is here: https://star4.slack.com/archives/C03QW0GU6P7/p1727251764419749
- Link
None.
None.
None.
=> fix(emergency_handler): emergency hazard timestamp

simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/articulate/sim_model_delay_articulate_acc_geared.hpp, simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp, simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/articulate/sim_model_delay_articulate_acc_geared.cpp
ハンドル旋回速度による車両角速度への影響への係数を追加。
None.
None.
None.
None.
=> feat: add rear_slip_coeff param to adt model

perception/multi_object_tracker/package.xml
I add diagnostic updater to the dependency of multi object tracker, because it cannot be built now.
- Link
https://evaluation.ci.tier4.jp/evaluation/reports/e7cad917-82ec-52b5-ba4a-1fd621ccd2ac/builds/5547e9db-6bc0-54ec-8b16-16b2d8210830?project_id=x2_dev
None.
None.
None.
=> chore: fix dependency of mult object tracker

control/autoware_autonomous_emergency_braking/package.xml, control/autoware_control_evaluator/CMakeLists.txt, control/autoware_control_evaluator/README.md, control/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp, control/autoware_control_evaluator/include/autoware/control_evaluator/metrics/deviation_metrics.hpp, control/autoware_control_evaluator/launch/control_evaluator.launch.xml, control/autoware_control_evaluator/package.xml, control/autoware_control_evaluator/param/control_evaluator.defaults.yaml, control/autoware_control_evaluator/src/control_evaluator_node.cpp, control/autoware_control_evaluator/src/metrics/deviation_metrics.cpp, control/autoware_evaluator_utils/CMakeLists.txt, control/autoware_evaluator_utils/README.md, control/autoware_evaluator_utils/include/autoware/evaluator_utils/evaluator_utils.hpp, control/autoware_evaluator_utils/package.xml, control/autoware_evaluator_utils/src/evaluator_utils.cpp
This PR introduces the control evaluator.
The control evaluator constantly monitors AEB topics and it is used by the driving log replayer V2 when doing scenario evaluations using rosbags.
requires changes to launch: https://github.com/tier4/autoware_launch.x1.eve/pull/486
- Link
PSim to check if control_evaluator's topic is properly published.
None.
None.
None.
=> feat(control_evaluator): add control_evaluator for v0.3.19

control/autoware_autonomous_emergency_braking/src/node.cpp
add sanity checks. cherry-pick ([#8998](https://github.com/autowarefoundation/autoware.universe/pull/8998)) 
- Link
None.
None.
None.
=> feat(autonomous_emergency_braking): add sanity chackes (#8998)

planning/behavior_path_planner_common/src/turn_signal_decider.cpp
cherry pick [PR](https://github.com/autowarefoundation/autoware.universe/pull/9005)
- [TIERIV INTERNAL TICKET LINK](https://tier4.atlassian.net/browse/RT0-33633)
run psim and confimed blinker keep turning on
[Screencast from 2024年10月02日 16時48分43秒.webm](https://github.com/user-attachments/assets/f907f9c3-7bd9-4769-b76e-2ea15cbfab05)
None.
None.
=> feat(autoware_behavior_path_planner_common): disable feature of turning off blinker at low velocity

control/autoware_autonomous_emergency_braking/src/node.cpp
add sanity checks to prevent crashes ([cherry-pick #8998](https://github.com/autowarefoundation/autoware.universe/pull/8998))
Related issue ticket: https://tier4.atlassian.net/browse/RT0-33710?focusedCommentId=188714
- Link
The changes only involve checking for vector emptiness so there is no change to the AEB behavior. Regardless, compilation was performed and Psim was used to test if the module compiles properly and if there are no problems. 
Psim simulation to see if the AEB module runs without problems and compiles properly: As it can be seen in the image below, the module executes without problems. Objects were also placed on the simulated vehicle way to see if the module works properly. No problems found.
None.
None.
None.
=> fix(autonomous_emergency_braking): add sanity checks (#8998)

planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
When the psim-ego stops in front of a red traffic lights and the rosbag-ego moves at a distance from the psim-ego, the reproducer stops publishing new messages so the psim-ego freezes forever (because the traffic lights keep red forever). 
- Link
Test with Psim:
(The purple trajectory is rosbag-ego.)
Before:
[Screencast from 10-04-2024 06:39:20 PM.webm](https://github.com/user-attachments/assets/f48e9967-e80e-46a2-871a-9472ed84109e)
After:
[Screencast from 10-04-2024 06:38:00 PM.webm](https://github.com/user-attachments/assets/b3457af6-44f7-42b8-ac19-e84868c01d7c)
None.
None.
None.
=> fix(planning_debug_tools): fix a bug of perception reproducer

planning/autoware_path_optimizer/src/mpt_optimizer.cpp
何度か発生しているpath_optimizer起因で、trajectoryが消える、あるいはegoから離れる問題へのv3.1系列側への対応PRです。
x2 v3.1系列に対しては、挙動の変更はせずに、WARNメッセージの追加のみを行うこととしました。
https://star4.slack.com/archives/CRUE57C30/p1727746662736939
https://tier4.atlassian.net/browse/RT0-33698
AWF側
https://github.com/autowarefoundation/autoware.universe/pull/9033
x2 2.3系列
https://github.com/tier4/autoware.universe/pull/1576
- Link
None.
None.
None.
=> chore(path_optimizer): add warn msg for exceptional behavior (#9033)

planning/behavior_path_lane_change_module/README.md, planning/behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_lane_change_module/src/scene.cpp
Fix issue where lane change module's approvals chatter when there's many parked object present.
These commits are already in the main branch, however due to the significant amount of conflicts, cherry-pick is not possible.
1. https://github.com/autowarefoundation/autoware.universe/pull/6288
2. https://github.com/autowarefoundation/autoware.universe/pull/8316
⚠️ : https://github.com/tier4/autoware_launch.x2/pull/809 needs to be merged together
Chattering is present before the final approval.
https://github.com/user-attachments/assets/b9509906-8610-40d9-b96a-76b427621421
The chattering is removed.
https://github.com/user-attachments/assets/88b22b98-7f4d-42dd-8fa2-1eaa1341d124
- Link
None.
None.
None.
=> fix(lane_change): reduce approval chattering

planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp
Fix issue where the lanelets at the end of the path were considered as "out of lane", causing wrong stops.
An similar fix is being added to the `main` branch with this PR: https://github.com/autowarefoundation/autoware.universe/pull/8870
Because the implementation on `main` is very different (moved from `behavior_velocity_planner` to `motion_velocity_planner`, new logic, etc), this fix cannot be cherry-picked.
- [TIER IV JIRA link](https://tier4.atlassian.net/browse/RT0-33630)
Perception replayer + Psim.
None.
None.
None.
=> feat(out_of_lane): ignore lanelets beyond the last path point

planning/autoware_mission_planner/README.md, planning/autoware_mission_planner/config/mission_planner.param.yaml, planning/autoware_mission_planner/launch/mission_planner.launch.xml, planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp, planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp
バス停スキップのテストに必要なreroute周りのfeatureを取り込みます。
- https://github.com/autowarefoundation/autoware.universe/pull/7842
- https://github.com/autowarefoundation/autoware.universe/pull/8757
launcher
- https://github.com/tier4/autoware_launch.xx1/commit/88e1fa10b51cc71b94244dc0133480f7f0ffad9a
None.
None.
None.
=> feat(mission_planner): reroute feature for bus stop skip

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_lane_change_module/src/utils/utils.cpp
The lane change module evaluates the validity of the lane change start point. If the start point is determined to be invalid, the module responds by placing a stop point only at the terminal start position.
An invalid start point occurs when it is not located within the target neighboring lane.
However, as highlighted in the `RT0-33761`, checking the start point's validity is impractical in certain scenarios. By the time the start point becomes valid, the expected stop point's position is already behind the ego vehicle. This results in the stop point being incorrectly placed behind the ego vehicle, leading to sudden and unintended deceleration.
The proposed PR addresses this issue by improving how the distance is captured. It ensures that only objects located between the target lane start …
=> fix(lane_change): change stopping logic (RT0-33761)

sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
https://github.com/autowarefoundation/autoware.universe/pull/8525 のbackport
- https://tier4.atlassian.net/browse/VEH-1097
- https://star4.slack.com/archives/CRUE57C30/p1729044019642129
コンソール出力のレベルの変更のため、コード確認のみ実施した
None.
None.
None.
=> chore(autoware_pointcloud_preprocessor): change unnecessary warning message to debug (#8525)

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp, planning/behavior_path_avoidance_module/src/scene.cpp
- Cherry pick: https://github.com/autowarefoundation/autoware.universe/pull/9089
- TICKET LINK: https://tier4.atlassian.net/browse/RT0-33610
- Link
None.
None.
None.
=> fix(avoidance): don't insert stop line if the ego can't avoid or return (#9089)

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
Crash happened in `goal planner` from  X2 v3.1.1.
```
[component_container_mt-6] [ERROR 1729579718.156755464] [lanelet2_extension] getExpandedLanelet(): "Fail to expand lanelet. output may be undesired. Lanelet points interval in map data could be too narrow." at (/home/autoware/autoware.proj/src/autoware/common/tmp/lanelet2_extension/lib/utilities.cpp:L437)
[component_container_mt-6] [ERROR 1729579719.252083043] [lanelet2_extension] getExpandedLanelet(): "Fail to expand lanelet. output may be undesired. Lanelet points interval in map data could be too narrow." at (/home/autoware/autoware.proj/src/autoware/common/tmp/lanelet2_extension/lib/utilities.cpp:L437)
[component_container_mt-6] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-6]   what(): …
```
=> fix: remove ScopedTimeTrack which causes goal planner crash

system/dummy_infrastructure/config/dummy_infrastructure.param.yaml, system/dummy_infrastructure/include/dummy_infrastructure/dummy_infrastructure_node.hpp, system/dummy_infrastructure/src/dummy_infrastructure_node/dummy_infrastructure_node.cpp
Modified to allow multiple states to be delivered to accommodate VTL in scenario simulation.
Added a mode to explore the state of Command.
Sends a state that permits Approve if the state is 1 or more in the Command from the Planner.
Apply the existing PR here as well.
- https://github.com/autowarefoundation/autoware.universe/pull/1717
- https://tier4.atlassian.net/wiki/spaces/EVA/pages/3081961596/eve+VTL+PSim+CI
- [Evaluator](https://evaluation.tier4.jp/evaluation/reports/b93ee41b-40bc-5efa-839e-12976d91705d?project_id=autoware_dev)
- Link
Already implemented in the above PR.
None.
None.
None.
=> feat(dummy_infrastructure): change to multiple virtual signal state outputs

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp
This PR updates the AEB module to account for bugs and to update the topic name for virtual wall visualization
cherry-picks: #9141 and #9078
- Link
None.
None.
None.
=> feat(autonomous_emergency_braking): cherry pick latest aeb

perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/9150
- Link
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): pointpainting bug fix for point projection (#9150)

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/traffic_light_utils.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/9163
https://github.com/autowarefoundation/autoware.universe/pull/9163
- Link
None.
None.
None.
=> fix(traffic_light_utils): prevent accessing nullopt (#9163)

planning/behavior_path_avoidance_module/src/scene.cpp
Small fix to suppress waring.
- See https://github.com/autowarefoundation/autoware.universe/pull/9142
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): suppress unnecessary warning (#9142)

perception/map_based_prediction/src/map_based_prediction_node.cpp
This reverts commit 5de95b01c51cabadc42cf11f83a534ff7cf4f11e.
- Link
None.
None.
None.
=> fix: sp develop remove non approved change

control/lane_departure_checker/README.md, control/lane_departure_checker/config/lane_departure_checker.param.yaml, control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/include/lane_departure_checker/util/create_vehicle_footprint.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
Reverts tier4/autoware.universe#1565
現時点、自己位置推定ずれ検出機能には「突然眼の前に発生した停止線」に対して自己位置推定のずれがなかった場合においても緊急停止してしまう問題がある。
この問題を孕んだ状態でリリースが難しいというプロジェクト判断により、v0.3.19としては自己位置推定ずれ検出機能のlaunch実装（起動設定及びMRM動作設定）を無効化し、次期リリースv0.3.20で正式にリリースする方針とする。
[管理チケット](https://tier4.atlassian.net/browse/AEAP-1873)
githubのrevert機能を利用していることから、 Revert処理について自動化できているためヒューマンエラーの混入リスクを防止できている。
他PR適用により削除されることが前提となるため、本PR単体としての機能変更の検証は不要と判断。 …
=> revert: "feat(lane_departure_checker): add parameter of footprint_extra_margin"

planning/behavior_velocity_traffic_light_module/src/scene.cpp
To address the issue in the traffic_light module where the vehicle abruptly stops the moment the light changes from amber to green without performing a pass judge when the speed is below 2.0 m/s, we will adjust the speed threshold.
[TIERIV internal link] https://tier4.atlassian.net/browse/RT0-33895
We confirmed an improvement in the sudden deceleration behavior using the rosbag-based logging_simulator, where sudden deceleration had previously been occurring.
None.
None.
None.
=> feat(behavior_velocity_traffic_light_module): change threshold velocity of pass judge for preventing sudden stop

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/traffic_light_utils.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/9204
- Link
None.
None.
None.
=> fix(bpp): prevent accessing nullopt (#9204)

control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp, launch/tier4_localization_launch/launch/localization.launch.xml, launch/tier4_localization_launch/launch/pose_twist_fusion_filter/pose_twist_fusion_filter.launch.xml, planning/autoware_path_optimizer/src/mpt_optimizer.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
Merge https://github.com/tier4/autoware.universe/tree/beta/v0.29.0-1 to [beta/x2_gen2/v0.29.0](https://github.com/tier4/autoware.universe/tree/beta/x2_gen2/v0.29.0).
beta/v0.29.0-1で入っているcommitで、beta/x2_gen2_v0.29.0に入っていないものを取り込みます。
- https://star4.slack.com/archives/CRUE57C30/p1730764602398469?thread_ts=1730763826.033959&cid=CRUE57C30
- Link
Evaluatorで確認済
https://evaluation.tier4.jp/evaluation/reports/b0d44bcc-9048-542e-824d-711539b67bb5?project_id=x2_dev
None.
None.
None.
=> feat: merge beta/v0.29.0 1 to beta/x2_gen2_v0.29.0

perception/autoware_image_projection_based_fusion/config/fusion_common.param.yaml, perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/fusion_node.hpp, perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/utils.hpp, perception/autoware_image_projection_based_fusion/src/fusion_node.cpp, perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/roi_cluster_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/utils/utils.cpp
Add an option point_project_to_unrectified_image to switch if the point project considers lens distortion or not.
cherry-picked from: https://github.com/autowarefoundation/autoware.universe/pull/9233
Change in xx1_lancher:
https://github.com/tier4/autoware_launch.xx1/pull/1010
- Link
None.
None.
None.
=> feat(autoware_image_projection_based_fusion): make optional to consider lens distortion or not

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp, planning/behavior_velocity_planner_common/src/scene_module_interface.cpp
cherry pick following two PRs
- https://github.com/autowarefoundation/autoware.universe/pull/9234
- https://github.com/autowarefoundation/autoware.universe/pull/9212
- Link
None.
None.
None.
=> fix(bvp): planning process death

planning/behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_lane_change_module/src/utils/utils.cpp
Cherry pick lane change cancel for delay lane change
- Link
[TIER IV internal Jira link](https://tier4.atlassian.net/browse/RT0-33952)
None.
None.
None.
=> fix(lane_change): delay lane change cancel (#8048)  (for RT0-33952)

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/9234
https://star4.slack.com/archives/C07K1PPNPTR/p1730811957253269?thread_ts=1730429713.872689&cid=C07K1PPNPTR
- Link
None.
None.
None.
=> fix(crosswalk): don't use vehicle stop checker to remove unnecessary callback (#9234)

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/traffic_light_utils.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/9269
- Link
None.
None.
None.
=> fix(bpp): prevent accessing nullopt (#9269)

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker.hpp, control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/9309 
ticket: https://tier4.atlassian.net/browse/RT1-8390
speed up by updating polygons
- Link
None.
None.
None.
=> feat(start_planner): speed up start planner v0.36

launch/tier4_control_launch/launch/control.launch.xml
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/9263 
Mainly used for DLRV2 planning control evaluation. 
Requires launch changes:  https://github.com/tier4/autoware_launch/pull/668
* set global param to override autoware state check
* change variable to be more general
* add comment
* move param to control component launch
* change param name to be more straightforward
---------
- Link
None.
None.
None.
=> feat(aeb): set global param to override autoware state check (#9263)

common/interpolation/include/interpolation/spline_interpolation.hpp, common/interpolation/include/interpolation/spline_interpolation_points_2d.hpp, common/interpolation/package.xml, common/interpolation/src/spline_interpolation.cpp
Reverts tier4/autoware.universe#1541
マージ先ブランチを間違えたのでrevertします
=> revert: "fix(interpolation): fix spline bug"

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-34275)
This PR cherry-pick following PR.
- https://github.com/autowarefoundation/autoware.universe/pull/7925
See https://tier4.atlassian.net/browse/RT0-34275?focusedCommentId=195849
None.
None.
None.
=> feat(blind_spot): consider road_shoulder if exist (autowarefoundation#7925)

sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_nodelet.hpp, sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
Added solution for concat diag warn with one frame drop in v3.0.0 Shiojiri (changed to pub warn when two consecutive frames drop).
Same as this [PR](https://github.com/tier4/autoware.universe/pull/1309).
[Tier IV internal link (ticket) ](https://tier4.atlassian.net/browse/RT0-34386)
None.
None.
None.
=> feat(pointcloud preprocessor): add hysteresis to concat diag

planning/behavior_velocity_planner/include/scene_module/detection_area/scene.hpp, planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
This PR implements functionality to enable stopping when obstacles are detected within the DA (Detection Area) after passing the stop line. 
The implemented code leverages existing features from autowarefoundation to meet the requirements specified in the [documentation](https://docs.google.com/presentation/d/1_OSWKhMmRUf1QYhQGOVd9jnOLOWl8S7rGE-5VcO04zk/edit#slide=id.g315595f3e6d_0_10363).
This PR is implemented with reference to the following PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/3114
- https://github.com/autowarefoundation/autoware.universe/pull/9255
The correspondence between design requirements and implementation is as follows:
|Requirement|Implementation Location|
|:--|:--|
|Add Param for margin in StopLine override …
=> feat(detection_area)!: suppression of giving up stopping

control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
Prevent steering when vehicle stopping.
本当の原因はadapiから発行されたpause serviceがvehicle cmd gateで反映されていなさそうなのが問題で、その原因が分かっていない。
暫定対策としてtier/autoware.universeにどの状態でもstop modeでは操舵を使わないようにするoptionを追加します。ただし走行中にstop modeに遷移すると操舵が効かなくなるデグレがありますが、高頻度で据え切りしてしまうより良いと考えての暫定対策。
https://tier4.atlassian.net/browse/RT0-34156
https://tier4.atlassian.net/browse/RT0-34158
https://star4.slack.com/archives/C074CCKN35E/p1730966121326069
- Link
None.
None.
None.
=> feat(autoware_vehicle_cmd_gate): prevent steering when vehicle stopping.

launch/tier4_system_launch/launch/system.launch.xml, system/diagnostic_graph_utils/CMakeLists.txt, system/diagnostic_graph_utils/package.xml, system/diagnostic_graph_utils/src/node/recovery.cpp, system/diagnostic_graph_utils/src/node/recovery.hpp, system/mrm_handler/config/mrm_handler.param.yaml, system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/schema/mrm_handler.schema.json, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
Update for launcher: https://github.com/tier4/autoware_launch.x2/pull/847
**このPRでは、MRMからの自動復帰を選択するための機能を取り込んでいます。**
具体的には、以下の変更を取り込んでいます。
- https://github.com/tier4/autoware.universe/pull/1316
- mrm_handlerでMRM復帰可能かどうかを選択できるようにする
- https://github.com/tier4/autoware.universe/pull/1511
- MRM保持を解除するサービスの追加
- https://github.com/tier4/autoware.universe/pull/1515
- 特定のMRMに対して、自動で復帰するかしないかを選択できるようにする
Related JIRA: https://tier4.atlassian.net/browse/RT0-34249
詳細は下記を確認ください。
[TIER IV INTERNAL](https://tier4.atlassian.net/wiki/spaces/~283541267/pages/3440902397/X2+v4.0.0+MRM#%E2%91%A2%5BinlineCard%5D%E3%81%AE%E5%8F%96%E3%82%8A%E8%BE%BC%E3%81%BF-%EF%BC%88%E3%81%99%E3%81%B9%E3%81%A6%E3%81%AE%E5%BF%85%E8%A6%81%E3%81%AA%E5%A4%89%E6%9B%B4%E3%82%92%E5%8F%96%E3%82%8A%E8%BE%BC%E3%82%93%E3%81%A0%E7%8A%B6%E6%8 …
=> feat(mrm_handler): mrm recoverable option (#1316)

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/README.md, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/shift_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/geometric_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/shift_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp
[RT0-34203](https://tier4.atlassian.net/browse/RT0-34203)対応
[RT0-34203]: https://tier4.atlassian.net/browse/RT0-34203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: lc goal update

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
cherry-pick 
https://github.com/autowarefoundation/autoware.universe/pull/9293
- Link
None.
None.
None.
=> feat(goal_planner): safety check with only parking path (#9293)

system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp, system/system_monitor/src/gpu_monitor/gpu_monitor_base.cpp, system/system_monitor/src/hdd_monitor/hdd_monitor.cpp, system/system_monitor/src/mem_monitor/mem_monitor.cpp, system/system_monitor/src/net_monitor/net_monitor.cpp, system/system_monitor/src/ntp_monitor/ntp_monitor.cpp, system/system_monitor/src/process_monitor/process_monitor.cpp, system/system_monitor/src/voltage_monitor/voltage_monitor.cpp
This PR is used for pilot-auto.x2 after version `beta/v3.1.0`. 
Because Autoware is running on main-ECU and sub-ECU, so we want to get their diagnostic information about the system monitor.
To confirm this information on the rqt-runtime-monitor, I add a hostname for diagnostic information.
[Ticket](https://tier4.atlassian.net/browse/RT0-33182)
This is a related PR. https://github.com/tier4/autoware_launch.x2/pull/833
I tested this PR on my local PC and J6 Bench.
**Local PC**
- Main ECU hostname: DPC***
- Sub ECU hostname: NPC***
**J6 Bench 1.0**
- Main ECU hostname: autoware
- Sub ECU hostname: sub
None.
None.
None.
=> feat(system_monitor): add a hostname for diagnostic information

common/tier4_state_rviz_plugin/package.xml, common/tier4_state_rviz_plugin/src/include/velocity_steering_factors_panel.hpp, common/tier4_state_rviz_plugin/src/velocity_steering_factors_panel.cpp
cherry-pick 
- https://github.com/autowarefoundation/autoware.universe/pull/9346
- https://github.com/autowarefoundation/autoware.universe/pull/9474
- Link
None.
None.
None.
=> feat(factors_panel, tier4_state_rviz_plugin): check abrupt deceleration

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp
なるべく https://github.com/autowarefoundation/autoware.universe/pull/6036/files のdiffを再現するように修正
以下の画像で一番左: オリジナル, 一番右: 今回
same as before
same as before
same as before
- Link
対応する信号をunknownにするとtraffic_lightの壁が出ることを確認
None.
None.
None.
=> revert(behavior_velocity): revert unknown traffic light handling PR6036

perception/lidar_centerpoint/lib/centerpoint_trt.cpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/9488
- Link
None.
None.
None.
=> feat(autoware_lidar_centerpoint): added a check to notify if we are dropping pillars (#9488)

system/control_cmd_switcher/CMakeLists.txt, system/control_cmd_switcher/README.md, system/control_cmd_switcher/config/control_cmd_switcher.yaml, system/control_cmd_switcher/launch/control_cmd_switcher.launch.xml, system/control_cmd_switcher/package.xml, system/control_cmd_switcher/src/control_cmd_switcher/control_cmd_switcher.cpp, system/control_cmd_switcher/src/control_cmd_switcher/control_cmd_switcher.hpp, system/control_cmd_switcher/tool/relay_trajectory.py
This PR adds control cmd switcher node.
- Link
None.
None.
None.
=> feat(control_cmd_switcher): add control cmd switcher

dummy/dummy_gear_cmd_publisher/CMakeLists.txt, dummy/dummy_gear_cmd_publisher/README.md, dummy/dummy_gear_cmd_publisher/config/dummy_gear_cmd_publisher.param.yaml, dummy/dummy_gear_cmd_publisher/launch/dummy_gear_cmd_publisher.launch.xml, dummy/dummy_gear_cmd_publisher/package.xml, dummy/dummy_gear_cmd_publisher/src/dummy_gear_cmd_publisher.cpp, dummy/dummy_gear_cmd_publisher/src/dummy_gear_cmd_publisher.hpp
This PR adds dummy gear cmd publisher node.
- Link
None.
None.
None.
=> feat(dummy_gear_cmd_publisher): add dummy gear cmd publisher

system/mrm_stop_operator/CMakeLists.txt, system/mrm_stop_operator/README.md, system/mrm_stop_operator/config/mrm_stop_operator.param.yaml, system/mrm_stop_operator/launch/mrm_stop_operator.launch.xml, system/mrm_stop_operator/package.xml, system/mrm_stop_operator/src/mrm_stop_operator.cpp, system/mrm_stop_operator/src/mrm_stop_operator.hpp
This PR adds mrm stop operator node.
- Link
None.
None.
None.
=> feat(mrm_stop_operator): add mrm stop operator

system/redundancy_switcher_interface/CMakeLists.txt, system/redundancy_switcher_interface/README.md, system/redundancy_switcher_interface/config/redundancy_switcher_interface.param.yaml, system/redundancy_switcher_interface/launch/redundancy_switcher_interface.launch.xml, system/redundancy_switcher_interface/package.xml, system/redundancy_switcher_interface/schema/redundancy_switcher_interface.schema.json, system/redundancy_switcher_interface/script/relay_to_sub.py, system/redundancy_switcher_interface/src/common/converter/availability_converter.cpp, system/redundancy_switcher_interface/src/common/converter/availability_converter.hpp, system/redundancy_switcher_interface/src/common/converter/log_converter.cpp, system/redundancy_switcher_interface/src/common/converter/log_converter.hpp, system/redundancy_switcher_interface/src/common/converter/mrm_converter.cpp, system/redundancy_switcher_interface/src/common/converter/mrm_converter.hpp, system/redundancy_switcher_interface/src/common/converter/udp_receiver.hpp, system/redundancy_switcher_interface/src/common/converter/udp_sender.hpp, system/redundancy_switcher_interface/src/node/redundancy_switcher_interface.cpp, system/redundancy_switcher_interface/src/node/redundancy_switcher_interface.hpp
This PR adds redundancy switcher interface node.
- Link
None.
None.
None.
=> feat(redundancy_switcher_interface): add redundancy switcher interface

launch/tier4_control_launch/launch/control.launch.py
This PR changes topic name of control cmd on psim and redundant mode.
- Link
None.
None.
None.
=> feat(tier4_control_launch): switch control cmd topic

simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
This PR changes initial control mode on psim.
- Link
None.
None.
None.
=> feat(simple_planning_simulator): initiate manual

perception/lidar_centerpoint/include/lidar_centerpoint/postprocess/non_maximum_suppression.hpp, perception/lidar_centerpoint/lib/postprocess/non_maximum_suppression.cpp
cherry pick of https://github.com/autowarefoundation/autoware.universe/pull/9595
- Link
None.
None.
None.
=> feat(lidar_centerpoint): optimize non-maximum suppression algorithm

perception/image_projection_based_fusion/src/fusion_node.cpp
camera_lidar_fusionの最大数が8になっている制限の撤廃
https://tier4.atlassian.net/browse/RT1-8582?atlOrigin=eyJpIjoiYWUyM2QwOWYwOGM1NDg0NTk3OGJmMTMyY2U3Y2M4MGYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
None.
None.
None.
=> feat: remove max rois limit in the image projection based fusion (#9596)

planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp, planning/surround_obstacle_checker/src/node.cpp
It seemed that surround obstacle checker took a lot of time to transform process. As a result, other callbacks couldn't recieve topics. In this PR, I fixed the timeout value of `tf2::lookupTransform`.
- Link
None.
None.
None.
=> fix(surround_obstacle_checker): use tf2::TimePointZero

control/autoware_mpc_lateral_controller/src/vehicle_model/vehicle_model_bicycle_kinematics.cpp
Cherry pick to fix MPC calculation
fix(autoware_mpc_lateral_controller): fix calculation method of predicted trajectory (#9048)
- Link
None.
None.
None.
=> fix(autoware_mpc_lateral_controller): fix calculation method 

perception/lidar_centerpoint/lib/preprocess/preprocess_kernel.cu
alternative of PR https://github.com/tier4/autoware.universe/pull/1672 
description: please see https://github.com/autowarefoundation/autoware.universe/pull/9608
- Link
None.
None.
None.
=> feat: optimize voxel indexing in preprocess_kernel.cu

perception/autoware_crosswalk_traffic_light_estimator/include/autoware_crosswalk_traffic_light_estimator/node.hpp, perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp
This PR enables to overwrite invalid detection result made by ML.
Concretely, overwrite if below condition:
- undetection -> color: unknown, shape: circle, confidence=0.0
- backlight      -> color: unknown, shape: unknown, confidence=0.0
- occlusion     -> color: unknown, shape: unknown, confidence=0.0
- https://github.com/autowarefoundation/autoware.universe/pull/9667
- Link
I have checked topic contents which is pedestrian signals on logging simulator(pilot-auto and pilot-auto.x2) w/ planning and put gorl pose in order to get route topic.
None.
None.
None.
=> feat(autoware_crosswalk_traffic_light_estimator): overwrite invalid detection result

perception/multi_object_tracker/include/multi_object_tracker/multi_object_tracker_core.hpp, perception/multi_object_tracker/src/multi_object_tracker_core.cpp
implementing trigger timing fix 
https://github.com/autowarefoundation/autoware.universe/pull/8657
https://tier4.atlassian.net/browse/RT2-2054
- Link
None.
None.
None.
=> fix(multi_object_tracker):  implementing trigger timing fix 

launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_merger.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_radar_merger.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml, perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml, perception/image_projection_based_fusion/launch/roi_detected_object_fusion.launch.xml, perception/image_projection_based_fusion/launch/roi_pointcloud_fusion.launch.xml
@TomohitoAndo 
v.4.0.1でAdd-onに刺さったカメラを試す用に必要な変更です．
camera 0--5
camera 8--10
の合計9個のカメラを最大で使用可能にする想定です．
大本のautoware_launchを変更しない限り今までと同様の同様の動作をします．
pointpaintingとsegmentationはこのversionでは使わないと思ったのでskipしました
下記が入る必要があります。
https://github.com/tier4/autoware_launch.x2/pull/882
起動の確認をしただけで処理負荷などは見れてません．
```sh
❯ ros2 node info /perception/object_recognition/detection/clustering/camera_lidar_fusion/roi_cluster_fusion
/perception/object_recognition/detection/clustering/camera_lidar_fusion/roi_cluster_fusion
Subscribers:
/clock: rosgraph_msgs/msg/Clock
/parameter_events: rcl_interfaces/msg/ParameterEvent
/perception/object_recognition/detection/clustering/clusters: tier4_perception_msgs/msg/DetectedObjectsWithFeature
/perception/object_recognition/detection/rois0: …
```
=> feat(camera_lidar_fusion): enable to use camera 8,9,10 in image_projection_based_fusion nodes

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/CMakeLists.txt, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/package.xml, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/test/test_util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test_map/intersection/lanelet2_map.osm
cherry pick https://github.com/tier4/autoware.universe/pull/1482
- Link
None.
None.
None.
=> fix(intersection): cherry pick/pr8561 v0.29.0-1

perception/autoware_crosswalk_traffic_light_estimator/include/autoware_crosswalk_traffic_light_estimator/node.hpp, perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp
same as https://github.com/tier4/autoware.universe/pull/1705
- Link
None.
None.
None.
=> fix: overwrite invalid detection result for gen1

planning/autoware_surround_obstacle_checker/src/debug_marker.cpp, planning/autoware_surround_obstacle_checker/src/debug_marker.hpp
None.
| New     | Pub | `/planing/planning_factors/surround_obstacle_checker` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(surrround_obstacle_checker): use planning factor

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/planner_interface.hpp, planning/autoware_obstacle_cruise_planner/src/node.cpp, planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp, planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp
1. launch Psim.
2. put Ego and Goal on Rviz.
3. put obstacle arround the path.
4. check the topic by echo command.
None.
| New     | Pub | `/planing/planning_factors/obstacle_cruise_planner` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> fix(obstacle_cruise_planner): use planning factor interface

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp, control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp
Cherry pick to fix unstable lateral controller steering command
fix(mpc_lateral_controller): prevent unstable steering command while stopped(https://github.com/autowarefoundation/autoware.universe/pull/9690)
- https://tier4.atlassian.net/browse/RT0-34623?focusedCommentId=200855&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-200855
- https://star4.slack.com/archives/CRUE57C30/p1733911916093339
- PSIM
None.
None.
Prevent unstable steering command when Ego is stopped.
=> fix(mpc_lateral_controller): prevent unstable steering command while stopped

planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/interface/scene_module_manager_interface.cpp
None.
| New     | Pub | `/planing/planning_factors/<MODULE_NAME>` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(bpp): use planning factor

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/path_safety_checker_parameters.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/marker_utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Important for debugging safety check result.
1. [fix(bpp): update collided polygon pose only once #9338](https://github.com/autowarefoundation/autoware.universe/pull/9338)
1. [refactor(lane_change): refactor extended object safety check #9322
](https://github.com/autowarefoundation/autoware.universe/pull/9322)
2. [fix(lane_change): cap ego's predicted path velocity (RT1-8505) #9341
](https://github.com/autowarefoundation/autoware.universe/pull/9341)
1. [feat(lane_change): fix delay logic that caused timing to be late #8549
](https://github.com/autowarefoundation/autoware.universe/pull/8549)
Signal the intention to change lane as soon as possible
1. [fix(lane_change): activate turn signal as soon as we have the intention to change lanes …
=> chore(lane change): cherry-pick bug fixes

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
https://tier4.atlassian.net/wiki/spaces/~382034962/pages/3479405302/v4.0.1
None.
None.
None.
=> fix(static_obstacle_avoidance): cherry pick PRs to improve processing time

control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/debug_values.hpp, control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp, control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/9656
launch側の変更に合わせて、当該機能について最低限の性能向上とデバッグ用データの追加を行うPRです。
以下の件の暫定対応PRです
https://star4.slack.com/archives/CRUE57C30/p1733992025709229
https://tier4.atlassian.net/browse/RT0-34411
None.
None.
None.
=> feat(pid_longitudinal_controller): update trajectory_adaptive; add debug_values, adopt rate limit fillter (#9656)

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
https://github.com/user-attachments/assets/f4cb7e64-fd2b-4247-97db-882db4fd5562
None.
| New     | Pub | `/planing/planning_factors/static_obstacle_avoidance` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(static_obstacle_avoidance): use planning factor

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.hpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_external_request_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp
https://github.com/user-attachments/assets/120b1317-4c74-418c-8fae-9a2e32cf7022
None.
| New     | Pub | `/planing/planning_factors/lane_change_right` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
| New     | Pub | `/planing/planning_factors/lane_change_left` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(lane_change): use planning factor

planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
https://github.com/user-attachments/assets/c4674f53-5f13-4fdc-af3f-ecf271c49e1b
None.
| New     | Pub | `/planing/planning_factors/behavior_path_planner` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(bpp-intersection): use planning factor

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp
https://github.com/user-attachments/assets/23f5eb75-4c67-4808-878b-0b773d09b746
None.
| New     | Pub | `/planing/planning_factors/goal_planner` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(goal_planner): use planning factor

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
https://github.com/user-attachments/assets/9fba8310-35f6-4f7a-9baa-1098204f84b6
None.
| New     | Pub | `/planing/planning_factors/start_planner` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(start_planner): use planning factor

planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/include/autoware/behavior_path_sampling_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/include/autoware/behavior_path_sampling_planner_module/sampling_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/scene.cpp
=> feat(dynamic_obstacle_avoidace, side_shift, sampling_planner): use planning factor

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/planner_manager.cpp
https://github.com/user-attachments/assets/58317ad5-5e6d-4f84-ab89-a576c4c4b48b
None.
| New     | Pub | `/planing/planning_factors/dynamic_obstacle_stop` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(dynamic_obstacle_stop): output planning factor interface

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp
https://github.com/user-attachments/assets/5a1c65a1-363c-4d63-8e8b-7bf3cfedfefa
None.
| New     | Pub | `/planing/planning_factors/out_of_lane` | `tier4_planning_msgs/PlanningFactorArray` | Topic description |
None.
=> feat(out_of_lane): use planning factor

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/9268
* RT1-8427 extending lc path for multiple lc
* Update planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
- Link
None.
None.
None.
=> fix(lane_change): extending lane change path for multiple lane change (RT1-8427) (#9268)

control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4712 により、goalに対してオーバーランした際に、オーバーラン距離が0になってしまうバグが混入していました。
この問題のhotfixし、オーバーラン距離を取得できるようにします。
awfでの修正
https://github.com/autowarefoundation/autoware.universe/pull/9685
3.1への修正
https://github.com/tier4/autoware.universe/pull/1713
related confluence page:
https://tier4.atlassian.net/wiki/spaces/~382034962/pages/3479405302/v4.0.1
- Link
None.
None.
None.
=> fix(pid_longitudinal_controller): fix overrun distance calculation against goal position

control/autoware_mpc_lateral_controller/README.md, control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp, control/autoware_mpc_lateral_controller/param/lateral_controller_defaults.param.yaml, control/autoware_mpc_lateral_controller/src/mpc.cpp, control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp, control/autoware_trajectory_follower_node/param/lateral/mpc.param.yaml
original pr: https://github.com/autowarefoundation/autoware.universe/pull/8436
should be merged with: https://github.com/tier4/autoware_launch.x2/pull/893
[TIER IV INTERNAL](https://tier4.atlassian.net/wiki/spaces/~382034962/pages/3479405302/v4.0.1)
- Link
None.
None.
None.
=> feat(mpc_lateral_controller): add delayed initial state and debug trajectory publishing flags

launch/tier4_system_launch/launch/system.launch.xml, system/hazard_status_converter/launch/hazard_status_converter.launch.xml, system/hazard_status_converter/src/converter.cpp, system/hazard_status_converter/src/converter.hpp
Modifications will be made to the hazard status converter to make it compatible with Tier IV tools.
Change the "diag" included in the hazard status to just the diag type.
Also convert safety faults to latent faults.
- Link
I tested with PSim.
We were able to supress the error content in FMS.
Also, diag that is not linked to MRM can be reported.
None.
None.
None.
=> feat: customize hazard status converter

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
cherry-pick 
- https://github.com/autowarefoundation/autoware.universe/pull/8997
- https://github.com/autowarefoundation/autoware.universe/pull/9279
- Link
None.
None.
None.
=> fix: cherry-pick #8997 and #9279

system/autoware_default_adapi/package.xml, system/autoware_default_adapi/src/planning.cpp, system/autoware_default_adapi/src/planning.hpp
New factor msgs were defined in https://github.com/tier4/tier4_autoware_msgs/pull/155 to output various information of module running state. And, each planning module will use them.
In this PR, I fixed adapi node to convert msg type from `tier4_planning_msgs/PlanningFactorArray` to `autoware_adapi_v1_msgs/VelocityFactorArray(SteeringFactorArray)`.
1. launch psim.
2. put ego and goal.
3. put object on ego path.
4. check the topic `/api/planning/velocity_factors` by echo command.
5. confirm that the node outputs factor like following one.
```
header:
stamp:
sec: 1735008280
nanosec: 610628888
frame_id: map
factors:
- pose:
position:
x: …
```
=> fix(default_adapi): subscribe planning factor

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
https://github.com/user-attachments/assets/84d06dfa-3efc-4f26-819d-b1f4859ca1d8
https://github.com/user-attachments/assets/e99d5647-7a27-4071-bc84-a8ae245bfd25
- https://tier4.atlassian.net/browse/RT0-34894
- https://tier4.atlassian.net/browse/RT0-34891
None.
None.
None.
=> fix(goal_planner_module): adjust object filtering to consider velocity threshold

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/velocity_planning_result.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/README.md, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp
Psim
None.
| Removed | Pub | `/planning/velocity_factors/<MODULE_NAME>` | `autoware_adapi_v1_msgs::msg::VelocityFactorArray`   | Topic description |
None.
=> fix(motion_velocity_planner)!: remove velocity factor 

perception/lidar_centerpoint/lib/preprocess/preprocess_kernel.cu
Revert "Merge pull request #1688 from technolojin/feat/centerpoint/voxel-fill-from-front"
This reverts commit 3326ba5dae3d9f22f78cbe9c6891e595ea31de25, reversing changes made to 16569fc00f58ed0fa45bee7c0bb6d66b3872c66f.
Revert since it had illegal memory access as following
```
[component_container_mt-1] [WARN] [1735120020.355710921] [sensing.lidar.concatenate_data]: transformed_raw_points[/sensing/lidar/top/pointcloud_before_sync] is nullptr, skipping pointcloud publish.
[component_container_mt-1] terminate called after throwing an instance of 'thrust::system::system_error'
[component_container_mt-1]   what():  parallel_for: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
[component_container_mt-1] *** Aborted at 1735120027 (unix time) try "date …
```
=> revert(autoware_lidar_centerpoint): process front voxels first

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
Psim
None.
| Removed | Pub | `/planning/velocity_factors/goal_planner` | `autoware_adapi_v1_msgs::msg::VelocityFactorArray`   | Topic description |
None.
=> fix(goal_planner): remove velocity factor

perception/lidar_centerpoint/lib/preprocess/preprocess_kernel.cu
reimplementation of PR https://github.com/tier4/autoware.universe/pull/1688
AWF implementation https://github.com/autowarefoundation/autoware.universe/pull/9608
with fix of voxel index bug
@knzo25 said
> ポイント: point.x=76.799995
> rangeのfiltert突破するけど
> floorf((point.x - min_x_range + pillar_x_size) / pillar_x_size) - 1;
> でも480になる
> -> floorfの実装おかしい？
```
(76.799995 + 76.800003 + 0.32) / 0.32 - 1
479.99999375
```
- Link
None.
None.
None.
=> fix(lidar_centerpoint): reintroduce voxel order from front

planning/autoware_surround_obstacle_checker/package.xml, planning/autoware_surround_obstacle_checker/src/debug_marker.cpp, planning/autoware_surround_obstacle_checker/src/debug_marker.hpp
Psim
None.
| Removed | Pub | `/planning/velocity_factors/surround_obstacle` | `autoware_adapi_v1_msgs::msg::VelocityFactorArray`   | Topic description |
None.
=> fix(surround_obstacle_checker)!: remove velocity factor

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
Psim
None.
| Removed | Pub | `/planning/velocity_factors/start_planner` | `autoware_adapi_v1_msgs::msg::VelocityFactorArray`   | Topic description |
None.
=> fix(start_planner): remove velocity factor

planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/interface/scene_module_manager_interface.cpp
Psim
None.
| Removed | Pub | `/planning/velocity_factors/intersection` | `autoware_adapi_v1_msgs::msg::VelocityFactorArray`   | Topic description |
None.
=> fix(behavior_path_planner): remove velocity factor

system/diagnostic_graph_utils/launch/logging.launch.xml, system/diagnostic_graph_utils/package.xml, system/diagnostic_graph_utils/src/node/logging.cpp, system/diagnostic_graph_utils/src/node/logging.hpp, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/CMakeLists.txt, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/README.md, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/package.xml, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/plugins/plugins_description.xml, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/jsk_overlay_utils.cpp, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/jsk_overlay_utils.hpp, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/string_stamped_overlay_display.cpp, visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/string_stamped_overlay_display.hpp
以下のbackport
https://github.com/autowarefoundation/autoware.universe/pull/9421
https://github.com/autowarefoundation/autoware.universe/pull/9741
https://github.com/autowarefoundation/autoware.universe/pull/9683
-
- [TIERIV internal ticket](https://tier4.atlassian.net/browse/VEH-1390)
psimにて動作確認を実施した
None.
None.
=> feat: publish error diagnostic graph and visualize in rviz

perception/multi_object_tracker/src/multi_object_tracker_core.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/8484
- Link
None.
None.
None.
=> fix: enable trigger publish when delay_compensation is false

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.hpp
=> add planning_factor_interface to behavior_velocity_planner da, vtl, no_stopping_area

dummy/dummy_gear_cmd_publisher/package.xml, dummy/dummy_gear_cmd_publisher/src/dummy_gear_cmd_publisher.cpp, dummy/dummy_gear_cmd_publisher/src/dummy_gear_cmd_publisher.hpp
This PR modify gear cmd type in dummy gear cmd publisher
- Link
None.
None.
None.
=> modify(dummy_gear_cmd_publisher): replace gear cmd type

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
https://github.com/autowarefoundation/autoware.universe/pull/8721 のbackport
- https://tier4.atlassian.net/browse/VEH-1586
None.
None.
None.
=> fix(static_obstacle_avoidance): change implementation the logic to remove invalid small shift lines (#8721)

planning/behavior_velocity_run_out_module/src/scene.cpp, planning/behavior_velocity_run_out_module/src/scene.hpp
run_outをslow_down_limit.enable = trueで動かすと、JerkFilterによりrun_out以外の停止線も上書きされて無効化されてしまう現象があったため、修正
None
Before:
- stop_lineによる停止線がrun_outのジャークフィルターによって上書きされてしまっている
(走行中にAutoware ControlをDisableにすることで強制的に停止線前で速度が出ている状況を再現)
https://github.com/user-attachments/assets/582469c9-3dd8-4f80-bd95-422d47589c0c
After:
- 既存の停止線がrun_outのジャークフィルターによって上書きされないように修正
(走行中にAutoware ControlをDisableにすることで強制的に停止線前で速度が出ている状況を再現)
https://github.com/user-attachments/assets/f60b82bd-0ee0-4a0d-ae7f-92e9b0678c00
- 通常のJerk Filterは今までどおり正常に機能している状態。直近のrun_outに対しては強い減速かからず、遠方のrun_outに対しては停止指示がかかっている。
(なお、下記の動画ではrun_outのテストのためにobstacle_cruiseを無効にしている)
https://github.com/user-attachments/assets/55c990b7-4a13-401c-adfc-ddbbcbac327c
None.
None.
slow_down_limit.enable = …
=> fix(behavior_velocity_run_out_module): fix slow_down jerk filter

system/diagnostic_graph_utils/src/node/recovery.cpp, system/diagnostic_graph_utils/src/node/recovery.hpp
> [!WARNING]
>  This change is not merged in main branch because this feature is only used in the specific version.
現状はclear_mrm serviceの呼び出しが自動走行中に限定されているため、
MRM発生 -> OR -> MRMが解消される
となった場合に、clear_mrm serviceが呼び出されずにMRMが解除されない課題があります。
これを解消するため、自動運転中という条件を削除しました。
ロジックの変更としてはこの部分のみで、これ以外は不要となった自動運転状態かどうかを取得する部分の削除です。
[INTERNAL JIRA](https://tier4.atlassian.net/browse/RT0-35089)
simple planning simulatorで確認しました。
diag error発生後に`Autoware Control`をOFFにして、**diag errorを解除したが、MRMが継続している。**
https://github.com/user-attachments/assets/5edbc3d1-daa3-41b6-8dbd-91dd89083caf
diag error発生後に`Autoware Control`をOFFにして、**diag errorを解除することで、MRMが解消されている。**
> [!NOTE]
>  Motionがチャタリングしているのは別の既知課題
https://github.com/user-attachments/assets/85339f34-fa34-4739-a933-bdaa468b4f17
None.
None.
None.
=> fix(recovery_node): recover from MRM even duaring manual driving

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/debug.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
This PR is going to cherry-pick: improve turn signal output timing when the ego returns original lane (#8726)
After the static obstacle avoidance, make it faster to turn on the left signal.
- [Slack](https://star4.slack.com/archives/C074CCKN35E/p1738135091382619)
I tested it on local PC by planning simulator.
None.
None.
None.
=> fix(static_obstacle_avoidance): improve turn signal output timing when the ego returns original lane

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/parameters.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_scene.cpp
cherry-pick of the [PR](https://github.com/autowarefoundation/autoware.universe/pull/9785)
Regarding the function stopping behind stationary object in the current lane, the version used in shiojiri have this feature.
Current v4.0.x lacks this feature. But cherry-picking this PR should fix it.
- [Slack conversation link](https://star4.slack.com/archives/C03QW0GU6P7/p1736920185898579)
None.
None.
None.
=> feat(lane_change): revise current lane objects filtering (#9785)

launch/tier4_system_launch/launch/system.launch.xml, system/hazard_status_converter/launch/hazard_status_converter.launch.xml, system/hazard_status_converter/src/converter.cpp, system/hazard_status_converter/src/converter.hpp
Revert this [PR](https://github.com/tier4/autoware.universe/pull/1725) because this change makes Rviz noisy.
- Link
None.
None.
None.
=> fix: revert customized hazard status converter

perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/10087
I added this in [v0.41.3 release note](https://tier4.atlassian.net/wiki/spaces/AIP/pages/3551331742/Pilot.Auto+v0.41.3+Release+Note#%5B%E4%B8%8D%E5%85%B7%E5%90%88%E4%BF%AE%E6%AD%A3%5D.1)
- Link
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): modify incorrect index access in pointcloud filtering for out-of-range points (#10087)

common/autoware_component_interface_tools/package.xml, launch/tier4_system_launch/launch/system.launch.xml, system/autoware_diagnostic_graph_utils/CMakeLists.txt, system/autoware_diagnostic_graph_utils/package.xml, system/autoware_diagnostic_graph_utils/src/node/recovery.cpp, system/autoware_diagnostic_graph_utils/src/node/recovery.hpp, system/autoware_mrm_handler/config/mrm_handler.param.yaml, system/autoware_mrm_handler/include/autoware/mrm_handler/mrm_handler_core.hpp, system/autoware_mrm_handler/package.xml, system/autoware_mrm_handler/schema/mrm_handler.schema.json, system/autoware_mrm_handler/src/mrm_handler/mrm_handler_core.cpp
PR for launcher: https://github.com/tier4/autoware_launch/pull/760
> [!TIP] 
> **These options are disabled as default parameters in the launcher PR, and there are no behavior changes as default.**
This PR cherry-picks these PRs:
- https://github.com/tier4/autoware.universe/pull/1654
- https://github.com/tier4/autoware.universe/pull/1777
This PR introduces the following features:
- `autoware_mrm_handler`
- Added an option to make MRM behavior non-recoverable when it occurs.
- This option is enabled when is_mrm_recoverable is set to false.
- `recovery` node
- Even if is_mrm_recoverable is set to false, the MRM behavior will be recovered unless it is associated with a fatal_error in the diagnostic_graph tree.
- **This node will not be launched as default**.
[TIER IV INTERNAL …
=> feat(mrm_handler): mrm recoverable option

common/autoware_component_interface_tools/package.xml
Fix the following error:
```
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
autoware_component_interface_tools: Cannot locate rosdep definition for [component_interface_utils]
```
- https://github.com/tier4/autoware.universe/pull/1818
None.
None.
None.
=> build: remove dependency on component_interface_utils

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/10121
- Link
Tested on planning simulator
None.
None.
None.
=> fix(lane_change): remove string literals from stopwatch toc (#10121)

sensing/autoware_pointcloud_preprocessor/schema/pickup_based_voxel_grid_downsample_filter_node.schema.json, sensing/autoware_pointcloud_preprocessor/src/downsample_filter/pickup_based_voxel_grid_downsample_filter_node.cpp
Fix crash in the PickupBasedVoxelGridDownsampleFilterComponent when processing empty point cloud data.
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/10115
- Link
None.
None.
None.
=> fix(autoware_pointcloud_preprocessor): empty input validation (#10115)

planning/motion_velocity_planner/autoware_motion_velocity_planner_node_universe/package.xml
xx1 v0.48 built failed. 
This is cherry-picked from https://github.com/autowarefoundation/autoware.universe/pull/10122
- Link
None.
None.
None.
=> chore(motion_velocity_planner_universe): fix build depends (#10122)

planning/autoware_static_centerline_generator/package.xml, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/package.xml, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
Add grid map core dependency for these nodes.
- autoware_static_centerline_generator
- autoware_behavior_velocity_planner
- autoware_motion_velocity_planner_node
- https://github.com/autowarefoundation/autoware.universe/pull/10122
None.
None.
None.
=> chore: add grdi map core dependency

planning/autoware_route_handler/src/route_handler.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/10138
- Link
Tested on planning simulator.
None.
None.
None.
=> fix(route_handler): use non-preferred route segment even if checkpoint is not on preferred lanelet at best (#10138)

sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/cloud_collector.hpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_node.hpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/cloud_collector.cpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/combine_cloud_handler.cpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_node.cpp, sensing/autoware_pointcloud_preprocessor/test/test_concatenate_node_unit.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/10074
None.
None.
None.
=> feat(autoware_pointcloud_preprocessor): reuse collectors to reduce creation of collector and timer (#10074)

sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/cloud_collector.hpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/collector_matching_strategy.hpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/combine_cloud_handler.hpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_node.hpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/cloud_collector.cpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_node.cpp
Cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/10082
None.
None.
Fix a potential bug.
=> fix(autoware_pointcloud_preprocessor): fix potential double unlock in concatenate node (#10082)

perception/autoware_image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp
Cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/10196
None.
None.
Fix a bug.
=> fix(segmentation_pointcloud_fusion): set valid pointcloud field for output pointcloud (#10196)

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
https://github.com/autowarefoundation/autoware.universe/pull/10217 のback port。
x1のv2025.3.0で使用する。
- Link
betaブランチでローカルではテストしていないです。
evaluator
2025/03/04 https://evaluation.tier4.jp/evaluation/reports/fc45f019-4655-534a-a07b-7fa4bef9095a/?project_id=prd_jt
3807/3809
None.
None.
None.
=> feat(behavior_planning): add behavior_path_planner_type to launch path_generator (#10217)

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
remap topics for path_generator
- ウィンカートピック名のリマップ忘れを修正。
- ハザードトピックを出力
cherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/10249
- Link
test with main psim
> Psim (The warning The operation mode is changed, but the HazardLightsCommand is not received yet is no longer showing up)
None.
None.
None.
=> fix(tier4_planning_launch): remap topics for path_generator (#10249)

planning/autoware_static_centerline_generator/package.xml, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/package.xml, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
Fix the same build dependency issue as https://github.com/autowarefoundation/autoware.universe/pull/10122 
None.
Confirmed the build passes locally.
None.
None.
None.
=> chore(planning): fix build depends on v0.39

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
* fix for point-cloud stop point
* style(pre-commit): autofix
---------
https://github.com/autowarefoundation/autoware.universe/pull/10250
のcherry-pick
https://star4.slack.com/archives/C07K1PPNPTR/p1741659706804699
- Link
mainでpsimとEvaluator (common, x1common)
None.
None.
None.
=> fix(obstacle_stop): accounting for vehicle bumper length when handling point-cloud stop points (#10250)

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp
Backport https://github.com/autowarefoundation/autoware.universe/pull/9913 to v0.39
None.
Confirmed on actual vehicle.
None.
None.
None.
=> chore: backport pr9913 to v0.39

.github/workflows/build-test-tidy-pr.yaml
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/10279
- Link
None.
None.
None.
=> fix(docker-build-test-tidy-pr.yaml): use `step-security/changed-files` action instead (#10279)

common/osqp_interface/design/osqp_interface-design.md, common/osqp_interface/include/osqp_interface/csc_matrix_conv.hpp, common/osqp_interface/include/osqp_interface/osqp_interface.hpp, common/osqp_interface/src/osqp_interface.cpp, common/osqp_interface/test/test_osqp_interface.cpp, control/autoware_mpc_lateral_controller/src/qp_solver/qp_solver_osqp.cpp, planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/velocity_optimizer.cpp, planning/autoware_path_optimizer/include/autoware/path_optimizer/mpt_optimizer.hpp, planning/autoware_path_optimizer/include/autoware/path_optimizer/node.hpp, planning/autoware_path_optimizer/include/autoware/path_optimizer/state_equation_generator.hpp, planning/autoware_path_optimizer/include/autoware/path_optimizer/utils/conditional_timer.hpp, planning/autoware_path_optimizer/src/mpt_optimizer.cpp, planning/autoware_path_optimizer/src/node.cpp, planning/autoware_path_smoother/src/elastic_band.cpp, planning/autoware_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp, planning/autoware_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp
Returns the smoothed_points trajectory fed into MPT when the latter fails, triggers an emergency stop MRM after 3s.
- [Link](https://tier4.atlassian.net/browse/RT1-9515)
None.
None.
None.
=> feat(path_optimizer): additional failure logging and failure mode handling

planning/autoware_path_optimizer/src/node.cpp
Fixes a bug where an MRM is triggered within 3s of setting a trajectory when emergency-stops are configured to be triggered by planning.
https://tier4.atlassian.net/browse/RT1-9579
None.
None.
None.
=> fix(autoware_path_optimizer): hotfix for wrong logic triggering MRM on start in 3 seconds

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp
Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10274
- Link
None.
None.
None.
=> fix(goal_planner): ignore use bus_stop_area flag if there are no BusStopArea on the pull over lanes (#10274)

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
This PR changed that  mrm can be used in all operation mode state,
- [TIER IV internal link](https://star4.slack.com/archives/C4P0NSMB5/p1741932283537309?thread_ts=1741750397.876449&cid=C4P0NSMB5)
1. prepare for [pilot-auto.s1](https://github.com/tier4/pilot-auto.s1/tree/beta/v0.39.0)
2. cherry-pick this PR commit to autoware.universe
3. conlcon build
4. launch psim
5. Set Autonomous operation mode
6. Set Autonomous Availability false
7. Comfirm that transition to MRM
8. clear
9. Set Local operation mode
10. Set Local Availability false
11. Comfirm that transition to MRM
[Screencast from 2025年03月18日 14時29分01秒.webm](https://github.com/user-attachments/assets/5613c1db-4b8f-4872-99fd-f7fa51011769)
Comfirm that transition to Routing in setting initial pose.
[Screencast from …
=> feat: use mrm in any operation mode

planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10205
- Link
None.
None.
None.
=> fix(behavior_path_planner, behavior_static_obstacle_avoidance_module): crash during goal changes (#10205)

perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.cpp
cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10351
- Link
None.
None.
None.
=> fix(compare_map_segmentation): last map update logic (#10351)

planning/behavior_velocity_planner/include/scene_module/detection_area/scene.hpp, planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
backport #1631 
[管理チケット](https://tier4.atlassian.net/browse/AEAP-2368)
backport PR のため不要
None.
None.
None.
=> feat(detection_area)!: suppression of giving up stopping (backport #1631)

planning/autoware_static_centerline_generator/src/centerline_source/optimization_trajectory_based_centerline.cpp
This PR will cherry-pick the PR submitted to autoware_tools. Since the old version of `autoware_static_centerline_generator` exists in autoware.universe, not in autoware_tools, I created this PR again.
- https://github.com/autowarefoundation/autoware_tools/pull/225
Evaluator build OK.
https://evaluation.tier4.jp/evaluation/reports/bd3988c8-9c66-5248-8e3c-449f4c8ce368?project_id=x2_dev
None.
None.
None.
=> fix(autoware_static_centerline_generator): cherry-pick changes to support modifications made to autoware.core

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/util.cpp
cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10393
- Link
None.
None.
None.
=> fix(start_planner): fix segmentation fault when generating backward path

system/autoware_command_mode_decider/CMakeLists.txt, system/autoware_command_mode_decider/launch/decider.launch.xml, system/autoware_command_mode_decider/src/command_mode_conversion.cpp, system/autoware_command_mode_decider/src/command_mode_decider_redundancy.cpp, system/autoware_command_mode_decider/src/command_mode_decider_redundancy.hpp, system/autoware_command_mode_switcher/launch/switcher.launch.xml
Adds command mode decider redundancy for mrmv0.7.
- Link
None.
None.
None.
=> feat(command_mode_decider): command mode decider change

launch/tier4_control_launch/launch/control.launch.xml, launch/tier4_system_launch/launch/system.launch.xml
Adds param path of control command gate, command mode switcher, and command mode decider to launch file.
- Link
None.
None.
None.
=> feat: add command mode param path

build_depends.repos
Fix autoware.core version on build_depends.repos to pass the build-and-test-differential action.
- [TIERIV internal link](https://star4.slack.com/archives/C07K1PPNPTR/p1744355746343759?thread_ts=1744273768.898139&cid=C07K1PPNPTR)
None.
None.
None.
None.
=> chore: fix autoware.core version on build_depends.repos

system/autoware_command_mode_switcher/src/command_mode_switcher.cpp
Add manual mode but not push commands_.
- Link
None.
None.
None.
=> fix: add manual mode but not push commands_

.github/workflows/build-and-test-differential.yaml, .github/workflows/build-test-tidy-pr.yaml
cherry-pick
https://github.com/autowarefoundation/autoware_universe/pull/10198
To fix `no space left` problem on CI
- Link
None.
None.
None.
=> ci: use Code Build for build-and-test-differentianl-cuda

common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp, common/autoware_motion_utils/test/src/trajectory/test_trajectory.cpp, planning/autoware_path_optimizer/src/mpt_optimizer.cpp, planning/autoware_path_optimizer/src/node.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
When applying the input velocity to the output of MPT, the initial pose of the output of MPT is used to trim the input trajectory. In certain cases when  there is a sharp U-turn, depending on the width of the adjacent, opposing lane into which Ego is turning into, the initial pose of the output trajectory may be mapped to a point in the opposing lane - leading to incorrect input velocity application.
This PR adds a yaw-thresholded closest-distance point search step to ensure that this doesn't occur and also trims the output of MPT to start from the current ego pose so that the initial pose of the MPT output will always map to a point within the current lane.
https://tier4.atlassian.net/browse/RT0-35764
Results in Ticket.
Evaluator Result:
Evaluator results borrowed from: …
=> fix(autoware_path_optimizer): incorrect application of input velocity due to badly mapping output trajectory to input trajectory

build_depends.repos
I updated `build_depends.repos` to match `autoware.repos` in [pilot-auto beta/v0.41 ](https://github.com/tier4/pilot-auto/blob/beta/v0.41/autoware.repos) to pass build on CI check.
[internal discuttion](https://star4.slack.com/archives/C07K1PPNPTR/p1744718842220209?thread_ts=1744718776.361219&cid=C07K1PPNPTR)
None.
None.
None.
=> ci: update build_depends.repos to match pilot-auto beta/v0.41

perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp
- V2I信号連携で歩行者信号を受信するとcrosswalk traffic light estimatorが落ちる現象への対策として、#10281 (以下#10281と記載)をcherry-pickする
- [Tier IV Internal Link](https://tier4.atlassian.net/browse/RT0-34969)
**cherry-pick PR:**
- #10281
- Planning Simulator(Local)
- PSIM上での自動走行および自動走行時にV2I信号連携で歩行者信号を受信してもcrosswalk traffic light estimatorが落ちないことを確認
- Evaluator
本branchを対象としたpilot.auto.x2環境(tmp/V2I_fix_check_v4.2_v0.41)および直近でEvaluatorにかけられたpilot.auto.x2環境(beta/4.2)との比較を以下の表に示す。
| テスト対象 | テスト総数 | OK数 | NG数 |
| :-------- | :------------ | :------ | :------ |
|[tmp/V2I_fix_check_v4.2_v0.41](https://github.com/tier4/pilot-auto.x2/tree/tmp/V2I_fix_check_v4.2_v0.41)| 2719 | 2153 | 566 |
|[beta/4.2(3/31時点)](https://evaluation.tier4.jp/evaluation/reports/cdada75f-7379-5c10-8cff-20f8f842010e?project_id=x2_dev) | …
=> fix(autoware_crosswalk_traffic_light_estimator): add process that guard access to empty elements (#10281) 

.github/workflows/clang-tidy-differential.yaml
Fix mistaking of https://github.com/tier4/autoware_universe/pull/1987, https://github.com/tier4/autoware_universe/pull/1989
- Link
None.
None.
None.
=> ci: use tier4 runner for clang-tidy-differential

perception/autoware_tensorrt_common/src/tensorrt_common.cpp
Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10399
This would allow autoware_universe working on TensorRT 8.5.
-----
How should this cherry-pick works?
- Link
None.
None.
None.
=> feat: should be using NvInferRuntime.h (#10399)

system/hazard_status_converter/CMakeLists.txt, system/hazard_status_converter/launch/hazard_status_converter.launch.xml, system/hazard_status_converter/package.xml, system/hazard_status_converter/src/converter.cpp, system/hazard_status_converter/src/converter.hpp, system/hazard_status_converter/src/mode_interface.cpp, system/hazard_status_converter/src/mode_interface.hpp
This is a backport of https://github.com/autowarefoundation/autoware_universe/pull/10224
- [TIER IV internal link](https://star4.slack.com/archives/C024FRX4UNL/p1741069363648149)
None.
None.
None.
=> fix: backport pr10224 v0.39.0

system/autoware_system_monitor/src/process_monitor/process_monitor.cpp
Cherry pick https://github.com/tier4/autoware_universe/commit/677447fae09f196b293f76240986da5572cf6076 to fix the `-Wno-stringop-overflow` error.
None
Local build succeeded.
None.
None
Expected to fix the building error of autoware_system_monitor
=> fix(autoware_system_monitor): quick fix by cherry-picking 677447f

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/test/test_util.cpp
Cherry pick of the following PR.
https://github.com/autowarefoundation/autoware_universe/pull/10450
- Link
None.
None.
None.
=> feat(blind_spot): extend attention area to straight lanelet

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/CMakeLists.txt
The target when exporting the plugin (`autoware_motion_velocity_planner`) cannot be found.
This PR fixes the issue by renaming it to `autoware_motion_velocity_planner_node_universe`.
https://github.com/tier4/autoware_universe/pull/1997
- Link
None.
None.
None.
=> fix(mvp_run_out): set proper target package name when exporting plugin

control/autoware_control_validator/README.md, control/autoware_control_validator/config/control_validator.param.yaml, control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp, control/autoware_control_validator/launch/control_validator.launch.xml, control/autoware_control_validator/msg/ControlValidatorStatus.msg, control/autoware_control_validator/package.xml, control/autoware_control_validator/src/control_validator.cpp, control/autoware_control_validator/test/test_control_validator.cpp, launch/tier4_control_launch/launch/control.launch.xml
beta/v0.41のcontrol_validator関係の設定をv0.41からv0.44相当に更新する変更です。
リファクタリングを含みますので、変更自体はそこそこの大きさがありますが、パイプラインからは独立しているモジュールですので、影響は限定的かと想定しています。
psimにおいて、以下を確認しました。
- /diagnosticsの内容がv0.44相当のものになっていること
- 坂道で走らせても、誤検知が発生しないこと
- シミュレータの車両モデルを意図的壊すとそれらしいMRM停止ができること  
launch: https://github.com/tier4/autoware_launch/pull/838
None.
None.
None.
=> feat(control_validator, tier4_diagnostics): sync upstream

launch/tier4_vehicle_launch/launch/vehicle.launch.xml
add `is_redundant` arg to vehicle.launch.xml for redundancy system and device authentication.
https://tier4.atlassian.net/wiki/spaces/~284395292/pages/3592554610/v4.2.0
- Link
None.
None.
None.
=> feat(tier4_vehicle_launch): add redundancy option

sensing/autoware_pointcloud_preprocessor/CMakeLists.txt
This PR is to solve the issue [here](https://star4.slack.com/archives/C076E8EBJTG/p1745472001162299).
Agnocast wrapper was introduced here.
- https://github.com/tier4/autoware_universe/pull/1964
- Link
None.
None.
None.
=> fix: explicitly include autoware_agnocast_wrapper_setup command

sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/cloud_collector.hpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/cloud_collector.cpp
In the current implementation of Agnocast, variables that can be accessed by both the Agnocast subscription callback and ROS2 subscription or timer callbacks must be protected by locks for exclusive control. Therefore, variables such as topic_to_cloud_map_ and status_ need to be accessed while holding a lock.
This mutex was once deleted in [this PR](https://github.com/autowarefoundation/autoware_universe/pull/10082) based on [this conversation](https://github.com/autowarefoundation/autoware_universe/pull/10082#issuecomment-2668139391).
[X2 bench debug for applying Agnocast](https://tier4.atlassian.net/wiki/spaces/CRL/pages/3678176064/X2+-#III%3A-autoware%3A%3Apointcloud_preprocessor%3A%3ACloudCollector%3A%3Aconcatenate_callback()-%E3%81%A7%E8%90%BD%E3%81%A1%E3%82%8B)
- …
=> fix(pointcloud_preprocessor): restore the previously deleted concatenate_mutex_ for Agnocast 

perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp
- V2I信号連携で歩行者信号を受信するとcrosswalk traffic light estimatorが落ちる現象への対策として、#10281 (以下#10281と記載)をcherry-pickする
- [Tier IV Internal Link](https://tier4.atlassian.net/browse/RT0-34969)
**cherry-pick PR:**
- #10281
- Planning Simulator(Local)
- PSIM上での自動走行および自動走行時にV2I信号連携で歩行者信号を受信してもcrosswalk traffic light estimatorが落ちないことを確認
- Evaluator
本branchを対象としたpilot.auto.x2環境(tmp/V2I_fix_check_v4.0_v0.29)および直近でEvaluatorにかけられたpilot.auto.x2環境(beta/4.0.2)との比較を以下の表に示す。
| テスト対象 | テスト総数 | OK数 | NG数 |
| :-------- | :------------ | :------ | :------ |
|[tmp/V2I_fix_check_v4.0_v0.29](https://evaluation.tier4.jp/evaluation/reports/701fe0dd-ad1e-5755-88d2-ea3dc074c783?project_id=x2_dev)| 2761 | 2141 | 620 |
|[beta/4.0.2(2/19時点)](https://evaluation.tier4.jp/evaluation/reports/0dd36591-500e-5dde-8879-f3d …
=> fix(autoware_crosswalk_traffic_light_estimator): add process that guard access to empty elements (#10281)

perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/utils/cuda_pointcloud.hpp
fix(autoware_probabilistic_occupancy_grid_map): fix to avoid division by zero (#10599)
- Link
None.
None.
None.
=> fix(autoware_probabilistic_occupancy_grid_map): fix to avoid division (#2021)

control/autoware_control_validator/README.md, control/autoware_control_validator/config/control_validator.param.yaml, control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp, control/autoware_control_validator/include/autoware/control_validator/debug_marker.hpp, control/autoware_control_validator/msg/ControlValidatorStatus.msg, control/autoware_control_validator/package.xml, control/autoware_control_validator/script/max_steering_rate_checker.py, control/autoware_control_validator/src/control_validator.cpp, control/autoware_control_validator/src/debug_marker.cpp
add lateral jerk validation to pc develope branch
cherry pick of the [PR](https://github.com/autowarefoundation/autoware_universe/pull/10619)
- Link
None.
None.
None.
=> add lateral jerk validation to pc develope branch

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/include/autoware/behavior_velocity_crosswalk_module/util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/debug.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
=> feat(crosswalk): comfortable stop for uncertain yield judgement

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
Pointcloud clusters too far from the footprint of the vehicle are considered to be obstructive and slow-down and stop modules are triggered unnecessarily.
This PR is for the universe changes.
https://tier4.atlassian.net/browse/RT1-10023
None.
None.
None.
=> fix(autoware_motion_velocity_obstacle_stop_module): fix for mishandling lateral-distance 

launch/tier4_simulator_launch/launch/simulator.launch.xml
This PR is cherry-pick below.
- https://github.com/autowarefoundation/autoware_universe/pull/10536
In https://github.com/tier4/autoware_universe/pull/2038, I forgot to cherry-pick this PR.
- Link
None.
None.
None.
=> chore(simulator.launch): remove params of traffic_light_selector

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/lanelets_selection.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp
cherry pick of following PRs:
- https://github.com/autowarefoundation/autoware_universe/pull/10446
- https://github.com/autowarefoundation/autoware_universe/pull/10447
- https://github.com/autowarefoundation/autoware_universe/pull/10448
- [Launcher PR](https://github.com/tier4/autoware_launch.x2/pull/1181)
- PSIM
None.
None.
None.
=> feat(out_of_lane): cherry pick out of lane improvements

planning/autoware_rear_obstacle_checker/src/node.cpp
=> feat(roc): output error/warn message when it's unsafe

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/test/test_utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/utils.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/test/test_utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/test/test_utils.cpp
X1 v2025.6リリース評価課題へのhotfixです。
behaivor velocity plannerでUターンレーンで、誤った位置へ停止線が出る問題への対応です。 
https://star4.slack.com/archives/C03QW0GU6P7/p1748401762847809?thread_ts=1747892870.837609&cid=C03QW0GU6P7
https://github.com/autowarefoundation/autoware_universe/pull/10435 をcherr-pick
coreの修正
- https://github.com/tier4/autoware_core/pull/20
https://evaluation.tier4.jp/evaluation/reports/c41bb852-2c1d-5ce6-8f3a-672a88f916ec?project_id=prd_jt
None.
None.
None.
=> feat(behavior_velocity_planner): extend stop line to path bound (#10435)

control/autoware_smart_mpc_trajectory_follower/autoware_smart_mpc_trajectory_follower/training_and_data_check/add_training_data_from_csv.py, planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.cpp
Cherry pick https://github.com/autowarefoundation/autoware_universe/pull/10746 to prevent crashes of the `run_out` module in the `motion_velocity_planner`.
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-37423)
Psim
None.
None.
None.
=> fix(run_out): guard against decreasing ego trajectory times (#10746)

perception/autoware_image_projection_based_fusion/config/roi_pointcloud_fusion.param.yaml, perception/autoware_image_projection_based_fusion/docs/roi-pointcloud-fusion.md, perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_pointcloud_fusion/node.hpp, perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/utils.hpp, perception/autoware_image_projection_based_fusion/schema/roi_pointcloud_fusion.schema.json, perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/utils/utils.cpp, perception/autoware_image_projection_based_fusion/test/test_utils.cpp
Cherry-pick: https://github.com/autowarefoundation/autoware_universe/pull/10655
チケット：https://tier4.atlassian.net/browse/RT0-37158?focusedCommentId=226483
Related PR:  https://github.com/tier4/autoware_launch.x2/pull/1232
* fix(roi_pointcloud_fusion): add remap output option
* chore: docs update
* fix: update refine cluster func
* chore: fix schema
* fix: test utils
---------
=> fix(roi_pointcloud_fusion): add remap output option (#10655)

perception/autoware_traffic_light_occlusion_predictor/launch/traffic_light_occlusion_predictor.launch.xml
This PR enables to use TLR, As the title says.
=> fix(autoware_traffic_light_occlusion_predictor): remove unnecessary comment out to use traffic_light_recognition by camera

map/map_height_fitter/CMakeLists.txt, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
`map_height_fitter` パッケージの `CMakeLists.txt` において、`autoware_package()` と `find_package(PCL ...)` の呼び出し順序を修正しました。
この変更により、PCLが依存する `libusb` が `autoware_package` の前に探索されるようになり、`libusb::libusb` ターゲットが見つからずに発生していたビルドエラーを解消します。
ローカル環境 & Evaluatorで対象パッケージのビルドが成功することを確認しました。
修正前: https://evaluation.tier4.jp/evaluation/reports/16bcc218-327f-5217-88a9-5c8a9196756a?project_id=X8ft5pPN
修正後: https://evaluation.tier4.jp/evaluation/reports/4d5babf8-842e-5022-bb7b-9075ef7cb327?project_id=X8ft5pPN
After all checkboxes are checked, anyone who has write access can merge …
=> fix: change the execution order of map_height_fitter cmake

perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
fix param missing bag in pointpainting to fix the compile error 
``` 
src/autoware/universe/perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp:189:66: error: no matching function for call to ‘autoware::lidar_centerpoint::CenterPointConfig::CenterPointConfig(std::vector<std::__cxx11::basic_string<char> >::size_type, const size_t&, const size_t&, const size_t&, std::vector<double, std::allocator<double> >&, const std::vector<double, std::allocator<double> >&, const size_t&, const size_t&, const float&, const float&, const std::vector<double, std::allocator<double> >&, bool&)’
189 |     circle_nms_dist_threshold, yaw_norm_thresholds, has_variance_);
```
Evaluatorも失敗：https://evaluation.tier4.jp/evaluation/reports/362d575e-266c-59e0-adcc-a6ae0e89e004/builds/278a …
=> fix: pointpainting mising param

perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/preprocess/pointcloud_densification.hpp, perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/preprocess/preprocess_kernel.hpp, perception/autoware_lidar_centerpoint/lib/centerpoint_trt.cpp, perception/autoware_lidar_centerpoint/lib/preprocess/pointcloud_densification.cpp, perception/autoware_lidar_centerpoint/lib/preprocess/preprocess_kernel.cu, perception/autoware_lidar_centerpoint/lib/preprocess/voxel_generator.cpp
Add intensity support to CenterPoint.
Note that the CenterPoint will choose corresponding input based on `point_feature_size` and `encoder_in_feature_size` in `centerpoint_ml_package.param.yaml`.
To run intensity, we need to set them as:
```
point_feature_size: 5
encoder_in_feature_size: 11
```
It still support previous config without intensity
Demo: 
Before intensity:
https://drive.google.com/file/d/1P4IwESC2VWblrmFL3gl_SM5kkZzu06Jz/view?usp=sharing
After intensity:
https://drive.google.com/file/d/1ZNhAGd4zrBL2iYZueqdeA6UEA-hGpVzO/view?usp=sharing
=> feat(autoware_lidar_centerpoint): Add intensity model 

control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
…rect direction when reverse (#10822)
* fix(pid): fix a bug that acceleration feedback does not go in the correct direction when reverse
* fix CI
---------
https://github.com/autowarefoundation/autoware_universe/pull/10808
=> fix(pid): fix a bug that acceleration feedback does not go in the correct direction when reverse

visualization/tier4_control_mode_rviz_plugin/CMakeLists.txt, visualization/tier4_control_mode_rviz_plugin/README.md, visualization/tier4_control_mode_rviz_plugin/include/control_mode_display.hpp, visualization/tier4_control_mode_rviz_plugin/package.xml, visualization/tier4_control_mode_rviz_plugin/plugins/plugin_description.xml, visualization/tier4_control_mode_rviz_plugin/src/control_mode_display.cpp
https://github.com/autowarefoundation/autoware_universe/pull/10706
* add rviz plugin for visualizing control mode
* fix(tier4_control_mode_rviz_plugin): update background colors for manual and disengaged modes
---------
=> feat(control_mode_rviz_plugin): add rviz plugin for visualizing control mode

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
cherry-pick the following PRs
[refactor(boundary_departure): use polling subscriber #10901](https://github.com/autowarefoundation/autoware_universe/pull/10901)
[fix(boundary_departure): exception and log handling #10914
](https://github.com/autowarefoundation/autoware_universe/pull/10914)
=> fix(boundary_departure): polling subscriber and exception handling

visualization/tier4_state_rviz_plugin/src/autoware_state_panel.cpp, visualization/tier4_state_rviz_plugin/src/include/autoware_state_panel.hpp
See 
https://github.com/autowarefoundation/autoware_universe/pull/10861
https://github.com/autowarefoundation/autoware_universe/pull/10895
When using the command_mode_decider node, the MrmState values can be arbitrarily defined per product—not just those predefined in the existing message. Make changes so that RViz will correctly visualize any arbitrary MrmState value.
=> feat(tier4_state_rviz_plugin): display unknown value (#10861)

control/autoware_control_command_gate/CMakeLists.txt, control/autoware_control_command_gate/config/default.param.yaml, control/autoware_control_command_gate/package.xml, control/autoware_control_command_gate/src/command/compatibility.cpp, control/autoware_control_command_gate/src/command/compatibility.hpp, control/autoware_control_command_gate/src/command/compatibility/adapi_pause_interface.cpp, control/autoware_control_command_gate/src/command/compatibility/adapi_pause_interface.hpp, control/autoware_control_command_gate/src/command/filter.hpp, control/autoware_control_command_gate/src/command/source.hpp, control/autoware_control_command_gate/src/control_command_gate.cpp, control/autoware_control_command_gate/src/control_command_gate.hpp
See https://github.com/autowarefoundation/autoware_universe/pull/10877
Since the Motion state was not implemented in the control command gate, it is implemented.
=> fix(control_command_gate): fix for pause interface  (#10877)

system/autoware_diagnostic_graph_aggregator/package.xml, system/autoware_diagnostic_graph_aggregator/src/common/graph/graph.cpp, system/autoware_diagnostic_graph_aggregator/src/common/graph/graph.hpp, system/autoware_diagnostic_graph_aggregator/src/common/graph/levels.cpp, system/autoware_diagnostic_graph_aggregator/src/common/graph/levels.hpp, system/autoware_diagnostic_graph_aggregator/src/common/graph/nodes.cpp, system/autoware_diagnostic_graph_aggregator/src/common/graph/nodes.hpp, system/autoware_diagnostic_graph_aggregator/src/node/aggregator.cpp, system/autoware_diagnostic_graph_aggregator/src/node/aggregator.hpp, system/autoware_diagnostic_graph_aggregator/test/src/test_levels.cpp, system/autoware_diagnostic_graph_aggregator/test/src/tests/timeline.cpp, system/autoware_diagnostic_graph_aggregator/test/src/tests/timeline.hpp
See https://github.com/autowarefoundation/autoware_universe/pull/10893
The aggregator node now includes a latching feature. This feature causes the aggregator to continue treating a diagnostic as an error—even if the diagnostic returns to OK—so long as the Error state persisted for a specified duration. Because many diagnostics are in Error when Autoware first starts up, the behavior  is modified so that the latching feature can be enabled only once Autoware is already running.
=> feat(diagnostic_graph_aggregator): add initializing flag (#10893)

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
Cherry-picking polling sub PRs and preventing node dying.
=> cherry_pick(boundary_departure): preventing node dying + disable when autoware disengaged

control/autoware_control_command_gate/CMakeLists.txt, control/autoware_control_command_gate/config/default.param.yaml, control/autoware_control_command_gate/package.xml, control/autoware_control_command_gate/src/command/compatibility.cpp, control/autoware_control_command_gate/src/command/compatibility.hpp, control/autoware_control_command_gate/src/command/compatibility/emergency_interface.cpp, control/autoware_control_command_gate/src/command/compatibility/emergency_interface.hpp, control/autoware_control_command_gate/src/command/compatibility/moderate_stop_interface.cpp, control/autoware_control_command_gate/src/command/compatibility/moderate_stop_interface.hpp
See https://github.com/autowarefoundation/autoware_universe/pull/10917
The functionality from the vehicle_cmd_gate node has been re-implemented in the control_command_gate node for compatibility. Specifically:
- Pressing the “Set Emergency” button in RViz now causes the vehicle to decelerate and come to a stop.
- Calling the /control/vehicle_cmd_gate/set_stop service from an external source will also bring the vehicle to a halt.
=> feat(control_command_gate): support vehicle_cmd_gate interface (#10917)

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
cherry pick [chore(boundary_departure): add logging for monitoring](https://github.com/tier4/autoware_universe/commit/682615144792bb9d50073fe68b4dd11170e2d995)](https://github.com/autowarefoundation/autoware_universe/pull/10969)
- The purpose of backlogging this is to ensure that we can monitor any false positive detections via MOB
=> chore(boundary_departure): add logging for monitoring (#10969)

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
When autoware is disengaged, the ego's predicted path behavior is undefined. As shown in the following video. This has caused boundary departure to produce false positive results. 
https://github.com/user-attachments/assets/04c90345-1859-4d63-8a31-b41ab46886bb
This PR aims to disable boundary departure during autonomous mode.
=> fix(boundary_departure): disable when autoware disengaged (#10962)

perception/autoware_radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node.cpp
backport: https://github.com/autowarefoundation/autoware_universe/pull/11002 
https://tier4.atlassian.net/browse/RT0-37772
tracked_objectsがemptyの場合にdetected_objectsがpublishされることを確認した
=> fix(radar_tracks_objects_converter): publish topic even if objects array is empty (backport autowarefoundation#11002)

planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/node.hpp, planning/planning_validator/autoware_planning_validator/src/node.cpp, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/config/intersection_collision_checker.param.yaml, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/intersection_collision_checker.hpp, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/types.hpp, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/param/intersection_collision_checker_node_parameters.yaml, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/intersection_collision_checker.cpp, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/utils.cpp
Cherry-pick of:
- https://github.com/autowarefoundation/autoware_universe/pull/10979
- changes planning_validator node to be event driven on trajectory msg to avoid delay
- https://github.com/autowarefoundation/autoware_universe/pull/11030
- Improves velocity estimation and tracking logic of intersection_collision_checker to address frequent false negatives
- https://github.com/autowarefoundation/autoware_universe/pull/11034
- minor fix to use parameterized values instead of hard coded constants
Requires https://github.com/tier4/autoware_launch/pull/1022
=> feat(planning_validator, intersection_collision_checker): cherry pick improvements

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
see https://github.com/autowarefoundation/autoware_universe/pull/11008 for more detail
=> fix(intersection): remove reference "traffic_light_id" as it is deprecated (#11008)

perception/autoware_traffic_light_classifier/src/classifier/cnn_classifier.cpp, perception/autoware_traffic_light_classifier/src/traffic_light_classifier_node.cpp
Cherry-pick to avoid `rclcpp::exceptions::RCLError`. 
Background : https://star4.slack.com/archives/C076ZGRC15X/p1752741243355159
https://evaluation.ci.tier4.jp/evaluation/reports/73ebdd30-0e16-579c-aa93-f90e3ab24489?project_id=prd_jt
=> fix(autoware_traffic_light_classifier): move `rclcpp::shutdown();` from child to parent to avoid `rclcpp::exceptions::RCLError`

planning/planning_validator/autoware_planning_validator_intersection_collision_checker/config/intersection_collision_checker.param.yaml, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/types.hpp, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/param/intersection_collision_checker_node_parameters.yaml, planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/intersection_collision_checker.cpp
cherry pick of https://github.com/autowarefoundation/autoware_universe/pull/11058
- improves logic for handling objects near overlap point
- adds configuration parameter `max_history_time`
requires https://github.com/tier4/autoware_launch/pull/1037
=> fix(intersection_collision_checker): cherry pick #11058

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
Cherry-pick 2 PR related to diagnostic and logging.
Both PRs are cherry-picked together to avoid conflict.
[refactor(boundary_departure): reduce autonomous mode logging level #10986](https://github.com/autowarefoundation/autoware_universe/pull/10986)
[fix(boundary_departure): configurable diagnostic level #11064](https://github.com/autowarefoundation/autoware_universe/pull/11064)
=> fix(boundary_departure): configurable diagnostic level #11064

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/type_alias.hpp
[fix(boundary_departure): subscribe to route to determine goal changes #11004](https://github.com/autowarefoundation/autoware_universe/pull/11004)
* fix(boundary_departure): use route msg to check for goal changes
* changed goal ptr to route ptr
=> fix(boundary_departure): subscribe to route to determine goal changes #11004

control/autoware_control_command_gate/launch/control_command_gate.launch.xml, launch/tier4_control_launch/launch/control.launch.xml
See https://github.com/autowarefoundation/autoware_universe/pull/11019
This PR enable to remap topics from autoware_launch.
- control_cmd
- gear_cmd
- turn_indicators_cmd
- hazard_lights_cmd
This change is necessary for X2 Psim of redundant configuration.
=> feat(tier4_control_launch, control_command_gate): enable to remap control cmd from autoware launch (#11019)

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
cherry pick for https://github.com/autowarefoundation/autoware_universe/pull/11026
- Link
None.
None.
None.
=> feat(start_planner): improve trajectory generation with consideration of current ego vehicle heading

sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.cpp
Cherry-pick of https://github.com/autowarefoundation/autoware_universe/pull/11055.
=> fix(autoware cuda pointcloud preprocessor): trim IMU/twist queues correctly (#11055)

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/CMakeLists.txt
Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11096 to fix the `run_out` module not being installed.
=> fix(run_out): add missing ament_auto_package in CMakeList (#11096)

workflow_sync_setting.yaml
[runner for the job was changes in awf](https://github.com/tier4/autoware_universe/pull/2266/files), so we need to update our setting to keep the tier4 runner the same
=> chore: keep runner

sensing/autoware_pointcloud_preprocessor/CMakeLists.txt, sensing/autoware_pointcloud_preprocessor/src/downsample_filter/pickup_based_voxel_grid_downsample_filter_node.cpp, sensing/autoware_pointcloud_preprocessor/test/test_pickup_based_voxel_grid_downsample_filter_node.cpp
* cherry-pick of https://github.com/autowarefoundation/autoware_universe/pull/11003
> ## Description
> 
> The `pickup_based_downsample_filter` currently fails to publish an output when it receives an empty pointcloud.
> 
> The expected behavior is to publish an empty pointcloud when the input is also empty. This PR fixes the node to ensure this behavior.
> 
> To verify the fix, I've added integration tests for both single-point and empty pointclouds.
> 
> **Note:** These integration tests are time-consuming. I plan to replace them with faster unit tests for the `filter()` function in a future PR.
> 
> 
> ## Related links
> 
> **Private Links:**
> 
> - [TIER IV internal link](https://tier4.atlassian.net/browse/RT2-2536)
=> fix(pointcloud_preprocessor): handle empty pointclouds in pickup_base (#11003)

control/autoware_operation_mode_transition_manager/src/state.cpp
This PR will cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11097 that fixes a problem.
When `check_engage_condition_` is set as `false`, `bool isModeChangeAvailable()` will return `true` before `enable_engage_on_driving_` is checked.
Here is the [ticket](https://tier4.atlassian.net/browse/RT0-38624)
For more details, please refer to this [thread](https://star4.slack.com/archives/C012LF6GV54/p1753755720858229?thread_ts=1751936472.561819&cid=C012LF6GV54).
=> fix(operation_mode_transition_manager): modify the engage condition

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.hpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.hpp
BDP inserts slow down distance when ego approaches or leaving lane through road border. 
Departure interval is first generated to find the distance to slow down point, and the lateral distance to boundary.
Then slow down point is computed
What the slow down feature do
1. Dynamic comfort to hard slow down
When the longitudinal gap is sufficient, the planner slows with the comfort limits (th_jerk_mps3.min, th_acc_mps2.min) for a smoother ride.
As the gap shrinks, it automatically escalates to the hard limits (.max) so that the target conditions are still met.
https://github.com/user-attachments/assets/9a92de78-9628-4b65-ba13-4727b794645b
----
* feat(boundary_departure): slow down computation
* fixed some logic
* refactor function get_interp_to_point()
* Update …
=> feat(boundary_departure): slow down computation (#11085)

control/autoware_mpc_lateral_controller/src/mpc_utils.cpp
update time_from_start variable in MPC's predicted trajectory.
=> fix(mpc): update time from start in the predicted trajectory (#10753)

system/autoware_system_monitor/include/system_monitor/cpu_monitor/cpu_monitor_base.hpp, system/autoware_system_monitor/include/system_monitor/cpu_monitor/intel_cpu_monitor.hpp, system/autoware_system_monitor/include/system_monitor/cpu_monitor/raspi_cpu_monitor.hpp, system/autoware_system_monitor/include/system_monitor/gpu_monitor/gpu_monitor_base.hpp, system/autoware_system_monitor/include/system_monitor/gpu_monitor/nvml_gpu_monitor.hpp, system/autoware_system_monitor/include/system_monitor/hdd_monitor/hdd_monitor.hpp, system/autoware_system_monitor/include/system_monitor/mem_monitor/mem_monitor.hpp, system/autoware_system_monitor/include/system_monitor/net_monitor/net_monitor.hpp, system/autoware_system_monitor/src/cpu_monitor/cpu_monitor_base.cpp, system/autoware_system_monitor/src/cpu_monitor/intel_cpu_monitor.cpp, system/autoware_system_monitor/src/cpu_monitor/raspi_cpu_monitor.cpp, system/autoware_system_monitor/src/gpu_monitor/gpu_monitor_base.cpp, system/autoware_system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp, system/autoware_system_monitor/src/hdd_monitor/hdd_monitor.cpp, system/autoware_system_monitor/src/mem_monitor/mem_monitor.cpp, system/autoware_system_monitor/src/net_monitor/net_monitor.cpp
Cherry-pick PR to beta/v0.48. This PR is expected to be included in X2 beta/v4.3.
Cherry-picking of the following PRs for Metrics collection
- https://github.com/autowarefoundation/autoware_universe/pull/11020
- https://github.com/autowarefoundation/autoware_universe/pull/11021
- https://github.com/autowarefoundation/autoware_universe/pull/11022
- https://github.com/autowarefoundation/autoware_universe/pull/11023
- https://github.com/autowarefoundation/autoware_universe/pull/11024
This PR implements the contents of the following PRs that added the API (msg) and have been already merged.
- https://github.com/tier4/tier4_autoware_msgs/pull/192
- https://github.com/tier4/pilot-auto/pull/1698
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-38268)
- Running lsim with …
=> feat(autoware_system_monitor): publish msgs for system_monitor API 

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/clothoid_pull_out.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp
https://github.com/autowarefoundation/autoware_universe/pull/11107 のbackport
https://tier4.atlassian.net/browse/RT0-38657
[Evaluator](https://evaluation.tier4.jp/evaluation/oidc/auth/cb/?code=ory_ac_UttrHL4OoC4WIuemgshf6hsg1o5R9WUOmWrdYUFQJSM.4kDPeMvj9e9M1Z9rumPQvVkXoCevOyVOzYAEqNWtonw&scope=openid+profile+email+offline_access&state=b8b18b290489492dbaa09ea950e15068)
にて該当シナリオでyaw_deviationおよびlon_distance_deviationが発生して発進できないことがなくなったのを確認した
該当シナリオについてはRelated Links記載のチケットを参照してください
=> fix(start_planner): incorrect function call (#11107)

common/autoware_component_interface_specs_universe/include/autoware/component_interface_specs_universe/planning.hpp, control/autoware_control_performance_analysis/README.md, control/autoware_control_performance_analysis/launch/control_performance_analysis.launch.xml, control/autoware_control_validator/launch/control_validator.launch.xml, control/autoware_lane_departure_checker/README.md, control/autoware_lane_departure_checker/launch/lane_departure_checker.launch.xml, control/autoware_obstacle_collision_checker/launch/obstacle_collision_checker.launch.xml, control/autoware_operation_mode_transition_manager/README.md, control/autoware_operation_mode_transition_manager/launch/autonomous_mode_transition_flag_node.launch.xml, control/autoware_operation_mode_transition_manager/launch/operation_mode_transition_manager.launch.xml, control/autoware_predicted_path_checker/launch/predicted_path_checker.launch.xml, control/autoware_pure_pursuit/launch/pure_pursuit.launch.xml, control/autoware_smart_mpc_trajectory_follower/scripts/pympc_trajectory_follower.py, control/autoware_trajectory_follower_node/launch/simple_trajectory_follower.launch.xml, evaluator/autoware_control_evaluator/launch/control_evaluator.launch.xml, evaluator/autoware_planning_evaluator/launch/planning_evaluator.launch.xml, launch/tier4_control_launch/launch/control.launch.xml, launch/tier4_planning_launch/launch/planning.launch.xml, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/optimization_based_planner/optimization_based_planner.cpp, planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml, simulator/autoware_simple_planning_simulator/launch/simple_planning_simulator.launch.py, system/autoware_component_state_monitor/config/topics.yaml, tools/reaction_analyzer/param/reaction_analyzer.param.yaml
* change planning output topic name to /planning/trajectory
Cherry-pick from https://github.com/autowarefoundation/autoware_universe/pull/11135
=> feat: change planning output topic name to /planning/trajectory (#11135)

common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/data_structs.hpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp
Simplify the merge_departure_intervals and make sure the intervals on a same side are properly merged.
*This PR solved boundary departure node dying issue.
https://github.com/autowarefoundation/autoware_universe/pull/11129
=> fix(boundary_departure): refactor merge_departure_intervals function to avoid crashes #11129

planning/autoware_path_optimizer/src/utils/geometry_utils.cpp
Cherry-picked from https://github.com/autowarefoundation/autoware_universe/pull/11211
Fix path optimizer die due to bound out of range
```
[component_container_mt-37]   what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
[component_container_mt-37] *** Aborted at 1755179481 (unix time) try "date -d @1755179481" if you are using GNU date ***
[component_container_mt-37] PC: @                0x0 (unknown)
[component_container_mt-37] *** SIGABRT (@0x3e80019d08c) received by PID 1691788 (TID 0x7f97417f2640) from PID 1691788; stack trace: ***
[component_container_mt-37]     @     0x7f97708b74d6 google::(anonymous namespace)::FailureSignalHandler()
[component_container_mt-37]     @     0x7f976fc42520 (unknown)
[component_container_mt-37]     @     0x7f976fc969fc …
```
=> fix(path_optimizer): fix out_of_range die

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/package.xml, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/test/test_util.cpp
cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11224
goal plannerで路肩に近いゴール候補が誤って弾かれる問題への対応
before
after
テスト
before
[tmp/test_random_fail_v0.48 retry=0](https://evaluation.tier4.jp/evaluation/reports/9e347204-3c3d-5c34-88b8-5b08cafb1da5?project_id=prd_jt)
3969/3987
after
[fix/goal_candidate_v0.48](https://evaluation.tier4.jp/evaluation/reports/74d7f9b0-37f2-513f-a208-3b70c25eab09?project_id=prd_jt)
3969/3987
=> fix(goal_planner): generate goal candidates using lane boundary to fix wrong validation (#11224)

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
backport:
- https://github.com/autowarefoundation/autoware_universe/pull/11217
- https://github.com/autowarefoundation/autoware_universe/pull/11243
- https://github.com/autowarefoundation/autoware_universe/pull/11245
Related issues:
[TIER IV Internal Link - Issue RT1-10999](https://tier4.atlassian.net/browse/RT1-10999)
[TIER IV Internal link - P/C Inquiry](https://star4.slack.com/archives/C074CCKN35E/p1755840492837879)
⚠️ Additional note:
* The issue is not reproducible in the local environment and occurs randomly in the evaluator. * So far, it has only been reported during manual driving. As mentioned in the [TIER IV Internal link – P/C Inquiry](https://star4.slack.com/archives/C074CCKN35E/p1755840492837879), it is not reproducible with the rosbag.
* The module has been tested several …
=> fix(boundary_departure): backport PRs to reduce possibility of random node crash

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/turn_signal_decider.cpp
JIRA Link: https://tier4.atlassian.net/browse/RT0-38988
Slack: https://star4.slack.com/archives/C074CCKN35E/p1755677377546649
For merging lanes that appear geometrically straight, the required section becomes very small and is easily overwritten. However, these merging lanes are deliberately labeled with turning signals during map creation and should maintain high priority.
This PR introduces modifications to the algorithm for determining the end index of turning lanelets.
----
https://github.com/tier4/autoware_universe/pull/2325
Thanks Daniel, for commenting. I cleaned up something in-correctly and make a new  single commit PR here
This is now a formal cherry-pick of
https://github.com/autowarefoundation/autoware_universe/pull/11288
---
- **Direction**: Forward iteration (start → end)
- …
=> chore: turn signal decider fix cherry-pick

system/autoware_system_monitor/include/system_monitor/gpu_monitor/gpu_monitor_base.hpp, system/autoware_system_monitor/include/system_monitor/gpu_monitor/nvml_gpu_monitor.hpp, system/autoware_system_monitor/src/gpu_monitor/gpu_monitor_base.cpp, system/autoware_system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp
This PR is a cherry-picking PR which backports the following PR to autowarefoundation/autoware_universe.
- [fix(gpu_monitor): explicitly qualify a function call to stop error from the cppcheck-differential CI workflow #11279](https://github.com/autowarefoundation/autoware_universe/pull/11279)
The preceding cherry-picking PR [feat(autoware_system_monitor): publish msgs for system_monitor API #2285](https://github.com/tier4/autoware_universe/pull/2285), which has already been merged, had a problem which may cause a CI workflow error (with cppcheck-differential) when "autoware_system_monitor" is modified.
This PR should be merged to avoid possible occurrence of the CI workflow error in near future.
=> fix(gpu_monitor): explicitly qualify a function call to stop error from the cppcheck-differential workflow

localization/autoware_pose_instability_detector/README.md, localization/autoware_pose_instability_detector/src/pose_instability_detector.cpp, localization/autoware_pose_instability_detector/test/test.cpp
This PR changes the level of diagnostics of `pose_instability_detector` from `WARN` to `ERROR`.
Cherry-pick of https://github.com/autowarefoundation/autoware_universe/pull/11095
=> feat(pose instability detector): change diag level (#11095)

perception/autoware_bytetrack/config/bytetrack.param.yaml, perception/autoware_bytetrack/include/autoware/bytetrack/bytetrack.hpp, perception/autoware_bytetrack/lib/include/byte_tracker.h, perception/autoware_bytetrack/lib/include/strack.h, perception/autoware_bytetrack/lib/src/byte_tracker.cpp, perception/autoware_bytetrack/lib/src/strack.cpp, perception/autoware_bytetrack/src/bytetrack.cpp, perception/autoware_bytetrack/src/bytetrack_node.cpp
* feat: enhance bytracker classification management
* fix a bug in score reset after switching label
* feat: update the score rule for same label
---------
Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10898 into beta/v0.41
I found out Yolox-related problems in XX1 beta/v0.48 Solio run. This needs to be solved with new bytetrack update.
=> feat: enhance bytracker classification management (#10898)

system/autoware_system_monitor/README.md, system/autoware_system_monitor/config/cpu_monitor.param.yaml, system/autoware_system_monitor/config/hdd_monitor.param.yaml, system/autoware_system_monitor/docs/hdd_reader.md, system/autoware_system_monitor/docs/msr_reader.md, system/autoware_system_monitor/docs/ros_parameters.md, system/autoware_system_monitor/docs/traffic_reader.md, system/autoware_system_monitor/include/system_monitor/cpu_monitor/intel_cpu_monitor.hpp, system/autoware_system_monitor/include/system_monitor/hdd_monitor/hdd_monitor.hpp, system/autoware_system_monitor/reader/hdd_reader/hdd_reader.cpp, system/autoware_system_monitor/reader/msr_reader/msr_reader.cpp, system/autoware_system_monitor/src/cpu_monitor/intel_cpu_monitor.cpp, system/autoware_system_monitor/src/hdd_monitor/hdd_monitor.cpp, system/autoware_system_monitor/test/config/test_hdd_monitor.param.yaml, system/autoware_system_monitor/test/src/cpu_monitor/test_intel_cpu_monitor.cpp
This PR is a cherry-picking PR which backports the following PR to tier4/autoware_universe.
- https://github.com/autowarefoundation/autoware_universe/pull/11199
This PR consists of the following changes:
* Use AF_UNIX socket for IPC between cpu_monitor (for x86_64) and msr_reader.
* Add the "msr_reader_socket_path" parameter to the "cpu_monitor" node (Intel/AMD x86_64)
* Remove the "port" parameter from the "cpu_monitor" node.
* Use AF_UNIX socket for IPC between hdd_monitor and hdd_reader.
* Add the "hdd_reader_socket_path" parameter to the "hdd_monitor" node.
* Remove the "port" parameter from the "hdd_monitor" node.
* Update configuration ".yaml" files about parameters.
* Update autoware_system_monitor documents for changes of node parameters.
**NOTE:**
The related cherry-picking PR to …
=> fix(hdd_monitor,cpu_monitor): use unix sockets for IPC with helper applications

system/autoware_diagnostic_graph_utils/src/node/logging.cpp
backport from https://github.com/autowarefoundation/autoware_universe/pull/11327
https://tier4.atlassian.net/browse/RT0-39004
I confirmed it works when stale diags exist.
=> feat(diagnostic_graph_utils): use raw level for leaf node (backport #11327)

system/autoware_system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp
This PR is a cherry-picking PR which backports the following PR to tier4/autoware_universe.
* https://github.com/autowarefoundation/autoware_universe/pull/11291
This PR stops the false warning "Failed to nvmlDeviceGetProcessUtilization(2nd) NVML: Not Found" from being reported when the GPU is idle.
When the GPU is idle, the error code NVML_ERROR_NOT_FOUND is returned from nvmlDeviceGetProcessUtilization(), but it is one of the expected results and it should be ignored.
=> fix(gpu_monitor): stop false warning messages reported by gpu_monitor when the GPU is idle

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
See original PR: https://github.com/autowarefoundation/autoware_universe/pull/11393
=> fix(crosswalk, traffic_light): correct distance calculation by swapping src and dst (#11393)

.github/workflows/co-pilot-auto-client.yaml
Co-Pilot Auto should be using the private bot key instead.
=> fix(co-pilot-auto): should be using private bot key
