sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp

* fix: cast field individually
* chore: cleanup
- cherry pick https://github.com/autowarefoundation/autoware.universe/pull/253 for beta branch
- **Check spelling**: …

fix: ring outlier filter bug (#253)

---

sensing/pointcloud_preprocessor/package.xml

- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.
[commit-guidelines]: …

chore(dual return outlier filter): update package.xml (#331)

---

.github/workflows/sync-upstream.yaml

Related: https://github.com/autowarefoundation/autoware/pull/74

ci(sync-upstream): update settings

---

planning/behavior_velocity_planner/include/utilization/util.hpp
planning/behavior_velocity_planner/src/scene_module/blind_spot/scene.cpp
planning/behavior_velocity_planner/src/scene_module/crosswalk/util.cpp
planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
planning/behavior_velocity_planner/src/scene_module/no_stopping_area/scene_no_stopping_area.cpp
planning/behavior_velocity_planner/src/scene_module/occlusion_spot/risk_predictive_braking.cpp
planning/behavior_velocity_planner/src/scene_module/stop_line/scene.cpp
planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
planning/behavior_velocity_planner/src/scene_module/virtual_traffic_light/scene.cpp
planning/behavior_velocity_planner/src/utilization/util.cpp

https://github.com/autowarefoundation/autoware.universe/issues/504
same as 
- https://github.com/autowarefoundation/autoware.universe/pull/505
- https://github.com/autowarefoundation/autoware.universe/pull/526
cherry-pick from
(https://github.com/autowarefoundation/autoware.universe/pull/505)
(https://github.com/autowarefoundation/autoware.universe/pull/526)
run ci to see successfully run
one below is failure of other reason.
for other scenarios failure is caused by ad_service state monitor which is unrelated to this fix
- **Build and …

fix(behavior_velocity): fix detection area ,stop line,traffic lights stop line insertion ,occlusion spot (#505)

---

planning/behavior_velocity_planner/include/behavior_velocity_planner/planner_data.hpp

Signed-off-by: Makoto Kurihara <mkuri8m@gmail.com>
Resolves https://github.com/autowarefoundation/autoware.universe/issues/524
Same as https://github.com/autowarefoundation/autoware.universe/pull/525 (Hotfix)
Same as https://github.com/autowarefoundation/autoware.universe/pull/525
Confirm that the ego vehicle's velocity falls below 10e-3m/s^2 and the stop line is released
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the …

fix(behavior_velocity_planner): lower stop decision velocity (#525)

---

planning/obstacle_velocity_planner/include/obstacle_velocity_planner/box2d.hpp
planning/obstacle_velocity_planner/include/obstacle_velocity_planner/node.hpp
planning/obstacle_velocity_planner/src/box2d.cpp
planning/obstacle_velocity_planner/src/node.cpp

work in progress
refactored obstacle velocity planner, and defined data structure required for ACC.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] …

feat(obstacle_velocity_planner): refactor, add debug markers, and prepare algorithmic data for acc

---

planning/behavior_path_planner/src/utilities.cpp

- cherry-pick for bug fix
- https://github.com/autowarefoundation/autoware.universe/pull/1035

fix(behavior_path_planner): get accurate drivable area (#1035)

---

perception/compare_map_segmentation/package.xml
perception/compare_map_segmentation/src/voxel_based_approximate_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_based_compare_map_filter_nodelet.cpp
perception/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/node.hpp
perception/lidar_apollo_instance_segmentation/package.xml
perception/lidar_apollo_instance_segmentation/src/node.cpp
perception/occupancy_grid_map_outlier_filter/include/occupancy_grid_map_outlier_filter/occupancy_grid_map_outlier_filter_nodelet.hpp
perception/occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_nodelet.cpp
sensing/pointcloud_preprocessor/config/processing_time_ms.xml
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_data_nodelet.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/distortion_corrector/distortion_corrector.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/filter.hpp
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp
sensing/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp

add cyclic and processing time ms to pcd related to pcd awf (#946)

perf(processing_time): add cyclic and processing time ms to pcd related to pcd

---

perception/occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_nodelet.cpp

Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>
reduce occ grid outlier filter calc cost at radius search
https://github.com/autowarefoundation/autoware.universe/pull/979

feat: reduce calc cost of occ grid outlier filter

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/util.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/util.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/util.cpp
planning/behavior_path_planner/src/scene_module/pull_out/util.cpp
planning/behavior_path_planner/src/scene_module/pull_over/util.cpp
planning/behavior_path_planner/src/utilities.cpp
planning/behavior_velocity_planner/include/utilization/trajectory_utils.hpp
planning/behavior_velocity_planner/src/node.cpp

Cherry-pick some bug fixes from upstream
- https://github.com/autowarefoundation/autoware.universe/pull/1067
- https://github.com/autowarefoundation/autoware.universe/pull/1091
- https://github.com/autowarefoundation/autoware.universe/pull/1095

chore: cherry-pick bug fixes

---

common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp

feat: ignore same points

---

planning/behavior_velocity_planner/src/scene_module/run_out/dynamic_obstacle.cpp

Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
- cherry pick for bug fiixes
- https://github.com/autowarefoundation/autoware.universe/pull/1183

fix(behavior_velocity): avoid zero division in pcl (#1183)

---

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
planning/behavior_velocity_planner/config/run_out.param.yaml
planning/behavior_velocity_planner/include/scene_module/run_out/dynamic_obstacle.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/scene.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/utils.hpp
planning/behavior_velocity_planner/run-out-design.md
planning/behavior_velocity_planner/src/scene_module/run_out/dynamic_obstacle.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/manager.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/scene.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/utils.cpp

Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
- cherry-pick for bug fix
- https://github.com/autowarefoundation/autoware.universe/pull/1220
- https://github.com/autowarefoundation/autoware.universe/pull/1073

chore: cherry pick bug fixes

---

planning/behavior_velocity_planner/src/node.cpp

Signed-off-by: tanaka3 <ttatcoder@outlook.jp>
cherry-pick bug fix
- https://github.com/autowarefoundation/autoware.universe/pull/1300

fix(behavior_velocity): fix segfo at for unstable clock (#1300)

---

perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp

- cherry-pick for bug fix
- https://github.com/autowarefoundation/autoware.universe/pull/1503

fix(scan_ground_filter): fix segmentation fault (#1503)

---

planning/behavior_velocity_planner/src/scene_module/occlusion_spot/risk_predictive_braking.cpp

- cherry-pick bug fix (workaround)
- https://github.com/autowarefoundation/autoware.universe/pull/1563#event-7189191297

chore(occlusion_spot): change min distance to insert (#1563)

---

system/velodyne_monitor/Readme.md
system/velodyne_monitor/config/HDL-32E.param.yaml
system/velodyne_monitor/config/VLP-16.param.yaml
system/velodyne_monitor/config/VLP-32C.param.yaml
system/velodyne_monitor/config/VLS-128.param.yaml
system/velodyne_monitor/config/Velarray_M1600.param.yaml
system/velodyne_monitor/launch/velodyne_monitor.launch.xml

https://github.com/autowarefoundation/autoware.universe/pull/1623 のbackport

fix(velodyne monitor): fix warning and error threshold of hot temperature (1623)

---

perception/lidar_apollo_instance_segmentation/CMakeLists.txt
perception/lidar_apollo_instance_segmentation/src/detector.cpp
perception/lidar_centerpoint/lib/network/tensorrt_wrapper.cpp
perception/tensorrt_yolo/lib/src/trt_yolo.cpp
perception/traffic_light_classifier/utils/trt_common.cpp
perception/traffic_light_classifier/utils/trt_common.hpp
perception/traffic_light_ssd_fine_detector/lib/src/trt_ssd.cpp

* fix: update trt api
Signed-off-by: Daisuke Nishimatsu <border_goldenmarket@yahoo.co.jp>
* compatible build with tensorrt 8.2
Signed-off-by: Daisuke Nishimatsu <border_goldenmarket@yahoo.co.jp>
* revert changes for caffe parser
Signed-off-by: Daisuke Nishimatsu <border_goldenmarket@yahoo.co.jp>
https://github.com/autowarefoundation/autoware.universe/pull/1472 のbackport …

fix: update trt api (#1472)

---

system/velodyne_monitor/Readme.md
system/velodyne_monitor/config/HDL-32E.param.yaml
system/velodyne_monitor/config/VLP-16.param.yaml
system/velodyne_monitor/config/VLP-32C.param.yaml
system/velodyne_monitor/config/VLS-128.param.yaml
system/velodyne_monitor/config/Velarray_M1600.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/1744 のbackport

fix(velodyne_monitor): add temp_hot_*** to 20 (#1744)

---

planning/behavior_velocity_planner/src/utilization/util.cpp

fix(behavior_velocity): fix insertVelocity (autowarefoundation#1768) 

---

system/ad_service_state_monitor/include/ad_service_state_monitor/state_machine.hpp
system/ad_service_state_monitor/src/ad_service_state_monitor_node/main.cpp
system/ad_service_state_monitor/src/ad_service_state_monitor_node/state_machine.cpp

beta/v0.3.9で `pre-commit run -a` を実行した結果を適用
clang-formatがかかっただけなので動作には影響なし

fix: pre-commit

---

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
perception/heatmap_visualizer/include/heatmap_visualizer/heatmap_visualizer_node.hpp
perception/lidar_apollo_instance_segmentation/CMakeLists.txt
perception/lidar_apollo_instance_segmentation/src/detector.cpp
perception/lidar_centerpoint/lib/network/tensorrt_wrapper.cpp
perception/tensorrt_yolo/lib/src/trt_yolo.cpp
perception/traffic_light_classifier/utils/trt_common.cpp
perception/traffic_light_classifier/utils/trt_common.hpp
perception/traffic_light_ssd_fine_detector/lib/src/trt_ssd.cpp
planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_merge_from_private_road.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp

hotfix to beta/v0.5.2: 
https://github.com/autowarefoundation/autoware.universe/pull/1472
https://github.com/autowarefoundation/autoware.universe/pull/1719
https://github.com/autowarefoundation/autoware.universe/pull/1781

fix: hotfix to 0.5.2

---

common/tier4_vehicle_rviz_plugin/src/tools/console_meter.cpp
common/tier4_vehicle_rviz_plugin/src/tools/steering_angle.cpp
common/tier4_vehicle_rviz_plugin/src/tools/turn_signal.cpp

https://github.com/autowarefoundation/autoware.universe/pull/1379
Hotfix to beta/v0.5.2

fix(tier4_vehicle_rviz_plugin): initialization vehicle rviz plugin (#1379)

---

map/lanelet2_extension/lib/query.cpp

https://github.com/autowarefoundation/autoware.universe/pull/1318 のbackport

fix(lanelet2_extension): fix getCurrentLanelets() (#1318)

---

perception/crosswalk_traffic_light_estimator/src/node.cpp

**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.
https://github.com/autowarefoundation/autoware.universe/pull/1825
Hotfix to beta v0.5.2

fix(crosswalk_traffic_light_estimator): fix invalid access (#1825)

---

build_depends.repos

see https://github.com/tier4/pilot-auto.xx1/blob/beta/v0.40.0.0/autoware.repos

ci: update repos

---

common/motion_utils/src/resample/resample.cpp
planning/behavior_velocity_planner/include/scene_module/traffic_light/scene.hpp
planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
planning/obstacle_cruise_planner/src/planner_interface.cpp

- fix stop reason for traffic light / obstacle cruise
- fix motion utils node die bug 
additional PR https://github.com/autowarefoundation/autoware.universe/pull/1867 ?
cc : @purewater0901 

fix: add hotfix

---

.github/workflows/slack-send.yaml

ci: add slack-send.yaml

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

https://github.com/autowarefoundation/autoware.universe/pull/1924
Hotfix to beta/v0.5.1-odaiba

fix(avoidance): guard invalid shift point (#1924)

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_path.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/util.cpp

feat(lane_change): added lane change point

---

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/turn_signal_decider.cpp
planning/behavior_path_planner/src/utilities.cpp
planning/behavior_path_planner/test/test_utilities.cpp

fix for https://tier4.atlassian.net/browse/T4PB-20862

fix(behavior_path_planner): support overlap lane

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

https://github.com/autowarefoundation/autoware.universe/pull/2012
hotfix to beta/v0.5.2-odaiba

fix(avoidance): fix avoidance path chattering (#2012)

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

以下PRのbackport
https://github.com/autowarefoundation/autoware.universe/pull/2012 

fix(avoidance): fix avoidance path chattering (backport #2012)

---

perception/tensorrt_yolox

remove unused file. (tensorrt_yolox)

fix: remove unused file

---

sensing/imu_corrector/README.md
sensing/imu_corrector/src/imu_corrector_core.cpp

* fix: change sign of offset in imu_corrector
Signed-off-by: kminoda <koji.m.minoda@gmail.com>
* add an equation in imu_corrector readme
Signed-off-by: kminoda <koji.m.minoda@gmail.com>
* update readme in imu_corrector
Signed-off-by: kminoda <koji.m.minoda@gmail.com>
* update readme in imu_corrector
Signed-off-by: kminoda <koji.m.minoda@gmail.com>
* ci(pre-commit): autofix
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
https://github.com/autowarefoundation/autoware.universe/pull/1022 のbackport
After all checkboxes are checked, anyone who has …

fix(imu_corrector): correct sign of offset in imu_corrector (#1022)

---

planning/behavior_velocity_planner/include/scene_module/crosswalk/scene_crosswalk.hpp
planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp

https://github.com/autowarefoundation/autoware.universe/pull/2137
Hotfix to beta/v0.5.2-odaiba3
> [TIER IV INTERNAL LINK] https://tier4.atlassian.net/browse/T4PB-20946
reduce crosswalk module's processing time

perf(crosswalk): reduce processing time (#2137)

---

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/eb_path_optimizer.hpp
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils.hpp
planning/obstacle_avoidance_planner/src/eb_path_optimizer.cpp
planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
planning/obstacle_avoidance_planner/src/node.cpp
planning/obstacle_avoidance_planner/src/utils.cpp

以下のbackport
- https://github.com/autowarefoundation/autoware.universe/pull/1881 
- https://github.com/autowarefoundation/autoware.universe/pull/1192

fix(obstacle_avoidance_planner): backport #1881 and #1192 in awf/autoware.universe

---

control/trajectory_follower_nodes/include/trajectory_follower_nodes/controller_node.hpp

https://github.com/autowarefoundation/autoware.universe/pull/2550

fix(trajectory_follower_node): remove unused include line (#2550)

---

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
planning/behavior_path_planner/README.md
planning/behavior_path_planner/config/pull_out/pull_out.param.yaml
planning/behavior_path_planner/config/pull_over/pull_over.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/shift_pull_out.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher_base.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_planner_base.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/shift_pull_over.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/util.hpp
planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp
planning/behavior_path_planner/src/scene_module/pull_over/goal_searcher.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/scene_module/pull_over/shift_pull_over.cpp
planning/behavior_path_planner/src/scene_module/pull_over/util.cpp
planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp
planning/behavior_path_planner/src/utilities.cpp
planning/planning_debug_tools/include/planning_debug_tools/trajectory_analyzer.hpp
planning/planning_debug_tools/include/planning_debug_tools/util.hpp

https://github.com/autowarefoundation/autoware.universe/pull/2335

feat(behavior_path_planner): plan shift pull over/out on curve 

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp

https://github.com/autowarefoundation/autoware.universe/pull/2577

fix(behavior_path_planner): return node status in each scene modules

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher.hpp
planning/behavior_path_planner/src/scene_module/pull_over/goal_searcher.cpp

https://github.com/autowarefoundation/autoware.universe/pull/2492

feat(behavior_path_planner): pull over no stopping area

---

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp

https://github.com/autowarefoundation/autoware.universe/pull/2572

fix(behavior_path_planner): pull over emergency stop velocity

---

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp

cherr-pick https://github.com/autowarefoundation/autoware.universe/pull/2601 for beta/v0.7.0

fix(behavior_path_planner): pull over emergency stop (#2601)

---

planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp
planning/external_velocity_limit_selector/include/external_velocity_limit_selector/external_velocity_limit_selector_node.hpp
planning/external_velocity_limit_selector/launch/external_velocity_limit_selector.launch.xml
planning/external_velocity_limit_selector/package.xml
planning/external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp

cherry pick bug fixes
- https://github.com/autowarefoundation/autoware.universe/pull/2581
- https://github.com/autowarefoundation/autoware.universe/pull/2584

chore: cherry pick PRs to 0.6.0

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Sorry for my mistakes.
The build can not pass due to https://github.com/tier4/autoware.universe/pull/234, so fixed the error in this PR.
check that build pass

fix(behavior_path_planner): build avoidance module

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/2617 for beta/v0.7.0
https://github.com/autowarefoundation/autoware.universe/pull/2617
psim

fix(behavior_path_planner): consider length for unavoidable objects around the goal (#2617)

---

planning/route_handler/src/route_handler.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/2683
build

fix(route_handler): fix getShoulderLaneletSequence (#2683)

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/utils/geometric_parallel_parking.hpp
planning/behavior_path_planner/src/scene_module/pull_out/geometric_pull_out.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp
planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/2759
build

fix(behavior_path_planner): support the goal behind ego in pull out (#2759)

---

planning/behavior_path_planner/src/scene_module/lane_change/util.cpp

https://github.com/autowarefoundation/autoware.universe/pull/2847
> Currently, the generated lane change points lane ids are not properly sorted.
Ideally the lane ids should be sorted

fix(lane_change): get sorted lane ids (#2847)

---

planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/2857
build

fix(behavior_path_planner): fix geometric parallel parking guard (#2857)

---

planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp

cherry-pick performance improvement of detection area.
- https://github.com/autowarefoundation/autoware.universe/pull/2846

perf(detection_area): point and polygon inclusion check by minimum enclosing circle

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/compare_map.launch.py
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/vector_map_inside_area_filter.launch.py
planning/behavior_velocity_planner/CMakeLists.txt
planning/behavior_velocity_planner/config/run_out.param.yaml
planning/behavior_velocity_planner/include/scene_module/run_out/debug.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/dynamic_obstacle.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/manager.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/scene.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/utils.hpp
planning/behavior_velocity_planner/package.xml
planning/behavior_velocity_planner/src/scene_module/run_out/debug.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/dynamic_obstacle.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/manager.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/scene.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/utils.cpp

cherry-pick new feature for run_out
- https://github.com/autowarefoundation/autoware.universe/pull/2864

feat(behavior_velocity): add mandatory detection area for run out module

---

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/utilities.cpp

cherr-pick 
- https://github.com/tier4/autoware.universe/pull/283
- https://github.com/autowarefoundation/autoware.universe/pull/2916
https://github.com/tier4/autoware.universe/pull/283
https://github.com/autowarefoundation/autoware.universe/pull/2916
build

fix(behavior_path_planner): fix cutOverlappedLanes (#2916)

---

common/path_distance_calculator/src/path_distance_calculator.cpp

backport
- https://github.com/autowarefoundation/autoware.universe/pull/975 
- https://github.com/autowarefoundation/autoware.universe/pull/2892
https://tier4.atlassian.net/browse/T4PB-25358

fix: path distance calculator (backport #975, #2892)

---

planning/obstacle_avoidance_planner/src/node.cpp

Added a guard for this operation
https://github.com/tier4/autoware.universe/blob/a74f2546ad02e3b206e55c34ebd85e7dbf034812/planning/obstacle_avoidance_planner/src/node.cpp#L1417-L1418
https://tier4.atlassian.net/browse/T4PB-26506

fix(obstacle_avoidance_planner): guard trajectory size

---

.pre-commit-config.yaml
common/autoware_testing/autoware_testing/smoke_test.py
common/tier4_debug_tools/package.xml
common/web_controller/www/web_controller/js/menu.js
control/external_cmd_selector/launch/external_cmd_selector.launch.py
launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
launch/tier4_planning_launch/launch/scenario_planning/parking.launch.py
map/map_loader/test/lanelet2_map_loader_launch.test.py
planning/obstacle_cruise_planner/scripts/trajectory_visualizer.py
planning/planning_debug_tools/scripts/trajectory_visualizer.py
system/system_monitor/launch/system_monitor.launch.py
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/scripts/calc_utils.py
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/scripts/new_accel_brake_map_server.py
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/scripts/plotter.py
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/scripts/view_plot.py
vehicle/external_cmd_converter/launch/external_cmd_converter.launch.py

Update pre-commit setteings to fix pre-commit.ci action
It is OK if the pre-commit.ci action is successful.

fix: pre-commit settings

---

simulator/fault_injection/CMakeLists.txt
simulator/fault_injection/package.xml

* fix(fault injection) add find package to cmake
* feat: add pluginlib to dependency
---------
Backport https://github.com/autowarefoundation/autoware.universe/pull/2973

fix(fault injection): add find package to cmake (#2973)

---

planning/behavior_path_planner/src/utilities.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3012

fix(behavior_path_planner): fix calcLateralDistanceFromEgoToObject (#3012)

---

planning/behavior_velocity_planner/src/scene_module/run_out/dynamic_obstacle.cpp

cherry-pick for bug fix.
- https://github.com/autowarefoundation/autoware.universe/pull/3021

fix(run_out): place of clearing points (#3021)

---

.github/workflows/dispatch-release-note.yaml

https://star4.slack.com/archives/C03QU7K50D8/p1678866810460479
リリースノート自動生成用のworkflow追加

feat: add release note workflow to v0.7.0 odaiba1

---

planning/motion_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp

fix : https://tier4.atlassian.net/browse/T4PB-26883
https://github.com/autowarefoundation/autoware.universe/pull/2989

fix(motion_velocity_smoother): fix too slow speed

---

.github/workflows/dispatch-release-note.yaml

https://star4.slack.com/archives/C03QU7K50D8/p1678866810460479
リリースノート自動生成用のworkflow追加

feat: add release note workflow to v0.7.2

---

.github/workflows/dispatch-release-note.yaml

- リリースノートを自動的に作成するためのGithub Actionsを追加．
- プロダクトの他のソフトウェアと独立しているため，それらに影響を与えない．
- tier4/mainやv0.6.1ブランチ等でテスト済．
- approve後はsquash mergeします．

feat: add release note workflow v0.3.15

---

perception/euclidean_cluster/config/voxel_grid_based_euclidean_cluster.param.yaml
perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py

Cherry-pick to beta/v0.7.0-odaiba1
https://github.com/autowarefoundation/autoware.universe/pull/2749
https://github.com/autowarefoundation/autoware.universe/pull/2749
See https://github.com/autowarefoundation/autoware.universe/pull/2749

fix(euclidean_cluster): keep pointcloud resolution in long-range for Euclidean cluster (#2749)

---

system/system_error_monitor/config/diagnostic_aggregator/system.param.yaml

fix(system_error_monitor): typo

---

control/trajectory_follower/src/mpc_utils.cpp

https://github.com/autowarefoundation/autoware.universe/pull/2482 のbackport

fix(trajectory_follower): fix mpc trajectory z pos (backport #2482)

---

.github/workflows/dispatch-release-note.yaml

https://star4.slack.com/archives/C03QU7K50D8/p1678866810460479
リリースノート自動生成用のworkflow追加

feat: add release note workflow to v0.7.0

---

.github/workflows/dispatch-release-note.yaml

https://star4.slack.com/archives/C03QU7K50D8/p1678866810460479
リリースノート自動生成用のworkflow追加

feat: add release note workflow to v0.7.1

---

system/system_error_monitor/config/diagnostic_aggregator/planning.param.yaml
system/system_error_monitor/config/diagnostic_aggregator/sensing.param.yaml

- Update aggregator settings
- https://github.com/tier4/aip_launcher/pull/124
- https://github.com/tier4/autoware_launch.x2/pull/269

chore: update aggregator

---

planning/behavior_path_planner/CMakeLists.txt

use new architecure in behavior_path_planner.
[#2919](https://github.com/autowarefoundation/autoware.universe/pull/2919), ([#2987](https://github.com/autowarefoundation/autoware.universe/pull/2987), [#2997](https://github.com/autowarefoundation/autoware.universe/pull/2997), [#3003](https://github.com/autowarefoundation/autoware.universe/pull/3003), [#3005](https://github.com/autowarefoundation/autoware.universe/pull/3005), [#3016](https://github.com/autowarefoundation/autoware.universe/pull/3016)、[#3481](https://github.com/autowarefoundation/autoware.universe/pull/3481) ... )
(TIER IV INTERNAL LINK) https://star4.slack.com/archives/CEV8XMJBV/p1682513646322729
I confirmed that Autoware launches without any erros.
-
no changes
Follow the link …

feat: use new behavior_path_planner architecture

---

planning/behavior_velocity_planner/src/utilization/util.cpp

Same as https://github.com/autowarefoundation/autoware.universe/pull/3572
See https://github.com/autowarefoundation/autoware.universe/pull/3572
See https://github.com/autowarefoundation/autoware.universe/pull/3572
See https://github.com/autowarefoundation/autoware.universe/pull/3572
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guid …

feat(behavior_velocity_planner::intersection): modify module deletion condition

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3601 for beta/v0.8
psim in main
no
no

fix(behavior_path_planner): fix goal planner backward parking (#3601)

---

common/rtc_manager_rviz_plugin/src/rtc_manager_panel.cpp
common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.cpp

Cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/3517
- https://github.com/autowarefoundation/autoware.universe/pull/3598
https://star4.slack.com/archives/C4P0NSMB5/p1683513235580879
Not needed

fix(*_rviz_plugin): the timing of updating

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/3637
- https://github.com/autowarefoundation/autoware.universe/pull/3638
- https://github.com/autowarefoundation/autoware.universe/pull/3636
- https://github.com/autowarefoundation/autoware.universe/pull/3649
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …

fix(behavior_path_planner): hotfix for behavior path planner

---

planning/behavior_path_planner/src/planner_manager.cpp

hotfix for beta/v0.8.0
https://github.com/autowarefoundation/autoware.universe/pull/3652

fix(planner_manager): delete subsequent approved modules (#3652)

---

.github/workflows/build-and-test-differential-self-hosted.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test-self-hosted.yaml
.github/workflows/build-and-test.yaml
.github/workflows/check-build-depends.yaml

galactic仕様のactionをhumbleに切り替える
https://tier4.atlassian.net/browse/AEAP-509
Humble対応したパッケージに対してこのPRをマージして、build-and-test-differentialが問題ないこと

fix(ci): fix action for Humble

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/utils/safety_check.hpp
planning/behavior_path_planner/src/utils/safety_check.cpp
planning/behavior_path_planner/test/test_safety_check.cpp

Hotfix for lane change safety check

feat(behavior_path_planner): update lane change safety check

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/utils/utils.cpp

https://github.com/autowarefoundation/autoware.universe/pull/3670
https://github.com/autowarefoundation/autoware.universe/pull/3672
https://github.com/autowarefoundation/autoware.universe/pull/3678
Check each PR
Check each PR

fix(behavior_path_planner): fix pull_over and pull_out

---

control/pure_pursuit/include/pure_pursuit/util/planning_utils.hpp
control/pure_pursuit/include/pure_pursuit/util/tf_utils.hpp
control/pure_pursuit/package.xml

pure_pursuitのhumbleでのビルドエラーを修正
ビルドが成功すること

fix(pure_pursuit): fix build error in Humble

---

common/autoware_auto_tf2/CMakeLists.txt
common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
common/autoware_auto_tf2/package.xml
common/autoware_auto_tf2/test/test_tf2_autoware_auto_msgs.cpp

https://github.com/autowarefoundation/autoware.universe/pull/718/files#diff-08a1db63ad65e385abc607cbf9bd8f717a67e664308e5371d7784e2b19e63464
を参考にビルドエラーを修正
ビルドが通ること

fix(autoware_auto_tf2): fix build error in Humble

---

common/osqp_interface/CMakeLists.txt

osqp_interfaceをHumbleでビルド出来るように修正
以下PRを参考
https://github.com/autowarefoundation/autoware.universe/pull/776
ビルドできることを確認

fix(osqp_interface): fix build error in Humble

---

common/motion_common/include/motion_common/motion_common.hpp
common/motion_common/src/motion_common/motion_common.cpp
common/motion_testing/src/motion_testing/motion_testing.cpp

fix(motion_common, motion_testing): fix buid error in Humble

---

sensing/tier4_pcl_extensions/include/tier4_pcl_extensions/voxel_grid_nearest_centroid.hpp
sensing/tier4_pcl_extensions/include/tier4_pcl_extensions/voxel_grid_nearest_centroid_impl.hpp

https://github.com/autowarefoundation/autoware.universe/pull/795
を参考にビルドエラーを修正
https://tier4.atlassian.net/browse/AEAP-486
ビルドが通ること。
残存Warning、Noteなし。

fix(tier4_pcl_extensions): modify build error in humble

---

localization/ndt_pcl_modified/CMakeLists.txt
localization/ndt_pcl_modified/include/ndt_pcl_modified/impl/ndt.hpp
localization/ndt_pcl_modified/include/ndt_pcl_modified/ndt.hpp

https://github.com/autowarefoundation/autoware.universe/pull/793 を参考にビルドエラーを修正
参考元と同じ変更になっていること
ndt_pcl_modifiedのビルドが成功すること

fix(ndt_pcl_modified): fix buid error in Humble

---

localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
localization/ndt_scan_matcher/include/ndt_scan_matcher/util_func.hpp
localization/ndt_scan_matcher/package.xml
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

https://github.com/autowarefoundation/autoware.universe/pull/793 を参考にビルドエラーを修正
一部上記PRに存在しない修正もあり
- tf2_sensor_msgs.h -> tf2_sensor_msgs.hpp
以下で依存パッケージの修正を行っているため、以下を先にマージする必要あり
https://github.com/tier4/autoware.universe/pull/446
https://github.com/tier4/autoware.universe/pull/445
ndt_scan_matcherがビルドできること …

fix(ndt_scan_matcher): fix build error in Humble

---

localization/gyro_odometer/include/gyro_odometer/gyro_odometer_core.hpp
localization/gyro_odometer/src/gyro_odometer_core.cpp

以下を修正
- tf2_geometry_msgs.h -> tf2_geometry_msgs.hpp
gyro_odometerのビルドが出来ること

fix(gyro_odometer): fix build error in Humble

---

common/tier4_perception_rviz_plugin/src/tools/interactive_object.hpp

以下を修正
tf2_geometry_msgs.h -> tf2_geometry_msgs.hpp
tier4_perception_rviz_pluginがビルドできること

fix(tier4_perception_rviz_plugin): fix build error in Humble

---

common/tier4_planning_rviz_plugin/src/mission_checkpoint/mission_checkpoint.cpp

以下を修正
tf2_geometry_msgs.h -> tf2_geometry_msgs.hpp
tier4_planning_rviz_pluginがビルドできること

fix(tier4_planning_rviz_plugin): fix build error in Humble

---

common/interpolation/include/interpolation/spline_interpolation_points_2d.hpp
common/interpolation/src/spline_interpolation_points_2d.cpp

https://github.com/autowarefoundation/autoware.universe/pull/698 を参考にビルドエラーを解消。
https://tier4.atlassian.net/browse/AEAP-486
ビルドが通ること。
残存Warning、Noteなし。

fix(interpolation): modify implementation of template function

---

map/map_loader/CMakeLists.txt

https://github.com/autowarefoundation/autoware.universe/pull/777 のbackport
map_loaderがビルドできること

fix(map_loader): modify build error in rolling (#777)

---

perception/shape_estimation/CMakeLists.txt
perception/shape_estimation/lib/corrector/utils.cpp
perception/shape_estimation/lib/model/bounding_box.cpp
perception/shape_estimation/src/node.cpp

https://github.com/autowarefoundation/autoware.universe/pull/802 を参考にビルドエラーを修正
shape_estimationがビルドできること

fix(shape_estimation): fix build error in Humble

---

planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
planning/obstacle_stop_planner/src/debug_marker.cpp
planning/obstacle_stop_planner/src/node.cpp

以下を参考に修正
- https://github.com/autowarefoundation/autoware.universe/pull/787
- https://github.com/autowarefoundation/autoware.universe/pull/839
obstacle_stop_plannerがビルドできること

fix(obstacle_stop_planner): fix build error in Humble

---

perception/compare_map_segmentation/src/distance_based_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_based_approximate_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_based_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_distance_based_compare_map_filter_nodelet.cpp

以下参考に修正
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-877fb71d93eed279ed17a40d7a15fd0fed864e3d1fcd9eda9f00ad3145673cfeL66-R66
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-ff3d527bac104f778101cba4bd857362ba2ab5734910170cd5b4ac37912b788aL75-R75
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-a9aa8090b5da3816a927fda531f4fde6055bd232d281f36dec075eddd33c1051L242-R242
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-65a8a8dc81e7c82675ff7d83637187d569a3da77cbb47ab7b38133c263bb0225L77-R77
compare_map_segmentationがビルドできること
The PR reviewers …

fix(compare_map_segmentation): fix build error in Humble

---

perception/ground_segmentation/CMakeLists.txt
perception/ground_segmentation/include/ground_segmentation/ransac_ground_filter_nodelet.hpp
perception/ground_segmentation/include/ground_segmentation/ray_ground_filter_nodelet.hpp
perception/ground_segmentation/include/ground_segmentation/scan_ground_filter_nodelet.hpp
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp
perception/ground_segmentation/src/ray_ground_filter_nodelet.cpp

以下を参考に修正を実施
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-544a6a8c6f91999bdab2733dd058d341ceef621c1ae161f05e7fe658f9d364a7L35-R40
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-0daa83cb73871768fe4b6c0c85c997da7023506e14206ce17fa429b94f2e9d6bR32
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-4fed771cf4c2d7eeb0dcfb255310bccda4874960fff689c8f1ef1cdb96ca4905R58
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-433178652c8774a40b0565f5b1f93d10de02a072b448e2e2f3cb603c657693c8R32
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-bf17ef89f53943bf9b777b67c356f3b994fb97937d99799928e4504b0c43a63bL20
- …

fix(ground_segmentation): fix build error in Humble

---

planning/behavior_velocity_planner/CMakeLists.txt
planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp
planning/behavior_velocity_planner/include/scene_module/occlusion_spot/occlusion_spot_utils.hpp
planning/behavior_velocity_planner/include/utilization/arc_lane_util.hpp
planning/behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner/src/scene_module/detection_area/debug.cpp
planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
planning/behavior_velocity_planner/src/scene_module/no_stopping_area/debug.cpp
planning/behavior_velocity_planner/src/scene_module/no_stopping_area/scene_no_stopping_area.cpp
planning/behavior_velocity_planner/src/scene_module/stop_line/debug.cpp
planning/behavior_velocity_planner/src/scene_module/traffic_light/debug.cpp
planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
planning/behavior_velocity_planner/src/utilization/path_utilization.cpp
planning/behavior_velocity_planner/test/src/test_occlusion_spot_utils.cpp
planning/behavior_velocity_planner/test/src/utils.hpp

以下を参考に修正を実施
https://github.com/autowarefoundation/autoware.universe/pull/799
behavior_velocity_plannerがビルドできること

fix(behavior_velocity_planner): fix build error in Humble

---

simulator/simple_planning_simulator/package.xml
simulator/simple_planning_simulator/test/test_simple_planning_simulator.cpp

以下を参考に修正
- https://github.com/autowarefoundation/autoware.universe/pull/718/files#diff-56839da3f888ce0de9fa9636be638f0ba79af19d9a63677ca251fe8dea8a3f9dR22-R24
- https://github.com/autowarefoundation/autoware.universe/pull/718/files#diff-34a227aa599a14cbb21c4fd43f04699e19bf9031ad4056246bb10adcf10dd522R22
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-34a227aa599a14cbb21c4fd43f04699e19bf9031ad4056246bb10adcf10dd522L276-R276
simple_planning_simulatorがビルドできること …

fix(simple_planning_simulator): fix build error in Humble

---

system/dummy_diag_publisher/package.xml

https://github.com/autowarefoundation/autoware.universe/pull/760 のbackport
dummy_diag_publisherがビルドできること

fix(dummy_diag_publisher): modify build error in rolling (#760)

---

common/motion_utils/include/motion_utils/marker/marker_helper.hpp
common/motion_utils/src/marker/marker_helper.cpp
planning/behavior_velocity_planner/src/scene_module/crosswalk/debug.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3654

fix(behavior_velocity_planner): fixed virtual wall marker id duplication  (#3654)

---

planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
planning/behavior_path_planner/docs/behavior_path_planner_manager_design.md
planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp

feat
- https://github.com/autowarefoundation/autoware.universe/pull/3642
- https://github.com/autowarefoundation/autoware.universe/pull/3717
- このPRで付随的にmodified_goalがpublishされないときがある問題が修正されます 
fix
- https://github.com/autowarefoundation/autoware.universe/pull/3721
docs
- https://github.com/autowarefoundation/autoware.universe/pull/3690
psim with main and beta
not applicable
not applicable
[pull request …

feat(behavior_path_planner): update and fix goal_planner

---

planning/behavior_path_planner/src/utils/path_utils.cpp

This reverts commit 605ea15c4333d42f9b0b8ff5f12dc5657f5402e2.
https://star4.slack.com/archives/C03QW0GU6P7/p1684233753903039
behavior_velocity周りのシナリオの失敗にhttps://github.com/autowarefoundation/autoware.universe/pull/3720 が怪しいそうなのでbeta/0.8では一旦revert
https://github.com/autowarefoundation/autoware.universe/pull/3720
not testd
not applicable
not applicable …

revert: "fix(behavior_path_planner): keep terminal point in resamplePathWithSpline (#3720)"

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

- cherry pick https://github.com/autowarefoundation/autoware.universe/pull/3730

fix(avoidance): update ego avoidance velocity if the ego is faster than saved velocity (#3730)

---

sensing/probabilistic_occupancy_grid_map/package.xml
sensing/probabilistic_occupancy_grid_map/src/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.cpp
sensing/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map.cpp
sensing/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp

fix(probabilistic_occupancy_grid_map): fix build error in Humble

---

planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Cherry-pick https://github.com/autowarefoundation/autoware.universe/commit/3f63c15a28920273f641c174231e87855bcb4f29

fix(behavior_path_planner): remove setting maximum velocity after lane change

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/3767

feat(avoidance): don't avoid objects around crosswalks (#3767)

---

planning/behavior_path_planner/src/utils/utils.cpp
planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

https://github.com/autowarefoundation/autoware.universe/pull/3781
https://github.com/autowarefoundation/autoware.universe/pull/3784

feat: hotfix to beta/v0.8.0

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/3798

fix(avoidance): reset rtc status in yield status (#3798)

---

planning/behavior_velocity_intersection_module/src/debug.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/util.cpp

https://github.com/autowarefoundation/autoware.universe/pull/3711 のhotfix
交差点_障害物停止が全passする
https://evaluation.tier4.jp/evaluation/reports/f0ee1c57-c27e-55ab-9eea-e7cc5f9462f9?project_id=prd_jt
commonも全pass（behavior_pathの新アーキでは不具合が出る）
新アーキではこのPRが入っているためfailしてしまう
https://github.com/tier4/autoware.universe/pull/488
このPRはbeta/v0.42.0ではrevertされているため，この問題は現在表面化はしていない． …

fix(intersection): static pass judge

---

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/src/node.cpp

https://github.com/autowarefoundation/autoware.universe/pull/3812 のbackport
https://tier4.atlassian.net/browse/AEAP-557
backport元と同じ修正であること

fix(autonomous_emergency_braking): fix imu tranform to base_link (#3812)

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/behavior_tree_manager.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

hotfix https://github.com/autowarefoundation/autoware.universe/pull/3807

feat(behavior_path_planner): output stop reasons (#3807)

---

system/system_monitor/include/system_monitor/mem_monitor/mem_monitor.hpp
system/system_monitor/src/mem_monitor/mem_monitor.cpp

cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/3795

feat(cherry-pick): add detection of ECC memory errors

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3854
https://github.com/autowarefoundation/autoware.universe/pull/3854
psim
not applicable
not applicable

fix(goal_planner): generate goal candidates after execution (#3854)

---

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Fix build error of behavior_path_planner.
I checked to success to build

fix(behavior_path_planner): fix build error

---

perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp

https://github.com/autowarefoundation/autoware.universe/pull/3914

fix(compare_map_segmentation): initialize timer_callback_group_ (#3914)

---

planning/behavior_path_planner/src/utils/utils.cpp

> Unable to fix lane boundary for avoid bug.
Fix bug is a future work.
https://github.com/autowarefoundation/autoware.universe/pull/3942
hotfix to beta/v0.8.0

fix(behavior_path_planner): unable to fix bound (#3942)

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Fix candidate path inconsistency.
https://github.com/tier4/autoware.universe/assets/44889564/be710f5c-b15a-44f9-953e-a6ef73a4d301
Psim
Nothing.

fix(avoidance): fix candidate path inconsistency

---

planning/motion_velocity_smoother/config/default_motion_velocity_smoother.param.yaml
planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp
planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
planning/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp
system/system_error_monitor/config/diagnostic_aggregator/planning.param.yaml

Fixed a problem with slow deceleration when rapid deceleration is required
https://tier4.atlassian.net/browse/RT0-24965
1. Spawn obstacles in front of the vehicle to rapid deceleration
2. The diagnostics of "smoother_errors" is triggered and emergency stop is performed.

feat(motion_velocity_smoother): add a diagnostic for smoothing failure

---

planning/motion_velocity_smoother/package.xml

- Fixing motion_velocity_smoother/package.xml
-  add `diagnostic_updater`

fix(motion velocity smoother): add dependency

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml

hotfix https://github.com/autowarefoundation/autoware.universe/pull/3645 to beta/v.0.8.1
---------

fix(tier4_perception_launch): fix duplicated topic name (#3645)

---

common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp

calcLongitudinalOffsetPose関数を、現時点autoware.universe 最新の https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp#L855-L968 からコピーします。
https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp#L855-L968
- https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp#L855-L968
と同一の関数が取り込まれていることを確認済みです。
- buildがパスすることを確認済みです。
- https://github.com/tier4/autoware.universe/pull/210 にて正常に動作することを確認済みです。
The PR reviewers **must** check the …

feat(tier4_autoware_utils): add function from 514fea4

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

This reverts commit 65a50655b543423285764ae59915b64ee745d065.
avoidance がシナリオfailしている
https://star4.slack.com/archives/CEV8XMJBV/p1687429597345409?thread_ts=1687153956.730319&cid=CEV8XMJBV
https://evaluation.tier4.jp/evaluation/reports/bae45056-940b-56e4-9d3d-ada35a05ae48?project_id=prd_jt
wip https://evaluation.tier4.jp/evaluation/reports/bae45056-940b-56e4-9d3d-ada35a05ae48?project_id=prd_jt
[pull …

revert(avoidance): reset rtc status in yield status (#3798)

---

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp

https://github.com/autowarefoundation/autoware.universe/pull/1694 のbackport
https://tier4.atlassian.net/browse/AEAP-508
動作については上記チケットにて確認
backport元と同じ変更となっていることを確認

fix(motion_velocity_smoother): fix stop point (backport #1694)

---

planning/behavior_path_planner/include/behavior_path_planner/utils/safety_check.hpp
planning/behavior_path_planner/src/utils/safety_check.cpp

Improve Lane Change Process
1. Remove pre-overlap check of ego_polygon and obj_polygon
2. Add rough check before detailed overlap check
3. Simplification of the function to judge whether the object is in front of ego
This PR improved ```path_with_lane_id``` Hz by about 2x, but it's still not enough. In my environment, still now the frequency of ```path_with_lane_id``` becomes 3 ~ 4 Hz at worst.
(TIERIV Internal Link: )
sample rosbag:
https://console.data-search.tier4.jp/projects/prd_jt/environments/9ba5b2bc-9b8e-438a-aba6-342d19c876a5/rosbags/94b8d76c-fac7-4b11-81f9-bef0a981e590
CI 
before:
https://evaluation.tier4.jp/evaluation/reports/96b5a931-fa46-5b9f-9ef4-5b78bbe62b49?project_id=prd_jt
after:
https://evaluation.tier4.jp/evaluation/reports/40703805-b4a1-50cc-b607-40c89b846ae6?project_i …

feat: improve lane change process

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/helper.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

hotfix(avoidance): cherry pick

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

feat(avoidance): set additional buffer margin independently (#4041)

---

planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/utils.cpp

https://github.com/autowarefoundation/autoware.universe/pull/4033
https://github.com/autowarefoundation/autoware.universe/pull/4033
See above PR.
Nothing.
Nothing.

feat(behavior_path_planner): dont cut centerline but insert stop

---

perception/map_based_prediction/config/map_based_prediction.param.yaml
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/src/map_based_prediction_node.cpp
planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/package.xml
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/utils/utils.cpp
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils/trajectory_utils.hpp
planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
planning/obstacle_avoidance_planner/src/node.cpp

動的回避の安定化、カットアウトする車を避けないように
実験で動作確認済み

hotfix: murooka's change for beta v0.42.1.0

---

planning/behavior_path_planner/src/utilities.cpp

https://github.com/autowarefoundation/autoware.universe/pull/1497 のbackport
https://tier4.atlassian.net/browse/AEAP-480
- 上記チケットにて挙動の確認を実施
- backport元と同じ変更となっていることを確認

feat(behavior_path_planner): fix goal velocity (backport #1497)

---

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

https://github.com/autowarefoundation/autoware.universe/pull/3991
See above PR.
Nothing.
Nothing.

feat(behavior_path_planner): enable delay lane change when necessary (#3991)

---

planning/behavior_path_planner/src/utils/avoidance/utils.cpp

> Extend ego lanelets for lane change planning in utils.cpp. This improves collision avoidance with traffic lights and crosswalks.
信号手前で不要に回避経路が出ることに対する修正
https://github.com/autowarefoundation/autoware.universe/pull/4189
上の画像と同じシナリオを使って回避せずに停止できることを確認

feat(avoidance): extend lanelets for target filtering (#4189)

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/utils.cpp

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4197
See above PR.
Nothing.
Nothing.

fix(behavior_path_planner): insert stop point in root reference path

---

planning/behavior_path_planner/include/behavior_path_planner/utils/geometric_parallel_parking/geometric_parallel_parking.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp
planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp
planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
planning/behavior_path_planner/src/utils/utils.cpp

hotfix for beta/v0.8.1-odaiba
- https://github.com/autowarefoundation/autoware.universe/pull/4108
- https://github.com/autowarefoundation/autoware.universe/pull/4109
- https://github.com/autowarefoundation/autoware.universe/pull/4166
- https://github.com/autowarefoundation/autoware.universe/pull/4167
before
https://evaluation.tier4.jp/evaluation/reports/6f16d581-5386-5f3f-a568-d8cb8c904a70?project_id=prd_jt
after
https://evaluation.tier4.jp/evaluation/reports/12388c2f-9093-5a6b-8980-406cb52cb2f5?project_id=prd_jt
After all checkboxes are checked, anyone who has write access can merge …

fix: hotfix start planner and goal planner

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp

Occasionally, the ```trimmed_ego_polygon``` in the intersection module becomes empty, leading to an invalid access to polygon.outer().front(). I have fixed this issue.
none
Tested on logging_simulator
none
none
The issue with the behavior_module crashing has been fixed.

fix(behavior_velocity_intersection_module): prevent invalid access for empty polygon

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

- output yellow virtual wall while the module insert decel point. (https://github.com/autowarefoundation/autoware.universe/pull/4341)
- add gurad to prevent uncomfortable stop. (https://github.com/autowarefoundation/autoware.universe/pull/4342) …

fix(avoidance): fix small issues

---

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py

behavior_velocityで
```
/perception/traffic_light_recognition/traffic_signals
```
を使っているので上記をtraffic_lightモジュールの最終出力としたが、
以下のPRでtraffic_lightモジュールの最終出力は
```
/perception/traffic_light_recognition/traffic_signals
```
であるほうがよく、behavior_velocityのinputを変えたほうがよい。となったのでtraffic_light、behavior_velocityのtopic名を修正
https://github.com/autowarefoundation/autoware.universe/pull/4133
https://github.com/autowarefoundation/autoware.universe/pull/4393 …

fix: change traffic light topic name

---

perception/image_projection_based_fusion/src/fusion_node.cpp
perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp
perception/traffic_light_occlusion_predictor/src/nodelet.cpp

Hotfix to beta/v0.10.0 for some sensing/perception issues.
https://github.com/autowarefoundation/autoware.universe/pull/4400
https://github.com/autowarefoundation/autoware.universe/pull/4426
https://github.com/autowarefoundation/autoware.universe/pull/4427

fix: add s/p hotfix for beta/v0.10.0

---

launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py
perception/compare_map_segmentation/CMakeLists.txt
perception/compare_map_segmentation/README.md
perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp
perception/compare_map_segmentation/package.xml
perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp
perception/euclidean_cluster/launch/euclidean_cluster.launch.py
perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py
perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp

Add hotfixs related to roi_cluster_fusion and compare_map_segmentation for beta/v0.10.0 
https://github.com/autowarefoundation/autoware.universe/pull/4448
https://github.com/autowarefoundation/autoware.universe/pull/4444

feat: roi_cluster_fusion bug fix and compare_map_segmentation input topic change

---

map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_searcher.hpp
planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp

* feat(behavior_path_planner): use no_parking_area for pull_over
* support no_stopping_area
---------
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3467
psim, sncenario test in main
wip: build beahvior path planner in this branch
none
none

feat(goal_planner): add no_parking_area for goal search (#3467)

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4469

chore(tier4_planning_launch): enable to abort lane change from a parameter file

---

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

See https://github.com/autowarefoundation/autoware.universe/pull/4520

fix(behavior_path_planner): fix turn signal for lane change abort

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

See https://github.com/autowarefoundation/autoware.universe/pull/4493
See https://github.com/autowarefoundation/autoware.universe/pull/4493
Nothing.
Nothing.

fix(behavior_path_planner): insert stop point for multiple lane change

---

control/vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml
control/vehicle_cmd_gate/package.xml
control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp

Merge https://github.com/autowarefoundation/autoware.universe/pull/4060

feat(vehicle_cmd_gate): use vehicle_stop_checker for  judging vehicle stop

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp

交差点自動化
https://github.com/autowarefoundation/autoware.universe/pull/4456

chore(intersection): publish decision status string (#4456)

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/util.cpp

交差点自動化
https://github.com/autowarefoundation/autoware.universe/pull/4468

feat: disable pass judge decision while peeking (#4468)

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4488 and https://github.com/autowarefoundation/autoware.universe/pull/4556
Tested in real vehicle
Nothing.
Basically, it samples accelerated lane change path.

feat(behavior_path_planner): improve lane change path sampling

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

cherry pick
- https://github.com/autowarefoundation/autoware.universe/pull/4522

chore(tier4_simulator_launch): launch camera and V2X fusion module in simple planning simulator

---

planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/util.hpp
planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
planning/behavior_path_planner/src/utils/start_planner/util.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4636 for beta/v0.10.0
The goal pose arc length can not be calculated correctly when the goal is out of current lanes.
This causes wrong path cut.
the end of current lanes is `112`
none
none

fix(start_planner): fix path when goal is out of current lanes (#4636)

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
planning/behavior_path_planner/src/utils/goal_planner/util.cpp

cherry-pick and resolve conflict https://github.com/autowarefoundation/autoware.universe/pull/4622
This fixes the following weird path
[tier4 internal slack](https://star4.slack.com/archives/CEV8XMJBV/p1692270937479599?thread_ts=1692259367.113739&cid=CEV8XMJBV)
psim
none
none …

fix(behavior_path_planner): fix simultaneous execution (#4622)

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp

fix(intersection): cherry pick for intersection die

---

planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/debug_marker.hpp
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/state_equation_generator.hpp
planning/obstacle_avoidance_planner/scripts/calculation_time_plotter.py
planning/obstacle_avoidance_planner/src/debug_marker.cpp
planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
planning/obstacle_avoidance_planner/src/node.cpp
planning/obstacle_avoidance_planner/src/state_equation_generator.cpp

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4600 and https://github.com/autowarefoundation/autoware.universe/pull/4608
Planning simulator
Nothing.
Elapsed time for obstacle avoidance planner becomes faster.

feat(obstacle_avoidance_planner): faster obstacle avoidance planner

---

system/system_monitor/launch/system_monitor.launch.xml

Disable gpu monitor until the bug is fixed.
Confirmed it on an actual vehicle.

chore(system_monitor): disable gpu monitor until bug is fixed

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/manager.cpp

merge from privateの停止線位置を外から変更できるようにする変更

feat(merge_from_private): use separate param (#4692)

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
planning/behavior_velocity_intersection_module/src/util.cpp
planning/behavior_velocity_intersection_module/src/util.hpp
planning/behavior_velocity_intersection_module/src/util_type.hpp

- https://github.com/autowarefoundation/autoware.universe/pull/4283 (バグ修正)
- https://github.com/autowarefoundation/autoware.universe/pull/4305 (差分が大きかったので取り込んだ)
- https://github.com/autowarefoundation/autoware.universe/pull/4466 (差分が大きかったので取り込んだ)
- https://github.com/autowarefoundation/autoware.universe/pull/4694 (バグ修正)
https://github.com/tier4/autoware_launch.x2/pull/374
コースを1周できることを確認
[pull request …

fix(intersection): modify ego polygon calculation

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/util.cpp
planning/behavior_velocity_intersection_module/src/util.hpp
planning/behavior_velocity_intersection_module/src/util_type.hpp

https://github.com/autowarefoundation/autoware.universe/pull/4694
https://tier4.atlassian.net/browse/RT1-3458

fix(intersection): modify ego polygon calculation (#4694)

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/freespace_pull_over.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/path_utils.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/freespace_pull_out.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/pull_out_planner_base.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
planning/behavior_path_planner/src/utils/goal_planner/freespace_pull_over.cpp
planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
planning/behavior_path_planner/src/utils/path_utils.cpp
planning/behavior_path_planner/src/utils/start_planner/freespace_pull_out.cpp
planning/behavior_path_planner/src/utils/utils.cpp

- Add freespace pull out
- launcherで`enable_freespace_planner: false`にするため既存機能への影響はないです。 https://github.com/tier4/autoware_launch.xx1/pull/619/commits/4dc92ece822cac10c5ff91d44dd53d4b1eef8053
- minor bug fix
psim
https://github.com/tier4/autoware.universe/assets/39142679/d6dbdb49-b9c5-4b2e-991c-4ca9109f8d62
https://evaluation.tier4.jp/evaluation/reports/883bda3a-6cd2-57d4-aef1-30b84aa356f1?project_id=prd_jt
none
none
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …

feat: update start goal planner

---

.github/workflows/dispatch-push-event.yaml

https://github.com/tier4/autoware.universe/pull/799
のマージ先をtier4/mainに変更したPRです。
制約：
workflow_dispatchで指定するブランチはmain固定となっているため、dispatch-repoのmainブランチにupdate-beta-branch.yamlが存在することが条件となっています。
https://github.com/tier4/autoware.universe/pull/803/files#diff-2669e526d20b4e0b507986b536a706e8890206a9b17ca9726a49602a7c3e0911R44
Slack参照
https://star4.slack.com/archives/C04CKSQ7ZFZ/p1693985325738439?thread_ts=1693903989.161479&cid=C04CKSQ7ZFZ …

ci: add dispatch-push-event workflow 

---

common/tier4_planning_rviz_plugin/include/path/display_base.hpp

- cherry pick from v0.9.1
- https://github.com/autowarefoundation/autoware.universe/pull/4907

chore: cherry-pick from v0.9.1

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/utils/utils.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_walkway_module/src/manager.cpp

cherry-pick from beta/v0.10.0
- https://github.com/tier4/autoware.universe/commits/beta/v0.10.0

chore: cherry pick from v0.10.0

---

.github/workflows/sync-upstream.yaml

- Make possible to specify target branch for sync-upstream script
- Periodic execution using cron has been removed
https://github.com/tier4/autoware.universe/actions/workflows/sync-upstream.yaml
Test1: https://github.com/tier4/autoware.universe/actions/runs/6069493855
Test2: https://github.com/tier4/autoware.universe/actions/runs/6069495007 …

chore: update sync upstream script

---

.github/workflows/beta-to-tier4-main-sync.yaml

Add workflow file to create PR for merging beta branch to tier4/main
Not yet. (I'll test after merge)

chore: add workflow to merge beta branch to tier4 main

---

common/tier4_system_rviz_plugin/CMakeLists.txt
common/tier4_system_rviz_plugin/README.md
common/tier4_system_rviz_plugin/package.xml
common/tier4_system_rviz_plugin/plugins/plugin_description.xml
common/tier4_system_rviz_plugin/src/jsk_overlay_utils.cpp
common/tier4_system_rviz_plugin/src/jsk_overlay_utils.hpp
common/tier4_system_rviz_plugin/src/mrm_summary_overlay_display.cpp
common/tier4_system_rviz_plugin/src/mrm_summary_overlay_display.hpp

cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/4945
https://tier4.atlassian.net/browse/RT0-29114
launcher PR: https://github.com/tier4/autoware_launch.x2/pull/424
Jira ticket link: https://tier4.atlassian.net/browse/RT0-29110
Launched PSim and confirmed that it is successfully loaded and visualizes the summary when checkbox marked.
Not applicable …

feat(tier4_system_rviz_plugin): add package (autowarefoundation#4945) 

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml

Same as https://github.com/tier4/autoware.universe/pull/833
https://github.com/tier4/autoware.universe/pull/831
Tested by logging.simulator.launch 

fix: camera lidar fusion launch

---

map/lanelet2_extension/CMakeLists.txt
perception/crosswalk_traffic_light_estimator/CMakeLists.txt
perception/map_based_prediction/CMakeLists.txt
perception/traffic_light_map_based_detector/CMakeLists.txt
planning/mission_planner/CMakeLists.txt
planning/route_handler/CMakeLists.txt
planning/scenario_selector/CMakeLists.txt

humble環境でlanelet2_extension関連ノードのビルドが通るようにする修正をbeta/v0.5.5へ入れる
参考：
- https://github.com/tier4/autoware.universe/pull/571
- https://github.com/tier4/autoware.universe/pull/591
build-and-test-differentialが通ればOK

fix: build v0.5.5

---

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp
planning/behavior_velocity_walkway_module/src/manager.cpp

cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/4820
- https://github.com/autowarefoundation/autoware.universe/pull/4823

chore: cherry pick

---

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_crosswalk_module/docs/ttc-ttv.svg
planning/behavior_velocity_crosswalk_module/src/debug.cpp
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

hotfix(crosswalk): cherry pick crosswalk module improvement

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml
perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py
perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.xml
sensing/pointcloud_preprocessor/CMakeLists.txt
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/crop_box_filter/crop_box_filter_nodelet.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/downsample_filter/faster_voxel_grid_downsample_filter.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/downsample_filter/voxel_grid_downsample_filter_nodelet.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/filter.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_nodelet.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/transform_info.hpp
sensing/pointcloud_preprocessor/src/downsample_filter/faster_voxel_grid_downsample_filter.cpp
sensing/pointcloud_preprocessor/src/downsample_filter/voxel_grid_downsample_filter_nodelet.cpp
sensing/pointcloud_preprocessor/src/filter.cpp

cherry-pick 
* https://github.com/autowarefoundation/autoware.universe/pull/4922
* https://github.com/tier4/autoware.universe/pull/833
Revert
* https://github.com/tier4/autoware.universe/pull/815
I will make another PR to cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4999
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/p …

feat(voxel_grid_downsample_filter): cherry-pick and revert

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.hpp

* feat(merge_from_private): make stop_distance_threshold tunable
* update
---------

feat(merge_from_private): make stop_distance_threshold tunable (#5086)

---

common/autoware_auto_geometry/CMakeLists.txt
common/autoware_auto_tf2/CMakeLists.txt
common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
planning/behavior_path_planner/CMakeLists.txt
planning/surround_obstacle_checker/CMakeLists.txt

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/5089 into release branch
None
None

fix(autoware_auto_tf2): remove tf2 geometry function duplicated in tf2 geometry msgs (#5089)

---

system/system_monitor/include/system_monitor/process_monitor/process_monitor.hpp
system/system_monitor/src/process_monitor/process_monitor.cpp

cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/5191
- https://tier4.atlassian.net/browse/RT0-28883

perf(system_monitor): fix program command line reading (#5191)

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/5022
- https://github.com/autowarefoundation/autoware.universe/pull/5046

fix(avoidance): cherry pick bug fix commits

---

localization/localization_error_monitor/config/localization_error_monitor.param.yaml

Cherry-picking: https://github.com/autowarefoundation/autoware_launch/pull/614
To resolve: https://tier4.atlassian.net/browse/RT0-29354
To be merged with: https://github.com/tier4/autoware_launch.x2/pull/470
To be done on the vehicle J6 Gen1 2

feat(localization_error_monitor): update parameter (#5201)

---

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

* feat(crosswalk): dyanmic timeout for no intention to walk decision
* update config
* update
* update config
---------
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5188
横断歩道で不要に停止しすぎないように
https://tier4.atlassian.net/browse/RT0-29311
を一部解決
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …

feat(crosswalk): dynamic timeout for no intention to walk decision (#5188)

---

planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp

https://github.com/tier4/autoware.universe/pull/695 で探索範囲を停止線に紐づくlane内に限定したが、Overlineの関数でindexの探索範囲を制限できていなかったため、重複経路において正しく判定が出来ていなかったのを修正
以下を参考にした
https://github.com/autowarefoundation/autoware.universe/pull/405/files#diff-4a562700ada9c3821029f9b18eef63077074de7135ddaadcff94418a3aa15587R213-R244
https://tier4.atlassian.net/browse/AEAP-685
AEAP-685のような重複経路において、
　
- Before: DA検知の停止線を越した場合に再度停止線が出てしまう
- After: DA検知の停止線を越した場合に正しくoverline判定される
正しくoverline判定できているかどうか
https://github.com/tier4/autoware.universe/pull/930/files#r1357577572
このソース差分を適用し、実際に停止線を超えたときに出力される値が停止線の手前側を正として、停止線を過ぎた場合にマイナス値が増加していくことを確認した
https://github.com/tier4/autoware.universe/assets/9547070/195cd04d-f3f3-44e4-8d49-4dd3c8e59888
The PR reviewers …

fix(detection_area): fix overline function

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/debug.cpp
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/util.cpp
planning/behavior_velocity_intersection_module/src/util.hpp
planning/behavior_velocity_intersection_module/src/util_type.hpp

- https://github.com/autowarefoundation/autoware.universe/pull/5270
- https://github.com/autowarefoundation/autoware.universe/pull/5304
- https://tier4.atlassian.net/browse/RT0-29415 を解決

feat(intersection): cherry-pick latest changes

---

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

cherry-pick 
https://github.com/autowarefoundation/autoware.universe/pull/5315

fix(lane_change): change logger level in isVehicleStuckByObstacle (#5315)

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp

cherry-pick 
- https://github.com/autowarefoundation/autoware.universe/pull/5337
- https://github.com/autowarefoundation/autoware.universe/pull/5346
- https://github.com/autowarefoundation/autoware.universe/pull/5348
psim
none
none

fix(lane_change): prevent stuck and chattering

---

control/autonomous_emergency_braking/src/node.cpp

improve autonomous_emergency_braking
- apply prediction_time_interval to predicted_path
- disable debug pointcloud publishing in aeb
Psim 
none
As the avove description

feat: improve autonomous_emergency_braking

---

planning/route_handler/src/route_handler.cpp

[[TICKET]](https://tier4.atlassian.net/browse/RT0-29454)
- https://github.com/autowarefoundation/autoware.universe/pull/5355

fix(route_handler): fix getting next lane logic to prevent from unexpected path cut (#5355)

---

planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5383
https://tier4.atlassian.net/browse/RT0-29562

fix(crosswalk): fix duplicated crosswalk launch

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/5399
This reverts commit 3d2a7f6038627ca52a4f0c2af6f5a8d56bc6962b.
dismiss degradation
https://github.com/autowarefoundation/autoware.universe/pull/5371#issuecomment-1776459751
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidel …

fix(goal_planner): revert "refactor(goal_planner): rebuild state transition (#5371)" (#5399)

---

common/motion_utils/include/motion_utils/vehicle/vehicle_state_checker.hpp
common/motion_utils/src/vehicle/vehicle_state_checker.cpp

https://github.com/autowarefoundation/autoware.universe/pull/5404

fix(motion_utils): fix build error (#5404)

---

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/utils/utils.cpp

related link: **[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-29578)**
- https://github.com/autowarefoundation/autoware.universe/pull/5109
- https://github.com/autowarefoundation/autoware.universe/pull/5198
- https://github.com/autowarefoundation/autoware.universe/pull/5384
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …

fix(utils): fix drivable area expansion with intersection area

---

planning/behavior_path_planner/src/turn_signal_decider.cpp

交差点内でウィンカーがつかなくなる問題の修正
https://github.com/autowarefoundation/autoware.universe/pull/4507
planning simulator

fix(behavior_path_planner): change straight turn signal condition

---

planning/behavior_velocity_intersection_module/src/util.cpp

hotfix for https://github.com/autowarefoundation/autoware.universe/pull/5516
see https://github.com/autowarefoundation/autoware.universe/pull/5516
none.
none.

fix(intersection): fix wrong resample process (#5516)

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

* fix a bug regarding nearest search
https://github.com/autowarefoundation/autoware.universe/pull/5575
see awf PR
see awf PR

fix(avoidance): fix a bug regarding the nearest search (#5575)

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Related Link: https://tier4.atlassian.net/browse/RT1-4390
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/4974
https://github.com/tier4/autoware.universe/assets/44889564/7e73aad7-b3ef-4495-a28a-ffde9fd7a80e
Psim + 852-20231113112939069790
https://github.com/tier4/autoware.universe/assets/44889564/dd19500a-d15e-46ae-85bb-a59aa800b76c …

fix(avoidance): fix avoidance path chattering

---

planning/behavior_velocity_intersection_module/src/util.cpp

cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5332

fix(intersection): fix infinite loop in tsort (#5332)

---

planning/behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp
planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/util.hpp
planning/behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_traffic_light_module/src/scene.hpp

V2Iからの通信が途切れた時に、最後に取得した赤信号までの残り時間を保持し続けてしまい、信号のGO, STOP判断が正常に動作しなかった。
これに対して、赤信号までの残り時間のstamp情報を使ってtimeout判定をするように修正。
When communication from V2I was interrupted, the remaining time until the last red signal was acquired was retained, and 　GO and STOP judgments did not work properly.
In response to this problem, I introduced timeout judgment to use the stamp information of the remaining time until the red signal.
Related:
[TIER IV INTERNAL JIRA](https://tier4.atlassian.net/browse/RT0-29815)
I tested with simple planning simulator.
The vehicle keeps stopping when the V2I communication was interrupted.
https://github.com/tier4/autoware.universe/assets/11865769/1a4d2a27-de79-406d-a9c8-2a916a02ce53
When the vehicle has stopped, I manually killed the V2I node, and the vehicle didn't keep …

fix(traffic_light): discard remaining time to red if it is timeout

---

system/component_state_monitor/config/topics.yaml

cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/5617

feat(component_state_monitor): monitor pose_estimator output (#5617)

---

localization/ndt_scan_matcher/CMakeLists.txt
localization/ndt_scan_matcher/package.xml
localization/ndt_scan_matcher/src/ndt_scan_matcher_node.cpp

cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/5465

feat(ndt_scan_matcher): use glog (#5465)

---

common/autoware_auto_geometry/CMakeLists.txt
common/autoware_auto_tf2/CMakeLists.txt
common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
planning/behavior_path_planner/CMakeLists.txt
planning/surround_obstacle_checker/CMakeLists.txt

Incorporate this commit to avoid build error.
- https://github.com/autowarefoundation/autoware.universe/pull/5127

chore: add workaround for tf2 update (#5127)

---

localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.
Click the `Preview` tab and select a PR template:
- [Standard change](?expand=1&template=standard-change.md)
- [Small change](?expand=1&template=small-change.md)
**Do NOT send a PR with this description.**

feat: add message

---

system/system_monitor/include/system_monitor/process_monitor/process_monitor.hpp
system/system_monitor/src/process_monitor/process_monitor.cpp

Incorporate this commit to improve the output of process monitor.
- https://github.com/autowarefoundation/autoware.universe/pull/5430
Enabled process monitor in PSim and confirmed that the command name in process monitor includes the full arguments.

fix(system_monitor): output command line (#5430)

---

perception/tracking_object_merger/CMakeLists.txt
perception/tracking_object_merger/README.md
perception/tracking_object_merger/config/data_association_matrix.param.yaml
perception/tracking_object_merger/config/decorative_tracker_merger.param.yaml
perception/tracking_object_merger/config/decorative_tracker_merger_policy.param.yaml
perception/tracking_object_merger/image/decorative_tracker_merger.drawio.svg
perception/tracking_object_merger/image/time_sync.drawio.svg
perception/tracking_object_merger/image/tracklet_management.drawio.svg
perception/tracking_object_merger/include/tracking_object_merger/data_association/data_association.hpp
perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/gnn_solver.hpp
perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/gnn_solver_interface.hpp
perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/mu_successive_shortest_path.hpp
perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/successive_shortest_path.hpp
perception/tracking_object_merger/include/tracking_object_merger/decorative_tracker_merger.hpp
perception/tracking_object_merger/include/tracking_object_merger/utils/tracker_state.hpp
perception/tracking_object_merger/include/tracking_object_merger/utils/utils.hpp
perception/tracking_object_merger/launch/decorative_tracker_merger.launch.xml
perception/tracking_object_merger/package.xml
perception/tracking_object_merger/src/data_association/data_association.cpp
perception/tracking_object_merger/src/data_association/mu_successive_shortest_path/mu_successive_shortest_path_wrapper.cpp
perception/tracking_object_merger/src/data_association/successive_shortest_path/successive_shortest_path.cpp
perception/tracking_object_merger/src/decorative_tracker_merger.cpp
perception/tracking_object_merger/src/utils/tracker_state.cpp
perception/tracking_object_merger/src/utils/utils.cpp

xx1やawf/mainで実装されているtracking objectのmergerを追加。
x2塩尻のスマートポールで使用できるか確認したい。
- https://github.com/tier4/autoware.universe/pull/947
xx1にて動作確認済

chore(tracking_object_merger): add tracking object merger from awf/main

---

system/system_monitor/include/system_monitor/process_monitor/process_monitor.hpp
system/system_monitor/src/process_monitor/process_monitor.cpp

以下PRのbackport
- https://github.com/autowarefoundation/autoware.universe/pull/5191
- https://github.com/autowarefoundation/autoware.universe/pull/5430
変更内容としては以下の通り
- topコマンドを256文字まで取得しその中からプログラム名を抽出していたが、これが問題となっていたため変更をrevertする
- 代わりにプログラム名の取得方法を変更し、 `/proc/{PID}/cmdline` から読み取るように変更
- `/proc/{PID}/cmdline` から取得できない場合はtopから取得する
- カーネルの場合これが起こりうるため 
https://tier4.atlassian.net/browse/AEAP-760
ベンチにおいて、以下の通り確認を実施した
1. ベンチを起動（Autowareを起動）
1. rqt_runtime_monitorを起動 `ros2 run rqt_runtime_monitor rqt_runtime_monitor`
1. process_monitorのHigh Load Procを確認し、プロセスとカーネルでコマンド名が取得できていることを確認した
1. Process
1. Kernel 
The PR author **must** check the checkboxes below …

fix(system_monitor): fix program command line reading (backport #5191, #5430)

---

system/default_ad_api_helpers/ad_api_distributor/CMakeLists.txt
system/default_ad_api_helpers/ad_api_distributor/README.md
system/default_ad_api_helpers/ad_api_distributor/launch/distributor.launch.xml
system/default_ad_api_helpers/ad_api_distributor/launch/remapped_api.launch.py
system/default_ad_api_helpers/ad_api_distributor/package.xml
system/default_ad_api_helpers/ad_api_distributor/src/distributor.cpp
system/default_ad_api_helpers/ad_api_distributor/src/distributor.hpp

Add function to distribute adapi for Main/Sub ECU switching function
- https://tier4.atlassian.net/wiki/spaces/T4DC/pages/2945255945/MRM+v0.5
- https://docs.google.com/presentation/d/1yLYPMf-yQI9o9YqnFDwMGrQY4RXTioNaD9A1nmneCgM/edit#slide=id.p

feat(ad_api_distributor): add adapi distributor

---

planning/behavior_path_planner/src/utils/utils.cpp

Related PR: https://github.com/autowarefoundation/autoware.universe/pull/5842
Related Ticket: https://tier4.atlassian.net/browse/RT1-4407

fix(static_drivable_area_expansion): fix bug in expansion logic for hatched road marking (#5842)

---

system/system_monitor/launch/system_monitor.launch.xml

Enable gpu monitor for v0.9.1 release.
Confirmed on actual vehicle.

chore(system_monitor): anable gpu monitor in beta/v0.9.1

---

.github/workflows/create-awf-latest.yml

awf-latestブランチをawf/autoware.universe:mainにrebaseするgithub workflowを作成

feat: add github workflow of create-awf-latest.yml

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml

Cherry pick https://github.com/autowarefoundation/autoware.universe/pull/6040

refactor(tier4_planning_launch): remove duplicate arguments in launch launch

---

.github/workflows/sync-awf-latest.yaml

Added a sync-awf-latest.yaml to sync tier4/autoware.unvierse:awf-latest with awf/autoware.universe:main
No need
Nothing

feat: add sync-awf-latest.yaml

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml

Cherry-picks [#6075](https://github.com/autowarefoundation/autoware.universe/pull/6075)

fix(image_projection_based_fusion): re-organize the parameters for image projection fusion (#6075)

---

planning/behavior_path_dynamic_avoidance_module/src/scene.cpp

不要なstd::cerrを削除
cherry-pick of
https://github.com/autowarefoundation/autoware.universe/pull/6137

fix(dynamic_avoidance): remove cerr

---

launch/tier4_vehicle_launch/launch/vehicle.launch.xml
vehicle/raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml
vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml
vehicle/raw_vehicle_cmd_converter/schema/raw_vehicle_cmd_converter.schema.json

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6136

fix(raw_vehicle_cmd_converter): fix parameter files to parse path to csv files

---

.github/workflows/sync-upstream.yaml

tier4/pilot-auto:awf-latestのautoware.universeがtier4/autoware.universe:awf-latestに変わったため、syncのupstream先も変更
https://star4.slack.com/archives/CTEJP8L4T/p1707295696704519

feat: use tier4/awf-latest for upstream sync

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/object_manager.cpp
planning/behavior_velocity_intersection_module/src/object_manager.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection_stuck.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/6328
- https://github.com/autowarefoundation/autoware.universe/pull/6299
- https://github.com/autowarefoundation/autoware.universe/pull/6325
https://github.com/tier4/autoware_launch.xx1/pull/772

feat(intersection): cherry-pick awf #6328 + #6299 + #6325

---

planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/6357

fix(static_drivable_area_expansion): fix invalid z-pos (#6357)

---

launch/tier4_vehicle_launch/launch/vehicle.launch.xml
vehicle/raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml
vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml
vehicle/raw_vehicle_cmd_converter/schema/raw_vehicle_cmd_converter.schema.json

backport from https://github.com/autowarefoundation/autoware.universe/pull/6136
https://tier4.atlassian.net/browse/RT0-30609
I confirmed in https://tier4.atlassian.net/browse/RT0-30609?focusedCommentId=155746

fix(raw_vehicle_cmd_converter): fix parameter files to parse path to csv files (#6136)

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/static_drivable_area.hpp
planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/6385
- https://github.com/autowarefoundation/autoware.universe/pull/6324

fix(avoidance): cherry pick

---

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/6349

fix(avoidance): limit drivable lane only when the ego in on original lane (#6349)

---

planning/behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_blind_spot_module/src/scene.hpp

https://github.com/autowarefoundation/autoware.universe/pull/6405
のcherry-pick
https://github.com/tier4/autoware_launch.xx1/pull/779

refactor(blind_spot): find first_conflicting_lane just as intersection module (#6405)

---

planning/behavior_path_dynamic_avoidance_module/src/scene.cpp

manual pick of 
https://github.com/autowarefoundation/autoware.universe/pull/6368

feat(dynamic_avoidance): change magic number  (autowarefoundation#6368)

---

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py

elevation_map_loaderでlanelet_filterを使うように変更
use_lane_filter : false
79/152
https://evaluation.tier4.jp/evaluation/reports/79122e12-95ae-5438-9d95-107ce0601812?project_id=odd2_reference
use_lane_filter : true
94/152
https://evaluation.tier4.jp/evaluation/reports/31cdf1e0-f3a4-5b10-a280-fbe4a64fc751?project_id=odd2_reference …

feat(ground_segmentation): use_lane_filter for elevation map

---

perception/image_projection_based_fusion/README.md
perception/image_projection_based_fusion/config/pointpainting.param.yaml
perception/image_projection_based_fusion/config/segmentation_pointcloud_fusion.param.yaml
perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml
perception/image_projection_based_fusion/launch/segmentation_pointcloud_fusion.launch.xml

hotfix: merge rework parameter PR to pilot-auto.xx1 v0.44.1.0
Ref: https://star4.slack.com/archives/CEV8XMJBV/p1709004315021389?thread_ts=1708431764.969459&cid=CEV8XMJBV
https://github.com/tier4/autoware_launch.xx1/pull/791#issue-2155587340
I did not check this PR.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidel …

chore(image_projection_based_fusion): rework parameters (#6169)

---

control/mpc_lateral_controller/src/mpc_lateral_controller.cpp

cherry pick of the [PR](https://github.com/tier4/autoware_launch.xx1/pull/798)

feat(mpc_lateral_controller): cherry pick

---

perception/tracking_object_merger/README.md
perception/tracking_object_merger/include/tracking_object_merger/utils/tracker_state.hpp
perception/tracking_object_merger/src/decorative_tracker_merger.cpp
perception/tracking_object_merger/src/utils/tracker_state.cpp

Cherry pick for awf universe change
https://github.com/autowarefoundation/autoware.universe/pull/6386.

fix(tracker_object_merger): add sanity check for tracker merger (#6386)

---

system/duplicated_node_checker/config/duplicated_node_checker.param.yaml
system/duplicated_node_checker/package.xml
system/duplicated_node_checker/src/duplicated_node_checker_core.cpp

cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/6488
rosbag playerを二重に起動して確認した

chore(duplicate_node_checker): print duplication name (#6488)

---

planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

cherry pick: https://github.com/autowarefoundation/autoware.universe/pull/6566
ticket link: https://tier4.atlassian.net/browse/RT1-5459

fix(drivable_area_expansion): fix invalid access (#6566)

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp

Reverts tier4/autoware.universe#1125

feat: revert keep stop policy v0.11.2

---

planning/behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_blind_spot_module/src/scene.hpp

https://star4.slack.com/archives/C04EY8CUNBC/p1710311240296419 の地図修正が適用されていたら入れて下さい

fix(blind_spot): find collision point using sibling straight lanelet boundary (#6599)

---

perception/shape_estimation/CMakeLists.txt
perception/shape_estimation/README.md
perception/shape_estimation/config/shape_estimation.param.yaml
perception/shape_estimation/launch/shape_estimation.launch.xml
perception/shape_estimation/lib/shape_estimator.cpp
perception/shape_estimation/schema/shape_estimation.schema.json
perception/shape_estimation/src/node.cpp
perception/shape_estimation/src/node.hpp

- To cherry-pick shape_estimation related PRs to solve issue at https://tier4.atlassian.net/browse/RT1-5644?focusedCommentId=160759
- https://github.com/autowarefoundation/autoware.universe/pull/5330
- https://github.com/autowarefoundation/autoware.universe/pull/6157
- https://github.com/autowarefoundation/autoware.universe/pull/6598 …

fix(shape estimation): 5330 + 6157 + 6598

---

map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/5971 partially  for using latest autoware_common
- https://github.com/autowarefoundation/autoware_common/pull/240
- https://github.com/tier4/pilot-auto.x2/pull/608
- https://tier4.atlassian.net/browse/RT0-31032
- https://star4.slack.com/archives/C0519A2HD1T/p1709599696458629?thread_ts=1709277662.657319&cid=C0519A2HD1T …

chore: cherry pick 5971

---

.github/workflows/sync-awf-latest.yaml

feat: run sync-awf-latest every one hour

---

perception/map_based_prediction/src/map_based_prediction_node.cpp

cherry pick https://github.com/autowarefoundation/autoware.universe/pull/6009
https://tier4.atlassian.net/browse/RT0-30511

feat(map_based_prediction): cope with consecutive crosswalks (#6009)

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp

change to read topic by polling
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/6702
https://star4.slack.com/archives/C03QW0GU6P7/p1712206710287159?thread_ts=1711538402.336329&cid=C03QW0GU6P7

feat(tier4_autoware_utils, obstacle_cruise): change to read topic by polling (#6702)

---

system/hazard_status_converter/package.xml
system/hazard_status_converter/src/converter.cpp
system/hazard_status_converter/src/converter.hpp

* fix: hazard status converter
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
* fix: topic name and modes
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
* fix check target mode
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
* fix message type
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
* Revert "fix check target mode"
This reverts commit 8b190b7b99490503a52b155cad9f593c1c97e553.
---------
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
(cherry picked from commit 41aab5122d416fd9c83ea49885eb5bf07673daf2)
https://github.com/autowarefoundation/autoware.universe/pull/6733
The PR author **must** check the checkboxes below …

fix(hazard_status_converter): check current operation mode (cherrypick autowarefoundation#6733)

---

planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/manager.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

cherry pick following PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/6759
- https://github.com/autowarefoundation/autoware.universe/pull/6355
- https://github.com/autowarefoundation/autoware.universe/pull/6698
- https://github.com/autowarefoundation/autoware.universe/pull/6768
- https://github.com/autowarefoundation/autoware.universe/pull/6765
[pull …

fix(avoidance): cherry pick avoidance hotfix PRs

---

planning/behavior_path_avoidance_module/src/utils.cpp

fix(avoidance): fix invalid road shoulder distance calculation
cherry pick https://github.com/autowarefoundation/autoware.universe/pull/6781

fix(avoidance): fix invalid road bound distance calculation (#6781)

---

planning/behavior_path_avoidance_by_lane_change_module/config/avoidance_by_lane_change.param.yaml
planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp
planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/src/manager.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/6786

refactor(avoidance): rebuild parameter structure (#6786)

---

planning/behavior_path_lane_change_module/src/interface.cpp

https://github.com/autowarefoundation/autoware.universe/pull/6800

revert(lane_change): disable terminal path (#6800)

---

planning/behavior_path_start_planner_module/config/start_planner.param.yaml

See: https://github.com/tier4/autoware_launch.x2/pull/642
and https://star4.slack.com/archives/C03QW0GU6P7/p1713954890172329

feat(start_planner): tune parameter to improve collision

---

.github/workflows/comment-on-pr.yaml

Similar to https://github.com/tier4/autoware_launch.x2/pull/480
Same as https://github.com/tier4/autoware_launch/pull/400

ci: add comment-on-pr.yaml

---

launch/tier4_perception_launch/launch/perception.launch.xml

to serve JT4 with 2 TL cameras

fix: use TRAFFIC_LIGHT_CAMERA_NUMBER env var

---

planning/planning_debug_tools/scripts/perception_replayer/utils.py
system/diagnostic_graph_aggregator/script/dump.py

https://results.pre-commit.ci/run/github/438106587/1713949692.oxOf5ClIR7GYX26o5SOXrQ
上記でエラーとなっている箇所を修正
https://github.com/tier4/autoware.universe/pull/1272#event-12737425385
pre-commitでエラーが出ないこと

fix: fix pre-commit

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/geometric_pull_over.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher_base.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/shift_pull_over.hpp
planning/behavior_path_goal_planner_module/src/geometric_pull_over.cpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/goal_searcher.cpp
planning/behavior_path_goal_planner_module/src/shift_pull_over.cpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/pull_out_planner_base.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

fix: start/goal_plannerのスレッドセーフ修正

---

planning/behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp

https://tier4.atlassian.net/browse/RT0-31379
This PR should be merged by default in earlier v0.20.1.x version of universe.

fix(geometric_parallel_parking): increase max dist threshold for geom pullout

---

system/default_ad_api/src/operation_mode.cpp

hotfix for beta/v0.29.0 from https://github.com/autowarefoundation/autoware.universe/pull/7590

feat(default_ad_api): add log when operation mode change fails

---

system/diagnostic_graph_utils/CMakeLists.txt
system/diagnostic_graph_utils/launch/logging.launch.xml
system/diagnostic_graph_utils/src/node/logging.cpp
system/diagnostic_graph_utils/src/node/logging.hpp

Hotfix for beta/v0.29.0 from https://github.com/autowarefoundation/autoware.universe/pull/7593

feat(diagnostic_graph_utils): add logging tool

---

launch/tier4_control_launch/launch/control.main.mrm-v0.6.tmp.launch.py
launch/tier4_planning_launch/launch/planning.main.mrm-v0.6.tmp.launch.xml
launch/tier4_system_launch/launch/system.main.mrm-v0.6.tmp.launch.xml
launch/tier4_system_launch/package.xml

This PR adds some launch files for MRMv0.6 one host test.

feat: add launch for one host test

---

simulator/simple_planning_simulator/CMakeLists.txt

feat: add control cmd switcher

---

system/leader_election_converter/src/common/converter/availability_converter.cpp

feat: add leader election converter

---

launch/tier4_perception_launch/package.xml
perception/euclidean_cluster/lib/voxel_grid_based_euclidean_cluster.cpp
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp

- Cherry-pick:
- https://github.com/autowarefoundation/autoware.universe/pull/7662  
- https://github.com/autowarefoundation/autoware.universe/pull/7734
- https://github.com/autowarefoundation/autoware.universe/pull/7771

fix(euclidean_cluster, ground_segmentation): cherry-pick bug fix PRs

---

planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp

fix(motion_velocity_planner): use the slowdown velocity (instead of 0)

---

planning/trajectory_repeater/CMakeLists.txt
planning/trajectory_repeater/README.md
planning/trajectory_repeater/config/trajectory_repeater.param.yaml
planning/trajectory_repeater/launch/trajectory_repeater.launch.xml
planning/trajectory_repeater/package.xml
planning/trajectory_repeater/src/trajectory_repeater.cpp
planning/trajectory_repeater/src/trajectory_repeater.hpp

This PR adds trajectory_repeater node which is for mrm v0.6 one host test.

feat(trajectory_repeater): mrm v0.6 add trajectory repeater based on x2 v3.0.0

---

system/mrm_stop_operator/CMakeLists.txt
system/mrm_stop_operator/README.md
system/mrm_stop_operator/config/mrm_stop_operator.param.yaml
system/mrm_stop_operator/launch/mrm_stop_operator.launch.xml
system/mrm_stop_operator/package.xml
system/mrm_stop_operator/src/mrm_stop_operator.cpp
system/mrm_stop_operator/src/mrm_stop_operator.hpp

This PR adds mrm_stop_operator node which is for mrm v0.6 function.

feat(mrm_stop_operator): mrm v0.6 add mrm stop operator based on x2 v3.0.0

---

launch/tier4_control_launch/launch/control.main.mrm-v0.6.tmp.launch.py
launch/tier4_planning_launch/launch/planning.main.mrm-v0.6.tmp.launch.xml
launch/tier4_system_launch/launch/system.main.mrm-v0.6.tmp.launch.xml
launch/tier4_system_launch/package.xml

This PR adds some launch files which is for mrm v0.6 one host test.

feat: mrm v0.6 add launch file one host test based on x2 v3.0.0

---

planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp

Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/7885

fix(motion_planning): fix processing time topic names (#7885)

---

perception/multi_object_tracker/src/multi_object_tracker_core.cpp

fix optimization of publish time check in multi_object_tracker_node.cpp
https://tier4.atlassian.net/wiki/spaces/AIP/pages/3197929026/Pilot.Auto+v0.30.0+Test+Report#%EF%BC%9CCARET%E8%A8%88%E6%B8%AC%EF%BC%9E

fix(multi_object_tracker): fix publish interval adjust timing (#7904)

---

perception/multi_object_tracker/src/multi_object_tracker_core.cpp

fix optimization of publish time check in multi_object_tracker_node.cpp
https://tier4.atlassian.net/wiki/spaces/AIP/pages/3197929026/Pilot.Auto+v0.30.0+Test+Report#%EF%BC%9CCARET%E8%A8%88%E6%B8%AC%EF%BC%9E
Implemented to v0.30.0
https://github.com/tier4/autoware.universe/pull/1400
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …

fix(multi_object_tracker): fix publish interval adjust timing

---

control/mpc_lateral_controller/src/mpc.cpp
control/pid_longitudinal_controller/include/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
control/trajectory_follower_node/test/test_controller_node.cpp

cherry-pick of
https://github.com/autowarefoundation/autoware.universe/pull/7903
- Link
None.
None.
None.

fix(controller): revival of dry steering (#7903)

---

system/dummy_diag_publisher/include/dummy_diag_publisher/dummy_diag_publisher_core.hpp
system/dummy_diag_publisher/src/dummy_diag_publisher_core.cpp

Cherry-pick of https://github.com/tier4/autoware.universe/pull/1272.
I will also propose this change to awf main later.
I have confirmed that all diags are ok in psim by dummy diag publisher.
This PR should be tested with this PR.
https://github.com/tier4/autoware_launch.x2/pull/703
- Link
None.
None.
None.

fix(dummy_diag_publisher): not use diagnostic_updater and param callback for v0.29.0

---

planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp
planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/debug.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/schema/avoidance.schema.json
planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/manager.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_avoidance_module/src/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/README.md

fix(static_obstacle_avoidance): cherry pick avoidance PRs

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

Fix missing update of https://github.com/tier4/autoware.universe/pull/1432.
- Link
None.
None.
None.

fix(tier4_simulator_launch): update diag name

---

perception/tensorrt_yolox/launch/yolox_s_plus_opt.launch.xml
perception/tensorrt_yolox/launch/yolox_tiny.launch.xml

- [Refactor PR](https://github.com/autowarefoundation/autoware.universe/pull/6746)の編集が足りなかったので追加修正します。
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076ZGRC15X/p1723623844125699?thread_ts=1723187018.138629&cid=C076ZGRC15X)
- Link
None.
None.
None.

fix(tensorrt_yolox): missing param file arg

---

localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp

Fix kalman gain 0 devision.
https://star4.slack.com/archives/C0657FNJ5EG/p1724146033607819?thread_ts=1724120481.152309&cid=C0657FNJ5EG
- Link
None.
None.
None.

fix(ekf_localizer): fix kalman gain 0 devision

---

system/leader_election_converter/CMakeLists.txt
system/leader_election_converter/package.xml
system/leader_election_converter/script/relay_to_sub.py

This PR adds an script which relay some topics from main to sub.
push y, stop relaying topics.
- Link
None.
None.
None.

feat(leader_election_converter): add relay to sub script

---

tools/reaction_analyzer/include/subscriber.hpp
tools/reaction_analyzer/include/topic_publisher.hpp

cherr-pick
https://github.com/autowarefoundation/autoware.universe/pull/8663
- Link
None.
None.
None.

fix(reaction_analyzer): fix include hierarchy of tf2_eigen (#8663)

---

common/tier4_planning_rviz_plugin/include/path/display_base.hpp

- cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/7164 
- https://star4.slack.com/archives/C03QU7K50D8/p1717638837227089
- Link
None.
None.
None.

fix(tier4_planning_rviz_plugin): memory leak (#7164)

---

planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp
planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp
planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.cpp
planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.hpp

Cherry pick of #8710
- Link
None.
None.
None.

fix(mission_planner): improve condition to check if the goal is within the lane

---

dummy/dummy_operation_mode_publisher/launch/dummy_operation_mode_publisher.launch.xml
dummy/dummy_operation_mode_publisher/src/dummy_operation_mode_publisher.cpp
dummy/dummy_operation_mode_publisher/src/dummy_operation_mode_publisher.hpp
planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
system/leader_election_converter/package.xml
system/leader_election_converter/script/relay_to_sub.py

Add `/api/operation/state` for dummy_operation_mode_publisher.
https://star4.slack.com/archives/C0657FNJ5EG/p1725412418652089?thread_ts=1725242010.450869&cid=C0657FNJ5EG
- Link
None.
None.
None.

feat(dummy_operation_mode_publisher): add an adapi topic

---

dummy/dummy_gear_cmd_publisher/CMakeLists.txt
dummy/dummy_gear_cmd_publisher/README.md
dummy/dummy_gear_cmd_publisher/config/dummy_gear_cmd_publisher.param.yaml
dummy/dummy_gear_cmd_publisher/launch/dummy_gear_cmd_publisher.launch.xml
dummy/dummy_gear_cmd_publisher/package.xml
dummy/dummy_gear_cmd_publisher/src/dummy_gear_cmd_publisher.cpp
dummy/dummy_gear_cmd_publisher/src/dummy_gear_cmd_publisher.hpp

Add dummy gear cmd publisher.
https://star4.slack.com/archives/C0657FNJ5EG/p1725242010450869
- Link
None.
None.
None.

feat(dummy_gear_cmd_publisher): add dummy gear cmd publisher

---

tools/reaction_analyzer/include/subscriber.hpp
tools/reaction_analyzer/include/topic_publisher.hpp

Fixed include hierarchy of tf2_eigen
- Link
None.
None.
None.

chore: patch tf2 eigen

---

sensing/imu_corrector/package.xml

To fix missing diagnostic_updater
- Link
None.
None.
None.

fix(package.xml): add diagnostic_updater for imu_corrector

---

system/leader_election_converter/script/relay_to_sub.py

Fix a script.
- Link
None.
None.
None.

modify(leader_election_converter): fix a mistake

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp

cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/8902
None
None
None.
None.
None.

fix(lane_change): set initial rtc state properly (#8902)

---

control/autoware_mpc_lateral_controller/param/lateral_controller_defaults.param.yaml
planning/autoware_obstacle_stop_planner/config/adaptive_cruise_control.param.yaml
planning/autoware_obstacle_stop_planner/config/obstacle_stop_planner.param.yaml
planning/autoware_obstacle_stop_planner/schema/obstacle_stop_planner.schema.json
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_planner/config/behavior_path_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml
vehicle/autoware_raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/8913
https://github.com/autowarefoundation/autoware.universe/pull/8914
https://github.com/autowarefoundation/autoware.universe/pull/8915
- Link
None.
None.
None.

fix: parameters

---

perception/autoware_detected_object_validation/README.md
perception/autoware_detected_object_validation/config/occupancy_grid_based_validator.param.yaml
perception/autoware_detected_object_validation/schema/object_lanelet_filter.schema.json
perception/autoware_detected_object_validation/schema/object_position_filter.schema.json
perception/autoware_detected_object_validation/schema/obstacle_pointcloud_based_validator.schema.json
perception/autoware_detected_object_validation/schema/occupancy_grid_based_validator.schema.json
perception/autoware_detected_object_validation/src/lanelet_filter/lanelet_filter.cpp
perception/autoware_detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp
perception/autoware_detected_object_validation/src/occupancy_grid_map/occupancy_grid_map_validator.cpp
perception/autoware_detected_object_validation/src/position_filter/position_filter.cpp

- https://github.com/autowarefoundation/autoware.universe/pull/7750
- Link
None.
None.
None.

refactor(detected_object_validation): rework parameters (#7750)

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

Resolve 
- https://docs.google.com/presentation/d/1mtx-eEXbdYYBoq1yeo0osMSPOwmSw_njXF6YoaMg30A/edit#slide=id.g2f838b942a5_0_1220
- https://star4.slack.com/archives/CEV8XMJBV/p1726544851935929?thread_ts=1726215977.926309&cid=CEV8XMJBV
- Link
None.
None.
None.

fix(goal_planner): fix time_keeper race (#8780)

---

control/autoware_autonomous_emergency_braking/package.xml

Fixes dependency problem for an unused dependency
[INTERNAL LINK](https://tier4.atlassian.net/browse/AEAP-1100)
`
colcon build and rosdep install -r --from-paths . --ignore-src --rosdistro=${ROS_DISTRO}
`
for details, [INTERNAL LINK](https://tier4.atlassian.net/browse/AEAP-1100)
None.
None.
None.

fix(autonomous_emergency_braking): delete unused dependency

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp

Cherry-pick #9040
None.
None.
None.

fix(intersection): set RTC enable (#9040)

---

perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/utils.hpp
perception/autoware_lidar_transfusion/lib/network/network_trt.cpp
perception/autoware_lidar_transfusion/lib/postprocess/postprocess_kernel.cu
perception/autoware_lidar_transfusion/lib/ros_utils.cpp

Cherry pick following 2 PRs
https://github.com/autowarefoundation/autoware.universe/pull/9057
https://github.com/autowarefoundation/autoware.universe/pull/9052
- Link
https://evaluation.tier4.jp/evaluation/reports/2b37e1da-6e28-5c31-b729-daf50689c7ca?project_id=prd_jt
Tested using webauto evaluator. Only once test fails, because the lidar does not include intensity field in it, and transfusion requires intensity value to function properly
None.
None.
None.

fix(autoware_lidar_transfusion): autoware transfusion  changes cherry pick

---

system/default_ad_api/src/interface.cpp
system/default_ad_api/test/node/interface_version.py

In oder to use FMS task skip feature, this PR updates ADAPI version to 1.5.
https://star4.slack.com/archives/CJVHMJDJ7/p1728960406286759?thread_ts=1728955553.602639&cid=CJVHMJDJ7
https://github.com/tier4/autoware.universe/pull/1583
None.
None.
None.

feat(default_ad_api): release adapi v1.5.0 (#8267)

---

launch/tier4_localization_launch/launch/localization.launch.xml
launch/tier4_localization_launch/launch/pose_twist_fusion_filter/pose_twist_fusion_filter.launch.xml

https://github.com/autowarefoundation/autoware.universe/pull/8681 のbackport
- https://tier4.atlassian.net/browse/VEH-1097
- https://star4.slack.com/archives/CRUE57C30/p1729044019642129
下記PRと一緒に確認する
- https://github.com/tier4/autoware_launch.x2.pix/pull/46
- https://github.com/tier4/autoware_launch.x2/pull/817
None.
None.
None.

chore(stop_filter): extract stop_filter.param.yaml to autoware_launch (#8681)

---

system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml

Reverts tier4/autoware.universe#1560
現時点、自己位置推定ずれ検出機能には「突然眼の前に発生した停止線」に対して自己位置推定のずれがなかった場合においても緊急停止してしまう問題がある。
この問題を孕んだ状態でリリースが難しいというプロジェクト判断により、v0.3.19としては自己位置推定ずれ検出機能のlaunch実装（起動設定及びMRM動作設定）を無効化し、次期リリースv0.3.20で正式にリリースする方針とする。
[管理チケット](https://tier4.atlassian.net/browse/AEAP-1873)
githubのrevert機能を利用していることから、 Revert処理について自動化できているためヒューマンエラーの混入リスクを防止できている。
他PR適用により削除されることが前提となるため、本PR単体としての機能変更の検証は不要と判断。 …

revert: "feat: apply pose_instability_risk to localization_diag"

---

perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp

recheckを遠距離でのみ発動するようにする変更
- Link
https://github.com/tier4/autoware_launch.x2/pull/831
None.
None.
None.

fix: ground segmentation recheck condition relax

---

common/interpolation/include/interpolation/spline_interpolation.hpp
common/interpolation/include/interpolation/spline_interpolation_points_2d.hpp
common/interpolation/package.xml
common/interpolation/src/spline_interpolation.cpp

マージ先間違えたのでPR再作成、rebaseします。
詳細やレビュー内容は以下のPRに書かれてます。
https://github.com/tier4/autoware.universe/pull/1541
https://github.com/tier4/autoware.universe/pull/1541
https://github.com/tier4/autoware.universe/pull/1541
との差分がないことを確認する
https://github.com/tier4/autoware.universe/pull/1541
こちらでレビュー済みです。
差分がないことを確認お願いします。
None.
None.

fix(interpolation): fix spline bug

---

.github/workflows/cppcheck-differential.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

[RT0-33313](https://tier4.atlassian.net/browse/RT0-33313) 対応
8/21のマージ内容の取り込み（ID:bb3d4b6）
及び、ワークフローのアクションバージョンを最新に修正
[RT0-33313]: https://tier4.atlassian.net/browse/RT0-33313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: compatible with RT0-33313

---

.github/workflows/cppcheck-differential.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

Revert following PR to fix build error.
- https://github.com/tier4/autoware.universe/pull/1652
- Link
None.
None.
None.

fix: revert Merge pull request #1652

---

dummy/dummy_operation_mode_publisher/CMakeLists.txt
dummy/dummy_operation_mode_publisher/README.md
dummy/dummy_operation_mode_publisher/config/dummy_operation_mode_publisher.param.yaml
dummy/dummy_operation_mode_publisher/launch/dummy_operation_mode_publisher.launch.xml
dummy/dummy_operation_mode_publisher/package.xml
dummy/dummy_operation_mode_publisher/src/dummy_operation_mode_publisher.cpp
dummy/dummy_operation_mode_publisher/src/dummy_operation_mode_publisher.hpp

This PR adds dummy operation mode publisher node.
- Link
None.
None.
None.

feat(dummy_operation_mode_publisher): add dummy operation mode publisher

---

planning/trajectory_repeater/CMakeLists.txt
planning/trajectory_repeater/README.md
planning/trajectory_repeater/config/trajectory_repeater.param.yaml
planning/trajectory_repeater/launch/trajectory_repeater.launch.xml
planning/trajectory_repeater/package.xml
planning/trajectory_repeater/src/trajectory_repeater.cpp
planning/trajectory_repeater/src/trajectory_repeater.hpp

This PR adds trajectory repeater node.
- Link
None.
None.
None.

feat(trajectory_repeater): add trajectory repeater node

---

localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp

This PR adds checking zero division.
- Link
None.
None.
None.

feat(ekf_localizer): check zero division

---

launch/tier4_control_launch/launch/control.launch.py
system/dummy_diag_publisher/include/dummy_diag_publisher/dummy_diag_publisher_core.hpp
system/dummy_diag_publisher/src/dummy_diag_publisher_core.cpp

This PR is enable to set param from command line.
- Link
None.
None.
None.

feat(dummy_diag_publisher): modify param setting

---

launch/tier4_control_launch/launch/control.launch.py
system/dummy_diag_publisher/include/dummy_diag_publisher/dummy_diag_publisher_core.hpp
system/dummy_diag_publisher/package.xml
system/dummy_diag_publisher/src/dummy_diag_publisher_core.cpp

This PR is enable to set params from command line.
- Link
None.
None.
None.

feat(dummy_diag_publisher): update param setting

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp

original pr link: https://github.com/autowarefoundation/autoware.universe/pull/9071
https://tier4.atlassian.net/wiki/spaces/~382034962/pages/3479405302/v4.0.1
- Link
None.
None.
None.

fix(crosswalk_module): improve direction calculation for vehicle passage at crosswalks

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

Psim
None.
| Removed | Pub | `/planning/velocity_factors/static_obstacle_avoidance` | `autoware_adapi_v1_msgs::msg::VelocityFactorArray`   | Topic description |
None.

fix(static_obstacle_avoidance): remove velocity factor

---

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/planner_interface.hpp
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/type_alias.hpp
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/utils.hpp
planning/autoware_obstacle_cruise_planner/package.xml
planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp
planning/autoware_obstacle_cruise_planner/src/utils.cpp

Psim
None.
| Removed | Pub | `/planning/velocity_factors/obstacle_cruise_planner` | `autoware_adapi_v1_msgs::msg::VelocityFactorArray`   | Topic description |
None.

fix(obstacle_cruise_planner): remove velocity factor

---

system/mrm_stop_operator/CMakeLists.txt
system/mrm_stop_operator/README.md
system/mrm_stop_operator/config/mrm_stop_operator.param.yaml
system/mrm_stop_operator/launch/mrm_stop_operator.launch.xml
system/mrm_stop_operator/package.xml
system/mrm_stop_operator/src/mrm_stop_operator.cpp
system/mrm_stop_operator/src/mrm_stop_operator.hpp

This PR adds mrm stop operator node.
- Link
None.
None.
None.

feat: add mrm stop operator mrm v0.6 for gen2

---

planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.cpp

add planning_factor_interface to behavior_velocity_planner_run_out

---

system/mrm_stop_operator/CMakeLists.txt
system/mrm_stop_operator/README.md
system/mrm_stop_operator/config/mrm_stop_operator.param.yaml
system/mrm_stop_operator/launch/mrm_stop_operator.launch.xml
system/mrm_stop_operator/package.xml
system/mrm_stop_operator/src/mrm_stop_operator.cpp
system/mrm_stop_operator/src/mrm_stop_operator.hpp

This PR adds mrm stop operator node.
- Link
None.
None.
None.

feat(mrm_stop_operator): add mrm stop operator mrm v0.6 for gen2

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp

 Feat/development branch planning factor bvp crosswalk

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/decisions.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp

add planning_factor_interface to behavior_velocity_planner_intersections

---

planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp

add planning_factor_interface to behavior_velocity_planner stopline, traffic_light

---

.github/sync-files.yaml

In the upstream `awf/autoware.universe`, the version control using ROS release tools has started, and tag names different from the current `github-release` workflow are being adopted. However, in this TIER IV fork repository, considering the impact on the product, the `github-release` workflow should remain unchanged. Therefore, this PR removes it from the `sync-files` list.
- https://github.com/autowarefoundation/autoware/pull/5652#issuecomment-2606304168
None.
None.
None.

chore(sync-files.yaml): not synchronize `github-release.yaml`

---

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp

Same change as https://github.com/tier4/autoware.universe/pull/1709
- [TIERIV internal link](https://tier4.atlassian.net/browse/RT0-34721)
None.
None.
None.

fix(mpc_lateral_controller): prevent unstable steering command while stopped v0.29.0 1

---

planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/config/traffic_light.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.hpp

This is a cherry-pick from [this PR](https://github.com/tier4/autoware.universe/pull/1774).
- First: https://github.com/tier4/pilot-auto/pull/1156
- Second: https://github.com/tier4/autoware_launch/pull/752
- Third: this PR.
- Link
None.
None.
None.

feat(autoware_behavior_velocity_traffic_light_module): add v2i to behavior_velocity_traffic_light

---

launch/tier4_perception_launch/launch/perception.launch.xml
launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
perception/autoware_traffic_light_multi_camera_fusion/README.md
perception/autoware_traffic_light_multi_camera_fusion/config/traffic_light_multi_camera_fusion.param.yaml
perception/autoware_traffic_light_multi_camera_fusion/launch/traffic_light_multi_camera_fusion.launch.xml
perception/autoware_traffic_light_multi_camera_fusion/schema/traffic_light_multi_camera_fusion.schema.json
perception/autoware_traffic_light_multi_camera_fusion/src/traffic_light_multi_camera_fusion_node.cpp

PR for launcher: https://github.com/tier4/autoware_launch/pull/762
In this PR, I'd like to incorporate following PR to pass the parameters for `traffic_light_multi_camera_fusion` from autoware_launch.
- https://github.com/autowarefoundation/autoware.universe/pull/10144
Following PRs are necessary to avoid conflicts.
- https://github.com/autowarefoundation/autoware.universe/pull/9994
- https://github.com/autowarefoundation/autoware.universe/pull/10071
- Link
Please see https://github.com/autowarefoundation/autoware.universe/pull/10144
None.
None.
None.

chore: cherry-pick 10144

---

control/autoware_mpc_lateral_controller/src/vehicle_model/vehicle_model_bicycle_kinematics.cpp

cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/10235
- Link
None.
None.
None.

chore: cherry-pick/10235

---

planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp

cherry-pick
- https://github.com/autowarefoundation/autoware_universe/pull/10245
There were merge conflicts. The current changes (not incoming changes) have been accepted.
None.
None.

chore: cherry-pick/10245

---

perception/autoware_compare_map_segmentation/src/voxel_based_compare_map_filter/node.cpp
perception/autoware_compare_map_segmentation/src/voxel_based_compare_map_filter/node.hpp
sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/filter.hpp

fix(voxel_based_compare_map): temporary fix pointcloud transform   (#10299)
* fix(voxel_based_compare_map): temporary fix pointcloud transform lookup_time
* pre-commit
* chore: reduce timeout
* fix: misalignment when tranform back output
* fix: typo
---------
- Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10299
https://tier4.atlassian.net/browse/RT0-35928
None.
None.
None.

chore: cherry-pick/10299

---

common/osqp_interface/design/osqp_interface-design.md
common/osqp_interface/include/osqp_interface/csc_matrix_conv.hpp
common/osqp_interface/include/osqp_interface/osqp_interface.hpp
common/osqp_interface/src/osqp_interface.cpp
common/osqp_interface/test/test_osqp_interface.cpp
control/autoware_mpc_lateral_controller/src/qp_solver/qp_solver_osqp.cpp
planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/velocity_optimizer.cpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/mpt_optimizer.hpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/node.hpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/state_equation_generator.hpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/utils/conditional_timer.hpp
planning/autoware_path_optimizer/src/mpt_optimizer.cpp
planning/autoware_path_optimizer/src/node.cpp
planning/autoware_path_smoother/src/elastic_band.cpp
planning/autoware_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp
planning/autoware_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp

cherry-pick [1905](https://github.com/tier4/autoware_universe/pull/1905 )and [1916](https://github.com/tier4/autoware_universe/pull/1916)
"beta/x2_gen/v0.29" is the current branch of pilot-auto.x2 "beta/v4.0".
- Link
None.
None.
None.

feat(path_optimizer): additional failure logging and failure mode handling for beta/x2_gen2/v0.29

---

system/autoware_dummy_infrastructure/config/dummy_infrastructure.param.yaml
system/autoware_dummy_infrastructure/include/autoware/dummy_infrastructure/dummy_infrastructure_node.hpp
system/autoware_dummy_infrastructure/launch/dummy_infrastructure.launch.xml
system/autoware_dummy_infrastructure/package.xml
system/autoware_dummy_infrastructure/schema/dummy_infrastructure.schema.json
system/autoware_dummy_infrastructure/src/dummy_infrastructure_node/dummy_infrastructure_node.cpp

cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10223
X1 v2025.3.0のリリースブロッキング課題への対応です。
https://tier4.atlassian.net/browse/RT0-36116
VTLのパラメータが変わっていたことで自動承認されなくなってました。
- Link
https://tier4.atlassian.net/browse/RT0-36116
チケットのEvidence欄に記載済み
[Evaluator](https://evaluation.tier4.jp/evaluation/reports/92133fe5-afba-5c2f-a711-5cb8d354b9fc?project_id=autoware_dev) 
手動での動作確認方法
- 上記PRをcherry-pick
- [Evaluator](https://evaluation.tier4.jp/evaluation/reports/cc51892d-12a6-58e4-a906-0a06d601dc83/tests/33cfc7c6-7b7a-5f91-ac08-b77bca235634/b95aeb84-759e-5308-9826-5a08dbc20528/b96577ad-567b-59a1-9894-f223a11ba50b?project_id=autoware_dev&state=failed) ここから地図をダウンロード
- [autoware_launch.x1のgrouping](https://github.com/tier4/autoware_launch.x1/blob/23efa7a7ce54a27f5b …

feat(dummy_infrastructure): auto approval when ego stops at stop line #10223

---

planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp
planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp

本PRはplanningモジュールでの以下の変更が対象である。
- 停止位置までの距離を、速度計画スムージングの影響を受けないものを新たにトピック出力する。
[テスト設計書](https://docs.google.com/presentation/d/1qBmcTJ8_LpzEllvpb0BZBogo7r7H4YBxWMFaQxQvPH8/edit#slide=id.g33b527edd91_2_0)における下記機能変更が対象である。
機能ID | 概要 
-- | -- 
F-2 | 停止位置までの距離を算出する 
- [Design](https://docs.google.com/presentation/d/1IExL0_uO_wpSKuP5OuOTVekuhOTNHYF_mXxz7ntZBEo/edit#slide=id.g2e414aff7a9_0_2799)
- [Developer Test Plan](https://docs.google.com/presentation/d/1qBmcTJ8_LpzEllvpb0BZBogo7r7H4YBxWMFaQxQvPH8/edit#slide=id.g33b69a57a1a_4_34)
- [Developer Test Report](https://docs.google.com/document/d/1jf_y4K6cuInsoT45Ytl8BReJJADuGFQXPzDVEhFYP-s/edit?tab=t.0)
- JIRA Ticket
- [Design Ticket](https://tier4.atlassian.net/browse/AEAP-2325)
- [Implementation and Testing …

feat: output the distance to stop line without smoothing processing

---

system/diagnostic_graph_utils/launch/logging.launch.xml
system/diagnostic_graph_utils/package.xml
system/diagnostic_graph_utils/src/node/logging.cpp
system/diagnostic_graph_utils/src/node/logging.hpp
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/CMakeLists.txt
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/README.md
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/package.xml
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/plugins/plugins_description.xml
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/jsk_overlay_utils.cpp
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/jsk_overlay_utils.hpp
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/string_stamped_overlay_display.cpp
visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/src/string_stamped_overlay_display.hpp

以下のbackport
https://github.com/autowarefoundation/autoware_universe/pull/9421
https://github.com/autowarefoundation/autoware_universe/pull/9741
https://github.com/autowarefoundation/autoware_universe/pull/9683
https://tier4.atlassian.net/browse/VEH-1303
- Link
Confirm at https://github.com/tier4/pilot-auto.x2/pull/1628
None.
None.
None.

feat: publish error diagnostic graph and visualize in rviz

---

perception/multi_object_tracker/src/multi_object_tracker_core.cpp

cherry-pick of https://github.com/tier4/autoware_universe/pull/1907
- Link
None.
None.
None.

feat: multi tracker sanitize update

---

perception/autoware_multi_object_tracker/src/processor/processor.cpp

cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10347
- Link
https://evaluation.tier4.jp/evaluation/reports/aea3df4d-8ebd-5b52-b058-570ddaead6ee?project_id=prd_jt
None.
None.
None.

feat(autoware_multi_object_tracker): update overlapped tracker removing process in multi obj tracker  (#10347)

---

perception/multi_object_tracker/src/processor/processor.cpp

Update sanitization(prune) process to fix the issue of temp lost for a laying adult found in LSim perception test
ソート更新：
Known objects(NO-UNKNOWN objs)かどうかを第一条件、meas timeを第二条件としてソートすることで、tracking objの削除が発生する場合は、”必ずインデックスの小さい方が大きい方を消す”ようにして、forループ以後の処理を単純化。
**更に第三条件として、meas 最終updateからの経過時間の小さいという条件を加えることで、area threshの制限等でassociation処理で関連付けできなかったobjに対して、無駄に100ms周期でどんどんspawnされるものを消せるように改善**
(
Added sorting concept:
By sorting with known objects (NO-UNKNOWN objs) as the first condition and mean time as the second condition, when a tracking obj is deleted, the smaller index will always delete the larger one, so that simplifying the processing after the for loop.
**Furthermore, by adding a third condition of checking the elapsed time since the last meas update, it is possible to eliminate the …

feat: beta/v0.29 mult obj tracker updates

---

launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_irregular_object_detector.launch.py
launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_irregular_object_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_merger.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_radar_merger.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/lidar_merger.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml
perception/autoware_image_projection_based_fusion/config/roi_pointcloud_fusion.param.yaml
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_pointcloud_fusion/node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/geometry.hpp
perception/autoware_image_projection_based_fusion/launch/roi_pointcloud_fusion.launch.xml
perception/autoware_image_projection_based_fusion/schema/roi_pointcloud_fusion.schema.json
perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/utils/geometry.cpp

- Need merge with 
- autoware_launch:  https://github.com/tier4/autoware_launch/pull/816
- autoware_launch.x2 Beta/v4.2用のCherry-pick：https://github.com/tier4/autoware_launch.x2/pull/1066
- Link
- Test by Evaluator: https://evaluation.tier4.jp/evaluation/reports/f6102c97-d341-5536-917e-53921c050a1e?project_id=prd_jt
None.
None.
None.

feat: cherry pick pr10160+10334+10333+10369 for irregular_object_detector pipeline

---

system/autoware_command_mode_switcher/launch/switcher.launch.xml
system/autoware_command_mode_switcher/src/command_mode_switcher.cpp

feat: remove sub manual mode

---

control/autoware_control_command_gate/src/command/filter.hpp
control/autoware_control_command_gate/src/command/selector.cpp
control/autoware_control_command_gate/src/command/selector.hpp
control/autoware_control_command_gate/src/control_command_gate.cpp
control/autoware_control_command_gate/src/control_command_gate.hpp
system/autoware_command_mode_switcher/src/command_mode_switcher.cpp

transition filter hotfix.
- Link
None.
None.
None.

hotfix: disable transition filter 1

---

build_depends.repos
common/autoware_agnocast_wrapper/CMakeLists.txt
common/autoware_agnocast_wrapper/README.md
common/autoware_agnocast_wrapper/cmake/agnocast_wrapper_config_extras.cmake
common/autoware_agnocast_wrapper/include/autoware/agnocast_wrapper/autoware_agnocast_wrapper.hpp
common/autoware_agnocast_wrapper/package.xml

cherry-pick
- https://github.com/autowarefoundation/autoware_universe/pull/10377
- https://github.com/autowarefoundation/autoware_universe/pull/10382
- https://github.com/autowarefoundation/autoware_universe/pull/10384
- https://github.com/autowarefoundation/autoware_universe/pull/10390
- https://github.com/autowarefoundation/autoware_universe/pull/10391
- https://github.com/autowarefoundation/autoware_universe/pull/10392
[Pilot.Auto Update Request](https://star4.slack.com/archives/C07K1PPNPTR/p1744092672405669)
[[Confluence] 20250407 Agnocast X2 v4.2.0 導入作業まとめ](https://tier4.atlassian.net/wiki/spaces/CRL/pages/3628697088/20250407+Agnocast+X2+v4.2.0)
Functionality was locally tested on X2 Gen2 (Shiojiri L4) with this PR and all the related PRs listed below applied. It was confirmed that …

feat: cherry-pick autoware_agnocast_wrapper

---

system/autoware_command_mode_switcher/src/plugins/comfortable_stop.cpp

fix: comfortable stop min jerk

---

control/autoware_stop_mode_operator/src/stop_mode_operator.cpp

fix: turn off hazard lights

---

system/autoware_command_mode_switcher/src/command_mode_switcher.cpp

fix: remove sub ecu nullptr access

---

perception/autoware_simple_object_merger/src/simple_object_merger_node.cpp
perception/autoware_simple_object_merger/src/simple_object_merger_node.hpp

* fix(simple_object_merger): add approximatefilter
* Update perception/autoware_simple_object_merger/src/simple_object_merger_node.cpp
* Update perception/autoware_simple_object_merger/src/simple_object_merger_node.cpp
* Update perception/autoware_simple_object_merger/src/simple_object_merger_node.cpp
* Update perception/autoware_simple_object_merger/src/simple_object_merger_node.cpp
* Update perception/autoware_simple_object_merger/src/simple_object_merger_node.hpp
---------
- Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10462
- Link
None.
None.
None.

fix(simple_object_merger): add approximatefilter (#10462)

---

.github/workflows/build-test-tidy-pr.yaml

Same as https://github.com/tier4/autoware_universe/pull/1982
- Link
https://github.com/tier4/autoware_universe/actions/runs/14530412416?pr=1987
None.
None.
None.

ci: use tier4 runner for build-test-tidy-pr

---

.github/workflows/build-and-test-differential.yaml
.github/workflows/build-test-tidy-pr.yaml

Fix mistaking of https://github.com/tier4/autoware_universe/pull/1987
- Link
None.
None.
None.

ci: use tier4 runner for build-and-test-differential

---

sensing/autoware_pointcloud_preprocessor/config/ring_outlier_filter_node.param.yaml
sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_node.hpp
sensing/autoware_pointcloud_preprocessor/schema/ring_outlier_filter_node.schema.json
sensing/autoware_pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_node.cpp

https://github.com/autowarefoundation/autoware_universe/commit/1d6f7616675384c869f8e29b7f2ac886ff77071b をpilot-auto.x2: beta/v4.2へ取り込むためのcherry-pick.
Launcher修正: https://github.com/tier4/aip_launcher/pull/441
- Link
None.
None.
None.

chore(ring_outlier_filter): cherry-pick #10537

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/config/obstacle_slow_down.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp

Point-Cloud clustering optimization
- Link
None.
None.
None.

feat(autoware_motion_velocity_planner): point-cloud clustering optimization

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
sensing/autoware_pointcloud_preprocessor/CMakeLists.txt

cherry pick some PRs

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
planning/autoware_rtc_interface/src/rtc_interface.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/CHANGELOG.rst
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/CMakeLists.txt
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/README.md
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/config/detection_lane.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/param/detection_lane_parameters.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/plugins.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/src/structs.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/src/utils.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/test/test_node_interface.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/test/test_utils.cpp

feat(detection_lane): add detection lane module

---

build_depends.repos

Go along with https://github.com/tier4/pilot-auto.x2/pull/1826
Related
- https://github.com/tier4/pilot-auto/pull/1390
- https://github.com/tier4/pilot-auto.xx1/pull/1703
- Link
None.
None.
None.

chore: fix agnocast version to 2.1.1

---

launch/tier4_planning_launch/launch/planning.launch.xml
planning/autoware_rear_obstacle_checker/CMakeLists.txt
planning/autoware_rear_obstacle_checker/README.md
planning/autoware_rear_obstacle_checker/config/rear_obstacle_checker.param.yaml
planning/autoware_rear_obstacle_checker/launch/rear_obstacle_checker.launch.xml
planning/autoware_rear_obstacle_checker/package.xml
planning/autoware_rear_obstacle_checker/param/rear_obstacle_checker_node_parameters.yaml
planning/autoware_rear_obstacle_checker/src/node.cpp
planning/autoware_rear_obstacle_checker/src/node.hpp
planning/autoware_rear_obstacle_checker/src/structs.hpp
planning/autoware_rear_obstacle_checker/src/utils.hpp
planning/autoware_rear_obstacle_checker/test/test_surround_obstacle_checker.cpp

feat(rear_obstacle_checker): add new module

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/scripts/ttc.py
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

https://github.com/autowarefoundation/autoware_universe/pull/10626
https://tier4.atlassian.net/browse/RT0-36216
- Link
None.
None.
None.

fix(intersection): interpolate object polygons precisely

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/config/obstacle_slow_down.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/types.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/config/obstacle_stop.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/include/autoware/motion_velocity_planner_common_universe/planner_data.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/include/autoware/motion_velocity_planner_common_universe/utils.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/src/polygon_utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/src/utils.cpp

update to v0.43 stop

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/types.hpp

feat(obstacle_stop_module): adopt PCL stop and others

---

perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/updater/binary_bayes_filter_updater.hpp
perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/utils/utils.hpp
perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/utils/utils_kernel.hpp
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed_kernel.cu
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_projective_kernel.cu
perception/autoware_probabilistic_occupancy_grid_map/lib/utils/utils.cpp
perception/autoware_probabilistic_occupancy_grid_map/lib/utils/utils_kernel.cu
perception/autoware_probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp
perception/autoware_probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/types.hpp

* fix: fixed transform issues and border conditions
* fix: fixed compilation on cpu only builds
---------
- Link
None.
None.
None.

fix(autoware_probabilistic_occupancy_grid_map): fixed transform issues and border conditions (#10344)

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp

fix param handling
- Link
None.
None.
None.

fix(obstacle_slow_down): fix object_type_specified_params

---

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_lane_module/config/detection_lane.param.yaml

fix(detection_lane): disable detection lane in komatsu

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

https://github.com/autowarefoundation/autoware_universe/pull/10682
- Link
None.
None.
None.

fix(intersection): fix possible interpolation error for predicted path

---

control/autoware_collision_detector/README.md
control/autoware_collision_detector/config/collision_detector.param.yaml
control/autoware_collision_detector/include/autoware/collision_detector/debug.hpp
control/autoware_collision_detector/include/autoware/collision_detector/node.hpp
control/autoware_collision_detector/package.xml
control/autoware_collision_detector/src/node.cpp

cherry-pick PR for
https://github.com/autowarefoundation/autoware_universe/pull/10638
and
https://github.com/autowarefoundation/autoware_universe/pull/10651
and
https://github.com/autowarefoundation/autoware_universe/pull/10683
- [TIERIV internal link](https://tier4.atlassian.net/browse/L4P-173)
None.
None.
None.

feat(collision_detector): time buffer and ignore behind rear axle

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/README.md
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/include/autoware/behavior_velocity_crosswalk_module/util.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/parked_vehicles_stop.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/parked_vehicles_stop.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/util.cpp

Implement feature described in https://tier4.atlassian.net/wiki/spaces/CT/pages/3646685185/RTL4
Requires launch PR: https://github.com/tier4/autoware_launch.x2/pull/1192
- [TIER IV JIRA](https://tier4.atlassian.net/browse/RT1-9976)
Psim
Evaluator (vanilla): https://evaluation.tier4.jp/evaluation/reports/4254f436-2d1d-5ae3-94c3-0025f11246b2?project_id=prd_jt
None.
None.
None.

feat(crosswalk): stop for parked vehicle

---

planning/autoware_rear_obstacle_checker/config/rear_obstacle_checker.param.yaml
planning/autoware_rear_obstacle_checker/src/node.cpp
planning/autoware_rear_obstacle_checker/src/structs.hpp

fix(roc): small update

---

planning/autoware_path_optimizer/src/node.cpp

* This is the cherry-pick of https://github.com/autowarefoundation/autoware_universe/pull/10726
* [TIER IV INTERNAL TICKET](https://tier4.atlassian.net/browse/RT0-37240)
Please see https://github.com/autowarefoundation/autoware_universe/pull/10726
None.
None.
None.

fix(path_optimizer): undefined behavior when optimizer failure (#10726)

---

control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/schema/run_out.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/collisions.cpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/objects_filtering.cpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/objects_filtering.hpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/types.hpp

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10754 and https://github.com/autowarefoundation/autoware_universe/pull/10754
Psim

feat(run_out): option to preserve parts of ignored predicted paths

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

https://github.com/tier4/autoware_universe/pull/2054
での取り込みミス

fix(intersection): additional fix for 10682

---

perception/autoware_image_projection_based_fusion/config/roi_detected_object_fusion.param.yaml
perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/centerpoint_config.hpp
perception/autoware_lidar_centerpoint/lib/postprocess/postprocess_kernel.cu
perception/autoware_lidar_centerpoint/src/node.cpp
perception/autoware_multi_object_tracker/lib/tracker/model/unknown_tracker.cpp

Added a new struct `is_score_greater_or_front_back_low_score` to enhance the filtering of detected 3D boxes based on score thresholds. This new logic allows for retaining lower-scoring boxes if they are within the ego vehicle's width, improving detection accuracy for objects in front or back. Updated the post-processing kernel to utilize this new condition during box suppression.
- Link
before
https://github.com/user-attachments/assets/d9c6b2d6-adcf-4512-a761-08733ae63cd6
after
https://github.com/user-attachments/assets/9be57e78-3e9a-4533-835e-21c2157def2d
Need to merge with https://github.com/tier4/autoware_launch.x2/pull/1256
None.
None.

feat(lidar_centerpoint): introduce new score filtering logic for detected boxes

---

control/autoware_smart_mpc_trajectory_follower/autoware_smart_mpc_trajectory_follower/training_and_data_check/add_training_data_from_csv.py

cherry pick this fix
https://github.com/autowarefoundation/autoware_universe/pull/10658

fix(smart_mpc): fix imperative mood by cherry picking 3cbb9f4

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/slowdown.cpp

* fix(run_out): fix  numerical stability in run_out interpolation
* fix build
---------
https://github.com/autowarefoundation/autoware_universe/pull/10808

fix(run_out): fix numerical stability in run_out interpolation (#10808)

---

control/autoware_control_validator/README.md
control/autoware_control_validator/config/control_validator.param.yaml
control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/msg/ControlValidatorStatus.msg
control/autoware_control_validator/src/control_validator.cpp

cherry-pick of https://github.com/autowarefoundation/autoware_universe/pull/10872 https://github.com/autowarefoundation/autoware_universe/pull/10876

feat(control_validator): add yaw_deviation

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/decision_state.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/bezier_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/thread_data.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp

- https://tier4.atlassian.net/browse/RT0-35453
- https://tier4.atlassian.net/browse/RT0-35454
- https://tier4.atlassian.net/browse/RT0-35455

fix(goal_planner): pr10694 + pr10776 + pr10784

---

planning/planning_validator/autoware_planning_validator_trajectory_checker/src/trajectory_checker.cpp

fix(planning_validator): check the yaw deviation of the initial trajectory

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/README.md
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/decision_result.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp

https://github.com/autowarefoundation/autoware_universe/pull/10868

feat(intersection_occlusion): adjustable occlusion wall position for intersection without traffic_light (#10868)

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/decision_state.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/bezier_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/thread_data.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

https://github.com/autowarefoundation/autoware_universe/pull/10784

feat(goal_planner): check pull over lane crossing validity when triggering candidate generation thread (#10784)

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/test/test_utils.cpp

Two bug fix PRs related to avoidance have been cherry-picked. Please refer to the following PR links for details.
- https://github.com/autowarefoundation/autoware_universe/pull/10865
- https://github.com/autowarefoundation/autoware_universe/pull/10870
Both are necessary changes for autonomous driving in Shiojiri.

chore: cherry pick PRs for static obstacle avoidance module

---

planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10891

fix: a launch mistake (#10891)

---

perception/autoware_bytetrack/config/bytetrack.param.yaml
perception/autoware_bytetrack/include/autoware/bytetrack/bytetrack.hpp
perception/autoware_bytetrack/lib/include/byte_tracker.h
perception/autoware_bytetrack/lib/include/strack.h
perception/autoware_bytetrack/lib/src/byte_tracker.cpp
perception/autoware_bytetrack/lib/src/strack.cpp
perception/autoware_bytetrack/src/bytetrack.cpp
perception/autoware_bytetrack/src/bytetrack_node.cpp

https://github.com/autowarefoundation/autoware_universe/pull/10898
* feat: enhance bytracker classification management
* fix a bug in score reset after switching label
* feat: update the score rule for same label
---------

feat: enhance bytracker classification management (#10898)

---

perception/autoware_map_based_prediction/src/predictor_vru.cpp
perception/autoware_multi_object_tracker/lib/tracker/model/tracker_base.cpp

fixing issue of https://tier4.atlassian.net/browse/RT0-37922
cherry-pick of
https://github.com/autowarefoundation/autoware_universe/pull/10906
https://github.com/autowarefoundation/autoware_universe/pull/10907

fix: pedestrian moonwalk fix 0.41

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/decision_result.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/intersection_stoplines.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp

- https://github.com/autowarefoundation/autoware_universe/pull/10911
- https://github.com/autowarefoundation/autoware_universe/pull/10900

feat(intersection): cherry-pick #10911 and #10900

---

planning/autoware_velocity_smoother/config/default_velocity_smoother.param.yaml
planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/smoother_base.hpp
planning/autoware_velocity_smoother/src/node.cpp
planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp
planning/autoware_velocity_smoother/src/smoother/smoother_base.cpp

This is a PR showing what I am testing --- Not a merging PR.
---
Update: 07/04
[This is a cherry-pick test ](https://github.com/autowarefoundation/autoware_core/pull/531) that already been tested on real vehicle

feat(velocity_smoother): implemting dynamic lateral acceleration and steering angle rate limit

---

perception/autoware_traffic_light_arbiter/README.md
perception/autoware_traffic_light_arbiter/config/traffic_light_arbiter.param.yaml
perception/autoware_traffic_light_arbiter/include/autoware/traffic_light_arbiter/signal_match_validator.hpp
perception/autoware_traffic_light_arbiter/include/autoware/traffic_light_arbiter/traffic_light_arbiter.hpp
perception/autoware_traffic_light_arbiter/schema/traffic_light_arbiter.schema.json
perception/autoware_traffic_light_arbiter/src/signal_match_validator.cpp
perception/autoware_traffic_light_arbiter/src/traffic_light_arbiter.cpp

[Background](https://tier4.atlassian.net/browse/RT0-37731)
testing results: ticket comments

feat(traffic_light_arbiter): prioritize internal TL signal when arrows are present

---

planning/planning_validator/autoware_planning_validator_trajectory_checker/src/trajectory_checker.cpp

Cherry-pick of https://github.com/autowarefoundation/autoware_universe/pull/10912

fix(planning_validator_trajectory_checker): cherry pick #10912

---

planning/planning_validator/autoware_planning_validator/README.md
planning/planning_validator/autoware_planning_validator/src/node.cpp
planning/planning_validator/autoware_planning_validator/src/utils.cpp
planning/planning_validator/autoware_planning_validator_trajectory_checker/src/trajectory_checker.cpp

Cherry-pick of https://github.com/autowarefoundation/autoware_universe/pull/10799

fix(planning_validator_trajectory_checker): cherry-pick of awf #10799

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/path.cpp

cherry pick of https://github.com/autowarefoundation/autoware_universe/pull/10951
requires https://github.com/tier4/autoware_launch/pull/995

feat(lane_change): cherry pick of awf#10951

---

control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/src/control_validator.cpp
control/autoware_control_validator/test/test_control_validator.cpp

cherry pick OR for https://github.com/autowarefoundation/autoware_universe/pull/10939

feat(control_validator): enhance trajectory validation with previous reference trajectory (#10939)

---

system/autoware_system_monitor/include/system_monitor/system_monitor_utility.hpp

Cherry-picking Pull Request to beta/v0.48 .
Cherry-picking of the following PR will fix the bug with which CPU & GPU temperatures cannot be monitored on NVIDIA Jetson AGX Orin on Central Tech (CTI) ANVIL.
- https://github.com/autowarefoundation/autoware_universe/pull/10937
This change should be included in X2 v4.3.0 Dev Freeze.

fix(autoware_system_monitor): cherry-pick : allow variations of arm64 thermal zone type name

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/test/test_utils.cpp

- See https://github.com/autowarefoundation/autoware_universe/pull/10902

fix(static_obstacle_avoidance): ensure sufficient avoidance margin on high-curvature paths for parked vehicle avoidance (#10902)

---

planning/.pages
planning/planning_validator/autoware_planning_validator/README.md
planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/debug_marker.hpp
planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/types.hpp
planning/planning_validator/autoware_planning_validator/package.xml
planning/planning_validator/autoware_planning_validator/src/debug_marker.cpp
planning/planning_validator/autoware_planning_validator/src/node.cpp
planning/planning_validator/autoware_planning_validator/src/utils.cpp
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/README.md
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/config/intersection_collision_checker.param.yaml
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/intersection_collision_checker.hpp
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/types.hpp
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/utils.hpp
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/package.xml
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/param/intersection_collision_checker_node_parameters.yaml
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/intersection_collision_checker.cpp
planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/utils.cpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/rear_collision_checker.cpp
planning/planning_validator/autoware_planning_validator_trajectory_checker/src/trajectory_checker.cpp

apply latest intersection_collision_checker improvements

feat(intersection_collision_checker): apply latest improvements

---

common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/data_structs.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.hpp

cherry-pick bdp slow down implementation test

fix(slow_down): improving slow down behavior

---

launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_merger.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_radar_merger.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml
perception/autoware_image_projection_based_fusion/launch/pointpainting_fusion.launch.xml
perception/autoware_image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml
perception/autoware_image_projection_based_fusion/launch/roi_detected_object_fusion.launch.xml
perception/autoware_image_projection_based_fusion/launch/roi_pointcloud_fusion.launch.xml
perception/autoware_image_projection_based_fusion/launch/segmentation_pointcloud_fusion.launch.xml

- Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10973

fix(tier4_perception_launch): add one more camera fusion (cherry-pick #10973)

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/debug.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/footprint.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/footprint.hpp

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/10949

feat(out_of_lane): cut trajectory footprints behind the current ego front

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp

cherry-pick
https://github.com/autowarefoundation/autoware_universe/pull/10840
related link
https://github.com/tier4/autoware_core/pull/27
https://github.com/tier4/autoware_launch/pull/998

feat(motion_utils, motion_velocity_planner, obstacle_stop): cut_in stop, RSS following, update polygon algorithm

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/config/obstacle_slow_down.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/types.hpp

feat(obstacle_slow_down): rework type specific params, split left/right

---

planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/types.hpp
planning/planning_validator/autoware_planning_validator/src/node.cpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/config/rear_collision_checker.param.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/param/rear_collision_checker_node_parameters.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/rear_collision_checker.cpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/utils.cpp

- See https://github.com/autowarefoundation/autoware_universe/pull/10992
- See https://github.com/autowarefoundation/autoware_universe/pull/11007

feat(planning_validator): cherry pick PRs

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp

Cherry-picked from https://github.com/autowarefoundation/autoware_universe/pull/11035

fix(static_obstacle_avoidance): load missing unstable classification parameter

---

perception/autoware_image_projection_based_fusion/src/roi_cluster_fusion/node.cpp

- Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11054
- Note: This only for debug mode and do not affect to operation mode.

fix(roi_cluster_fusion): fix bug in debug mode (cherry-pick #11054)

---

build_depends.repos
common/autoware_universe_utils/README.md
control/autoware_autonomous_emergency_braking/README.md
control/autoware_collision_detector/README.md
control/autoware_smart_mpc_trajectory_follower/autoware_smart_mpc_trajectory_follower/training_and_data_check/add_training_data_from_csv.py
perception/autoware_bytetrack/config/bytetrack.param.yaml
perception/autoware_bytetrack/include/autoware/bytetrack/bytetrack.hpp
perception/autoware_bytetrack/lib/include/byte_tracker.h
perception/autoware_bytetrack/lib/include/strack.h
perception/autoware_bytetrack/lib/src/byte_tracker.cpp
perception/autoware_bytetrack/lib/src/strack.cpp
perception/autoware_bytetrack/src/bytetrack.cpp
perception/autoware_bytetrack/src/bytetrack_node.cpp
perception/autoware_probabilistic_occupancy_grid_map/pointcloud-based-occupancy-grid-map.md
perception/autoware_radar_object_tracker/models.md
perception/autoware_shape_estimation/README.md
planning/autoware_path_optimizer/README.md
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/README.md
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
simulator/autoware_carla_interface/README.md
system/bluetooth_monitor/README.md
tools/reaction_analyzer/README.md

* feat: enhance bytracker classification management
* fix a bug in score reset after switching label
* feat: update the score rule for same label
Additional cherry-pick to fix build failure
https://github.com/autowarefoundation/autoware_universe/pull/10122
---------
Cherry pick bytetrack updates in v0.40 so that Xavier with older BSP version can still enjoy updates.

feat: bytetrack update v40

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

- See https://github.com/autowarefoundation/autoware_universe/pull/11032

fix(static_obstacle_avoidance): correct lane departure check during obstacle avoidance (#11032)

---

control/autoware_vehicle_cmd_gate/README.md
control/autoware_vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml
control/autoware_vehicle_cmd_gate/schema/vehicle_cmd_gate.json
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/autoware_vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp
control/autoware_vehicle_cmd_gate/test/src/test_vehicle_cmd_filter.cpp

parameter change PR: https://github.com/tier4/autoware_launch/compare/beta/v0.48...tier4:autoware_launch:v0.48+PR1570+PR1574?expand=1
cherry pick PR for 
- https://github.com/autowarefoundation/autoware_universe/pull/10781
- https://github.com/autowarefoundation/autoware_universe/pull/11057

feat(vehicle_cmd_gate): rename variable naming consistency and add steer rate constraint

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

Cherry-picked from https://github.com/autowarefoundation/autoware_universe/pull/11046

fix(autoware_behavior_path_static_obstacle_avoidance_module): prevent chattering in avoidance decision

---

common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/boundary_departure_checker.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/data_structs.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/parameters.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/utils.hpp
common/autoware_boundary_departure_checker/src/boundary_departure_checker_abnormality.cpp
common/autoware_boundary_departure_checker/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/config/boundary_departure_prevention.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/schema/boundary_departure_prevention.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/type_alias.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.hpp

cherry-pick several bdc/p commits

cherry-pick(boundary_departure): update experiment branch to latest implementation

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/CMakeLists.txt
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/config/road_user_stop.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/param/road_user_stop_module_parameters.yaml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/plugins.xml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/debug.cpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/path_length_buffer.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/road_user_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/road_user_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/type_alias.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/types.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/utils.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/test/test_utils.cpp

- cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11041

feat(road_user_stop): add road_user_stop module (#11041)

---

perception/autoware_map_based_prediction/include/map_based_prediction/data_structure.hpp
perception/autoware_map_based_prediction/include/map_based_prediction/predictor_vru.hpp
perception/autoware_map_based_prediction/src/predictor_vru.cpp

- See https://github.com/autowarefoundation/autoware_universe/pull/11084

fix(map_based_prediction): pedestrian crossing intention estimation logic (#11084)

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/CMakeLists.txt
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/config/run_out.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/schema/run_out.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/debug.hpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.cpp

feat(run_out): add parameters to select which debug markers to publish

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/CMakeLists.txt
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/config/road_user_stop.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/param/road_user_stop_module_parameters.yaml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/plugins.xml
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/debug.cpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/path_length_buffer.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/road_user_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/road_user_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/type_alias.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/types.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/src/utils.hpp
planning/motion_velocity_planner/autoware_motion_velocity_road_user_stop_module/test/test_utils.cpp

- cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11041

feat(road_user_stop): add road_user_stop module config

---

map/autoware_lanelet2_map_visualizer/src/lanelet2_map_visualization_node.cpp

* feat(lanelet2_map_visualizer): visualize fences and road borders
* only visualize road border
* use a more general function
---------

feat(lanelet2_map_visualizer): visualize road borders (#575)

---

common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/boundary_departure_checker.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/data_structs.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/parameters.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/utils.hpp
common/autoware_boundary_departure_checker/src/boundary_departure_checker_abnormality.cpp
common/autoware_boundary_departure_checker/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/config/boundary_departure_prevention.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/schema/boundary_departure_prevention.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/type_alias.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.hpp

revert(boundary_departure): remove unmerged changes

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/config/boundary_departure_prevention.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.hpp

bdp cherry pick for experiment

fix(boudary_departrure): off time buffer for departure points for pc beta branch

---

evaluator/autoware_perception_online_evaluator/CMakeLists.txt
evaluator/autoware_perception_online_evaluator/include/autoware/perception_online_evaluator/parameters.hpp
evaluator/autoware_perception_online_evaluator/include/autoware/perception_online_evaluator/perception_analytics_calculator.hpp
evaluator/autoware_perception_online_evaluator/include/autoware/perception_online_evaluator/perception_analytics_publisher_node.hpp
evaluator/autoware_perception_online_evaluator/launch/perception_analytics_publisher.launch.xml
evaluator/autoware_perception_online_evaluator/param/perception_analytics_publisher.defaults.yaml
evaluator/autoware_perception_online_evaluator/src/perception_analytics_calculator.cpp
evaluator/autoware_perception_online_evaluator/src/perception_analytics_publisher_node.cpp
launch/tier4_perception_launch/launch/perception.launch.xml
launch/tier4_simulator_launch/launch/simulator.launch.xml

cherry-pick
https://github.com/autowarefoundation/autoware_universe/pull/11089

feat(perception_online_evaluator): add functionality to publish perception analytics info

---

system/autoware_command_mode_switcher_plugins/src/comfortable_stop.cpp

See https://github.com/autowarefoundation/autoware_universe/pull/11141

feat(autoware_command_mode_swicher_plugins): publish velocity limit again in stopping

---

planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.hpp

Cherry-picked from https://github.com/autowarefoundation/autoware_universe/pull/10867

feat(autoware_behavior_velocity_traffic_light_module): enhance rviz for v2i

---

planning/planning_validator/autoware_planning_validator_rear_collision_checker/README.md
planning/planning_validator/autoware_planning_validator_rear_collision_checker/config/rear_collision_checker.param.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/param/rear_collision_checker_node_parameters.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/utils.cpp

See originl PR: https://github.com/autowarefoundation/autoware_universe/pull/11151

feat(rear_collision_checker): add parameter to make collision detection behavior configurable (#11151)

---

visualization/tier4_planning_factor_rviz_plugin/src/planning_factor_rviz_plugin.cpp
visualization/tier4_planning_factor_rviz_plugin/src/planning_factor_rviz_plugin.hpp

- cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11218

feat(planning_factor_rviz_plugin): change some property (#11218)

---

launch/tier4_control_launch/launch/control.launch.xml
launch/tier4_planning_launch/launch/planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/parking.launch.xml
planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml

cherry pick pr for https://github.com/autowarefoundation/autoware_universe/pull/11242

refactor(launch): topic remapping for object recognition and point cloud input to planning/control module

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/decision_result.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

- cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11247

fix(intersection): hold collision stop pose (#11247)

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp

cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11209
https://github.com/tier4/autoware_core/pull/40
https://github.com/tier4/autoware_launch/pull/1100

feat(obstacle_stop, motion_velocity_planner_common, motion_utils): update pointcloud stop

---

planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/utils.cpp

See original PR: https://github.com/autowarefoundation/autoware_universe/pull/11286

fix(rear_collision_checker): correct deviation judgment logic from current driving lane (#11286)

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/CMakeLists.txt
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/lane_change.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/package.xml
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/lane_change.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/thread_data.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/test/test_lane_change.cpp

- https://github.com/autowarefoundation/autoware_universe/pull/11210
- https://github.com/autowarefoundation/autoware_universe/pull/11270

feat(goal_planner): improve lane change coordination by monitoring lane change completion

---

system/autoware_system_monitor/src/hdd_monitor/hdd_monitor.cpp

This PR is a cherry-picking PR which backports the following PR to tier4/autoware_universe.
- https://github.com/autowarefoundation/autoware_universe/pull/11160
This PR enables the Perception ECU for X2 (CTI Anvil with NVIDIA Jetson AGX Orin) to report the status of its storage (eMMC SSD).
Without this PR, "hdd_monitor" reports errors to "/diagnostics" topic.
**NOTE:**
The preceding cherry-picking PR https://github.com/tier4/autoware_universe/pull/2353 should be merged before this PR because the CI workflow "cppcheck-differential" may fail without the fix included in PR #2353.

fix(hdd monitor): emmc storage device type support

---

planning/planning_validator/autoware_planning_validator_trajectory_checker/src/utils.cpp
planning/planning_validator/autoware_planning_validator_trajectory_checker/test/test_trajectory_checker.cpp

Cherry-pick the jerk  computation update:
https://github.com/autowarefoundation/autoware_universe/pull/11306

fix: use the correct jerk computation formula

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp

Cherry-picked from https://github.com/autowarefoundation/autoware_universe/pull/11302

fix(static_obstacle_avoidance): fix multiple shift line generation algorithm

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.cpp

- cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11267

fix(run_out): fix virtual wall pose (#11267)

---

planning/autoware_diffusion_planner/include/autoware/diffusion_planner/conversion/lanelet.hpp

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11367

fix(diffusion_planner): fixed `const` to `constexpr` (#11367)

---

planning/autoware_route_handler/src/route_handler.cpp

cherry pick from https://github.com/autowarefoundation/autoware_core/pull/632

fix(route_handler): add same lane ID check in getRightLanelet/getLeftLanelet function

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/CMakeLists.txt
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/pid_based_planner/pid_based_planner.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/type_alias.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/types.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/test/test_planning_factor.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/CMakeLists.txt
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/config/obstacle_slow_down.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/type_alias.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/types.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/test/test_planning_factor.cpp

- デバッグ情報の追加
- パラメータによっては、slow_downの壁が不必要に過剰にでる問題の対応
- slow_downカーブで横マージンを追加する機能の追加
core: https://github.com/tier4/autoware_core/pull/46
launch: https://github.com/tier4/autoware_launch/pull/1132

feat(obstacle_slow_down, obstacle_cruise): add curve additional margin feature

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/default_fixed_goal_planner.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/test/test_utils.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_utils.cpp

- cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11381

fix(goal_planner): smooth goal connection for goal_planner (#11381)

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/lanelets_selection.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11407

fix(out_of_lane): ignore collisions inside the trajectory lanelets

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/map_data.cpp

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11412

feat(run_out): support specifying polygon subtypes for map filtering

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

https://github.com/autowarefoundation/autoware_universe/pull/11361 のbackport

feat(intersection): ignore precited path overtaking ego (#11361)

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/collisions.cpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/debug.hpp

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11433

fix(run_out): improve logic for opposite direction collisions (#11433)

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp

Cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11442

fix(out_of_lane): ensure the calculated stop pose is feasible (#11442)

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

- cherry-pick https://github.com/autowarefoundation/autoware_universe/pull/11455

feat(static_obstacle_avoidance): avoidance for parking violation and vru (#11455)
