tier4/autoware_universe

common/web_controller/launch/web_controller.launch.xml, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_data_nodelet.hpp, sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
- hotfix PR for beta/v0.1.0
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.
[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/ …
=> fix: cherry pick hotfix PRs for beta v0.1.0

sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_data_nodelet.hpp, sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
Signed-off-by: Shinnosuke Hirakawa <shinnosuke.hirakawa@tier4.jp>
- cherry-pick from autowarefoundation/autoware.universe
- fix pointcloud conversion method for concatenate_data
https://github.com/autowarefoundation/autoware.universe/pull/336
- **Check spelling**: NOT …
=> fix: changed pointcloud conversion method (#336)

common/osqp_interface/include/osqp_interface/osqp_interface.hpp, common/osqp_interface/src/osqp_interface.cpp
* fix(osqp_interface): memory leak problem
Signed-off-by: Fumiya Watanabe <rej55.g@gmail.com>
* fix: typo
Signed-off-by: Fumiya Watanabe <rej55.g@gmail.com>
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] …
=> fix(osqp_interface): memory leak problem (#333)

control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp, system/ad_service_state_monitor/src/ad_service_state_monitor_node/ad_service_state_monitor_node.cpp
- Cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/516
- Restore callback group settings for external_cmd_selector and ad_service_state_monitor_node 
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See …
=> fix: set callback group to timer (#516)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/approval_handler.hpp
In some cases, even if the lane change is approved, it will time out in the approval_handler and the lane change will not be executed.
It is a temporary fix for that
=> feat: change timeout in approval handler 

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/657
To solve https://github.com/autowarefoundation/autoware.universe/issues/275 in behavior path planner, multi thread is used for callbacks by passing a different callback group, whose type is MutuallyExclusive, to each calback.
Hotfix to v0.2.1
This PR will be merged after confirmation using the actual vehicle. …
=> feat(behavior_path): use multi thread

planning/behavior_velocity_planner/src/scene_module/run_out/scene.cpp
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
- cherry pick for bug fix
- https://github.com/autowarefoundation/autoware.universe/pull/1052
=> fix(behavior_velocity): use pose for min velocity if the object is stopped (#1052)

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
When I chrry-picked https://github.com/autowarefoundation/autoware.universe/pull/657 for beta/v0.2.1,
( https://github.com/tier4/autoware.universe/pull/45 ) I made some mistakes.
So, I Fixed it.
- set CallbackGroupType to subscriber and enable multi-thread
- add unlock of mutex (avoid double lock )
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/p …
=> fix: behavior path multi thread

common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp, common/tier4_state_rviz_plugin/src/autoware_state_panel.hpp, system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/1085
- https://github.com/autowarefoundation/autoware.universe/pull/1048
- https://github.com/autowarefoundation/autoware.universe/pull/1079
- https://github.com/autowarefoundation/autoware.universe/pull/1132
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guid …
=> chore: cherry pick 2022-06-22

common/interpolation/src/spline_interpolation.cpp, common/interpolation/test/src/test_spline_interpolation.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/1162
=> chore: cherry pick bug fixes

planning/behavior_path_planner/CMakeLists.txt
cherry-pick後にbuildエラーの対策を入れる。
対象のcherry-pickはこちら
https://github.com/autowarefoundation/autoware.universe/pull/1167
https://github.com/autowarefoundation/autoware.universe/pull/1096
autoware_packageを導入していないため、
ament_add_ros_isolated_gmockが見つからないできないことが原因
autoware_pakageのPR→https://github.com/autowarefoundation/autoware.universe/pull/849
本PRを入れることで、ament_add_ros_isolated_gmockが見つかるようになる。
[pull request …
=> fix: building error for cherry-pick

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
Fixed a problem with pull over mosule not working when goal is placed on shoulder lane after loop. This is just a workaround.
The problem is that the arc length cannot be calculated correctly, so this workaround will be considered in the lanelet function.
https://star4.slack.com/archives/CEV8XMJBV/p1659608990931289?thread_ts=1659523164.728609&cid=CEV8XMJBV …
=> fix(behavior_path_planner): set shuolder goal after loop

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
cherry-pick 
https://github.com/autowarefoundation/autoware.universe/pull/1571
for v0.5.0
> Solved a problem where setting a goal after a loop pull_over did not work well. Because current_lanes does not contain goal, goal_arc_length cannot be calculated correctly (it becomes 0) and pull_oevr module is invoked. In addition, arc_length could not be calculated properly in the module processing, this caused bug.
In this PR, when a goal is far away and current_lanes does not contain the goal, the module will not be launched.
https://github.com/autowarefoundation/autoware.universe/pull/1571 …
=> fix(behavior_path_planner): pull_over far goal bug (#1571)

common/tier4_debug_tools/scripts/stop_reason2pose.py
https://github.com/autowarefoundation/autoware.universe/pull/1040 のbackport
=> fix(tier4_debug_tools): fix unnecessary use of map (#1040)

build_depends.humble.repos, build_depends.repos
Fix autoware_common version in build_depends.repos and build_depends.humble.repos
=> fix: autoware_common version in build_depends files

map/lanelet2_extension/include/lanelet2_extension/utility/query.hpp, map/lanelet2_extension/lib/query.cpp, planning/behavior_velocity_planner/include/scene_module/crosswalk/manager.hpp, planning/behavior_velocity_planner/include/scene_module/occlusion_spot/occlusion_spot_utils.hpp, planning/behavior_velocity_planner/include/scene_module/scene_module_interface.hpp, planning/behavior_velocity_planner/include/scene_module/stop_line/manager.hpp, planning/behavior_velocity_planner/include/utilization/util.hpp, planning/behavior_velocity_planner/src/scene_module/blind_spot/manager.cpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/manager.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/no_stopping_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/stop_line/manager.cpp, planning/behavior_velocity_planner/src/scene_module/traffic_light/manager.cpp, planning/behavior_velocity_planner/src/scene_module/virtual_traffic_light/manager.cpp, planning/behavior_velocity_planner/src/scene_module/virtual_traffic_light/scene.cpp, planning/behavior_velocity_planner/src/utilization/util.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1028 のbackport
=> fix(behavior_velocity_planner): use only forward path for launching module (#1028)

system/ad_service_state_monitor/include/ad_service_state_monitor/ad_service_state_monitor_node.hpp, system/ad_service_state_monitor/src/ad_service_state_monitor_node/ad_service_state_monitor_node.cpp, system/ad_service_state_monitor/src/ad_service_state_monitor_node/diagnostics.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1395 のbackport
=> fix(ad_service_state_monitor): lock shread variables to prevent race condition (#1395)

planning/behavior_velocity_planner/src/scene_module/occlusion_spot/scene_occlusion_spot.cpp
- fix interpolation interval not to insert bag point at high curvature path
=> fix: interpolation interval

build_depends.humble.repos, build_depends.repos
fix ci build
this PR will back to 1f36fa7579edbe2ed41f745a0ee029a427e468fe which does not include "move lanelet2 packages" commit
=> ci: fix build depends

planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/src/node.cpp
Hotfix to 0.5.2
https://github.com/autowarefoundation/autoware.universe/pull/1894
**
I created a another PR because merging [this PR](https://github.com/autowarefoundation/autoware.universe/pull/1894) would cause a lot of conflict
=> fix(obstacle_cruise_planner): ignore behind obstacles #1894

planning/behavior_velocity_planner/include/utilization/util.hpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/manager.cpp, planning/behavior_velocity_planner/src/utilization/util.cpp
cherry-pick  and resolve conflicts
- https://github.com/autowarefoundation/autoware.universe/pull/1323
- https://github.com/autowarefoundation/autoware.universe/pull/1594
=> fix(behavior_velocity_planner): port the algorithm to get lane_ids from path to beta/v0.4.1

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
update turn signal logic (avoidance module)
=> fix(avoidance): use new turn signal algorithm

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
Update pull over for new winker logic of @purewater0901 
Discussion pull over/out winker behavior (TIER IV internal links)
- https://star4.slack.com/archives/CTEJP8L4T/p1655901876416379
- https://star4.slack.com/archives/CTEJP8L4T/p1663754549602919
Merge the following PRs
- https://github.com/autowarefoundation/autoware.universe/pull/1911
- https://github.com/autowarefoundation/autoware.universe/pull/1946
- pull over
shift pull over
https://user-images.githubusercontent.com/39142679/192089354-f647653b-e02f-4256-9bf0-5fa513aca659.mp4
arc forward
https://user-images.githubusercontent.com/39142679/192089383-3733986a-b5f4-4e9a-8eea-ca9b5dee03d9.mp4
arc backward
https://user-images.githubusercontent.com/39142679/192089396-1fa71984-319f-4d1b-b8e4-e870d7a3be57.mp4
- pull out 
Since pull_out …
=> feat(behavior_path_planner): update pull over/out for new blinker logic 

planning/behavior_velocity_planner/include/scene_module/crosswalk/scene_crosswalk.hpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1978
(TIERIV Internal: https://star4.slack.com/archives/CEV8XMJBV/p1664358448041849?thread_ts=1664323130.934649&cid=CEV8XMJBV )
https://github.com/autowarefoundation/autoware.universe/pull/1978
> In crosswalk module, the parameter stop_line_distance should be considered only when the explicit stop_line is not defined in lanelet. But, in the current implementation, stop_line_distance is always considered. I fixed it.
Hotfix to beta/v0.5.2.
After all checkboxes are checked, …
=> fix(behavior_velocity_planner): do not consider stop_line_margin when a stop line is defined at map in crosswalk module

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/eb_path_optimizer.hpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils.hpp, planning/obstacle_avoidance_planner/src/eb_path_optimizer.cpp, planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp, planning/obstacle_avoidance_planner/src/utils.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1192
Fix obstacle avoidance planner dying in some cases.
This change was already included in main branch.
=> fix(obstacle_avoidance_planner): use prev eb traj when failed (#1192)

planning/obstacle_avoidance_planner/src/node.cpp
porting https://github.com/autowarefoundation/autoware.universe/pull/1881
不具合により、出力経路と参照経路が1e7レベルのオーダーでずれていたので、それより小さく、また現実的な値 (現状のAutowareでは大きくても1e1)の間を取って1e4としました。かなりテンポラリな値です。
fix inf loop in mpt because of diverged elastic band
https://tier4.atlassian.net/browse/EVT4-2059 …
=> fix(obstacle_avoidance_planner): fix inf loop in mpt

localization/pose_initializer/src/pose_initializer_core.cpp
Correction of a problem in which a fixed value was assigned to covariance in the Pose initializer.
[Fixed response of initialize pose API on iv](https://github.com/tier4/autoware.iv/pull/2128/files),  It was not incorporated into the universe version, [so the PR was adapted it. ](https://github.com/autowarefoundation/autoware.universe/pull/1020/files#diff-076ef3f74b5024fd7148eb1c2b230225b446ca2809ceb717e9e84f9ff25d5561R234-R241)
However, It have reverted to assigning a fixed value to covariance.Therefore, there is a problem that the values in the parameter file are not applied.
Adaptation to v0.3.10 is not necessary for tier4/main, since the problem does not exist.
However, v0.4 and v0.5 series have the same problem and need to be adapted.
https://tier4.atlassian.net/browse/EVT4-2065
The …
=> fix(pose_initializer): modifying the assignment of covariance variables to output poses

common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp, common/autoware_auto_perception_rviz_plugin/include/object_detection/predicted_objects_display.hpp, common/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2065
hotfix to beta/v0.5.2-odaiba
=> feat(autoware_auto_perception_rviz_plugin): rviz predicted objects multi-threading (#2065)

launch/tier4_perception_launch/config/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml, launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py, launch/tier4_perception_launch/package.xml, perception/ground_segmentation/CMakeLists.txt, perception/ground_segmentation/docs/ray-ground-filter.md, perception/ground_segmentation/docs/scan-ground-filter.md, perception/ground_segmentation/include/ground_segmentation/ray_ground_filter_nodelet.hpp, perception/ground_segmentation/include/ground_segmentation/scan_ground_filter_nodelet.hpp, perception/ground_segmentation/src/ray_ground_filter_nodelet.cpp, perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1899
Hotfix to beta/v0.5.2-odaiba
To merge this [PR](https://github.com/autowarefoundation/autoware.universe/pull/1899), another [PR](https://github.com/autowarefoundation/autoware.universe/pull/1614) is needed. so We well merge this one too.
(Note:  https://github.com/autowarefoundation/autoware.universe/pull/1614  does not affect Autoware behavior.)
https://github.com/tier4/autoware_launch.xx1/pull/337 …
=> feat: add grid elevation ground filter

system/velodyne_monitor/Readme.md, system/velodyne_monitor/config/HDL-32E.param.yaml, system/velodyne_monitor/config/VLP-16.param.yaml, system/velodyne_monitor/config/VLP-32C.param.yaml, system/velodyne_monitor/config/VLS-128.param.yaml, system/velodyne_monitor/config/Velarray_M1600.param.yaml, system/velodyne_monitor/launch/velodyne_monitor.launch.xml
backport two PRs
- https://github.com/autowarefoundation/autoware.universe/pull/1623
- https://github.com/autowarefoundation/autoware.universe/pull/1744
These are merged at https://github.com/tier4/autoware.universe/tree/v0.4.1
- https://github.com/tier4/autoware.universe/pull/95
- https://github.com/tier4/autoware.universe/pull/101 …
=> fix(velodyne_monitor): backport #1623 and #1744 from awf/autoware.universe

perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2117
Hotfix to 0.5.2-odaiba
(TierIV Internal Link https://star4.slack.com/archives/C4P0NSMB5/p1666227925545509?thread_ts=1666227340.967779&cid=C4P0NSMB5 )
=> fix(ground segmentation): correct initial condition of ground grid (#2117)

perception/compare_map_segmentation/CMakeLists.txt, sensing/pointcloud_preprocessor/CMakeLists.txt
Hotfix to beta/v0.5.2-odaiba-2
https://github.com/autowarefoundation/autoware.universe/pull/1982
https://github.com/autowarefoundation/autoware.universe/pull/2101
Fix following issue
https://github.com/autowarefoundation/autoware.universe/issues/1009
> sometimes the sensing module cannot launch concatenated and cropbox filter with the following error …
=> fix: compare map segmentation load

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp, planning/rtc_interface/include/rtc_interface/rtc_interface.hpp, planning/rtc_interface/src/rtc_interface.cpp
Hotfix to beta/v0.5.2-odaiba-2
https://github.com/autowarefoundation/autoware.universe/pull/1541
> RTC Auto Approver had a problem that behavior velocity planning module inserts stop line for a moment because RTC Auto Approver sends a command after receiving RTC status from the planning module.
> To solve this problem, I add the function to approve automatically to rtc_interface.
Furthermore, I removed approving function from RTC Auto Approver.
So, RTC Auto Approver just has the function to set default value to enable auto mode.
To clarify the function, I rename RTC Auto Approver to RTC Auto Mode Manager.
The PR author **must** check the checkboxes …
=> feat(rtc_interface): lock command update (#2073)

system/system_monitor/include/system_monitor/ntp_monitor/ntp_monitor.hpp, system/system_monitor/include/system_monitor/process_monitor/process_monitor.hpp, system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp, system/system_monitor/src/hdd_monitor/hdd_monitor.cpp, system/system_monitor/src/mem_monitor/mem_monitor.cpp, system/system_monitor/src/ntp_monitor/ntp_monitor.cpp, system/system_monitor/src/process_monitor/process_monitor.cpp
Signed-off-by: v-nakayama7440-esol <v-nakayama7440@esol.co.jp>
This PR is a backport for v0.3.11.
Exactly the same content as https://github.com/autowarefoundation/autoware.universe/pull/1714 . 
boost::process::pipe internally creates file descriptor. However, this file descriptor does not support multithreading because O_CLOEXEC is not set. Because of this, when each thread of SystemMontor uses boost::process to create a child process, the file descriptors of boost::process::pipe conflict between child processes. As a result, the child process waits for the file descriptor to be released.
In this PR, the SystemMonitor application creates file descriptor with O_CLOEXEC set and passes it to boost::process::pipe to eliminate the wait for child process to release file descriptor.
- The issue …
=> fix(system_monitor): multithreading support for boost::process (#1714)

planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2214
Hotfix to beta/v0.5.2-odaiba3
> Fixed stop point insertion in intersection module
=> fix(intersection): fixed (stop) point insertion (#2214)

planning/rtc_interface/include/rtc_interface/rtc_interface.hpp, planning/rtc_interface/src/rtc_interface.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2223
Hotfix to beta/v0.5.2-odaiba3
> In rtc_interface, stored_commands is updated only when onCooperateCommandService() is called and is_locked_ is true.
However, the stored_commands are copied to the cooperate command status every time unlockCommandUpdate() is called.
As a result, the cooperate commands that are cleared once may be re-registered through stored_commands_.
I fixed this by properly clearing the stored_command.
Note: This bug is caused by performing lane-change in the same direction more than once.
After all …
=> fix: sync stored_commands to cooperate status (#2223)

planning/behavior_velocity_planner/include/scene_module/crosswalk/scene_crosswalk.hpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp
Reverts tier4/autoware.universe#175
Autoware upstream and beta/v0.5.2 have large  code differences in crosswalk module, and it causes bugs when cherry-picking simply.
I Revert the PR as this is hard to fix.
=> revert(crosswalk): reduce processing time (#2137)

planning/rtc_replayer/CMakeLists.txt, planning/rtc_replayer/README.md, planning/rtc_replayer/include/rtc_replayer/rtc_replayer_node.hpp, planning/rtc_replayer/launch/rtc_replayer.launch.xml, planning/rtc_replayer/package.xml, planning/rtc_replayer/src/rtc_replayer_node.cpp
* feat(rtc_replayer): add rtc_reaplayer
Signed-off-by: taikitanaka3 <taiki.tanaka@tier4.jp>
this can be merged if there is no build error 
this will be added to debug tool
https://github.com/tier4/debug_tools/blob/ad465ef3d3e082e6a2bf42165fa6a03f4d7b4c61/analyze_without_planning.tmux#L66
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …
=> feat(rtc_reaplyer): add rtc_replayer (#1993)

control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp
fix: add diagnostic force_update
Signed-off-by: Azumi Suzuki <azumi.suzuki@tier4.jp>
Signed-off-by: Azumi Suzuki <azumi.suzuki@tier4.jp>
https://github.com/autowarefoundation/autoware.universe/pull/2299 のbackport
=> fix(external_cmd_selector): add diagnostic force_update (#2299)

control/vehicle_cmd_gate/README.md, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
* fix: add check for external_emergency_stop_heartbeat_received_time to isDataReady
Signed-off-by: Azumi Suzuki <azumi.suzuki@tier4.jp>
* feat: add README about `use_external_emergency_stop` parameter
Signed-off-by: Azumi Suzuki <azumi.suzuki@tier4.jp>
* fix: update README as recommended
Signed-off-by: Azumi Suzuki <azumi.suzuki@tier4.jp>
Signed-off-by: Azumi Suzuki <azumi.suzuki@tier4.jp>
Backport https://github.com/autowarefoundation/autoware.universe/pull/2155 to beta/v0.5.4
TIER IV ticket link : https://tier4.atlassian.net/browse/T4PB-20370
After all checkboxes are checked, anyone …
=> fix: add check for external_emergency_stop_heartbeat_received_time to isDataReady (autowarefoundation#2155)

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/util.cpp, planning/behavior_path_planner/src/utilities.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2379
hotfix to beta/v0.5.2-odaiba3
> Lane change module sometimes generates an invalid path.
The root cause has not been determined, but in this PR such kind of path is filtered by checking lane_departure and relative_angle.
(TierIV Internal Link): https://evaluation.tier4.jp/evaluation/reports/6fcdbecf-fcb4-5587-8c30-cf1cedd92b39?project_id=prd_jt
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …
=> fix(behavior_path_planner): check lane departure and relative angle for lane change (#2379)

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
fix(behavior_path_planner): consider almost zero longitudinal start length
as title says
this is cherry-pick from awf universe
TIER IV INTERNAL LINK: https://tier4.atlassian.net/browse/T4PB-23560
=> fix(behavior_path_planner): consider almost  zero longitudinal start length (#2395)

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/util.cpp, planning/behavior_path_planner/src/utilities.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
Hotfix to beta/v0.5.2-odaiba4
https://github.com/autowarefoundation/autoware.universe/pull/2379
https://github.com/autowarefoundation/autoware.universe/pull/2421
check lane departure and relative angle for lane change
(I confirmed that the lane-change module works normally by the planning-simulator)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/ …
=> fix(behavior_path_planner): check lane departure and relative angle for lane change

planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
fix for https://tier4.atlassian.net/browse/T4PB-23420
When optimization failed, trajectory sometimes diverged.
In order to send this kind of trajectory to the latter module, I added a guard seeing how much deviation the trajectory has against the reference path.
If the deviation is too large, sends a previously planned path to the latter module. …
=> fix(obstacle_avoidance_planner): add guard for failed optimized trajectory

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- cherry pick fix for Inappropriate data copy in behavior path planner
- https://github.com/autowarefoundation/autoware.universe/pull/2501
=> fix(behavior_path_planner): fix planner data copy (#2501)

planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2323 のbackport
=> feat(behavior_velocity_planner): output stop reason of traffic light whenever a stop point is inserted (backport #2323)

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
- cherry pick fix for intersection
- https://github.com/autowarefoundation/autoware.universe/pull/2529
- Rlated Jira (TIER IV internal)
- https://tier4.atlassian.net/browse/T4PB-24351
=> fix(intersection): always set RTC distance to default stop line (#2529)

planning/obstacle_avoidance_planner/src/node.cpp
* fix(obstacle_avoidance_planner): deal with wider path interval
port universe's main bug fix commit to x1 release branch
https://github.com/autowarefoundation/autoware.universe/pull/1616
ticket
https://tier4.atlassian.net/browse/T4PB-22568
=> fix(obstacle_avoidance_planner): deal with wider path interval (#1616)

perception/elevation_map_loader/package.xml, perception/elevation_map_loader/src/elevation_map_loader_node.cpp
This PR is backport from https://github.com/autowarefoundation/autoware.universe/pull/1772
=> fix(elevation_map_loader): remove and create map bagfile if it cannot be loaded (backport #1772)

system/system_error_monitor/README.md, system/system_error_monitor/include/system_error_monitor/system_error_monitor_core.hpp, system/system_error_monitor/launch/system_error_monitor.launch.xml, system/system_error_monitor/launch/system_error_monitor_node.launch.xml, system/system_error_monitor/src/system_error_monitor_core.cpp
This PR is backport from https://github.com/autowarefoundation/autoware.universe/pull/1501
=> feat(system_error_monitor): add heartbeat timeout for subscribed data (backport #1501)

planning/surround_obstacle_checker/src/node.cpp
https://tier4.atlassian.net/browse/T4PB-24283
boost::assign::list_ofがbad_allocを起こしてそうということがcoredumpを確認してわかったため、それを使わない形にする
最新では使わないようにリファクタリングがはいっているので、それを移植する形で対策を講じる
https://github.com/tier4/autoware.universe/blob/52c7ce377e7504a2223f332e33c93161bd85ae0e/planning/surround_obstacle_checker/src/node.cpp#L89-L140
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
=> fix(surround_obstacle_checker): not use boost::assign::list_of

planning/obstacle_stop_planner/src/node.cpp
https://tier4.atlassian.net/browse/T4PB-24093
object_ptrがnullptrを確認せずに使われている箇所があったため、使う前にnullptrを確認するように修正
=> fix(obstacle_stop_planner): add error handling for nullptr of object_ptr

planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2548
> With https://github.com/autowarefoundation/autoware.universe/pull/2088, goal can not be set in shoulder lane.
=> fix(mission_planner): set goal in shoulder lane (#2548)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_planner_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/shift_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/utils/geometric_parallel_parking.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/scene_module/pull_out/geometric_pull_out.cpp, planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp, planning/behavior_path_planner/src/scene_module/pull_over/geometric_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/goal_searcher.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/shift_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/util.cpp, planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp, planning/behavior_path_planner/src/utilities.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2578
=> feat(behavior_path_planner): generate pull over path candidates in advance

planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2584
> Plot of the original path, the resampled path, and the calculated stop position for the kashiwanoha crossing.
The stop point is calculated from the resampled path.
The stop point is inserted in the original path.
In this specific case, the stop point is very close to its previous point in the path and after being inserted in the path, the calculated yaw will be very wrong.
To fix the above problem, the path used as a reference for calculating the stopping point is changed from sparse resampled path to original path.
The PR author **must** check the checkboxes …
=> fix(crosswalk): fix base path for stop point caluculation (#2584)

planning/external_velocity_limit_selector/include/external_velocity_limit_selector/external_velocity_limit_selector_node.hpp, planning/external_velocity_limit_selector/launch/external_velocity_limit_selector.launch.xml, planning/external_velocity_limit_selector/package.xml, planning/external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2581
=> fix(external_velocity_limit_selector): increase history depth external velocity limit selector

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
* fix(avoidance): ignore unavoidable objects around the goal
* Update planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
* Update planning/behavior_path_planner/src/behavior_path_planner_node.cpp
Co-authored-by: Kosuke Takeuchi <kosuke.tnp@gmail.com>
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/2612 …
=> fix(avoidance): ignore unavoidable objects around the goal (#2612)

planning/obstacle_avoidance_planner/src/utils/utils.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2594
hotfix to beta/v0.7.0
> Currently drivable area check for traj footprints in MPT doesn't work. Because lat_dist_to_front_bound (lateral distance of footprint corners to front bound) is always positive.
=> fix(obstacle_avoidance_planner): fix lat_dist_to_front_bound comparison (autowarefoundation#2594)

planning/behavior_path_planner/include/behavior_path_planner/path_utilities.hpp, planning/behavior_path_planner/src/path_utilities.cpp, planning/behavior_path_planner/src/scene_module/lane_change/util.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2622
> To reduce the computational cost of the LaneChange module, the target_section is introduced for the spline resampling.
Run on psim. The Hz increases from 1.8Hz to 4.4Hz when making lane change path candidate with 10m/s ego speed. …
=> feat(lane_change): update resamplePath function for target section (#2622)

planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
feat(behavior_path_planner): error messsage when no pull over/out planner
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/2644
build 
=> feat(behavior_path_planner): error messsage when no pull over/out planners (#2644)

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils/utils.hpp, planning/obstacle_avoidance_planner/src/utils/utils.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2639
> Currently, the obstacle avoidance planner checks if the footprint of the vehicle is outside of the drivable area by lateral distance from the left and right boundary. However, this method does not work well when the boundary is not straight. In this PR, I use the polygon instead of the line to check if the footprint is outside of the drivable area.
For example, in the following scene, the trajectory point will be judged outside of the drivable area even though it is inside of it. This is because it uses the line created by point0 and point1, so the trajectory point is judged to be located right side of the line.
The PR reviewers …
=> fix(obstacle_avoidance_planner): fix drivable area checker (#2639)

system/system_error_monitor/include/system_error_monitor/system_error_monitor_core.hpp, system/system_error_monitor/src/system_error_monitor_core.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2634 のbackport
TIERIV_INTERNAL_LINK: https://tier4.atlassian.net/browse/T4PB-25040
=> fix(system_error_monitor): hold emergency when timeout happens (#2634)

planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp, planning/behavior_path_planner/src/utilities.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2648
> The behavior path planner cannot handle semi-looped routes now, and some specific nodes die when we give a start pose and goal pose. In order to fix this problem, I changed the lane-cutting method. 
https://github.com/autowarefoundation/autoware.universe/pull/2648
See https://github.com/autowarefoundation/autoware.universe/pull/2648 . …
=> fix(behavior_path_planner): fix overlapping lane cutter (#2648)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2672
https://github.com/autowarefoundation/autoware.universe/pull/2672
See https://github.com/autowarefoundation/autoware.universe/pull/2672
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines …
=> fix(lane_change): fix lane change force approval by rtc (#2672)

planning/behavior_path_planner/README.md, planning/behavior_path_planner/config/pull_out/pull_out.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_parameters.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2675
> Same to pull_over https://github.com/autowarefoundation/autoware.universe/pull/2667,
ignore pull_out start candidate near the lane end to prevent distortion with the path generated close to the drivable area.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pu …
=> feat(behavior_path_planner): ignore pull out start near lane end (#2675)

vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/package.xml, vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2682
> Fix usage of transform listener.
transform_listener_->getTransform don't throw an error when getting transform fails. So, in current implementation, accel_brake_map_calibrator dies when there is no available tf. I fixed it.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
=> fix(accel_brake_map_calibrator): fix usage of transform listener (#2682)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2678
> When not found safe pull out path, empty path is returned in plan().
In this PR, return stop_path.
Even if it is an empty path, it keeps stopping, so there is no change in the actual behavior.
https://github.com/autowarefoundation/autoware.universe/pull/2692
> Fix https://github.com/autowarefoundation/autoware.universe/pull/2675
We need to check all pull_out lanes length, not just the end lane length
https://github.com/autowarefoundation/autoware.universe/pull/2678
https://github.com/autowarefoundation/autoware.universe/pull/2692
See each PR
The PR author …
=> feat(behavior_velocity_planner): improve pull over and pull out module

planning/behavior_path_planner/src/scene_module/lane_change/util.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2752
> When target_lane_reference_path is empty, behavior_path_planner dies with the following error.
I fixed it.
=> fix(lane_change): fix bug when target reference path is empty (#2752)

perception/map_based_prediction/src/path_generator.cpp, planning/behavior_velocity_planner/config/blind_spot.param.yaml, planning/behavior_velocity_planner/include/scene_module/blind_spot/scene.hpp, planning/behavior_velocity_planner/src/scene_module/blind_spot/manager.cpp, planning/behavior_velocity_planner/src/scene_module/blind_spot/scene.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2570
> To prevent over-detection of blind_spot, I added yaw difference threshold between ego and target objects as detection conditions.
https://github.com/autowarefoundation/autoware.universe/pull/2570
Done (Planning simulator)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …
=> fix(behavior_velocity_planner): fix blind spot over-detection (#2570)

.pre-commit-config.yaml
ci(pre-commit): update isort version to avoid pre-commit failure
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
https://github.com/autowarefoundation/autoware.universe/pull/2777
> Fixes the pre-commit.ci failure.
https://results.pre-commit.ci/run/github/429651616/1675041634.tp_4EmctSLqQDalbXYYjaw
https://github.com/autowarefoundation/autoware.universe/pull/2777
[pull …
=> ci(pre-commit): update isort version to avoid CI failure (#2777)

planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2779
> When enable_back is false, the pull_over module does not publish a valid path.
Not found safe pull out path, publish stop path
It is because in planWithPriorityOnEfficientPath or planWithPriorityOnShortBackDistance no process runs when the size of start_pose_candidates is 1. I fixed it.
https://github.com/autowarefoundation/autoware.universe/pull/2779
checked using Psim and real vehicle. …
=> fix(behavior_path_planner): fix pull out module when enable_back is false (#2779)

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2781
> Before this change, if ego vehicle is near of the objects, avoidance is preferred over lane change.
To fix this behavior, in this change, it disables avoidance module if ego vehicle is not on preferred lane.
https://github.com/autowarefoundation/autoware.universe/pull/2781
checked using Psim.
[pull request …
=> fix(behavior_path_planner): disable avoidance in preferred lane

common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
Currently, the topic Hz of  ```/perception/object_recognition/objects``` drops to about 2-3 Hz due to the excessive computation of map_based_prediction.
This causes the object to blink in Rviz.
To fix this issue, temporarily increased lifetime from 0.2 to 1.0
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
=> chore: change lifetime of object marker

planning/behavior_velocity_planner/include/scene_module/intersection/manager.hpp, planning/behavior_velocity_planner/include/scene_module/traffic_light/manager.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/traffic_light/manager.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2790
> I fixed the way to get expired module in intersection/merge_from_private/traffic_light modules to consider each scene_modules's id respectively.
https://github.com/autowarefoundation/autoware.universe/pull/2790
checked using Psim. …
=> fix(behavior_velocity_planner): clean up expired intersection/merge_from_private/traffic_light (#2790)

planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2805
> In pull out module ,sometimes route_handler.getCenterLinePath(road_lanes, s_start, s_end, true); returns empty path and then a invalid access occurs. I fixed it.
https://github.com/autowarefoundation/autoware.universe/pull/2805
https://github.com/autowarefoundation/autoware.universe/pull/2805
[pull request …
=> fix(behavior_path_planner): do not access empty path in pull out module (#2805)

common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_detail.hpp, common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp, common/autoware_auto_perception_rviz_plugin/package.xml, common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
Hotfix to beta/v0.7.0. Improve performance of rviz.
https://github.com/autowarefoundation/autoware.universe/pull/2780
https://github.com/autowarefoundation/autoware.universe/pull/2814
> Add simple visualization mode to autoware_auto_perception_rviz_plugin for reduction of visualization cost.
Compared to before the PR merge, there is no change when using default parameters. …
=> feat(autoware_auto_perception_rviz_plugin): add simple visualize mode (autowarefoundation#2814)

common/interpolation/include/interpolation/zero_order_hold.hpp, common/motion_utils/src/resample/resample.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2744
> when closest_segment_idx is found in backward loop in zero_order_hold function, immediatly break the loop. The previous implementation was forward and continue updating the idx value, which is unnecessary.
pre-calculate the closest_segment_idx with base and query keys. In the several calls of zero_order_hold from resample.cpp in the form of zoh, the two parameters base_keys and query_keys are the same. Thus the calculation of closest_segment_idx is also the same, which includes double for loops and has a heavy computational cost.
The PR author **must** check …
=> perf(motion_utils): improve performance of zero_order_hold (#2744)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2829
> Fix path distortion of pull out path when backward driving is disabled.
The geometric pull out assumes that the start pose and the end pose is in parallel, but when backward driving is disabled the raw current pose is used as start pose and is not refined. In this PR, the current pose is refined to the lane for the start pose.
And add a guard for discontinuity. …
=> fix(behavior_path_planner): fix path distortion of no back pull out (#2829)

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/2898 to beta/v0.7
https://github.com/autowarefoundation/autoware.universe/pull/2898
https://star4.slack.com/archives/C03QW0GU6P7/p1676600411181709
psim, scenario test(main)
build behavior path(v0.7)
=> fix(behavior_path_planner): fix pull over deceleration before search area start (#2898)

perception/map_based_prediction/src/map_based_prediction_node.cpp, perception/map_based_prediction/src/path_generator.cpp
Hotfix to beta/v0.7.0-odaiba1
https://github.com/autowarefoundation/autoware.universe/pull/2883
https://github.com/autowarefoundation/autoware.universe/pull/2895
The improvement of the latency of map_based_prediction node.
https://github.com/autowarefoundation/autoware.universe/pull/2883
https://github.com/autowarefoundation/autoware.universe/pull/2895
See description of each PR.
[pull request …
=> feat: improve map_based_prediction

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml
以下PRにて、pre-commitでエラーが発生しているので修正
https://github.com/tier4/autoware.universe/pull/281
isortのバージョンが古い様子のため、tier4/mainから変更をpickした
https://github.com/tier4/autoware.universe/blob/tier4/main/.pre-commit-config.yaml#L57-L60
また、workflowに関しても、tier4/mainから変更をpick
https://github.com/tier4/autoware.universe/blob/tier4/main/.github/workflows/pre-commit.yaml
- pre-commitが成功すること
- pre-commitはスキップされて、pre-commit.ciのみが実施されていること
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contr …
=> fix: pre-commit settings for beta/v0.3.x

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/common_structs.hpp, planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
https://github.com/autowarefoundation/autoware.universe/pull/2579 のbackport
debug_dataだとビルドエラーが発生したためdebug_data_ptrに書き換えている箇所あり
TIER IV INTERNAL LINK: https://tier4.atlassian.net/browse/T4PB-23301
=> fix(obstacle_avoidance_planner): add guard for too large yaw deviation (backport #2579)

.github/workflows/build-and-test-differential.yaml, .github/workflows/check-build-depends.yaml, build_depends.repos, common/tier4_state_rviz_plugin/src/autoware_state_panel.hpp
- build-and-test-differential、及びcheck-build-dependsのアクションがrosdep周りで失敗してたのを修正
- check-build-dependsが依然失敗しているが、lanelet2_extensionが残っているのが理由のためここでは一旦無視する
- build-and-test-differentialが成功していること
- check-build-dependsの失敗理由がrosdepのエラーでないこと
=> ci: fix action for build-test-differential and check-build-depends for beta/v0.3.x

build_depends.repos
build_depends.reposのversionがハッシュ固定でないため、pilot-auto.x1.eveのautoware.reposを参考に修正する
- autoware_common: https://github.com/tier4/pilot-auto.x1.eve/blob/beta/v3.3.0/autoware.repos#L10
- autoware_auto_msgs: https://github.com/tier4/pilot-auto.x1.eve/blob/beta/v3.3.0/autoware.repos#L30
check-build-dependsが成功する
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …
=> chore: fix build_depends.repos for beta/v0.3.x

common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp, control/trajectory_follower/src/longitudinal_controller_utils.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1268 のbackport
cherry-pickではコンフリクトが発生したため、必要な部分を手動でピックアップしている
https://tier4.atlassian.net/browse/T4PB-25358
- ビルドが問題ないこと
- 元のPRと同じ箇所が編集されていること
- 以下のコードとdiffを取ると見やすいかもしれません
- [trajectoty.zip](https://github.com/tier4/autoware.universe/files/10837999/trajectoty.zip) …
=> fix(tier4_autoware_utils): exception handling in tier4 autoware utils for beta/v0.3.x (backport #1268)

simulator/dummy_perception_publisher/CMakeLists.txt, simulator/dummy_perception_publisher/include/dummy_perception_publisher/node.hpp, simulator/dummy_perception_publisher/include/dummy_perception_publisher/signed_distance_function.hpp, simulator/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml, simulator/dummy_perception_publisher/src/node.cpp, simulator/dummy_perception_publisher/src/pointcloud_creator.cpp, simulator/dummy_perception_publisher/src/signed_distance_function.cpp, simulator/dummy_perception_publisher/test/src/test_signed_distance_function.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1166 のbackport
単独ではconflictが発生したため、conflictが発生しないところまでさかのぼってcherry-pickを実施
https://github.com/autowarefoundation/autoware.universe/pull/527
https://github.com/autowarefoundation/autoware.universe/pull/926
https://tier4.atlassian.net/browse/T4PB-25357
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …
=> fix(dummy_perception_publisher): independent of pointcloud from detection_successful_rate (backport #527, #926, #1166)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/util.cpp, planning/behavior_path_planner/src/utilities.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
Hotfix to beta/v0.7.0-odaiba1
https://github.com/autowarefoundation/autoware.universe/pull/2776
https://github.com/autowarefoundation/autoware.universe/pull/2825 
https://github.com/autowarefoundation/autoware.universe/pull/2839
https://github.com/autowarefoundation/autoware.universe/pull/2776
https://github.com/autowarefoundation/autoware.universe/pull/2825 
https://github.com/autowarefoundation/autoware.universe/pull/2839
See each PR …
=> feat: improve lc computing performance

common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp, common/tier4_autoware_utils/test/src/trajectory/test_trajectory.cpp, control/trajectory_follower/test/test_longitudinal_controller_utils.cpp
https://github.com/tier4/autoware.universe/pull/282 でビルドエラーが発生するようになってしまっているため修正
また、テストでエラーが起きる。これはテスト部分のコードが移植できていないため
https://github.com/autowarefoundation/autoware.universe/pull/1268 より移植する
=> fix(tier4_autoware_utils): fix build error

simulator/fault_injection/CMakeLists.txt, simulator/fault_injection/package.xml
Hotfix to beta/v0.7.0-odaiba1
https://github.com/autowarefoundation/autoware.universe/pull/2973
> fixed build error of fault injection.
https://github.com/autowarefoundation/autoware.universe/pull/2973
checked to success build
=> fix(fault injection): add find package to cmake (#2973)

planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp
cherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/2828
=> fix(behavior_path_planner): fix geometric pull out lane id for overlapping (#2828)

planning/behavior_velocity_planner/include/scene_module/intersection/manager.hpp, planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/include/scene_module/intersection/scene_merge_from_private_road.hpp, planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp, planning/behavior_velocity_planner/include/utilization/util.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_merge_from_private_road.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp, planning/behavior_velocity_planner/src/utilization/util.cpp
Additional fix PRs for https://github.com/tier4/autoware.universe/pull/268 (https://github.com/autowarefoundation/autoware.universe/pull/2790) containing following PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/2874
- https://github.com/autowarefoundation/autoware.universe/pull/2899
to handle path/route change on the intersection due to Lane Change or Avoidance.
Worked properly on PSim with avoidance and re-routing. …
=> feat(intersection): additional fix for LC and Avoidance on intersection

planning/behavior_path_planner/src/utilities.cpp
https://tier4.atlassian.net/browse/T4PB-26825 の対応
=> fix(behavior_path_planner): backport drivable area for loop route

.github/workflows/dispatch-release-note.yaml
We mostly cannot dispatch workflow with GITHUB_TOKEN.
Instead, we often use Github Apps for organization authorization.
This PR is a substitue for https://github.com/tier4/autoware.universe/pull/314
=> ci(dispatch-release-note): use Github Apps instead of GIHUB_TOKEN

perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_cluster_fusion/node.hpp, perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml, perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
See https://github.com/autowarefoundation/autoware.universe/issues/2659
( https://github.com/autowarefoundation/autoware.universe/pull/2701): cherry-pick to avoid conflicts
https://github.com/autowarefoundation/autoware.universe/pull/2844
tested by logging_simulator
=> feat: update roi_cluster_fusion

perception/ground_segmentation/docs/scan-ground-filter.md, perception/ground_segmentation/include/ground_segmentation/scan_ground_filter_nodelet.hpp, perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp
- cherry-pick for ground_segmentation
=> chore: cherry pick for ground segmentation

planning/rtc_interface/include/rtc_interface/rtc_interface.hpp, planning/rtc_interface/src/rtc_interface.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3029
https://github.com/autowarefoundation/autoware.universe/pull/3029
https://tier4.atlassian.net/browse/T4PB-26888
Confirmed that the rtc approval status changes properly when an  rtc approval instruction is given from the MOT on the planning simulator (see the above Jira ticket). …
=> fix(rtc_interface): fix initial auto mode (#3029)

planning/hazard_lights_selector/CMakeLists.txt, planning/hazard_lights_selector/README.md, planning/hazard_lights_selector/config/hazard_lights_selector.param.yaml, planning/hazard_lights_selector/include/hazard_lights_selector/hazard_lights_selector_node.hpp, planning/hazard_lights_selector/launch/hazard_lights_selector.launch.xml, planning/hazard_lights_selector/package.xml, planning/hazard_lights_selector/src/hazard_lights_selector_node.cpp, system/mrm_comfortable_stop_operator/include/mrm_comfortable_stop_operator/mrm_comfortable_stop_operator_core.hpp, system/mrm_comfortable_stop_operator/launch/mrm_comfortable_stop_operator.launch.py, system/mrm_comfortable_stop_operator/package.xml, system/mrm_comfortable_stop_operator/src/mrm_comfortable_stop_operator/mrm_comfortable_stop_operator_core.cpp
https://tier4.atlassian.net/browse/T4PB-22513
Add hazard_lights_selector so that hazard lights can be directed from nodes other than behavior_path_planner
**Related PR**
- https://github.com/tier4/autoware_launch.x2/pull/258
**Before**
**After**
**Test**
緩停止MRMを発動させて`/planning/hazard_lights_cmd`のcommandが2 (=ENABLE)をpublishすること …
=> feat(hazard_lights_selector): turn on hazard lights from mrm comfortable stop operator

planning/behavior_velocity_planner/config/detection_area.param.yaml, planning/behavior_velocity_planner/detection-area-design.md, planning/behavior_velocity_planner/include/scene_module/detection_area/scene.hpp, planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3114 for the following scenario.
https://evaluation.tier4.jp/evaluation/scenarios/8c413181-1a5c-4a2e-a926-bb373fdb68a2?project_id=x2_dev
[TIER IV slack](https://star4.slack.com/archives/CRUE57C30/p1678697490241789)
https://github.com/autowarefoundation/autoware.universe/pull/3114 …
=> fix(behavior_velocity_planner): fix detection area being ignored when the ego vehicle stops over the stop line (#3114)

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
https://github.com/autowarefoundation/autoware.universe/pull/3082
Hotfix to beta/v0.7.0-odaiba1
https://github.com/autowarefoundation/autoware.universe/pull/3082
See https://github.com/autowarefoundation/autoware.universe/pull/3082
=> perf(motion_utils): improve performance of findNearestIndex (#3082)

planning/obstacle_avoidance_planner/CMakeLists.txt
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3009 to prevent nodes from dying in CI simulator.
=> fix(obstacle_avoidance_planner): remove the option march=native (#3009)

.github/workflows/sync-upstream.yaml
- Trigger this workflow at 10 a.m. on weekdays
- Judge if national or public holidays (祝日)
- Run this job on workflow dispatch or weekdays except holidays
Not tested this but tested in the related PR: https://github.com/tier4/autoware_launch/pull/51
=> ci(sync-upstream): run weekdays except holidays

system/system_error_monitor/config/diagnostic_aggregator/control.param.yaml, system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml
It has occurred a Stale error in both tf_status and external_cmd_converter.
This PR fixes the issues.
- tf_status
- It has already been contained in ocalization_topic_status
- external_cmd_converter
- changed the aggregator key which was checked on the bench system.
- https://github.com/tier4/autoware_launch.x2/pull/278
- https://tier4.atlassian.net/browse/RT0-28037
- https://tier4.atlassian.net/browse/RT0-28038
Tested on the X2 bench system
Affects for diag behaviour. …
=> chore: fix MRM diag are tf_status and external_cmd_converter #278

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3494 
This solves the problem that the ego vehicle can't stop when external velocity limit is set to 0.
JIRA Ticket
[TIER IV Internal Link](https://tier4.atlassian.net/browse/RT0-27120)
- Planning Simulator
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull- …
=> fix(motion_velocity_smoother): insert the point when applying external velocity limit

system/system_error_monitor/config/diagnostic_aggregator/sensing.param.yaml
- Fix settings for diagnostics aggregator
- https://github.com/tier4/autoware_launch.x2/pull/281
Test Result : [link](https://evaluation.tier4.jp/evaluation/reports/b269ea0b-b9f4-5588-8b14-290bfc87e8d2?project_id=x2_dev)
- visibility and blockage values are available as expected on driving log replayer …
=> fix: performance_monitoring

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
停止してからパラメーターで指定される時間だけ厳密に停止するように修正
Same as 
https://github.com/autowarefoundation/autoware.universe/pull/3528
https://github.com/autowarefoundation/autoware.universe/pull/3539
=> fix(behavior_velocity_planner::intersection): strictly wait at 1st stop line when occlusion is detected

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
死角がクリアになった後に再発進するように修正
Same as https://github.com/autowarefoundation/autoware.universe/pull/3552
死角クリア後の挙動の確認
https://user-images.githubusercontent.com/28677420/235409008-d2c01f40-163e-4a7f-8925-fef29c5a60f9.mp4
=> fix(intersection): fixed to restart after occlusion is cleared (#3552)

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
自車レーン上で死角認識をしないように修正
Same as https://github.com/autowarefoundation/autoware.universe/pull/3553
=> feat(intersection): clear costmap on adjacent lanes

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
死角頭出しラインまでの距離が非承認時にも有限の値になるよう修正
Same as https://github.com/autowarefoundation/autoware.universe/pull/3573
https://user-images.githubusercontent.com/28677420/235409120-154a8fc6-cb02-4c16-b128-875e92aebd1e.mp4
https://user-images.githubusercontent.com/28677420/235409204-e0b450b0-6591-4b87-9def-bef16aa041d7.mp4
https://user-images.githubusercontent.com/28677420/235409229-9caf092e-f112-440a-bed9-fe5b838283ff.mp4
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …
=> fix(intersection): always send finite distance to occlusion peeking stop line in RTC

planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_merge_from_private_road.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp
remove lanelets on path from detection area
xx1の発着発進のシナリオで交差点死角検知が不要に働いていてfailしていた問題にたいする修正
https://github.com/autowarefoundation/autoware.universe/pull/3655 と同じ内容
=> feat(intersection): remove lanelets on path from detection area (#3655)

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/behavior_tree_manager.cpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/src/utils/utils.cpp
Hotfix to v0.8.0
https://github.com/autowarefoundation/autoware.universe/pull/3660
See https://github.com/autowarefoundation/autoware.universe/pull/3660
=> fix(behavior_path_planner): add drivable area information (#3660)

common/autoware_auto_tf2/CMakeLists.txt, common/autoware_auto_tf2/package.xml
backport: https://github.com/autowarefoundation/autoware.universe/pull/848
I confirmed same changes.
=> fix: remove unused orocos kdl from dependencies (#848)

common/autoware_auto_common/CMakeLists.txt, common/autoware_auto_common/package.xml
ROS2 Humble環境でビルドエラーとなるので、`geometry_msgs`パッケージへの依存関係をCMakeLists.txtとpackage.xmlに記述する。
https://tier4.atlassian.net/browse/AEAP-486
以下の環境下で、autoware_auto_commonパッケージのビルド時に、ビルドエラーが出ないことを確認。
- OS
- Ubuntu22.04
- ROS2 Distribution
- Humble
- pilot-auto.x1.eveのバージョン
- [9735f6f69a3a7132a7fa60dea1f30569ebf9b27d](https://github.com/tier4/pilot-auto.x1.eve/tree/9735f6f69a3a7132a7fa60dea1f30569ebf9b27d)
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …
=> fix(autoware_auto_common): fix build dependency on geometry_msgs

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp
ROS2 Humble環境で、tf2_geometry_msgsのヘッダ拡張子が`.h`だとビルドエラーになるので、拡張子を`.hpp`に変更する。
https://tier4.atlassian.net/browse/AEAP-486
以下の環境下で、tier4_autoware_utilsパッケージのビルド時に、ビルドエラーが出ないことを確認。
- OS
- Ubuntu22.04
- ROS2 Distribution
- Humble
- pilot-auto.x1.eveのバージョン
- [9735f6f69a3a7132a7fa60dea1f30569ebf9b27d](https://github.com/tier4/pilot-auto.x1.eve/tree/9735f6f69a3a7132a7fa60dea1f30569ebf9b27d) …
=> fix(tier4_autoware_utils): change the header extension of the included tf2_geometry_msgs from .h to .hpp

build_depends.repos
grid_mapはHumbleからaptで取得するので、不要
参照: https://github.com/tier4/pilot-auto.x1.eve/pull/519
check-build-dependsは他のパッケージでビルド失敗するため、無視して良い
=> ci: delete grid_map from build_depends.repos

perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp
add initialize for anchor point vector
trackerで初期値が未初期化されていた問題の修正
https://github.com/autowarefoundation/autoware.universe/pull/3651 と同じ内容
=> fix(multi_object_tracker): fix unintended perturbation in tracking estimation via non initialized eigen vector (#3651)

sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/distortion_corrector/distortion_corrector.hpp, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/passthrough_filter/passthrough_uint16.hpp, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/vector_map_filter/lanelet2_map_filter_nodelet.hpp, sensing/pointcloud_preprocessor/src/outlier_filter/radius_search_2d_outlier_filter_nodelet.cpp
Humbleでのビルドエラーを修正
- boost::shared_ptr -> pcl::shared_ptr
- tf2_geometry_msgs.h -> tf2_geometry_msgs.hpp
- tf2_eigen.h -> tf2_eigen.hpp
=> fix(pointcloud_preprocessor): fix build error in Humble

localization/ndt/CMakeLists.txt, localization/ndt/include/ndt/base.hpp, localization/ndt/include/ndt/impl/omp.hpp, localization/ndt/include/ndt/impl/pcl_generic.hpp, localization/ndt/include/ndt/impl/pcl_modified.hpp, localization/ndt/include/ndt/omp.hpp, localization/ndt/include/ndt/pcl_generic.hpp, localization/ndt/include/ndt/pcl_modified.hpp
https://github.com/autowarefoundation/autoware.universe/pull/793 を参考にビルドエラーを修正
https://github.com/tier4/autoware.universe/pull/445 で依存パッケージのndt_pcl_modifiedの修正も実施しているため、先にこちらをマージする必要あり
参考元と同じ変更になっていること
ndtがビルドできること
=> fix(ndt): fix build error in Humble

common/tier4_vehicle_rviz_plugin/src/tools/steering_angle.cpp
https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-63a4e57abc1bb5508efbb58428d1a48ec1da6f91318ba8f2c836e2bd7784ec02R133 を参考にwarningを修正
以下のwarningが出ないこと
```
warning: ‘QPixmap QPixmap::transformed(const QMatrix&, Qt::TransformationMode) const’ is deprecated: Use transformed(const QTransform &, Qt::TransformationMode mode) [-Wdeprecated-declarations]
``` …
=> fix(tier4_vehicle_rviz_plugin): fix build warning in Humble

localization/localization_error_monitor/src/node.cpp
以下を修正
tf2_geometry_msgs.h -> tf2_geometry_msgs.hpp
localization_error_monitorがビルドできること
=> fix(localization_error_monitor): fix build warning in Humble

localization/stop_filter/package.xml
https://github.com/autowarefoundation/autoware.universe/pull/805 のbackport
stop_filterがビルドできること
=> fix(stop_filter): modify build error in rolling (#805)

localization/pose_initializer/src/pose_initializer_core.cpp
以下を参考に修正
https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-076ef3f74b5024fd7148eb1c2b230225b446ca2809ceb717e9e84f9ff25d5561R21
https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-076ef3f74b5024fd7148eb1c2b230225b446ca2809ceb717e9e84f9ff25d5561R195
pose_initializerのビルドwarningが出ないこと
[pull request …
=> fix(pose_initializer): fix build warning in Humble

localization/pose2twist/src/pose2twist_core.cpp
以下を修正
tf2_geometry_msgs.h -> tf2_geometry_msgs.hpp
ビルドwarningが出ないこと
=> fix(pose2twist): fix build warning in Humble

map/map_tf_generator/package.xml
https://github.com/autowarefoundation/autoware.universe/pull/778 のbackport
map_tf_generatorがビルドできること
=> fix(map_tf_generator): modify build error in rolling (#778)

system/ad_service_state_monitor/include/ad_service_state_monitor/state_machine.hpp, system/ad_service_state_monitor/src/ad_service_state_monitor_node/ad_service_state_monitor_node.cpp, system/ad_service_state_monitor/src/ad_service_state_monitor_node/diagnostics.cpp, system/ad_service_state_monitor/src/ad_service_state_monitor_node/state_machine.cpp
以下を参考に修正
https://github.com/tier4/autoware.universe/commit/12c64922addf52fe21663048aaefec19e3245adf
Humbleとそれ以前の切り替えについては、別PRでは切替なしとしており、本PRも切替なしとする。
ad service state monitorのビルドが成功。
Warning/Noteも出力されないこと。
=> fix(ad_service_state_monitor): fix build error in Humble

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
https://github.com/autowarefoundation/autoware.universe/pull/3664 と同一の内容
intersection/intersection_occlusionをmanualにすると"intersection"を承認してもまた非承認に戻されてしまう，という問題があったのを解決した．それに伴ってintersectionモジュールが持つuuidの個数が3個から2個に減ったが，RTCのinterfaceとしては透過的であり操作面での変更はない．
こちらのバージョンのFOAを使用して動作確認を行った．
https://github.com/tier4/FieldOperatorApplication/pull/590 …
=> feat(intersection): switch default/occlusion_first_stop when occlusion appeared/disappeared or approved/disapproved (#3664)

planning/mission_planner/lib/mission_planner_base.cpp, planning/mission_planner/src/mission_planner_lanelet2/mission_planner_lanelet2.cpp
以下を修正
- tf2_geometry_msgs.h -> tf2_geometry_msgs.hpp
mission_plannerにおいて、tf2_geometry_msgs.hのwarningがなくなっていること
=> fix(mission_planner): fix build warning in Humble

control/autonomous_emergency_braking/src/node.cpp
Galactic環境で存在しなかったdoTransform関数を追加していたが、Humble環境ではtf2_geometry_msgs.hppに存在しているため削除する
autonomous_emergency_brakingがビルドできること
=> fix(autonomous_emergency_braking): fix build error in Humble

control/trajectory_follower/include/trajectory_follower/mpc_utils.hpp, control/trajectory_follower/src/longitudinal_controller_utils.cpp, control/trajectory_follower/src/pid.cpp, control/trajectory_follower/test/test_longitudinal_controller_utils.cpp, control/trajectory_follower/test/test_mpc.cpp
https://github.com/autowarefoundation/autoware.universe/pull/803 を参考にビルドエラーを修正
ビルド時に出てくる以下のようなwarningについては最新でも未修正のため、今回は無視する
```
/home/hrkota/pilot-auto.x1.eve/src/autoware/universe/control/trajectory_follower/src/mpc.cpp:53:46: warning: use of old-style cast to ‘rcutils_duration_value_t’ {aka ‘long int’} [-Wold-style-cast]
53 |     RCLCPP_WARN_THROTTLE(m_logger, *m_clock, 1000 /*ms*/, "fail to get Data.");
|                                          
```
最新は以下
https://github.com/tier4/autoware.universe/blob/tier4/main/control/mpc_lateral_controller/src/mpc.cpp#L42
The PR author **must** check the checkboxes below …
=> fix(trajectory_follower): fix build error in Humble

perception/occupancy_grid_map_outlier_filter/include/occupancy_grid_map_outlier_filter/occupancy_grid_map_outlier_filter_nodelet.hpp, perception/occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_nodelet.cpp
以下を参考に修正を実施
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-504112b873cf64e14556e7730dc483a5a84ff0249328972754fde52fde0d687aR34
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-e382b99e67e2f34bd5d96eb3680fc112dd8081c161715aa41a55e1647aca4bc3R28
- https://github.com/autowarefoundation/autoware.universe/pull/804/files#diff-e382b99e67e2f34bd5d96eb3680fc112dd8081c161715aa41a55e1647aca4bc3L106-R111
- 
occupancy_grid_map_outlier_filterがビルドできること
After all checkboxes are …
=> fix(occupancy_grid_map_outlier_filter): fix build error in Humble

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
以下を参考に修正
- https://github.com/autowarefoundation/autoware.universe/pull/823
- https://github.com/autowarefoundation/autoware.universe/pull/756
behavior_path_plannerがビルドできること
=> fix(behavior_path_planner): fix build error in Humble

planning/surround_obstacle_checker/src/debug_marker.cpp, planning/surround_obstacle_checker/src/node.cpp
以下を参考に修正を実施
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-5c75aea45aea3eb5921c89fdc2690a1ca61bf2e9ab4e0d81207fc068a35e56e0R20
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-fef6c5b3345390ea49efda07ce3f02cf110961b5e7abe38a4b415d2b30e6f6fcR24
surround_obstacle_checkerがビルドwarningがないこと …
=> fix(surround_obstacle_checker): fix build warning in Humble

simulator/dummy_perception_publisher/include/dummy_perception_publisher/node.hpp, simulator/dummy_perception_publisher/src/node.cpp, simulator/dummy_perception_publisher/src/signed_distance_function.cpp
以下を参考に修正を実施
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-f7025aa1b2846894c7a4a3495b2ff2abefc334d78c350ef4de488373ece32f24R35
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-9e63f577908171e00f9199eac93ea6cddd65ead39b0f83a93123a438a3267ba2R24
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-3290f2cb97b611502587a1421628ad062a0c09a16ab3407fd2e9d572ffae1957R73
dummy_perception_publisherがビルドwarningが出ないこと …
=> fix(dummy_perception_publisher): fix build warning in Humble

planning/scenario_selector/include/scenario_selector/scenario_selector_node.hpp, planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
以下を参考に修正を実施
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-eb274b7f1ef24244f52685ea0b593feab249ebe5b4b703dbcd5a57d6588d392dR33
- https://github.com/autowarefoundation/autoware.universe/pull/852/files#diff-2895dbd698a277514b53ced0b819f72662eabcb678f1b37dc8c11efaa74b3d29L189-R189
scneario_selectorのビルド時にwarningが出ないこと …
=> fix(scenario_selector): fix build warning in Humble

system/system_monitor/CMakeLists.txt, system/system_monitor/launch/system_monitor.launch.py, system/system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp
https://github.com/autowarefoundation/autoware.universe/pull/788 を参考にビルドエラーを修正
system_monitor.launch.pyでtier4_system_launchを参照しているのを修正
system_monitorがビルドできること
=> fix(system_monitor): fix build error in Humble

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
cherry-pick 
https://github.com/autowarefoundation/autoware.universe/pull/3709
これが無いとバックして、路肩発進しながら回避が上手く動かないです。
psim, scenario test in main
build in this branch
not applicable
not applicable
=> fix(behavior_path_planner): init idling module (#3709)

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
こちらもバックしてから、路肩発進+avoidanceに必要です。
avoidanceが承認していないのにapprovedに入るバグ修正です
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3662
psim in main
build in this branch
=> fix(avoidance): clear waiting approval only when all target module are unavoidable (#3662)

control/shift_decider/include/shift_decider/shift_decider.hpp, control/shift_decider/src/shift_decider.cpp, control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp, launch/tier4_control_launch/launch/control.launch.py
https://github.com/autowarefoundation/autoware.universe/pull/3683
https://github.com/autowarefoundation/autoware.universe/pull/3684
( Solve this [Issue](https://github.com/autowarefoundation/autoware.universe/issues/3526) about gear. )
https://github.com/autowarefoundation/autoware.universe/pull/3683
https://github.com/autowarefoundation/autoware.universe/pull/3684
I confirmed that it worked well on actual vehicle.
none
none
Solve the issue that the gear does not change to PARKING on goal.
After all checkboxes are checked, anyone who has write access can merge …
=> fix(vehicle_cmd_gate): fix the gear transition

perception/compare_map_segmentation/README.md, perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp
* fix: bug when using dynamic mode on no-split map
* fix: unify split and no-split map
* chore: update readme
* chore: typo
---------
**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.
Click the `Preview` tab and select a PR template:
- [Standard change](?expand=1&template=standard-change.md)
- [Small change](?expand=1&template=small-change.md)
**Do NOT send a PR with this description.**
=> fix(compare_map_segmentation): fix bug when set dynamic map loader for no split map (autowarefoundation#3732)

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
This hotfix make [these avoidance fails scenarios](https://evaluation.tier4.jp/evaluation/reports/c8b4c4d8-a04f-5852-94f2-cf8123d1cb66/tests/bc0a91d8-f473-5d2c-919d-abae0ee31c28/2ad53fde-f273-51b9-9536-67385a86bf7a?project_id=prd_jt) possible to pass.
- https://github.com/autowarefoundation/autoware.universe/pull/3687 …
=> fix(lane_change): get lane change lanes actual length (#3687)

common/motion_utils/src/resample/resample.cpp, planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/utils.cpp, planning/behavior_path_planner/test/test_lane_change_utils.cpp
Add dynamic lateral acceleration for lane change
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/3705
- https://github.com/autowarefoundation/autoware.universe/pull/3742
=> feat(lane_change): add dynamic lateral acceleration for lane change

planning/behavior_path_planner/src/utils/utils.cpp
以下のdrivable areaがバグる現象のhotfix
https://star4.slack.com/archives/CEV8XMJBV/p1684493198710939?thread_ts=1684403609.020779&cid=CEV8XMJBV
元PR: https://github.com/autowarefoundation/autoware.universe/pull/3772
psim
柏の葉のフリースペースの路肩駐車でdrivable areaが正常になる
=> fix(behavior_path_planner): generate drivable area for long backward path (#3772)

common/motion_utils/src/distance/distance.cpp, common/motion_utils/test/src/distance/test_distance.cpp, common/signal_processing/include/signal_processing/lowpass_filter_1d.hpp, common/signal_processing/src/lowpass_filter_1d.cpp, planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/planner_interface.cpp
障害物に対する減速機能の安定化
以下のmain内のコミットをcherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/3747
- https://github.com/autowarefoundation/autoware.universe/pull/3775
- https://github.com/autowarefoundation/autoware.universe/pull/3743
- https://github.com/autowarefoundation/autoware.universe/pull/3751
- https://github.com/autowarefoundation/autoware.universe/pull/3778
- https://github.com/autowarefoundation/autoware.universe/pull/3744
- planning simulator
- scenario simulator
- without this PR: https://evaluation.tier4.jp/evaluation/reports/fc75b567-170a-5d09-8e6a-26088cf2ff8f?project_id=prd_jt (1692/1722 pass)
- with this PR: https://evaluation.tier4.jp/evaluation/reports/534ac908-f7c4-52d6-ab98-bb2813475ddc?project_id=prd_jt (1697/1722 pass)
※3, …
=> feat(obstacle_cruise_planner): make slow down feature stabler

perception/map_based_prediction/config/map_based_prediction.param.yaml
lane_change_detectionを横移動量ベース(旧)からカットインまでの時間ベース(新)に変更
https://star4.slack.com/archives/C03S84LDJGG/p1684717842809799
psim/scenario sim (本来はコンポーネントチームでの実車試験後に適用するのが望ましいが、シミュレータで問題がないため適用)
=> feat(map_based_prediction): use time_to_change_lane

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3796 for beta/v0.8.0
https://tier4.atlassian.net/browse/RT1-2382
psim
not applicable
not applicable
=> fix(behavior_path_planner): do not execute goal_planner when the fixed goal is not in current lanes (#3796)

planning/motion_velocity_smoother/scripts/trajectory_visualizer.py
以下PRのbackport
https://github.com/autowarefoundation/autoware.universe/pull/737
https://github.com/autowarefoundation/autoware.universe/pull/745
trajectory_visualizer自体の動作を確認
デバッグツールのため、システムへの影響なし
=> feat: update trajectory visualizer (backport #737 #745)

localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp, planning/behavior_velocity_planner/src/node.cpp, planning/surround_obstacle_checker/src/node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/3359 のbackportとして、必要な部分をピックアップして適用する
なお、tier4_autoware_utilsのパッケージに手を加える場合影響範囲が膨大なため、修正が必要な箇所のみの対応とする
https://tier4.atlassian.net/browse/AEAP-517
- ビルドが問題ないこと
- コード内に存在している pcl::transformPointCloudが tier4_autoware_utils::transformPointCloudに変更されていること
- planning_simulatorで自己位置およびゴールを設定した際にbehavior_velocity_plannerが強制終了しないこと …
=> fix(transformPointCloud): use tier4_autoware_utils instead of pcl

simulator/dummy_perception_publisher/CMakeLists.txt
https://docs.ros.org/en/humble/Releases/Release-Humble-Hawksbill.html#rosidl-cmake
Humbleではrosidl_target_interfaces()が非推奨となったので、https://github.com/ros2/demos/pull/529 を参考に修正します。
Related Links: https://tier4.atlassian.net/browse/AEAP-550
colconでdummy_perception_publisherをビルドし、Error/Warningが出力されないこと。
Note: 修正前は次のWarningが出力される。
```sh
CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
Use rosidl_get_typesupport_target() and target_link_libraries() instead of
rosidl_target_interfaces()
Call Stack (most recent call first):
CMakeLists.txt:68 (rosidl_target_interfaces)
```
The …
=> fix(dummy_perception_publisher): use rosidl_get_typesupport_target instead of rosidl_target_interfaces

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/3801
https://github.com/autowarefoundation/autoware.universe/pull/3801
psim and scneario tests with main
build with this branch
not applicable
not applicable
=> fix(goal_planner): add buffer to stop_pose for restarting (#3801)

common/path_distance_calculator/CMakeLists.txt, common/path_distance_calculator/package.xml, common/tier4_autoware_utils/CMakeLists.txt, common/tier4_autoware_utils/package.xml, common/tier4_vehicle_rviz_plugin/CMakeLists.txt, common/tier4_vehicle_rviz_plugin/package.xml
下記のコマンドでビルドしてBoostのwarningが出ないこと
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests --parallel-workers 8 --packages-up-to  $(colcon list --base-path src/autoware/universe/common/ | awk '{print $1}')
```
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/con …
=> feat(common): use autoware_cmake to avoid Boost warning

common/polar_grid/CMakeLists.txt, common/tier4_calibration_rviz_plugin/CMakeLists.txt, common/tier4_datetime_rviz_plugin/CMakeLists.txt, common/tier4_localization_rviz_plugin/CMakeLists.txt, common/tier4_perception_rviz_plugin/CMakeLists.txt, common/tier4_planning_rviz_plugin/CMakeLists.txt, common/tier4_simulated_clock_rviz_plugin/CMakeLists.txt, common/tier4_state_rviz_plugin/CMakeLists.txt, common/tier4_traffic_light_rviz_plugin/CMakeLists.txt, common/tier4_vehicle_rviz_plugin/CMakeLists.txt, localization/initial_pose_button_panel/CMakeLists.txt
https://github.com/autowarefoundation/autoware.universe/pull/1474 のbackport
下記のコマンドでビルドしてEXACTをignoreするwarningが出ないこと
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests --parallel-workers 8 --packages-up-to  $(colcon list --base-path src/autoware/universe/common/ | awk '{print $1}')
``` …
=> fix: remove unused check of rviz plugin version (#1474)

control/lane_departure_checker/CMakeLists.txt, control/lane_departure_checker/package.xml
下記のコマンドでビルドしてcontrol以下のパッケージでBoostのwarningが出ないこと
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests --parallel-workers 8 --packages-up-to  $(colcon list --base-path src/autoware/universe/control/ | awk '{print $1}')
``` …
=> feat(control): use autoware cmake to avoid Boost warning

map/lanelet2_extension/CMakeLists.txt, map/lanelet2_extension/package.xml
下記のコマンドでビルドしてmap以下のパッケージでBoostのwarningが出ないこと
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests --parallel-workers 8 --packages-up-to  $(colcon list --base-path src/autoware/universe/map/ | awk '{print $1}')
``` …
=> feat(map): use autoware_cmake to avoid Boost warning

perception/elevation_map_loader/CMakeLists.txt, perception/elevation_map_loader/package.xml, perception/ground_segmentation/CMakeLists.txt, perception/ground_segmentation/package.xml, perception/occupancy_grid_map_outlier_filter/CMakeLists.txt, perception/occupancy_grid_map_outlier_filter/package.xml, perception/shape_estimation/CMakeLists.txt, perception/shape_estimation/package.xml
下記のコマンドでビルドしてperception以下のパッケージでBoostのwarningが出ないこと
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests --parallel-workers 8 --packages-up-to  $(colcon list --base-path src/autoware/universe/perception | awk '{print $1}')
``` …
=> feat(perception): use autoware_cmake to avoid Boost warning

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/package.xml, planning/behavior_velocity_planner/CMakeLists.txt, planning/behavior_velocity_planner/package.xml, planning/mission_planner/CMakeLists.txt, planning/mission_planner/package.xml, planning/obstacle_avoidance_planner/CMakeLists.txt, planning/obstacle_avoidance_planner/package.xml, planning/obstacle_stop_planner/CMakeLists.txt, planning/obstacle_stop_planner/package.xml, planning/planning_error_monitor/CMakeLists.txt, planning/planning_error_monitor/package.xml, planning/route_handler/CMakeLists.txt, planning/route_handler/package.xml, planning/scenario_selector/CMakeLists.txt, planning/scenario_selector/package.xml, planning/surround_obstacle_checker/CMakeLists.txt, planning/surround_obstacle_checker/package.xml
下記のコマンドでビルドしてplanning以下のパッケージでBoostのwarningが出ないこと
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests --parallel-workers 8 --packages-up-to  $(colcon list --base-path src/autoware/universe/planning | awk '{print $1}')
``` …
=> feat(planning): use autoware_cmake to avoid Boost warning

planning/behavior_path_planner/include/behavior_path_planner/marker_util/lane_change/debug.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_path.hpp, planning/behavior_path_planner/src/marker_util/lane_change/debug.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp
* feat(lane_change): lane change virtual wall marker
* virtual wall new architecture
---------
cherry pick from https://github.com/autowarefoundation/autoware.universe/pull/3808 to `beta/v0.8.0`
With the addition of https://github.com/autowarefoundation/autoware.universe/pull/3566, the flow of lane change states has been changed, and lane changing process will only be cancelled if ego vehicle **is in prepare phase**. 
However, it is difficult to distinguish prepare phase and lane changing phase. Therefore, the aim of this PR is to add virtual marker that will enable see where lane changing is starting.
After PR is merged, we expect the result to be as follows.
https://github.com/autowarefoundation/autoware.universe/pull/3808
Tested via PSIM
None
None
None
The PR author **must** check the …
=> feat(lane_change): lane change virtual wall marker (#3808)

sensing/probabilistic_occupancy_grid_map/src/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.cpp, sensing/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map.cpp, sensing/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp
以下のwarningを修正
```
--- stderr: probabilistic_occupancy_grid_map                                                                                                         
** WARNING ** io features related to pcap will be disabled
In file included from /home/hrkota/pilot-auto.x1.eve/src/autoware/universe/sensing/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map.cpp:62:
/opt/ros/humble/include/tf2_sensor_msgs/tf2_sensor_msgs.h:32:2: warning: #warning This header is obsolete, please include tf2_sensor_msgs/tf2_sensor_msgs.hpp instead [-Wcpp]
32 | #warning This header is obsolete, please include tf2_sensor_msgs/tf2_sensor_msgs.hpp instead
|  ^~~~~~~
In file included from /home/hrkota/pilot-auto.x1.eve/src/autoware/universe/sensing/probabilistic_occupancy_ …
```
=> fix(probablistic_occupancy_grid_map): fix build warning

sensing/pointcloud_preprocessor/CMakeLists.txt, sensing/pointcloud_preprocessor/package.xml, sensing/probabilistic_occupancy_grid_map/CMakeLists.txt, sensing/probabilistic_occupancy_grid_map/package.xml
下記のコマンドでビルドしてsensing以下のパッケージでBoostのwarningが出ないこと
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests --parallel-workers 8 --packages-up-to  $(colcon list --base-path src/autoware/universe/sensing | awk '{print $1}')
``` …
=> feat(sensing): use autoware_cmake to avoid Boost warning

control/autonomous_emergency_braking/src/node.cpp
現在のAEB実装でgalactic環境で動かすと以下のエラーが発生してしまう
```
[component_container-10] /opt/ros/galactic/lib/rclcpp_components/component_container: symbol lookup error: /home/hrkota/pilot-auto.x1.eva/install/autonomous_emergency_braking/lib/libautonomous_emergency_braking_node.so: undefined symbol: _ZN3tf211doTransformIN13geometry_msgs3msg8Vector3_ISaIvEEEEEvRKT_RS6_RKNS2_17TransformStamped_IS4_EE
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/control/trajectory_follower/lane_departure_checker_node' in container '/control/control_container'
[ERROR] [component_container-10]: process has died [pid 28558, exit code 127, cmd '/opt/ros/galactic/lib/rclcpp_components/component_container --ros-args -r __node:=control_container -r __ns:=/control --params-file /tmp/launch_params_ns5yss68'].
``` …
=> fix(autonomous_emergency_braking): add doTransform to fix undefined symbol

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
cherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/3843
https://tier4.atlassian.net/browse/RT1-2532
LCとexternal LCのチャタリングが治る
=> fix(behavior_path_planner): return default value if no registered module exists (#3843)

planning/behavior_velocity_planner/src/scene_module/bus_stop/scene.cpp
Fixed the position of the virtual wall.
(TIER IV Internal Link)
- https://tier4.atlassian.net/browse/RT0-27989
Tested with simple planning simulator.
=> fix(bus_stop): create virtual wall at the stop line

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
https://github.com/autowarefoundation/autoware.universe/pull/3820
Not applicable. (Check the original PR)
Not applicable. (Check the original PR)
=> fix(behavior_path_planner): do not return FAILURE in lane change module if it uses new architecture (#3820)

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
hotfix
https://github.com/autowarefoundation/autoware.universe/pull/3861
=> feat(lane_change): check lateral offset at lc finish judgement (#3861)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
=> fix(avoidance): hotfix

common/motion_utils/src/vehicle/vehicle_state_checker.cpp, common/motion_utils/test/src/vehicle/test_vehicle_state_checker.cpp
Cherry-pick this PR.
- https://github.com/autowarefoundation/autoware.universe/pull/3883
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-28230)
Tested with the unit test.
Please see the PR for the details.
https://github.com/autowarefoundation/autoware.universe/pull/3883
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …
=> fix(motion_utils): check if the buffer is empty (#3883)

planning/behavior_path_planner/config/behavior_path_planner.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/utils/safety_check.cpp
Lane Change hotfix to disable virtual wall and parameterize velocity scale
https://github.com/tier4/autoware_launch.xx1/pull/504
https://github.com/autowarefoundation/autoware_launch/pull/384
https://github.com/autowarefoundation/autoware.universe/pull/3906
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-reques …
=> fix(lane_change): hotfix visualization and parameterization

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
fix(behavior_path_planner): clear stop reason
hotfix
- https://github.com/autowarefoundation/autoware.universe/pull/3910
=> fix(behavior_path_planner): clear stop factors (#3910)

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/3881
(TIER IV Inetnal link: https://star4.slack.com/archives/C03QW0GU6P7/p1686212813442949 )
Not applicable. ( Check the original PR. )
=> fix(avoidance): candidate path must be filled no matter when (#3881)

planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
cruiseの色がほぼ赤でstopと似ていたので、ピンク色に変更
hotfix for https://github.com/autowarefoundation/autoware.universe/pull/3925
planning simulator
Nothing
=> chore(obstacle_cruise_planner): change cruise color

system/imu_monitor/config/imu_monitor.param.yaml
Changed yaw_rate_diff_threshold based on experimental data.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-28314)
- https://github.com/tier4/autoware.universe/pull/333
=> chore(imu_monitor): change yaw_rate_diff_threshold from 0.07 to 0.14

map/lanelet2_extension/CMakeLists.txt
https://github.com/tier4/pilot-auto.x1.eve/actions/runs/5232576503/jobs/9447373065
でビルドエラーが発生しているため
https://github.com/autowarefoundation/autoware_common/pull/183 と同様の変更を実施
なお、utilities-testについても同じエラーが発生したため、対策を実施
build-and-test-differentialが成功することを確認
=> fix(lanelet2_extension): fix build error

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
cherry pick https://github.com/autowarefoundation/autoware.universe/pull/3971
=> fix(avoidance): don't reset registered shift lines if the base offset is not zero (#3971)

system/imu_monitor/config/imu_monitor.param.yaml
Tuned yaw_rate_diff_threshold based on experimental data.
I modified this value in this [PR](https://github.com/tier4/autoware.universe/pull/569) before, but the threshold was not enough.
Related ticket
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-28314?focusedCommentId=126589)
Tested on an actual vehicle. …
=> chore(imu_monitor): change yaw_rate_diff_threshold from 0.14 to 0.18

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
fix running module simulataneously
cherry-pick
- feat(behavior_path_planner): use module status idle before approval and keep candiate running module when approved module succeed #3928
- https://github.com/autowarefoundation/autoware.universe/pull/3929
- https://github.com/autowarefoundation/autoware.universe/pull/3709
- https://github.com/autowarefoundation/autoware.universe/pull/3931
psim, scneario tests in main
- old archi https://evaluation.tier4.jp/evaluation/reports/fbd639d3-080a-5f66-8701-559bb1b770f2?project_id=prd_jt 1332
- new archi https://evaluation.tier4.jp/evaluation/reports/fd64fc50-e100-5081-bcb3-f437378c7f97?project_id=prd_jt 1367
- base_line 1331/1372([2023/06/19](https://evaluation.tier4.jp/evaluation/reports/df9038aa-d030-5376-9015-f4c1d5dc5419/?project_id=prd_jt)) …
=> feat(behavior_path_planner): use module status idle before approval and keep candiate running module when approved module succeed #3928

planning/mission_planner/CMakeLists.txt, planning/route_handler/CMakeLists.txt, planning/scenario_selector/CMakeLists.txt
humble環境にて、ビルドエラーが発生しているため
https://github.com/autowarefoundation/autoware_common/pull/183 と同様の変更を実施
colcon build が成功することを確認
=> fix(planning): fix build error

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp, common/tier4_autoware_utils/test/src/geometry/test_geometry.cpp
以下をバックポートします。
- https://github.com/autowarefoundation/autoware.universe/pull/1097
- https://github.com/autowarefoundation/autoware.universe/pull/1100
- https://github.com/autowarefoundation/autoware.universe/pull/1126
各PRについてコンフリクトはありません。（全く同一の変更内容）
https://github.com/autowarefoundation/autoware.universe/pull/1097
https://github.com/autowarefoundation/autoware.universe/pull/1100
https://github.com/autowarefoundation/autoware.universe/pull/1126
- 上記PRが変更なく本PRに適用されていることを確認済みです。
- また、https://github.com/tier4/autoware.universe/pull/210 にて正常動作することを確認済みです。
- https://github.com/tier4/autoware.universe/pull/210 における build and test differential のCI/CDもパスしています。
The PR reviewers **must** check the checkboxes below before …
=> feat(tier4_autoware_utils): add interpolation function (backport #1097, #1100, #1126)

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp, common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/path_with_lane_id_geometry.hpp, common/tier4_autoware_utils/include/tier4_autoware_utils/tier4_autoware_utils.hpp
下記の関数を現時点autoware.universe 最新の https://github.com/tier4/autoware.universe/blob/f321e40c02328f9d7ad6ec7c6a210e1a53e6b369/common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp からコピーします。
- getLongitudinalVelocity
- setPose
- setOrientation
- setLongitudinalVelocity
- isDrivingForward
その依存関係である下記をincludeします。
- tf2/utils.h
- (isDrivingForward 内でtf2::getYaw関数を利用するため)
- tier4_autoware_utils/math/constants.hpp
- (isDrivingForward 内で定数piを利用するため)
- tier4_autoware_utils/math/normalization.hpp
- (isDrivingForward 内でnormarizeRadian関数を利用するため)
また、現時点autoware.universe最新のhttps://github.com/tier4/autoware.universe/blob/f321e40c02328f9d7ad6ec7c6a210e1a53e6b369/common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/path_with_lane_id_geometry.hpp をコピーします。
- …
=> feat(tier4_autoware_utils): add geometry func

common/tier4_autoware_utils/include/tier4_autoware_utils/tier4_autoware_utils.hpp, common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/path_with_lane_id.hpp, common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp
下記の関数を現時点autoware.universe 最新の https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp からコピーします。
- validateNonSharpAngle
- isDrivingForward
- isDrivingForwardWithTwist
- insertTargetPoint
また、現時点autoware.universe最新の https://github.com/tier4/autoware.universe/blob/7ef1bee35c60cfc4637840bfacc0162d14e31143/common/motion_utils/include/motion_utils/trajectory/path_with_lane_id.hpp をコピーし、tier4_autoware_utilsとして置き換えます。
- https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp#L45-L117
- https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include …
=> feat(tier4_autoware_utils): add trajectory func

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_velocity_planner/include/scene_module/occlusion_spot/occlusion_spot_utils.hpp, planning/behavior_velocity_planner/include/utilization/util.hpp, planning/behavior_velocity_planner/src/scene_module/virtual_traffic_light/scene.cpp
https://github.com/tier4/autoware.universe/pull/599 および https://github.com/tier4/autoware.universe/pull/600 をbehavior_plannerへ適用する場合、下記でredefinitionが発生する。
- 既存のutil内関数でのredifinition
- 既存の各scene_moduleでのredifinition
これを回避するため、既存のutil内関数を削除し、tier4_autoware_utils内の関数へ置き換える。
https://github.com/autowarefoundation/autoware.universe/pull/990/files
https://github.com/tier4/autoware.universe/blob/0f43ed3c3d793f049bb2c29f9d94655bc03781dc/common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/path_with_lane_id_geometry.hpp#L24-L37
- 上記の path_with_lane_id_geometry.hpp内実装と置き換え対象の実装が同一であることを確認済みです。これにより機能劣化の心配はありません。
- build testはhttps://github.com/tier4/autoware.universe/pull/596 にてまとめて確認済みです。
The PR reviewers **must** …
=> feat(behavior_planner): replace get_point function

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- hotfix (https://github.com/autowarefoundation/autoware.universe/pull/4034)
=> feat(avoidance): ignore behind unavoidable objects (#4034)

system/system_error_monitor/config/diagnostic_aggregator/sensing.param.yaml
Current threshold sometimes cause the STALE error because  the receiving interval of the sensor is 1Hz.
So changed the threshold to 2.0 [sec].
Tested on an actual vehicle.
=> chore(system_error_monitor): change the timeout threshold of temperature monitor

common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp
下記の関数を現時点autoware.universe 最新の https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp からコピーします。
- insertStopPoint
- insertDecelPoint
- insertOtientation
- removeInvalidOrientationPoints
- calcSignedArcLength
- findFirstNearestIndexWithSoftConstraints
- findFirstNearestSegmentIndexWithSoftConstraints
- calcDistanceToForwardStopPoint
- cropForwardPoints
- cropBackwardPoints
- cropPoints
- calcYawDeviation
- isTargetPointFront
https://github.com/tier4/autoware.universe/blob/514fea4bf80bf460fa880d96377eb1230823fb7b/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp#L1186-L1810
- trajectory.hpp内の関数は、上記リンク箇所の実装と基本的に同一内容であることを確認済みです。
- …
=> feat(tier4_autoware_utils): add trajectory funcs at 514fea4

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/planner_manager.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4058
See above PR.
Nothing.
Nothing.
=> fix(behavior_path_planner): print avoidance and lane change debug message (#4058)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4077
See above PR.
Nothing.
Nothing.
=> feat(behavior_path_planner): remove redundant process (#4077)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
LC先の物体が動的回避の回避対象にならないように
psim
LC先の物体を動的回避で避けない
=> fix(dynamic_avoidance): ignore objects on LC target lane

control/vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml, control/vehicle_cmd_gate/package.xml, control/vehicle_cmd_gate/script/delays_checker.py, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp, system/default_ad_api/src/motion.cpp, system/default_ad_api/src/motion.hpp
Adds https://github.com/autowarefoundation/autoware.universe/pull/3385 and https://github.com/autowarefoundation/autoware.universe/pull/4060
Also needs https://github.com/tier4/autoware_launch.xx1/pull/534
Psim with `pilot-auto.xx1`.
Reduced delays when restarting.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidel …
=> feat(vehicle_cmd_gate): reduce delay

planning/behavior_path_planner/config/start_planner/start_planner.param.yaml, planning/behavior_path_planner/docs/behavior_path_planner_start_planner_design.md, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4151
https://github.com/autowarefoundation/autoware.universe/pull/4151
psim
none
none
=> feat(start_planner): add option for lane departure (#4151)

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_path.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/marker_util/lane_change/debug.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/utils.cpp
Fix and refactor of lane change functions.
- Safety check chattering
- Abort condition
- Object filtering
- Turn signal
launch PR:
https://github.com/tier4/autoware_launch.xx1/pull/540
Tested in real vehicle and planning simulator.
=> fix(behavior_path_planner): some fixes for lane change

planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp, planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4163
Hotfix to beta/v0.9.0
> This PR reduces the cost of running the dynamic drivable area expansion.
Currently, the calculations are very heavy and do not scale well with the number of "uncrossable lines".
This PR improves the performances but do not completely solve the scaling issue.
https://tier4.atlassian.net/browse/RT0-28451
> I checked the frequency of /planning/scenario_planning/lane_driving/behavior_planning/path_with_lane_id in the curved lane.
( I enabled dynamic_expansion and changed extra_footprint_offset from 0.5 to 3.0. )
On my PC (ThinkPad X1 Extreme Gen4), the frequency was 0.2Hz before PR merge, but it becomes >9.9Hz after PR merge.
none
This PR will fix [the …
=> perf(behavior_path_planner): simplify calculateDistanceLimit for dynamic drivable area expansion (#4163)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/utils.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4197
See https://github.com/autowarefoundation/autoware.universe/pull/4197
Nothing.
Bug fixed.
=> fix(behavior_path_planner): fix execution request condition 

planning/behavior_velocity_run_out_module/src/debug.cpp
Cherry pick bug fix for run out.
#4240
Tested on a simple planning simulator.
None.
=> fix(run_out): clear stop pose to prevent virtual wall from remaining

perception/elevation_map_loader/src/elevation_map_loader_node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4187 のbackport
以下の通りbackportが適用されていることを確認した
```
[component_container_mt-1] [INFO 1689293078.412637383] [perception.obstacle_segmentation.elevation_map.elevation_map_loader] onPointcloudMap(): subscribe pointcloud_map
[component_container_mt-1] [INFO 1689293078.460765760] [perception.obstacle_segmentation.elevation_map.elevation_map_loader] onVectorMap(): subscribe vector_map
[component_container_mt-1] [INFO 1689293078.477021059] 
[component_container_mt-1] [INFO 1689292962.307476140] [perception.obstacle_segmentation.elevation_map.elevation_map_loader] publish(): Load elevation map from: /home/hrkota/pilot-auto.x1.eve/install/elevation_map_loader/share/elevation_map_loader/data/elevation_maps/2da791365627241513c56a88a78baaf17d86b …
```
=> feat(elevation_map_loader): add error handling for std::runtime_error (backport #4187)

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
https://github.com/autowarefoundation/autoware.universe/pull/4283 のhotfix
[TIER IV COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2875)
=> fix(intersection): fix uninitialized tl_arrow_info variable issue (autowarefoundation#4283)

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
hotfix for https://github.com/autowarefoundation/autoware.universe/pull/4097
https://tier4.atlassian.net/browse/RT1-2847?focusedCommentId=128228
=> fix(intersection): do not plan if detection area is not empty and stop line idx is 0 (autowarefoundation#4097)

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4121
psim and scenario test in main
none
none
=> feat(start_planner): add offset to not finish before engage (autowarefoundation#4121)

planning/behavior_velocity_occlusion_spot_module/config/occlusion_spot.param.yaml
main branchにマージ済みのPRをcherry-pickする。
- https://github.com/autowarefoundation/autoware.universe/pull/4290
パラメータを追加する前に、Planning SimulatorやLogging Simulatorを立ち上げると、component_containerノードが死んでしまいます。
パラメータを追加後、ノードは落ちないことが確認できました。
=> fix(occlusion_spot): add lacking param (#4290)

common/tier4_traffic_light_rviz_plugin/README.md, common/tier4_traffic_light_rviz_plugin/package.xml, common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.cpp, common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.hpp, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, planning/behavior_velocity_crosswalk_module/package.xml, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp, planning/behavior_velocity_intersection_module/package.xml, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_planner/README.md, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/src/node.hpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/util.hpp, planning/behavior_velocity_planner_common/package.xml, planning/behavior_velocity_traffic_light_module/package.xml, planning/behavior_velocity_traffic_light_module/src/manager.cpp, planning/behavior_velocity_traffic_light_module/src/manager.hpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp, planning/behavior_velocity_traffic_light_module/src/scene.hpp, planning/planning_debug_tools/scripts/perception_reproducer.py, planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager.hpp, planning/planning_test_utils/package.xml
https://github.com/autowarefoundation/autoware.universe/pull/4133
Hotfix to beta/v0.10.0
> In this Pull Request, we are introducing support for the new traffic signal messages within the planning modules.
For more detailed information about the new messages, please refer to the associated issue linked below.
https://github.com/autowarefoundation/autoware.universe/issues/2567
https://github.com/tier4/autoware.universe/pull/677
Tested on a simple planning simulator.
> For the traffic light module, I have removed the old messages and variables previously used to manage inputs from either Perception or External sources, given that the External input is no longer used.
Moreover, since the input Traffic Signal message, processed by traffic_signal_arbiter, already contains the selected data …
=> feat(behavior_velocity): support new traffic signal interface

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml, perception/traffic_light_arbiter/launch/traffic_light_arbiter.launch.xml
> Previously, arguments were not passed from traffic_light.launch.xml to traffic_light_arbiter.launch.xml, causing some unexpected behavior.
With the changes in this PR, that problem has been solved. The system now works as expected.
https://github.com/autowarefoundation/autoware.universe/pull/4393
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/p …
=> fix(traffic_light): fix traffic_light_arbiter pipeline

common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.cpp
Fixed the output topic of traffic light RViz panel.
Related PR.
- https://github.com/autowarefoundation/autoware.universe/pull/4393
- https://github.com/tier4/autoware.universe/pull/689
=> chore: change output topic of traffic light RViz plugin

perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
Cherry pick bug fix of traffic_light_arbiter.
- https://github.com/autowarefoundation/autoware.universe/pull/4464
=> fix(traffic_light_arbiter): clear perception msg when the stamp is over the tolerance

launch/tier4_perception_launch/launch/perception.launch.xml, launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml, launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light_node_container.launch.py, launch/tier4_perception_launch/package.xml, perception/traffic_light_arbiter/launch/traffic_light_arbiter.launch.xml, perception/traffic_light_multi_camera_fusion/src/node.cpp
cherry-pick following PR to beta/v0.9.0
- https://github.com/autowarefoundation/autoware.universe/pull/4176
- https://github.com/autowarefoundation/autoware.universe/pull/4393
I confirmed necessary nodes are launched when [fusion_only](https://github.com/tier4/autoware.universe/pull/692/files#diff-8db88e79f00f5a189cca61139efce67e525831a19f94028a9420d34e30895287R53) is set to true.
```
❯ ros2 node list | grep traffic
/autoware_api/internal/traffic_signals
/awapi/nearest_traffic_signal_relay
/awapi/overwrite_traffic_signals_relay
/awapi/traffic_signal_relay
/perception/traffic_light_recognition/camera6/classification/traffic_light_occlusion_predictor
/perception/traffic_light_recognition/camera6/classification/transform_listener_impl_55df7cba5c08 …
```
=> chore(traffic_light): cherry pick traffic light launcher updates

common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.cpp, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
Merged this commit to fix the topic name of traffic singal.
- https://github.com/autowarefoundation/autoware.universe/pull/4133/commits/1f5cf31c4a3cda1ce7fc32b28a6cdf58667a6d07
The output topic of traffic light recognition was changed here.
- https://github.com/autowarefoundation/autoware.universe/pull/4393
related
- https://github.com/tier4/autoware.universe/pull/692 …
=> chore: update input topic of traffic signal in planning modules

launch/tier4_perception_launch/launch/perception.launch.xml, perception/traffic_light_arbiter/CMakeLists.txt, perception/traffic_light_arbiter/config/traffic_light_arbiter.param.yaml, perception/traffic_light_arbiter/launch/traffic_light_arbiter.launch.xml
cherry-pick adding of parameter file.
- https://github.com/autowarefoundation/autoware.universe/pull/4454
Please see https://github.com/autowarefoundation/autoware.universe/pull/4454
=> refactor(traffic_light_arbiter): read parameters from config file

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, perception/image_projection_based_fusion/CMakeLists.txt, perception/image_projection_based_fusion/config/pointpainting.param.yaml, perception/image_projection_based_fusion/config/roi_detected_object_fusion.param.yaml, perception/image_projection_based_fusion/docs/roi-detected-object-fusion.md, perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_detected_object_fusion/node.hpp, perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml, perception/image_projection_based_fusion/launch/roi_detected_object_fusion.launch.xml, perception/image_projection_based_fusion/package.xml, perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp, perception/image_projection_based_fusion/src/pointpainting_fusion/preprocess_kernel.cu, perception/image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp, perception/image_projection_based_fusion/src/utils/utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/4057
- https://github.com/autowarefoundation/autoware.universe/pull/4546
- https://github.com/autowarefoundation/autoware.universe/pull/4544
=> fix(image_projection_based_fusion, tier4_perception_launch): update camera-lidar-fusion based detection

perception/image_projection_based_fusion/src/fusion_node.cpp, perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp
Merge following PRs
- https://github.com/autowarefoundation/autoware.universe/pull/4572
- https://github.com/autowarefoundation/autoware.universe/pull/4570
- The code base had changed, so I made equivalent changes.
=> chore: fix to throttle log

planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/drivable_area_expansion.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/expansion.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/footprints.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/map_utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/types.hpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/footprints.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/map_utils.cpp, planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
This PR improves the dynamic drivable area expansion, making the bounds look cleaner, especially at the at the start and end of the path.
See https://github.com/autowarefoundation/autoware.universe/pull/4259
Psim
Evaluator: https://evaluation.tier4.jp/evaluation/reports/tables/new?project_id=x2_dev&job_id=727d6936-d9ae-5829-98ec-a0f489b09ba9&catalog_id=6888286a-35b1-4121-b322-0c6f0e3d8868&filter=&table_config=date
Prevent crashes when using the dynamic drivable area expansion. …
=> fix(behavior_path_planner): fix bad dynamic drivable area expansion at path extremities (#4259)

planning/behavior_velocity_intersection_module/CMakeLists.txt, planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/package.xml, planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
交差点自動化対応
https://github.com/autowarefoundation/autoware.universe/pull/4442
launcher: https://github.com/tier4/autoware_launch.xx1/pull/594
=> feat(intersection): extract occlusion contour as polygon (#4442)

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
交差点自動化対応
https://github.com/autowarefoundation/autoware.universe/pull/4466
launcher: https://github.com/tier4/autoware_launch.xx1/pull/595
=> feat(intersection_occlusion): ignore occlusion behind parked vehicles on the attention lane (#4466)

planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
The original motivation of skipping updateData() when module is not running is the other process were not necessary. 
But when `IDLE` status is introduced, condition of not runnnig module is changed from `running` to `running` || `idle`.
So in this PR, skip condition is changed.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …
=> fix(behavior_path_planner): fix side shift node die

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp, planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp, planning/behavior_path_planner/src/utils/goal_planner/util.cpp
cherry-pick and resolve conflict
https://github.com/autowarefoundation/autoware.universe/pull/4622 
https://tier4.atlassian.net/browse/RT1-3390
failed scenario test
```
webauto ci scenario run --project-id x2_dev --scenario-id 94ca41a5-67bf-427c-acc2-c2534195f8e7 --runtime-path . --scenario-parameters __tier4_modifier_ego_speed=2.7778,__tier4_modifier_inter_vehicular_distance=0,__tier4_modifier_npc_speed=2.7778,__tier4_modifier_spawntime=3,__tier4_modifier_prepare_time=1
```
https://github.com/tier4/autoware.universe/assets/39142679/350a119e-8722-484d-9b38-1f764fcf26be
please set enable_simultaneous_execution_as_approved_module: true in lanechange if using x2 branch
```
lane_change_left:
enable_module: true
enable_rtc: true
enable_simultaneous_execution_as_approved_module: true …
```
=> fix(behavior_path_planner): fix simultaneous execution

planning/planning_error_monitor/README.md, planning/planning_error_monitor/launch/planning_error_monitor.launch.xml
自動運転車両がクランク形状の車線で停車した場合に再発車できなくなる問題が発生した。
本PRはこの問題の対策実装である。
本問題の原因は、実運用のODDと設計での想定ODDとの不一致である。
経路計画には、通行が困難となる鋭角なカーブにおける発車を未然に防止する安全機構が備わっているが、
設計で想定される一般公道におけるODDと（特に工場内自動搬送における）実運用のODDとの間に乖離があるため、
物理的には通行可能なカーブにおいても安全機構の過剰反応により発車を阻害してしまう。
本PRでは上記安全機構におけるカーブの角度制約を適切な値に変更することで、工場内搬送における実運用において上記安全機構が適切に動作するように修正する。
本リポジトリは多種多様な車種での利用を想定している。
机上検討の結果、設定値を2.0 [rad]とすることで現時点弊社が想定する全ての車種へ適合可能であることが判明した。
（この値は https://github.com/tier4/autoware.universe/tree/tier4/main/planning/planning_validator#thresholds でも採用されている）
本PRではこの値を流用したうえで、実運用としての機能成立性を確認する。
https://tier4.atlassian.net/browse/AEAP-565
- 機能検証
実運用で利用されているクランクを含む地図にて、クランク中に停車し再発車出来る事を確認済み。
（Psim、サンプル数=10）
- リグレッション評価
　運用で通常想定されない通行困難なカーブにおいて任意の地点で停車した場合に再発車を防止できることを確認済み
　（PSim, サンプル数=10） 
The PR author **must** check the checkboxes …
=> feat(plannig_error_monitor): update error sharp angle threshold

perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
cherry pick bug fix
- https://github.com/autowarefoundation/autoware.universe/pull/4635
=> fix(traffic_light_arbiter): use the shape as a key to find the highest confidence signal

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
The lane change module can not know the final planned velocity, so the safety check in lane change may be broken.
This is the temporary fix for this issue.
**THIS CHANGE WILL BE REVERTED.**
Tested in real vehicle
Nothing.
The max lane change speed will be restricted to 40 km/h.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideline …
=> fix(behavior_path_planner): [TO BE REVERTED] set max velocity

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4632
Hotfix to beta/v0.10.0
> Refactored the `avoidance_module` to handle small gaps in shift lines more robustly. Modified the `trimSmallShiftLine` function in `avoidance_module.cpp` to merge adjacent shift lines instead of discarding them.
(TIER IV Internal https://evaluation.tier4.jp/evaluation/reports/5e54ef73-e07b-59eb-9a34-8e4dabc8bd70?project_id=prd_jt ) …
=> fix(avoidance): fix trimmed shift line alignment

planning/behavior_path_planner/src/planner_manager.cpp
=> fix(planner_manager): output total time

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
Disable internal traffic light signals
Confirmed it on an actual vehicle.
=> chore(tier4_perception_launch): disable internal traffic light signals

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp, common/tier4_autoware_utils/test/src/geometry/test_geometry.cpp, control/lane_departure_checker/README.md, control/lane_departure_checker/config/lane_departure_checker.param.yaml, control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
Add road boarder departure check
https://tier4.atlassian.net/browse/RT0-28542
https://tier4.atlassian.net/browse/RT1-3073
Confirmed on psim.
Not yet confirmed on actual vehicle.
=> feat(lane_departure_checker): add road boarder deparcher checker

perception/traffic_light_occlusion_predictor/src/nodelet.cpp
cherry-pick bug fix of occlusion predictor
Related
- https://github.com/autowarefoundation/autoware.universe/pull/4426
- [JIRA](https://tier4.atlassian.net/browse/RT0-28809)
=> fix(traffic_light_occlusion_predictor): bug fix (#4426)

perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp
>Fix a potential bug in compare_map_segmentation that could cause out-of-bounds access to a vector. Add a validity check for the index variable in voxel_grid_map_loader.hpp.
```
[component_container_mt-10] terminate called after throwing an instance of 'std::out_of_range'
[component_container_mt-10]   what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 320)
```
https://github.com/autowarefoundation/autoware.universe/pull/4676 …
=> fix(compare_map_segmentation): fix process died for invalid access #4676

planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp, planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
…ivable area into left and right bounds (#4646)
Merge the following PR for fixing drivable area expansion during lane change.
https://github.com/autowarefoundation/autoware.universe/pull/4646
https://tier4.atlassian.net/browse/RT0-28551
https://tier4.atlassian.net/browse/RT1-3461
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideli …
=> fix(behavior_path_planner): add fallback for splitting the dynamic drivable area into left and right bounds (autowarefoundation#4646)

planning/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp
> Add guard for preventing access to null current_pose_wrt_map.
(Fixed costmap_generator process dying when playing rosbag)
https://github.com/autowarefoundation/autoware.universe/pull/4696
=> fix(costmap_generator): prevent invalid access for current_pose (#4696)

planning/behavior_velocity_planner/include/scene_module/detection_area/scene.hpp, planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
https://github.com/autowarefoundation/autoware.universe/pull/405 を参考に
Detection Areaに紐づく停止線の挿入位置を間違えないようにするために
-  Detection AreaをRegulatory Elementとして持つlaneletのidを変数として保持
- Detection Areaの停止線と交差する経路位置の探索を、上記idのlanelet内に限定する
これにより、「1つのlaneletにおいて重複が発生し、かつ重複している場所にdetection_areaがある」の場合を除けば停止線の位置を間違えることはなくなる
図示すると以下の通り
https://tier4.atlassian.net/browse/AEAP-685
経路が重複する位置にdetection areaが設定されている地図においてAfterのとおりになることを確認した
Before: 
https://github.com/tier4/autoware.universe/assets/9547070/c2fb3348-7d62-45d6-950a-dcfac7b9dc70
After:
https://github.com/tier4/autoware.universe/assets/9547070/7571bb28-0c72-404b-8d60-3d87ef16cd78
The PR author **must** check …
=> fix(detection_area): search collision index only in lanelet

perception/map_based_prediction/config/map_based_prediction.param.yaml, perception/map_based_prediction/src/map_based_prediction_node.cpp
map_based_predictionのパラメタ定義周りのリファクタリングコミットを取り入れる。
https://github.com/autowarefoundation/autoware.universe/pull/4756
Buildしてノードの起動を確認
None
=> chore(map_based_prediction): prediction param to yaml

common/glog_component/CMakeLists.txt, common/glog_component/README.md, common/glog_component/include/glog_component/glog_component.hpp, common/glog_component/package.xml, common/glog_component/src/glog_component.cpp, launch/tier4_control_launch/launch/control.launch.py, launch/tier4_planning_launch/launch/mission_planning/mission_planning.launch.xml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py, launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml, launch/tier4_planning_launch/package.xml
glogの有効化。ノードが死んだときに自動でstack traceが印字されるので、解析が楽になります！
関連PR：
- https://github.com/autowarefoundation/autoware.universe/pull/4714
- https://github.com/autowarefoundation/autoware.universe/pull/4745
- https://github.com/autowarefoundation/autoware.universe/pull/4746
Now working:
ノードが死んだときに自動でstack traceが印字される
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contrib …
=> feat(launch): enable glog to print stack trace autonatically when the process die in planning/control modules

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp
走行している車両のyawがブレてbboxがブレる問題の修正hotfix
=> chore(multi_object_tracker): fix jerky object yaw

system/system_monitor/include/system_monitor/process_monitor/diag_task.hpp, system/system_monitor/src/process_monitor/process_monitor.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4553 のbackport
どんなコマンドが実行されているか、これまでは一部しか見れなかったが、詳細まで256字の範囲で見れるように修正する
https://tier4.atlassian.net/browse/AEAP-709
以下のコマンドを起動
`ros2 run system_monitor process_monitor`
別ターミナルで以下を起動
`ros2 run rqt_runtime_monitor rqt_runtime_monitor`
のように、COMMANDが途中まででなく、何が実行されているのか、解析に十分な詳細が見れることを確認した …
=> fix(system_monitor): extend command line to display (backport #4553)

system/system_error_monitor/config/diagnostic_aggregator/system.param.yaml, system/system_monitor/launch/system_monitor.launch.py
- NVMLのエラーにより、gpu_monitorが強制終了してしまうため、無効化する
- 無効化する対象は以下の通り
- gpu_monitorの起動
- disgnostics_aggregatorのgpuの記載。これをコメントアウトしないと、 `/autoware/system/resource_monitoring` にてgpuがstaleしてしまうため
https://tier4.atlassian.net/browse/AEAP-723
psimを起動し
- gpu_monitorが起動していないことを確認した
- `/autoware/system/resource_monitoring` がgpu_monitor起因でエラーとならないことを確認した …
=> fix(system_monitor): disable gpu_monitor

planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp
Add change from https://github.com/autowarefoundation/autoware.universe/pull/4198
Allows to set a buffer distance between the expanded drivable area and the linestrings to avoid.
=> fix(behavior_path_planner): use the avoid_linestring.distance param

system/system_monitor/src/process_monitor/process_monitor.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4654 のbackport
メモリを使用するプロセスのランキングを正しく出力する
https://tier4.atlassian.net/browse/AEAP-711
以下のコマンドを起動
`ros2 run system_monitor process_monitor`
以下のように、stress コマンドで予めメモリ負荷をかけておく
`stress --vm 2 --vm-bytes 2G` 
別ターミナルで以下を起動
`ros2 run rqt_runtime_monitor rqt_runtime_monitor`
メモリの使用量に応じてランク付けされていることを確認した …
=> fix(system_monitor): high-memory process are not provided in MEM order (backport #4654)

perception/traffic_light_multi_camera_fusion/include/traffic_light_multi_camera_fusion/node.hpp, perception/traffic_light_multi_camera_fusion/src/node.cpp
Fixed the bug that some stop lines might be ignored in traffic light recognition.
Related PR
- https://github.com/autowarefoundation/autoware.universe/pull/4727
Jira
- [TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-28838)
=> fix(traffic_light_multi_camera_fusion): assign multiple regulatory element id for one traffic light

planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
sorry for missing commit in  https://github.com/tier4/autoware.universe/pull/794 :bow: 
build failed 
https://evaluation.tier4.jp/evaluation/reports/883bda3a-6cd2-57d4-aef1-30b84aa356f1?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/a6d3fc2c-a215-515e-8d44-0f672a8cb9bb?project_id=prd_jt …
=> fix(start_planner): fix build

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
fix cherry-pick mistakes of https://github.com/tier4/autoware.universe/commit/eb134333639523cc1c74b23667998fbe5e93e212
build failed in
https://evaluation.tier4.jp/evaluation/reports/39b89374-45b2-5c16-b180-58e9ddfed30f?project_id=prd_jt
```
/home/autoware/autoware.proj/src/autoware/universe/planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp: In member function ‘tier4_autoware_utils::Polygon2d behavior_velocity_planner::CrosswalkModule::getAttentionArea(const PathWithLaneId&, const std::pair<double, double>&) const’:
/home/autoware/autoware.proj/src/autoware/universe/planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp:750:60: error: ‘p_ego_front’ was not declared in this scope
750 |     const auto ego_one_step_polygon = createOneStepPolygon(p_ego_front, …
```
=> fix(crosswalk): fix build

common/tier4_planning_rviz_plugin/include/path/display_base.hpp
rviz pluginでglobal parameterから取ってきたvehicle infoの値がパネルの値に反映されていなかった
https://star4.slack.com/archives/G015H42UVBK/p1694007269443579?thread_ts=1694005783.661109&cid=G015H42UVBK
https://tier4.atlassian.net/browse/RT0-29005
=> fix(tier4_planning_rviz_plugin): update vehicle info parameters in panel received from global parameter

perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/4870
=> chore(traffic_light_arbiter): use THROTTLE to prevent obscuring other logs (autowarefoundation#4870)

control/control_validator/src/utils.cpp
`[WARN 1694487074.997379606] [control.control_validator]: planning trajectory is too far from ego!! (operator()():201)` is shown too much unnecessarily.
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/4846
=> fix(control_validator): resolve the bug causing inappropriate diagnostic messages. (#4846)

simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp, simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py, simulator/simple_planning_simulator/package.xml, simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
https://tier4.atlassian.net/browse/RT0-29026
psimで勾配を考慮して加速度計算のシミュレーションをする機能を実装 (デフォルト無効化)
https://github.com/autowarefoundation/autoware.universe/pull/4941
以下の設定で↑のシミュレーションを有効化
https://github.com/tier4/j6_gen1_description/pull/6
=> feat(simple_planning_simulator): consider ego pitch angle for simulation

localization/ar_tag_based_localizer/src/tag_tf_caster_core.cpp, map/util/lanelet2_map_preprocessor/src/fix_lane_change_tags.cpp, perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
Cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/4819
autoware_common側の変更でビルドが通らなくなるので↑のhotfix
=> chore(build): include missing lanelet2 header (#4819)

planning/behavior_velocity_intersection_module/README.md, planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/docs/stuck-vehicle.drawio.svg, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
交差点のwallが勝手に消える問題の対策。
https://github.com/tier4/autoware_launch.xx1/pull/629
と同様
=> fix: suppress unintended permits at intersections

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/config/behavior_path_planner.param.yaml, planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp, planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp, planning/behavior_path_planner/test/test_safety_check.cpp
> 回避
回避キャンセルが過敏
[右折ルートスタート直後の回避](https://tieriv-fi.slack.com/archives/CEV8XMJBV/p1694400915778529?thread_ts=1694164812.546249&cid=CEV8XMJBV)
テレコムセンター前交差点右折後路駐車回避（[動画](https://tieriv-fi.slack.com/archives/CEV8XMJBV/p1694400915778529?thread_ts=1694164812.546249&cid=CEV8XMJBV) 4:06~）
[@Tomoya Kimura](https://star4.slack.com/team/USC6TAA78)
cc 
[@shiori kawata(OST)](https://star4.slack.com/team/U01D34V1AC8)
上記FBに対するコメントです。やっぱりv0.42.0.0と比較しても回避キャンセルが過敏になっていそうですね。場合によってはv0.43.1.0でcherry pickする予定だったhotfixを前倒しでv0.43.0.0に入れるのも検討してもいいのかもしれません。
https://star4.slack.com/archives/CEV8XMJBV/p1694565649818809?thread_ts=1694164812.546249&cid=CEV8XMJBV
The PR author …
=> feat(avoidance): safety check improvement

perception/map_based_prediction/src/path_generator.cpp
cherry-pick performance improvement of map_based_prediction.
- https://github.com/autowarefoundation/autoware.universe/pull/2883
Related discussion
- https://star4.slack.com/archives/C03N9GQ31LJ/p1694013028982309?thread_ts=1693786089.383419&cid=C03N9GQ31LJ
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …
=> perf(map_based_prediction): performance improvement of interpolateReferencePath with cumulative sum

planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
cherry pick the performance improvement of detection_area module.
- https://github.com/autowarefoundation/autoware.universe/pull/2846
=> perf(detection_area): point and polygon inclusion check by minimum enclosing circle (autowarefoundation#2846)

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
Hotfix: In order to properly connect the topics, remove unnecessary nodes.
https://star4.slack.com/archives/CTEJP8L4T/p1694625147360389?thread_ts=1694501199.212649&cid=CTEJP8L4T
Confirmed the prediction object is being output, using logging.simulator.launch in camera_lidar_fusion mode
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-gu …
=> fix(tier4_perception_launch): camera lidar fusion launch

common/motion_utils/src/resample/resample.cpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/4965
To suppress annoying messages.
see https://github.com/autowarefoundation/autoware.universe/pull/4965
see https://github.com/autowarefoundation/autoware.universe/pull/4965
=> fix(resample): remove duplicated point before resampling (#4965)

planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
start_planner dies due to an uninitialized value.
run psim and check if the node will not die
node will not die
=> fix(start_planner): uninitialized hysteresis_factor_expand_rate

planning/surround_obstacle_checker/config/surround_obstacle_checker.param.yaml, planning/surround_obstacle_checker/include/surround_obstacle_checker/debug_marker.hpp, planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp, planning/surround_obstacle_checker/src/debug_marker.cpp, planning/surround_obstacle_checker/src/node.cpp
https://tier4.atlassian.net/browse/RT0-29010
https://tier4.atlassian.net/browse/RT0-29017
surround obstacle checkerでobjectのlabelごとに、ego footprintのfront, side, backマージンを変更できるように修正
https://star4.slack.com/archives/C03QW0GU6P7/p1694059751441509?thread_ts=1694059532.809519&cid=C03QW0GU6P7
実際のパラメータ変更はこちら
https://github.com/tier4/autoware_launch.x2/pull/411
=> feat(surround_obstacle_checker): make parameters more tunable (#4925)

planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml, planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md, planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/freespace_pull_out.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/geometric_pull_out.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/pull_out_planner_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/shift_pull_out.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp, planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp, planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp, planning/behavior_path_planner/src/utils/goal_planner/freespace_pull_over.cpp, planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp, planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp, planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp, planning/behavior_path_planner/src/utils/goal_planner/util.cpp, planning/behavior_path_planner/src/utils/start_planner/freespace_pull_out.cpp, planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp, planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp, planning/behavior_path_planner/src/utils/utils.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
- drivable areaが歪む問題修正
- レーンをはみ出してもstart planner起動
- fixed goal plannerはcurrent lanesにgoalを含むようになったら起動
- start plannerで経路開始点が少しegoからずれる問題を修正
- start plannerでbackward pathがレーンからはみ出した部分はcrop
https://github.com/tier4/autoware_launch.xx1/pull/636
https://evaluation.tier4.jp/evaluation/oidc/auth/cb/?code=ory_ac_N1b6veealaL9tA9-5ozIEizBFJr78RZR4M9dv1fHqdY.HzrRWlsYFz30fJBQM6iqf_6ixJpg8wquCXCU4KxMZ9Y&scope=openid+profile+email+offline_access&state=fbcb8cf47b4f41e78b06062d405201ec
1832/1845
psim
[contribution …
=> feat: update start goal planner v0.10.1

planning/behavior_path_planner/config/scene_module_manager.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/planner_manager.cpp
* feat(interface): add new option last_keep
* feat(planner_manager): keep last module
* update param config
---------
cerry-pick https://github.com/autowarefoundation/autoware_launch/pull/543
psim
https://github.com/tier4/autoware.universe/assets/39142679/e97d5a84-3b18-4685-9bd4-fd5839931465
https://evaluation.tier4.jp/evaluation/reports/2c16c238-f411-507b-b525-9e5c41c82547?project_id=prd_jt
1833/1845 …
=> feat(interface): add new option `last_keep` (#4811)

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml, planning/behavior_path_planner/config/behavior_path_planner.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/1604 のbackport
- https://tier4.atlassian.net/browse/AEAP-661
で起きている問題を改善するため、behavior_pathの経路出力のタイミングで、spline補間を実施するようにする
- 以下PRと一緒に確認する
https://github.com/tier4/autoware_launch.x1.eve/pull/422
https://tier4.atlassian.net/browse/AEAP-661
https://tier4.atlassian.net/browse/AEAP-661 の「対策」欄にて効果確認した結果を記載している …
=> feat(behavior_path_planner): resample output path (backport #1604)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
* feat(behavior_path_planner): add always executable module option
* fix conditions
* rename itr
* Update planning/behavior_path_planner/src/planner_manager.cpp
* Update planning/behavior_path_planner/src/planner_manager.cpp
* Update planning/behavior_path_planner/src/planner_manager.cpp
* fix candidate break
* Revert "fix candidate break"
This reverts commit 0071bbdd8aa4d510a67f6d9bc32e23716f7aa416.
* remove continue
* check manager_ptr->isAlwaysExecutableModule first
* common similar process
* fix getRequestModules
---------
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4785
psim with this branch
The PR …
=> feat(behavior_path_planner): add always executable module option (#4785)

common/motion_utils/include/motion_utils/marker/marker_helper.hpp, common/motion_utils/include/motion_utils/marker/virtual_wall_marker_creator.hpp, common/motion_utils/src/marker/marker_helper.cpp, common/motion_utils/src/marker/virtual_wall_marker_creator.cpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/planner_interface.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/5031
- https://github.com/autowarefoundation/autoware.universe/pull/5028
psim in main
building now
none
none
=> fix(obstacle_cruise_planner): fix stop against objects after backward trajectory terminal 

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml, planning/behavior_path_planner/config/start_planner/start_planner.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/geometric_parallel_parking/geometric_parallel_parking.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/pull_over_planner_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/objects_filtering.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_goal_planner_common/common_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_goal_planner_common/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/pull_out_path.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/util.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp, planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp, planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp, planning/behavior_path_planner/src/utils/goal_planner/freespace_pull_over.cpp, planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp, planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp, planning/behavior_path_planner/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/src/utils/path_utils.cpp, planning/behavior_path_planner/src/utils/start_goal_planner_common/utils.cpp, planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp, planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
[PR](https://github.com/tier4/autoware_launch.xx1/pull/641) to launcher should be merged first 
cherry-pick below PRs
https://github.com/autowarefoundation/autoware.universe/pull/4691
https://github.com/autowarefoundation/autoware.universe/pull/4669
https://github.com/autowarefoundation/autoware.universe/pull/4742
https://github.com/autowarefoundation/autoware.universe/pull/4804
https://github.com/autowarefoundation/autoware.universe/pull/4859
https://github.com/autowarefoundation/autoware.universe/pull/4873
https://github.com/autowarefoundation/autoware.universe/pull/4953
https://github.com/autowarefoundation/autoware.universe/pull/5002
The PR reviewers **must** check the checkboxes …
=> Feat/sugahara/update start goal planner v0.10.1 2

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
* feat(route_handler): add function to get closest preferred lanelet
* perf(planner_manager): remove module immediately once its status is success
---------
cherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/4458
psim
=> perf(planner_manger): remove lifo limitation (#4458)

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp, planning/behavior_path_planner/src/utils/utils.cpp
https://tier4.atlassian.net/browse/RT1-3023 の修正
https://github.com/autowarefoundation/autoware.universe/pull/4467 
https://github.com/autowarefoundation/autoware.universe/pull/4706 
https://github.com/autowarefoundation/autoware.universe/pull/5029
https://github.com/autowarefoundation/autoware.universe/pull/5051
launcher: https://github.com/tier4/autoware_launch.xx1/pull/644
https://evaluation.tier4.jp/evaluation/reports/6c890f29-9310-5bb5-b6bb-44fc19d44d7e?project_id=prd_jt
psim …
=> feat(avoidance): imporove avoidance near goal

planning/behavior_path_planner/config/drivable_area_expansion.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/drivable_area_expansion.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/footprints.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/replan_checker.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/types.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/footprints.cpp, planning/behavior_path_planner/src/utils/utils.cpp, planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
以下を解決
https://tier4.atlassian.net/browse/RT1-3504
& drivable area expansionの安定化
launcher PR: https://github.com/tier4/autoware_launch.x2/pull/442
https://github.com/tier4/autoware.universe/pull/844 からdrivable area expansionを抽出
- https://github.com/autowarefoundation/autoware.universe/pull/4710
- https://github.com/autowarefoundation/autoware.universe/pull/4677
- https://github.com/autowarefoundation/autoware.universe/pull/4738 …
=> fix(drivable_area_expansion): stabler expansion

control/mpc_lateral_controller/include/mpc_lateral_controller/mpc_lateral_controller.hpp, control/mpc_lateral_controller/src/mpc_lateral_controller.cpp
(記録用にPR出してます)
実験用に,
$ros2 topic pub /debug_control tier4_debug_msgs/Float32MultiArrayStamped "{stamp: now, data: [0.5, -0.2]}" -1 
で強制的にステアのコントロールを奪うデバッグトピックを追加しました。
一項目が秒数 (< 2.0s), 二項目がステア値(<0.4rad)です。
(mainにはマージしません)
Psimで確認済
https://github.com/tier4/autoware.universe/assets/59680180/afe9dbe8-826b-4af5-b7ec-21bce59ed529 …
=> tmp: add mpc steer intervention topic

.github/workflows/dispatch-push-event.yaml
#803 のbackport PRです。mainブランチにワークフローがあっても、beta/v0.3.17での変更でActionがトリガーされないため、こちらにも取り込みます。
=> ci: backport dispatch-push-event workflow to v0.3.17

planning/behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_crosswalk_module/src/manager.hpp, planning/behavior_velocity_walkway_module/src/manager.cpp, planning/behavior_velocity_walkway_module/src/manager.hpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5129
塩尻の地図で、walkwayでcrosswalkの機能が働かない (= ただ一時停止するだけで歩行者には反応しない) 不具合修正
=> fix(crosswalk): fix module launch condition

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/objects_filtering.hpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/src/utils/utils.cpp
https://tier4.atlassian.net/browse/RT0-29049
を解決
以下をcherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/5035 (コンフリクト解決のため)
https://github.com/autowarefoundation/autoware.universe/pull/5068 (横断歩道でLCしない)
=> feat(lane_change): not execute LC on crosswalk

control/pid_longitudinal_controller/include/pid_longitudinal_controller/longitudinal_controller_utils.hpp, control/pid_longitudinal_controller/include/pid_longitudinal_controller/pid_longitudinal_controller.hpp, control/pid_longitudinal_controller/src/longitudinal_controller_utils.cpp, control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp, control/pid_longitudinal_controller/test/test_longitudinal_controller_utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/5090 (無視してOK)
- https://github.com/autowarefoundation/autoware.universe/pull/5092 (無視してOK)
- https://github.com/autowarefoundation/autoware.universe/pull/5093 
- velocity controllerのstateが手動走行中にemergencyになった際、一時停止せずにdriveに移行できるように変更 (自動運転中は今までどおり一時停止必須)
- https://github.com/autowarefoundation/autoware.universe/pull/5094
- ずり下がり時に現在車速が正になる不具合の修正
- https://tier4.atlassian.net/browse/RT0-29231 を解決
- https://github.com/autowarefoundation/autoware.universe/pull/5095 (無視してOK)
After all checkboxes …
=> feat(pid_longitudinal_controller): several bug fix

common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
https://github.com/autowarefoundation/autoware.universe/pull/5089
=> fix(autoware_auto_tf2): remove tf2 geometry function duplicated in tf2 geometry msgs

common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
2023-09-27時点のHumble Syncにおいて、ビルドが通らなくなっている
https://github.com/autowarefoundation/autoware.universe/pull/5089 を参考に修正が必要な場所をpickした
https://star4.slack.com/archives/C04CKSQ7ZFZ/p1695796136636259
以下のビルドエラーが解消されていることを確認した
```
Starting >>> autoware_auto_tf2
Finished <<< autoware_auto_vehicle_msgs [13.4s]                                                                        
--- stderr: autoware_auto_tf2                                
In file included from /home/hrkota/pilot-auto.x1.eve/src/autoware/universe/common/autoware_auto_tf2/test/test_tf2_autoware_auto_msgs.cpp:22:
/home/hrkota/pilot-auto.x1.eve/src/autoware/universe/common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp:55:6: error: redefinition of ‘void tf2::doTransform(const T&, T&, const TransformStamped&) …
```
=> fix(autoware_auto_tf2): remove tf2 geometry function duplicated in tf2 geometry msgs (backport #5089)

system/ad_service_state_monitor/config/ad_service_state_monitor.param.yaml
ad_service_monitorのmodule名を修正
topic名と異なるものがあるため、同一に修正
https://tier4.atlassian.net/browse/AEAP-764
https://github.com/tier4/autoware_launch.x1.eve/pull/428
9/11で実車での確認済
system_error_monitorでのmodule設定がsensing系からperception系に変更されます。
=> feat(ad_service_state_monitor): change configs name

common/autoware_auto_geometry/CMakeLists.txt, common/autoware_auto_tf2/CMakeLists.txt, common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp, planning/behavior_path_planner/CMakeLists.txt, planning/surround_obstacle_checker/CMakeLists.txt
最近tf2_gemotryの更新の影響で、ビルドが通らない問題が発生している。
(https://github.com/autowarefoundation/autoware.universe/issues/5128)
自機環境でsudo apt upgradeをしてから、該当問題が発生することを確認できた。
既に、autowarefoundationの方が以下2つのPRを取り込んでいます。こちらでbeta/v0.11.0へcherry-pickする。
https://github.com/autowarefoundation/autoware.universe/pull/5127
https://github.com/autowarefoundation/autoware.universe/pull/5089
=> fix(autoware_auto_tf2): remove duplicated function in tf2_geometry_msg

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py, sensing/pointcloud_preprocessor/docs/concatenate-data.md, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_nodelet.hpp, sensing/pointcloud_preprocessor/launch/preprocessor.launch.py, sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
Fix a bug in concatenate_filter. 
Cherry-picked from: https://github.com/autowarefoundation/autoware.universe/pull/5125
To address: https://tier4.atlassian.net/browse/RT0-29158
Which is validated in: https://tier4.atlassian.net/wiki/spaces/MiS/pages/2881388553
=> fix(pointcloud_preprocessor): organize input twist topic (#5125)

sensing/imu_corrector/CMakeLists.txt, sensing/imu_corrector/README.md, sensing/imu_corrector/config/gyro_bias_estimator.param.yaml, sensing/imu_corrector/launch/gyro_bias_estimator.launch.xml, sensing/imu_corrector/package.xml, sensing/imu_corrector/src/gyro_bias_estimation_module.cpp, sensing/imu_corrector/src/gyro_bias_estimation_module.hpp, sensing/imu_corrector/src/gyro_bias_estimator.cpp, sensing/imu_corrector/src/gyro_bias_estimator.hpp, sensing/imu_corrector/src/imu_corrector_core.cpp, sensing/imu_corrector/src/imu_corrector_core.hpp, sensing/imu_corrector/test/test_gyro_bias_estimation_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4729 のbackport
手元の環境で
https://github.com/autowarefoundation/autoware.universe/pull/4980
も合わせて取り込まないとBuildができなかったためこちらも合わせて取り込んだ
diagの値の表示できるようにする
https://github.com/autowarefoundation/autoware.universe/pull/5054
も更新(tier4 syncに時間がかかるため、追加commitをbackport）
launchに関しては
https://github.com/tier4/aip_launcher.x1.eve/pull/43
で対応
https://github.com/tier4/aip_launcher.x1.eve/pull/43
https://tier4.atlassian.net/browse/AEAP-746
となり、diagnosticsとして出ていることは確認
Lsimでv1'のデータを再生して
と表示されることを確認しました
また実機のIMUでも
が表示されることまでは確認済
rqt_publisherで
/localization/twist_estimator/vehicle_velocity_converter/twist_with_covariance
に現在時刻の
stamp
sec now().sec
nanosec now().nanosec
で送り込むと
下記のように流れると
下記画像のように数値確認までは済
system_error_monitorの追加はこちらで取り込まれます …
=> feat(imu_corrector): add gyro_bias_validator (backport #4729)

launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml, perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml, perception/lidar_centerpoint/launch/centerpoint_vs_centerpoint-tiny/centerpoint_vs_centerpoint-tiny.launch.xml, perception/lidar_centerpoint/launch/lidar_centerpoint.launch.xml, perception/lidar_centerpoint/launch/single_inference_lidar_centerpoint.launch.xml, perception/tensorrt_yolo/README.md, perception/tensorrt_yolo/launch/tensorrt_yolo.launch.xml, perception/tensorrt_yolox/README.md, perception/tensorrt_yolox/launch/yolox_s_plus_opt.launch.xml, perception/tensorrt_yolox/launch/yolox_tiny.launch.xml, perception/traffic_light_classifier/README.md, perception/traffic_light_classifier/launch/traffic_light_classifier.launch.xml, perception/traffic_light_fine_detector/README.md, perception/traffic_light_fine_detector/launch/traffic_light_fine_detector.launch.xml, perception/traffic_light_ssd_fine_detector/README.md, perception/traffic_light_ssd_fine_detector/launch/traffic_light_ssd_fine_detector.launch.xml
Hotfix: Fix model paths used in ML packages
cherry-pick PRs below
https://github.com/autowarefoundation/autoware.universe/pull/5069
https://github.com/autowarefoundation/autoware.universe/pull/5118
https://github.com/autowarefoundation/autoware.universe/pull/5119
https://github.com/autowarefoundation/autoware.universe/pull/5141
https://github.com/autowarefoundation/autoware.universe/pull/5144
https://github.com/autowarefoundation/autoware.universe/pull/5158
https://github.com/autowarefoundation/autoware.universe/pull/5162
https://github.com/autowarefoundation/autoware.universe/pull/5163
The PR author **must** check the checkboxes below before …
=> fix: ml model path

system/system_error_monitor/config/system_error_monitor.param.yaml, system/system_error_monitor/config/system_error_monitor.planning_simulation.param.yaml, system/system_error_monitor/include/system_error_monitor/system_error_monitor_core.hpp, system/system_error_monitor/src/system_error_monitor_core.cpp
初期化中やwait for route中に不要なdiagがtimeoutのerror_diagになっている状態を無効化する関数を追加
configで
before_planning_control_ignore: "true"にすることでspf->nfに変更する。
defaultについてはfalseに設定しています。
configの追加のためlaunchと同時にマージをする必要があります。
https://tier4.atlassian.net/browse/AEAP-763
https://github.com/tier4/autoware_launch.x1.eve/pull/431
Psimでwait for routeのときにplanning,controlのtimeoutが出ていないことを確認した。 …
=> feat(system_error_monitor): add ignore_until_waiting_for_route module

planning/behavior_velocity_out_of_lane_module/src/decisions.cpp, planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.hpp
Cherry pick https://github.com/autowarefoundation/autoware.universe/pull/5145
Psim
Less debug messages from the `behavior_velocity_planner` .
=> fix(out_of_lane): reduce "Same Points are given" messages

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/package.xml, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp
右折時にwalkwayでの停止がある場合はそれを見越してintersectionで停止する機能
https://tier4.atlassian.net/browse/RT0-29263 のチケットに対応
prediction時間を伸ばせば
- https://tier4.atlassian.net/browse/RT0-29263
- https://tier4.atlassian.net/browse/RT0-29263
でORがなくなることが期待される
launcher PR: https://github.com/tier4/autoware_launch.x2/pull/459
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull …
=> feat(intersection): use planned velocity from upstream modules (#5156)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
fix(lane_change): skip parked object filtering
https://github.com/autowarefoundation/autoware.universe/pull/4868
feat(behavior_path_planner): add virtual stop wall for lane change
https://github.com/autowarefoundation/autoware.universe/pull/4808
lane change stop wall will be shown.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …
=> feat(behavior_path_planner): add virtual stop wall for lane change

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/5105
Please merge https://github.com/tier4/autoware.universe/pull/869 and https://github.com/tier4/autoware.universe/pull/872 first.
=> feat(lane_change): enable lane change in crosswalk/intersection if ego vehicle gets stuck

perception/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/cluster2d.hpp, perception/lidar_apollo_instance_segmentation/src/cluster2d.cpp, perception/lidar_apollo_segmentation_tvm/include/lidar_apollo_segmentation_tvm/cluster2d.hpp, perception/lidar_apollo_segmentation_tvm/src/cluster2d.cpp, perception/radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp, perception/radar_object_tracker/src/tracker/model/linear_motion_tracker.cpp, perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/4992/
- https://github.com/autowarefoundation/autoware.universe/pull/4993/
- https://github.com/autowarefoundation/autoware.universe/pull/4987/
- https://github.com/autowarefoundation/autoware.universe/pull/5024 …
=> fix(radar_detection): radar detection bugs

planning/behavior_path_planner/src/utils/avoidance/utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/4874
module outputs avoidance path for unintentional objects.
https://github.com/tier4/autoware.universe/assets/44889564/e155b074-91a3-4873-97d6-3780e049d893
=> fix(avoidance): use find nearest index to calculate object's overhang & longitudinal (#4874)

perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/map_based_prediction/src/map_based_prediction_node.cpp
Cherrypicking: https://github.com/autowarefoundation/autoware.universe/pull/5195
To resolve: https://tier4.atlassian.net/browse/RT0-29313
To be done
As stated in the original PR in awf
=> fix(map_based_prediction): filter by distance for opposite lanes as well (#5195)

perception/crosswalk_traffic_light_estimator/src/node.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
cherry-pick following PRs
- https://github.com/autowarefoundation/autoware.universe/pull/5168
- https://github.com/autowarefoundation/autoware.universe/pull/5169
This fixes the bug that crosswalk module doesn't ignore the red pedestrian light.
Related ticket:
[TEIR IV INTERNAL](https://tier4.atlassian.net/browse/RT0-29271)
See https://github.com/autowarefoundation/autoware.universe/pull/5169
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …
=> fix: crosswalk pedestrian lights

planning/obstacle_cruise_planner/src/node.cpp
hotfix PR of 
https://github.com/autowarefoundation/autoware.universe/pull/5180
https://tier4.atlassian.net/browse/RT0-29266
local build was completed in success
bug fixed
=> fix(obstacle_cruise_planner): fix coordinate transformation bag (#5180)

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
depends https://github.com/tier4/autoware.universe/pull/910
launcherのPR: https://github.com/tier4/autoware_launch.xx1/pull/652
https://github.com/autowarefoundation/autoware.universe/pull/5047
対向車線に車両先頭が入る前に必ず一時停止する機能（フラグ）
=> feat(intersection): ensure temporal stop before peeking into oncoming lane

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
depends: https://github.com/tier4/autoware.universe/pull/913
launcher: https://github.com/tier4/autoware_launch.xx1/pull/654
https://github.com/autowarefoundation/autoware.universe/pull/5223
湾曲したレーンでは死角検知しない機能
=> feat(intersection): ignore high curvature lane occlusion

sensing/imu_corrector/src/gyro_bias_estimator.cpp
sfなどでsyslogに数値などが残らないため、gyro_bias_estimator側にwarnのlogを追加する。
https://tier4.atlassian.net/browse/AEAP-746
=> feat(imu_corrector): add gyro bias log

planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp
This PR add a guards for when the boost::geometry::buffer function returns an empty set of polygons.
Prevents some crashes of the behavior_path_planner.
=> fix(behavior_path_planner): prevent crashes with the drivable area expansion

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/marker_utils/lane_change/debug.hpp, planning/behavior_path_planner/include/behavior_path_planner/marker_utils/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/src/marker_utils/lane_change/debug.cpp, planning/behavior_path_planner/src/marker_utils/utils.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
Cherry-picking lane change commits.
[fix(lane_change): fix target object filter #4930](https://github.com/autowarefoundation/autoware.universe/pull/4930)
[fix(lane_change): object filter other lane object #5083](https://github.com/autowarefoundation/autoware.universe/pull/5083)
[feat(lane_change): expand target lanes for object filtering #5167](https://github.com/autowarefoundation/autoware.universe/pull/5167)
[feat(behavior_path_planner): lane change collided polygon intersect lanes #5135](https://github.com/autowarefoundation/autoware.universe/pull/5135)
[feat(lane_change): object filter visualization #5082](https://github.com/autowarefoundation/autoware.universe/pull/5082)
[fix(lane_change): current lane obj treated as target lane obj …
=> fix(lane_change): cherry pick lane change PRs for x2

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
don't consider margin when stop line is found
PR:https://github.com/autowarefoundation/autoware.universe/pull/5231
チケット:https://tier4.atlassian.net/browse/RT0-29264
perception reproducerで動作確認済み
[Screencast from 2023年10月05日 14時52分43秒.webm](https://github.com/tier4/autoware.universe/assets/32741405/83231f8a-623f-4eec-8cdc-57a785ca07c8) …
=> fix(behavior_velocity_crosswalk_module): stop at stop line associated with crosswalk

launch/tier4_perception_launch/launch/object_recognition/detection/radar_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml
Fixing node order in radar_based_detection.launch to reduce calculation cost.
https://github.com/autowarefoundation/autoware.universe/pull/5233
Tests by rosbag
=> fix(tier4_perception_launch): fix faraway detection to reduce calculation cost

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
https://github.com/tier4/autoware.universe/pull/782 において、behavior_pathの出力経路をspline補間するように修正したが、turn_signalの処理はspline補間を実施しないのが前提のロジックとなってしまっっているため、チャタリングする問題が発生していた
そこで、spline補間する対象をbehavior_pathの出力経路に限定し、turn_signalの処理にはspline補間をしない経路を与えるかたちに修正する
https://tier4.atlassian.net/browse/AEAP-768
AEAP-768で問題が出ている箇所を走行し、turn_signalがチャタリングしないことを確認した …
=> fix(behavior_path): only apply spline interpolation for its output, not for turn_signal processing

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
https://tier4.atlassian.net/browse/RT0-29407
cherry pick following two PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/4899
- https://github.com/autowarefoundation/autoware.universe/pull/5051
---
Before this PR, since unfeasible (measingless) avoidance path whose shift length is 0.0[m] was output from avoidance module, sometimes the vehicle stucked in front of the objects. In this case, rtc interface doesn't send any avoidance cooperate status.
After this PR, avoidance module never outputs unfeasible path. Additionaly, if it is not possible to avoid object, the avoidance module doesn't insert stop point in order to prevent stuck.
Test with perception reproducer + [rosbag](https://console.data-search.tier4.jp/projects/x2_dev/environments/c032962a-c7ce-4ae1-896c-72af73733 …
=> fix(avoidance): cherry pick PRs for avoidance issue

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/5266
- https://github.com/autowarefoundation/autoware.universe/pull/5267
https://tier4.atlassian.net/browse/RT0-29368
=> fix(avoidance): prevent endless planning loop in behavior path planner

planning/behavior_path_planner/src/planner_manager.cpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/common_structs.hpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/type_alias.hpp, planning/obstacle_avoidance_planner/src/node.cpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp, planning/obstacle_stop_planner/src/node.cpp, planning/path_smoother/include/path_smoother/common_structs.hpp, planning/path_smoother/include/path_smoother/elastic_band_smoother.hpp, planning/path_smoother/include/path_smoother/type_alias.hpp, planning/path_smoother/src/elastic_band_smoother.cpp, planning/planning_validator/include/planning_validator/planning_validator.hpp, planning/planning_validator/src/planning_validator.cpp
Cherry-pick PRs for processing_time publication
https://github.com/autowarefoundation/autoware.universe/pull/5273
https://github.com/autowarefoundation/autoware.universe/pull/5274
https://github.com/autowarefoundation/autoware.universe/pull/5276
https://github.com/autowarefoundation/autoware.universe/pull/5279
https://github.com/autowarefoundation/autoware.universe/pull/5278
https://github.com/autowarefoundation/autoware.universe/pull/5281
run sim
processing time topics will be published by default …
=> refactor(planning_modules): publish processing time topics

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp
INTERNAL LINK: https://tier4.atlassian.net/browse/RT0-29472
MERGED WITH: https://github.com/tier4/autoware_launch.x2/pull/492
=> feat(avoidance): add feature to guard unfeasible path

planning/behavior_path_planner/src/utilities.cpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp, planning/obstacle_avoidance_planner/src/node.cpp, planning/obstacle_stop_planner/src/node.cpp
ゴールよりもスタート位置を先に設定した場合など、経路が明らかにおかしな結果となった場合にノードが落ちる問題を修正
https://tier4.atlassian.net/browse/AEAP-773
動画のようにゴールに対してめちゃくちゃに設定した場合にノード落ちが発生しないことを確認した
https://github.com/tier4/autoware.universe/assets/9547070/8c7fe670-e6ce-4561-98fe-5705b4876655
https://tier4.atlassian.net/browse/AEAP-773
ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$HOME/map/ryuyo/courseZ/ pointcloud_map_file:=0.10_nashi_soto_removed_20220105.pcd localization:=false planning:=true control:=false perception:=true sensing:=true system:=false vehicle_id:=eva_j4j1-0028 sensor_model:=aip_x1
を再生してノードが死なないことを確認した）
The PR author **must** check the checkboxes below before …
=> fix: add error handling when path is invalid

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/polygon_utils.hpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/polygon_utils.cpp
hotfix of https://github.com/autowarefoundation/autoware.universe/pull/5036
https://star4.slack.com/archives/C022RLPU1PZ/p1697016552543899?thread_ts=1696573047.550449&cid=C022RLPU1PZ
* feat: add the feature to consider the current ego position
* feat: add ego pose consideration. Both the lateral error and the yaw error are assumed to decrease to zero by a specified constant time (e.g 1.5 second).
* feat: (continue) implement parameter settings for "cosider-current-ego-pose"
* cleaned up the code
* change description of the parameters
* align format
* Update planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
* Update planning/obstacle_cruise_planner/src/node.cpp
---------
**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-doc …
=> feat(obstacle_cruise_planner)!: add ego pose consideration (#5036)

planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/path_utils.cpp
prevent node from dying for trimmed shifted path
https://github.com/autowarefoundation/autoware.universe/pull/5271
See https://github.com/autowarefoundation/autoware.universe/pull/5271
=> fix(lane_change): prevent node from dying for trimmed shifted path (#5271)

planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp
fix(lane_change): add visualization for passParkedObject https://github.com/autowarefoundation/autoware.universe/pull/5291
fix(lane_change): fix force path not appear https://github.com/autowarefoundation/autoware.universe/pull/5288
See above PRs
Not applicable
Not applicable …
=> fix(lane_change): add visualization for passParkedObject

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
https://tier4.atlassian.net/browse/RT0-29412
https://tier4.atlassian.net/browse/RT0-29455
cherry-pick of
- https://github.com/autowarefoundation/autoware.universe/pull/5268
- https://github.com/autowarefoundation/autoware.universe/pull/5265
- https://github.com/autowarefoundation/autoware.universe/pull/5277
- https://github.com/autowarefoundation/autoware.universe/pull/5264
- https://github.com/autowarefoundation/autoware.universe/pull/5280 …
=> feat(intersection): cherry-pick latest changes

control/mpc_lateral_controller/src/qp_solver/qp_solver_osqp.cpp, control/mpc_lateral_controller/test/test_mpc.cpp
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/4673
Psim
MPC will not stop for polish failure.
=> fix(mpc): use optimization result when polish failed (#4673)

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_radar_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/radar_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml, perception/object_merger/include/object_association_merger/node.hpp, perception/object_merger/launch/object_association_merger.launch.xml, perception/object_merger/src/object_association_merger/node.cpp, perception/radar_fusion_to_detected_object/src/radar_object_fusion_to_detected_object_node/radar_object_fusion_to_detected_object_node.cpp, perception/simple_object_merger/src/simple_object_merger_node/simple_object_merger_node.cpp
**Radar遠距離出力を対応①**
X2塩尻で田中さんが導入したdetectionベースの`camera_lidar_radar_fusion`の実装PRになります。
事前に https://github.com/tier4/autoware_launch.xx1/pull/667 の変更が取り込まれていることを確認してください。
Merge radar far detection related PRs.
- https://github.com/autowarefoundation/autoware.universe/pull/4779
- https://github.com/autowarefoundation/autoware.universe/pull/4780
- https://github.com/autowarefoundation/autoware.universe/pull/4837
- https://github.com/autowarefoundation/autoware.universe/pull/4990
- https://github.com/autowarefoundation/autoware.universe/pull/4992
- https://github.com/autowarefoundation/autoware.universe/pull/4993
- https://github.com/autowarefoundation/autoware.universe/pull/4994
- https://github.com/autowarefoundation/autoware.universe/pull/5026
- …
=> feat: add radar far detection pipeline

perception/tracking_object_merger/CMakeLists.txt, perception/tracking_object_merger/README.md, perception/tracking_object_merger/config/data_association_matrix.param.yaml, perception/tracking_object_merger/config/decorative_tracker_merger.param.yaml, perception/tracking_object_merger/config/decorative_tracker_merger_policy.param.yaml, perception/tracking_object_merger/image/decorative_tracker_merger.drawio.svg, perception/tracking_object_merger/image/time_sync.drawio.svg, perception/tracking_object_merger/image/tracklet_management.drawio.svg, perception/tracking_object_merger/include/tracking_object_merger/data_association/data_association.hpp, perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/gnn_solver.hpp, perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/gnn_solver_interface.hpp, perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/mu_successive_shortest_path.hpp, perception/tracking_object_merger/include/tracking_object_merger/data_association/solver/successive_shortest_path.hpp, perception/tracking_object_merger/include/tracking_object_merger/decorative_tracker_merger.hpp, perception/tracking_object_merger/include/tracking_object_merger/utils/tracker_state.hpp, perception/tracking_object_merger/include/tracking_object_merger/utils/utils.hpp, perception/tracking_object_merger/launch/decorative_tracker_merger.launch.xml, perception/tracking_object_merger/package.xml, perception/tracking_object_merger/src/data_association/data_association.cpp, perception/tracking_object_merger/src/data_association/mu_successive_shortest_path/mu_successive_shortest_path_wrapper.cpp, perception/tracking_object_merger/src/data_association/successive_shortest_path/successive_shortest_path.cpp, perception/tracking_object_merger/src/decorative_tracker_merger.cpp, perception/tracking_object_merger/src/utils/tracker_state.cpp, perception/tracking_object_merger/src/utils/utils.cpp
Radar遠距離Tracking関連のPRを使えるようにするためのPRその②です。その①はこちら：https://github.com/tier4/autoware.universe/pull/949
デフォルトは塩尻と同じdetectionでradar objectのmergeをしようとしています。
Related PR in awf
- autoware_launch: https://github.com/autowarefoundation/autoware_launch/pull/627
- tracking object merger: https://github.com/autowarefoundation/autoware.universe/pull/4340
- launcher merger: https://github.com/autowarefoundation/autoware.universe/pull/5269
デグレチェックでPredictionが出せるか確認します。
radarとlidar objectのmergerで失敗。多分timestampが大きく違いすぎるため。
|radar vs lidar timestamp| diff of timestamp|
|--|--|
| ![image](https://github.com/tier4/autoware.universe/assets/20086766/4a5e9541-dbba-4a0f-b456-ca8e480397f2)|![image](https://github.com/tier4/autoware.universe/assets/20086766/1a649aac-f4c3-42ba-bd25-d02b3fcd590e)|
The PR author …
=> feat(tracking_object_merger): add radar far object tracking and its merger into perception flow

control/mpc_lateral_controller/src/mpc.cpp
Hotfix to beta/v0.10.3
https://github.com/autowarefoundation/autoware.universe/pull/5320
(TIERIV INTERNAL LINK https://star4.slack.com/archives/C03QW0GU6P7/p1697445979466779 )
> （MPCの修正：これがないとフィルターに常に引っかかるが、走行挙動には変化なし）
none
none
MPCが制限値を超えてステア出力されてしまう挙動が修正される　
=> fix(mpc): change the way to calculate target steering rate

planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/5325
Psim
Fix an issue with the drivable area expansion, prevents crashes due to out of bound vector index.
=> fix(drivable_area_expansion): correct bound limit check (#5325)

common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml, planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/src/marker_utils/utils.cpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp, planning/behavior_path_planner/test/test_safety_check.cpp
LC改善のcherry-picks
This PR should be tested with https://github.com/tier4/autoware_launch.x2/tree/lc-update-20231013 branch which contains 
- https://github.com/tier4/autoware_launch.x2/pull/493
- https://github.com/tier4/autoware_launch.x2/pull/495
https://tier4.atlassian.net/wiki/spaces/~793737791/pages/2909798824/LC#%E5%AE%A4%E5%B2%A1%E3%81%8F%E3%82%93%E3%81%8B%E3%82%89%E3%81%AE%E8%A6%81%E6%B1%82
https://github.com/tier4/autoware.universe/assets/21360593/6d697630-7ca4-4c7b-86fb-def110422ed4
After all checkboxes are checked, anyone who has write access can merge the …
=> feat(lane_change): cherry-pick LC PRs

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
https://star4.slack.com/archives/C03QW0GU6P7/p1697507171534699
This reverts commit 9b10ca9f3524dea8b96850e6a767a7aab16163e2.
The commit makes the avoidance cancelled while performing it, making the vehicle executes a very dangerous trajectory.
Tested on PSim that now the avoidance is enabled
Now the avoidance is enabled, while some issues that has been addressed with #936 may arise again.
[pull request …
=> feat: revert "feat(avoidance): add feature to guard unfeasible path"

control/mpc_lateral_controller/include/mpc_lateral_controller/mpc.hpp, control/mpc_lateral_controller/src/mpc.cpp
mpcのステアレート制約を線形補間で適用する（https://github.com/autowarefoundation/autoware.universe/pull/4666）
=> feat(mpc): 1d interpolate in steering rate limit calculation

control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
- Cherry-picks https://github.com/autowarefoundation/autoware.universe/pull/5250
- To resolve https://tier4.atlassian.net/browse/RT0-29417
Please see the original PR
Please see the original PR
=> fix(vehicle_cmd_gate): fix filtering condition (#5250)

control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
ずり下がり防止対応のうちの1つ
https://tier4.atlassian.net/browse/RT0-28971
https://tier4.atlassian.net/browse/RT0-29231
DRIVEの状態で停止しきらずにずり下がると永遠にSTOPPEDへ移行できない不具合修正
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5255
=> feat(pid_longitudinal_controller): transit to STOPPED even if the sign of the ego velocity goes opposite

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5345
=> feat(intersection): suppress pass judge sudden stop

sensing/imu_corrector/README.md, sensing/imu_corrector/config/gyro_bias_estimator.param.yaml, sensing/imu_corrector/launch/gyro_bias_estimator.launch.xml, sensing/imu_corrector/src/gyro_bias_estimation_module.cpp, sensing/imu_corrector/src/gyro_bias_estimation_module.hpp, sensing/imu_corrector/src/gyro_bias_estimator.cpp, sensing/imu_corrector/src/gyro_bias_estimator.hpp, sensing/imu_corrector/test/test_gyro_bias_estimation_module.cpp
Cherry-picks https://github.com/autowarefoundation/autoware.universe/pull/5259
Should be merged with:
- https://github.com/tier4/autoware.universe/pull/956
=> feat(imu_corrector): changed GyroBiasEstimator to use ndt pose instead of twist

perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/map_based_prediction/src/map_based_prediction_node.cpp
cherry pick of https://github.com/autowarefoundation/autoware.universe/pull/5356
チケット
https://tier4.atlassian.net/browse/RT0-29527
フェンス内で走り回る幼稚園児に対してcrosswalkを通過＆fenceを横切るpredicted pathを生成するため、弾く処理を追加。
チケット内でmerge前後の挙動が変わっていることを確認しているため要参照。
先にautoware_commonの[変更](https://github.com/autowarefoundation/autoware_common/pull/209)取り込みも必要。 …
=> feat(map_based_prediction): remove crossing fence path (#5356)

common/autoware_auto_geometry/CMakeLists.txt, common/autoware_auto_tf2/CMakeLists.txt, common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp, planning/behavior_path_planner/CMakeLists.txt, planning/surround_obstacle_checker/CMakeLists.txt
Incorporated this to avoid build error due to humble-sync.
- https://github.com/autowarefoundation/autoware.universe/pull/5127
=> chore: add workaround for tf2 update (#5127)

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
https://github.com/autowarefoundation/autoware.universe/pull/5243
https://github.com/autowarefoundation/autoware.universe/pull/5264
https://github.com/autowarefoundation/autoware.universe/pull/5280
https://github.com/autowarefoundation/autoware.universe/pull/5304
https://github.com/autowarefoundation/autoware.universe/pull/5332
https://github.com/autowarefoundation/autoware.universe/pull/5353
のうち https://github.com/autowarefoundation/autoware.universe/pull/5353 （本PRのintersectionのスタック防止に関わる）以外についてはコードやデータ構造の変更だけ残して機能面の変更は削除
feature PR: https://github.com/tier4/autoware_launch.xx1/pull/678
The PR author **must** check the checkboxes below before …
=> feat(intersection): timeout static occlusion with traffic light

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml
As described in awf PR https://github.com/autowarefoundation/autoware.universe/pull/5313, this PR aiming to turn off detection_by_tracker to lower computation burden in X2 sihojiri.
Set `use_detection_by_tracker` to false if you want skip the process/
Check node diagram in Lsim.
Discussed in [Ticket](https://tier4.atlassian.net/browse/RT0-29473?focusedCommentId=141703&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-141703). …
=> feat(tier4_perception_launch): make switchable detection by tracker in x2 project

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/drivable_area_expansion.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/map_utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/types.hpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/map_utils.cpp
This PR improves the performance of the two heaviest function of the dynamic drivable area expansion feature.
AWF PR: https://github.com/autowarefoundation/autoware.universe/pull/5349
Psim
Evaluator: https://evaluation.tier4.jp/evaluation/reports/fe916395-fa5c-5497-a3e4-612d519cb149?project_id=x2_dev
The runtime of the `behavior_path_planner` should be greatly reduced when using the dynamic drivable area expansion.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/c …
=> perf(drivable area expansion): use faster lateral offset and nearest line calculations

system/system_error_monitor/src/system_error_monitor_core.cpp
問題としては、初期化中に処理負荷が高い処理が実行中に
isDataHeartbeatTimeout()でemとなる現象が発現する。
そのため、
初期化中のheart_beattimeoutを無効化する。
無効化処理時が発生しているかを解析者にlogとして残るように、logも追加する。
[INTERNA  slack LINK](https://star4.slack.com/archives/C04CKSQ7ZFZ/p1697706212101009)
[INTERNAL Ticket LINK](https://tier4.atlassian.net/browse/AEAP-790)
初期化中のheart_beattimeoutを無効化する。
=>
変更前には …
=> feat(system_error_monitor): add ignore hartbeat timeout in initializing state

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_radar_based_detection.launch.xml
<s>**Merge前に要相談**</s> DONE. Ready to merge.
- 参考URL
- [JIRA チケット](https://tier4.atlassian.net/browse/RT1-4144)
- [10/18試験結果](https://docs.google.com/presentation/d/1VTZyhELVqYNhQEuxYmnB7YrDoqMbCJoBrOY9CrZzopA/edit#slide=id.g29150911371_1_27)
ars408のradarのdetectionを矯正するPRになります。
- **解決したい課題**
- お台場や柏でradarのdetectionが単一のobjから複数出現することが後段のtrackingに悪影響を及ぼすことがわかっています
- radar clusteringというノードにはこのクラスタリングの閾値があります。（距離・角度・速度）
- 現状角度の閾値がかなり厳しく、そのせいでOverlapするほどBBOXが接近していても別Objとして出力されています（BBOXが重なった物体同士の距離と角度差を以下のスライドで可視化しました）
- この角度の閾値を30deg=0.52付近まであげればBBOXが重なるレベルのdetectionを統合することができます
- 想定される動作とデグレ
- radarから出てくる速度と位置と姿勢が近いdetectionを統合するようになります
- デグレの可能性として2台の車が隣り合って走っている場合に1台のObjにまとめられてしまう可能性はあります。
上記のデメリットを考慮しても交差点モジュールに導入可能か @soblin  に要相談。
（補足）Trackingへの悪影響
- …
=> feat(tier4_perecption_launch): change radar object clustering parameter for ars408 in xx1

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/utils/utils.cpp
* fix(lane_change): fix terminal stop distance
* make current lanes include path front id
* fixup! make current lanes include path front id
---------
cherry-pick
https://github.com/autowarefoundation/autoware.universe/pull/5392
https://github.com/autowarefoundation/autoware.universe/pull/5406
停止位置がゴールに近づくと変わる問題を修正
https://tier4.atlassian.net/browse/RT0-29586 …
=> fix(lane_change): fix terminal stop distance (#5392)

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
fix(lane_change): filter objects for skip parking objects [#5419](https://github.com/autowarefoundation/autoware.universe/pull/5419)
=> fix(lane_change): filter objects for skip parking objects 

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/utils.cpp
fix(lane_change): separate backward buffer for blocking object
https://github.com/autowarefoundation/autoware.universe/pull/5434
launch PR:
https://github.com/tier4/autoware_launch.x2/pull/535
=> fix(lane_change): separate backward buffer for blocking object

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5405
https://tier4.atlassian.net/browse/RT0-29604
=> feat(avoidance): add use_conservative_buffer_longitudinal

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
取り込み元
- https://github.com/autowarefoundation/autoware.universe/pull/5096
- https://github.com/autowarefoundation/autoware.universe/pull/5304
対応するlauncher PR: https://github.com/tier4/autoware_launch.xx1/pull/688
LSIM結果は
https://github.com/tier4/autoware_launch.xx1/pull/688
に貼った動画を参照
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-gui …
=> feat(intersection): 信号連携周りの改善

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml, perception/detected_object_validation/config/obstacle_pointcloud_based_validator.param.yaml, perception/detected_object_validation/include/obstacle_pointcloud_based_validator/obstacle_pointcloud_based_validator.hpp, perception/detected_object_validation/launch/obstacle_pointcloud_based_validator.launch.xml, perception/detected_object_validation/src/obstacle_pointcloud_based_validator.cpp, perception/image_projection_based_fusion/docs/roi-cluster-fusion.md, perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_cluster_fusion/node.hpp, perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml, perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
- cherry-pick of https://github.com/autowarefoundation/autoware.universe/pull/5177 and https://github.com/autowarefoundation/autoware.universe/pull/5148. 
- We need to merge https://github.com/tier4/autoware_launch.xx1/pull/680 and https://github.com/tier4/autoware_launch.xx1/pull/681 with this PR. …
=> feat(perception): add iou x and change the points_num of the validator

launch/tier4_perception_launch/launch/perception.launch.xml
先ほど確認したところ、TrackingでFusionしたいのでこの変更が抜けてました :bow: 
当日手入力で変更するのでもOKです。
=> chore(tier4_perception_launch): use tracking fusion for far radar detection

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- レーンチェンジに必要な距離を保って停止する位置にwallを表示する機能追加
- https://github.com/autowarefoundation/autoware.universe/pull/4808
- abort時にpathをカットしないようにする修正
- https://github.com/autowarefoundation/autoware.universe/pull/5509
=> fix(lane_change): do not cut abort path

localization/ndt_scan_matcher/include/ndt_scan_matcher/map_update_module.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp, localization/ndt_scan_matcher/src/map_update_module.cpp, localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
As a result of verification, the following error occurred within the timer_diagnostics function, causing the node to crash. 
Therefore, to make it thread-safe, we decided to remove the thread processing.
Furthermore, to ensure thread safety, I've made sure that functions other than callback_sensor_points do not access `state_ptr_`.
N/A
LSim works.
We plan to make significant improvements to the diagnostics of the ndt_scan_matcher in the near future.
https://github.com/autowarefoundation/autoware.universe/pull/5076
N/A
N/A
After all checkboxes are checked, anyone who has write access …
=> fix(ndt_scan_matcher): delete diagnostics thread (#5532)

planning/behavior_path_planner/src/utils/avoidance/utils.cpp
Cherry Pick PR: https://github.com/autowarefoundation/autoware.universe/pull/5388
Related Link: https://tier4.atlassian.net/browse/RT1-4243
Psim
Fix bug.
=> fix(avoidance): discard envelope polygon if the objects move long distance (#5388)

planning/route_handler/src/route_handler.cpp
重複点削除のしきい値を0.1m（10cm）に変更する
修正経緯については、https://tier4.atlassian.net/browse/AEAP-816 のEvidence、解析結果を参照のこと
- https://star4.slack.com/archives/C017JDNQCMV/p1699947638325929?thread_ts=1699921891.695269&cid=C017JDNQCMV
- https://tier4.atlassian.net/browse/AEAP-816
https://tier4.atlassian.net/browse/AEAP-816 の確認事項を参照のこと
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/c …
=> fix(route_handler): fix threshold for removing overlapping points

planning/behavior_velocity_intersection_module/README.md, planning/behavior_velocity_intersection_module/docs/data-structure.drawio.svg, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/util.hpp, planning/behavior_velocity_planner_common/src/utilization/util.cpp
計算時間の改善
- https://github.com/autowarefoundation/autoware.universe/pull/5507
- https://github.com/autowarefoundation/autoware.universe/pull/5516
pass_judge（ある程度交差点に入ったらそのまま進む位置）の改善
- https://github.com/autowarefoundation/autoware.universe/pull/5547
=> feat(intersection): reduce calculation and improve pass judge

perception/image_projection_based_fusion/src/pointpainting_fusion/voxel_generator.cpp
Hotfix to beta/v0.10.5
https://github.com/autowarefoundation/autoware.universe/pull/5603
improve the calculation time in image_projecttion_based_fusion (= pointpainting )
=> perf(image_projection_based_fusion): replace std::bitset

launch/tier4_system_launch/launch/system.launch.xml, system/duplicated_node_checker/CMakeLists.txt, system/duplicated_node_checker/README.md, system/duplicated_node_checker/config/duplicated_node_checker.param.yaml, system/duplicated_node_checker/include/duplicated_node_checker/duplicated_node_checker_core.hpp, system/duplicated_node_checker/launch/duplicated_node_checker.launch.xml, system/duplicated_node_checker/package.xml, system/duplicated_node_checker/schema/duplicated_node_checker.schema.json, system/duplicated_node_checker/src/duplicated_node_checker_core.cpp, system/system_error_monitor/config/diagnostic_aggregator/system.param.yaml, system/system_error_monitor/config/system_error_monitor.param.yaml, system/system_error_monitor/config/system_error_monitor.planning_simulation.param.yaml
Chrry-pick duplicated node checker
- https://github.com/autowarefoundation/autoware.universe/pull/5286
- https://github.com/autowarefoundation/autoware.universe/pull/5382
Test both Lsim and Psim
=> feat(duplicated_node_checker): add new package

planning/external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp, planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/5555
=> feat(motion_velocity_smoother): add motion_velocity_smoother's virtual wall

common/autoware_auto_perception_rviz_plugin/include/object_detection/predicted_objects_display.hpp, common/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp
cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/5418
=> refactor(perception_rviz_plugin): apply thread pool to manage detached thread

simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5563 backport
simulatorの手動モード時のギア初期値をDRIVEからPARKに変更する
https://tier4.atlassian.net/browse/RT0-29756
https://tier4.atlassian.net/browse/RT0-29756 のチケットの確認結果に記載した
=> fix(simple_planning_simulator): change default value of manual gear, DRIVE -> PARK (backport #5563)

simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5501 のbackport
- ロジックのリファクタリング
- `enable_road_slope_simulation_` がtrueのときのみ `calculate_ego_pitch()` を計算するように修正する
https://tier4.atlassian.net/browse/RT0-29756
- ロジックとして最終的な結果に違いないことを目視で確認した
=> fix(simple_planning_simulator): set ego pitch to 0 if road slope is not simulated (#5501)

planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/util.hpp, planning/behavior_velocity_planner_common/src/utilization/util.cpp
Intersectionの処理時間を改善する
https://github.com/autowarefoundation/autoware.universe/pull/5507
https://github.com/autowarefoundation/autoware.universe/pull/5516
[beta/v0.10.5へマージ済み](https://github.com/tier4/autoware.universe/pull/1018)
[関連チケット](https://tier4.atlassian.net/browse/RT0-29846?focusedCommentId=146585&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-146585)
問題が発生した地図を使って、PSIMで回して見たら、intersection/processing_time_msが800msから10msまで減りました。
N/A
N/A
N/A
[contribution …
=> fix(intersection): reduce processing time and fix wrong resample process

simulator/simple_planning_simulator/README.md, simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5616 のbackport
https://tier4.atlassian.net/browse/RT0-29756
- 変更内容に問題ないことを目視で確認した
=> fix(simple_planning_simulator): fix ego sign pitch problem (#5616)

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml, perception/detection_by_tracker/CMakeLists.txt, perception/detection_by_tracker/config/detection_by_tracker.param.yaml, perception/detection_by_tracker/include/detection_by_tracker/detection_by_tracker_core.hpp, perception/detection_by_tracker/include/utils/utils.hpp, perception/detection_by_tracker/launch/detection_by_tracker.launch.xml, perception/detection_by_tracker/src/detection_by_tracker_core.cpp, perception/detection_by_tracker/src/utils.cpp
Hotfix https://github.com/autowarefoundation/autoware.universe/pull/5473 to beta/v0.11.1
* fix(detection_by_tracker): add ignore for each class
* fix: launch
---------
塩尻と小松では、Detection_by_trackerは車に対してOff、歩行者に対してOnにした方が検知結果はより安定になる傾向であるので、各のクラスをOn/Off機能を追加。
関係チケット：
https://tier4.atlassian.net/browse/RT0-29682
https://tier4.atlassian.net/browse/RT0-29721
[pull request …
=> fix(detection_by_tracker): add ignore option for each label

common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
Fix autoware_auto_tf2 package build for beta/v0.9.1
Related to https://github.com/autowarefoundation/autoware.universe/pull/5089
=> fix(autoware_auto_tf2): remove tf2 geometry function duplicated in tf2 geometry msgs (#5089)

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
cherry pick from https://github.com/autowarefoundation/autoware.universe/pull/5402
=> fix(lane_change): stop point activated too early

perception/image_projection_based_fusion/include/image_projection_based_fusion/pointpainting_fusion/pointpainting_trt.hpp, perception/image_projection_based_fusion/include/image_projection_based_fusion/pointpainting_fusion/preprocess_kernel.hpp, perception/image_projection_based_fusion/include/image_projection_based_fusion/pointpainting_fusion/voxel_generator.hpp, perception/image_projection_based_fusion/src/pointpainting_fusion/pointpainting_trt.cpp, perception/image_projection_based_fusion/src/pointpainting_fusion/preprocess_kernel.cu, perception/image_projection_based_fusion/src/pointpainting_fusion/voxel_generator.cpp, perception/lidar_centerpoint/include/lidar_centerpoint/centerpoint_trt.hpp, perception/lidar_centerpoint/include/lidar_centerpoint/network/scatter_kernel.hpp, perception/lidar_centerpoint/include/lidar_centerpoint/preprocess/preprocess_kernel.hpp, perception/lidar_centerpoint/include/lidar_centerpoint/preprocess/voxel_generator.hpp, perception/lidar_centerpoint/lib/centerpoint_trt.cpp, perception/lidar_centerpoint/lib/network/scatter_kernel.cu, perception/lidar_centerpoint/lib/preprocess/preprocess_kernel.cu, perception/lidar_centerpoint/lib/preprocess/voxel_generator.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5681
Hotfix to beta/v0.10.**6**
> This pull request refactors and optimizes the code for the pointpainting fusion and centerpoint algorithms for 3D object detection. It introduces new CUDA functions and kernels for voxel generation and feature extraction, and improves the memory management and performance of the existing ones. It also renames and modifies some functions and classes to better reflect their functionality and simplify their interface. The main files affected are pointpainting_trt.hpp, preprocess_kernel.cu, voxel_generator.cpp, and centerpoint_trt.cpp.
https://github.com/autowarefoundation/autoware.universe/pull/5681/
> I've tested with rosbag and standalone launch file.
I've confirmed the pre-processing time …
=> perf(image_projection_based_fusion,lidar_centerpoint): add cuda preprocess

planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp, planning/rtc_interface/include/rtc_interface/rtc_interface.hpp, planning/rtc_interface/src/rtc_interface.cpp
Cherry-pick for
https://github.com/autowarefoundation/autoware.universe/pull/4420
https://github.com/autowarefoundation/autoware.universe/pull/5697
関連チケット
https://tier4.atlassian.net/browse/RT1-4037
=> fix(behavior_velocity_planner_common): sync activation when safety status is set

perception/shape_estimation/include/shape_estimation/corrector/truck_corrector.hpp, perception/shape_estimation/lib/filter/truck_filter.cpp
detection_by_trackerやroi_cluster_fusionで使われるshape fittingにおいてトラックのサイズの制限が現実より大分厳しかったので法令を確認して修正しました。
大きなトラックの検出が今まで一部検出対象外になっていたのを直したので上記の関連手法におけるの出力が少し改善されるはずです。
From awf: https://github.com/autowarefoundation/autoware.universe/pull/5650
お台場データで修正。
=> feat(shape_estimation): fix truck filter max size is too small problem

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/config/avoidance_by_lc/avoidance_by_lc.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/5699
Related Ticket: https://tier4.atlassian.net/browse/RT1-4126
=> feat(avoidance): configurable object type for safety check (#5699)

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5693 のhotfix
=> feat(intersection): ignore occlusion on amber color too (#5693)

planning/behavior_velocity_out_of_lane_module/src/overlapping_range.hpp, planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp, planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.hpp
Improve the reuse of the previous decision in the `out_of_lane` module, avoiding bugs when the path changes suddenly.
Universe PR: https://github.com/autowarefoundation/autoware.universe/pull/5611
Psim.
Evaluator (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/5acb952b-1060-56b1-a8b4-18b1254312fb?project_id=x2_dev …
=> feat(out_of_lane): improve reuse of previous decision

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
Incorporate improvement of intersection.
- https://github.com/autowarefoundation/autoware.universe/pull/5394
Related link
[TIER IV INTERNAL](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2945384668/2023-11-09+v2.3.1)
Tested on an actual vehicle.
=> feat(intersection): check path margin for overshoot vehicles on red light (#5394)

planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/route_handler/include/route_handler/route_handler.hpp
fix https://tier4.atlassian.net/browse/RT1-4453
psim on beta/v0.43.6.0
=> fix(avoidance): include shoulder lane to avoid (#5750)

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/5489
Related Ticket: https://tier4.atlassian.net/browse/RT1-4125
Attempt1.
https://github.com/tier4/autoware.universe/assets/44889564/90338580-93f0-41bb-a2b9-a9b7d7d68479
Attempt2.
https://github.com/tier4/autoware.universe/assets/44889564/8d09c0d4-666e-483f-82ff-ca76c252468a …
=> fix(avoidance): fix avoidance return dead point calculation logic for high curverture path (#5489)

perception/image_projection_based_fusion/include/image_projection_based_fusion/pointpainting_fusion/preprocess_kernel.hpp, perception/image_projection_based_fusion/src/pointpainting_fusion/pointpainting_trt.cpp, perception/image_projection_based_fusion/src/pointpainting_fusion/preprocess_kernel.cu, perception/lidar_centerpoint/include/lidar_centerpoint/preprocess/preprocess_kernel.hpp, perception/lidar_centerpoint/lib/centerpoint_trt.cpp, perception/lidar_centerpoint/lib/preprocess/preprocess_kernel.cu
cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/5824
=> fix(lidar_centerpoint,image_projection_based_fusion): add guard to avoid exceeding max voxel size 

planning/obstacle_stop_planner/README.md, planning/obstacle_stop_planner/config/obstacle_stop_planner.param.yaml, planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp, planning/obstacle_stop_planner/src/debug_marker.cpp, planning/obstacle_stop_planner/src/node.cpp
このPRはv0.3.17リリース向けに開発していたもののドロップしたPR https://github.com/tier4/autoware.universe/pull/733 を、v0.3.18リリース向けに適用し直すためのPRです。
本PRは下記問題を対策する。
- 問題A
- 経路上の障害物を検知した状態で自車両に対して前後方向に検知位置が振動する挙動があり、これにあわせて車両が停車と発車を交互に繰り返す（チャタリングする）。
- 音声発話として、停車と発車も繰り返す
- 問題B
- 経路上に複数の障害物を検知した場合、停止線が異常な位置に設定される
- 対策１
- 問題Aの対策として、障害物検知による停車時に一定時間その停止計画を維持するようにする事で、検知した障害物が移動した場合でも一定時間停止計画を維持する。
これにより、障害物の移動によるチャタリングを回避する。 
- 停止状態を維持する時間は、`chattering_threshold`で設定する。(defalut : 0.5s)
- 本機能は下記の流用である。
- https://github.com/autowarefoundation/autoware.universe/pull/1458
- https://github.com/autowarefoundation/autoware.universe/pull/1627
- 対策２
- 問題Bを対策する。
- 本機能は下記の流用である。
- https://github.com/autowarefoundation/autoware.universe/pull/2647
- 対策３
- 問題Aの追加対策として、対策1の適応範囲を停車時のみとする。
- …
=> feat(obstacle_stop): upd obstacle hunting

map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
(cherry-pick)display curbstone as marker array
original PR: https://github.com/autowarefoundation/autoware.universe/pull/4958
Issue: https://tier4.atlassian.net/browse/RT0-29081
curbstone(縁石)がrvizに表示されていないため、実車実験やpsimで車両がcurbstoneにどれぐらい近づいているか把握できない。対策としてMarkerArrayを追加し、curbstoneをrvizで表示する。
https://tier4.atlassian.net/browse/RT0-29081
藍色の線でcurbstoneが表示される。 …
=> feat(map_loader): display curbstone as marker array (#4958)

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_avoidance_module/src/shift_line_generator.cpp, planning/behavior_path_avoidance_module/src/utils.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/traffic_light_utils.hpp, planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp, planning/behavior_path_planner_common/src/utils/traffic_light_utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6006
- https://github.com/autowarefoundation/autoware.universe/pull/6016
- https://github.com/autowarefoundation/autoware.universe/pull/6017
=> fix(avoidance): cherry pick

common/interpolation/include/interpolation/spherical_linear_interpolation.hpp, common/interpolation/src/spherical_linear_interpolation.cpp, common/motion_utils/include/motion_utils/trajectory/conversion.hpp, control/pid_longitudinal_controller/include/pid_longitudinal_controller/longitudinal_controller_utils.hpp, control/pid_longitudinal_controller/src/longitudinal_controller_utils.cpp, control/pid_longitudinal_controller/test/test_longitudinal_controller_utils.cpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_utils.hpp, planning/behavior_path_planner_common/src/utils/path_utils.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/trajectory_utils.hpp, planning/behavior_velocity_planner_common/src/utilization/trajectory_utils.cpp, planning/planning_test_utils/include/planning_test_utils/planning_interface_test_manager_utils.hpp, planning/planning_test_utils/package.xml, planning/planning_test_utils/src/planning_interface_test_manager.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5909
=> refactor(motion_utils): cherry picked from a merged PR

planning/behavior_path_lane_change_module/src/interface.cpp
cherry pick lane change
Before abort process, lane change module should check if ego vehicle can return to original lane or not. And if it can't, abort path should not be computed.
This is a critical fix. Without this fix, ego will perform unwanted abort and it can be quite dangerous.
https://github.com/autowarefoundation/autoware.universe/pull/6034
[pull request …
=> fix(lane_change): check able to return to current lane

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp
=> feat(intersection): cherry pick awf #6036, #6042, #6050

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
* change params
* change the TTC formula
https://github.com/autowarefoundation/autoware.universe/pull/6033
=> feat(crosswalk): change the TTC formula

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml
…age projection fusion (#6075)
re-organize the parameters for image projection fusion
- Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6075
- Need to merge together with https://github.com/tier4/autoware_launch.x2/pull/568
https://tier4.atlassian.net/browse/RT1-4990 …
=> fix(image_projection_based_fusion): re-organize the parameters for image projection fusion (autowarefoundation#6075)

launch/tier4_planning_launch/launch/planning.launch.xml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving.launch.xml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml, launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml, planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_manager_interface.hpp, planning/behavior_velocity_blind_spot_module/src/manager.cpp, planning/behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_detection_area_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_no_stopping_area_module/src/manager.cpp, planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp, planning/behavior_velocity_traffic_light_module/src/manager.cpp
https://github.com/autowarefoundation/autoware.universe/pull/6093
https://github.com/autowarefoundation/autoware.universe/pull/6094
auto_mode is controlled by parameter of enable_rtc
(Related PR: https://github.com/tier4/autoware_launch.xx1/pull/747 )
See https://github.com/tier4/autoware_launch.xx1/pull/747 (TIERIV Internal Link)
Not applicable (no effects when using default parameters).
[pull request …
=> feat: add enable_all_modules_auto_mode argument to launch files for behavior modules

planning/behavior_path_dynamic_avoidance_module/src/scene.cpp, planning/behavior_path_goal_planner_module/README.md, planning/behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_parameters.hpp, planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher.hpp, planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher_base.hpp, planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_goal_planner_module/src/goal_searcher.cpp, planning/behavior_path_goal_planner_module/src/manager.cpp, planning/behavior_path_goal_planner_module/src/util.cpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
Update behavior path panner for v0.20.1
especially goal planner
https://evaluation.tier4.jp/evaluation/reports/76a00e0e-855d-5e39-8af4-21c6f383b007?project_id=prd_jt
none
none
=> feat(behavior_path_planner): update behavior path panner for v0.20.1

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_avoidance_module/config/avoidance.param.yaml, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/data_manager.hpp, planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/static_drivable_area.hpp, planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6001
- https://github.com/autowarefoundation/autoware.universe/pull/6172 (necessary for chery pick without conflicts)
=> fix(avoidance): cherry pick new feature

planning/behavior_path_avoidance_module/src/debug.cpp, planning/behavior_path_avoidance_module/src/utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6206
Related link: https://tier4.atlassian.net/browse/RT1-5044
=> fix(avoidance): update filtering logic for non-vehicle (#6206)

sensing/imu_corrector/README.md, sensing/imu_corrector/config/gyro_bias_estimator.param.yaml, sensing/imu_corrector/src/gyro_bias_estimator.cpp, sensing/imu_corrector/src/gyro_bias_estimator.hpp
Make the diagnostics publication from gyro_bias_estiamator constant.
The default period is 0.5 seconds.
You can change this in `gyro_bias_estimator.param.yaml` but note that the period will be `min(timer_callback_interval_sec, diagnostics_updater_interval_sec)`.
Cherry-pick from the autowarefoundation/autoware.universe #6139
I've test this code via [rosbag replay simulation tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/).
`/diagnostics` from gyro_bias_estimator should be more periodical than before
The content of the `/diagnostics` will be changed as mentioned in #6139 …
=> feat(imu_corrector): cherry pick diagnostics modification in gyro_bias_estimatior from awf

planning/behavior_velocity_traffic_light_module/README.md, planning/behavior_velocity_traffic_light_module/config/traffic_light.param.yaml, planning/behavior_velocity_traffic_light_module/src/manager.cpp, planning/behavior_velocity_traffic_light_module/src/scene.cpp, planning/behavior_velocity_traffic_light_module/src/scene.hpp
Incorporate this commit to stop when the traffic signal is timed out.
- https://github.com/autowarefoundation/autoware.universe/pull/5819
PSim
- Red signal: Stop line is inserted
- No information: Stop line is inserted
- Green signal: Stop line is not inserted
https://github.com/tier4/autoware.universe/assets/11865769/a818c091-840e-48d5-a2e7-422fe0f548bf …
=> fix(traffic_light): stop if the traffic light signal timed out (#5819)

control/mpc_lateral_controller/include/mpc_lateral_controller/qp_solver/qp_solver_interface.hpp, control/mpc_lateral_controller/include/mpc_lateral_controller/qp_solver/qp_solver_osqp.hpp, control/mpc_lateral_controller/include/mpc_lateral_controller/qp_solver/qp_solver_unconstraint_fast.hpp, control/mpc_lateral_controller/src/mpc.cpp
cherry-pick this PR to save the OSQP debug information
- https://github.com/autowarefoundation/autoware.universe/pull/5459
- https://tier4.atlassian.net/browse/RT0-30353
Confirmed debug value of 18, 19, 20 is published.
=> refactor(mpc_lateral_controller): add debug info of qp solver (#5459)

perception/tracking_object_merger/config/data_association_matrix.param.yaml, perception/tracking_object_merger/src/utils/utils.cpp
cherry-pick 
- https://github.com/autowarefoundation/autoware.universe/pull/6182
https://star4.slack.com/archives/C03QU7K50D8/p1706685403389279
=> fix(tracking_object_merger): enable to association unknown class in tracker merger #6182

planning/behavior_path_avoidance_module/src/utils.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6285
=> fix(avoidance): don't use polygon centroid in shiftable ratio calculation (#6285)

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_start_planner_module/src/start_planner_module.cpp
=> fix(goal_planner): fix multithread and magin

planning/behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_start_planner_module/README.md, planning/behavior_path_start_planner_module/config/start_planner.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/6353
=> feat(goal_planner): cherry pick 

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp, control/autonomous_emergency_braking/package.xml, control/autonomous_emergency_braking/src/node.cpp
https://github.com/autowarefoundation/autoware.universe/pull/6346
=> fix(AEB): check pick awf #6346

planning/behavior_velocity_out_of_lane_module/src/footprint.cpp, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.hpp, planning/behavior_velocity_out_of_lane_module/src/overlapping_range.cpp, planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
Cherry-pick https://github.com/autowarefoundation/autoware.universe/pull/6334
- https://tier4.atlassian.net/browse/RT1-4533
- https://tier4.atlassian.net/browse/RT1-4534
Evaluator: https://evaluation.tier4.jp/evaluation/reports/9762ef84-5c89-5f73-8571-4f4e141a359e?project_id=prd_jt
None
`out_of_lane` module causes less stops. …
=> fix(out_of_lane): ignore overlaps over all lanelets crossed by the ego path

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/path.hpp, planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_lane_change_module/src/utils/utils.cpp
Cherry-pick
- https://github.com/autowarefoundation/autoware.universe/pull/6088
- https://github.com/autowarefoundation/autoware.universe/pull/6175
- https://github.com/autowarefoundation/autoware.universe/pull/6176
- https://github.com/autowarefoundation/autoware.universe/pull/6234
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guid …
=> feat(lane_change): terminal lane change and abort behavior

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp, planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp, planning/behavior_path_avoidance_module/src/debug.cpp, planning/behavior_path_avoidance_module/src/scene.cpp, planning/behavior_path_avoidance_module/src/shift_line_generator.cpp, planning/behavior_path_avoidance_module/src/utils.cpp
* fix(avoidance): check safety for only moving objects
* feat(avoidance): consider ignore object in avoid margin calculation
* fix(avoidance): use nearest overhang point
---------
Related ticket: https://tier4.atlassian.net/browse/RT1-4740
- https://github.com/autowarefoundation/autoware.universe/pull/6252 …
=> feat(avoidance): consider objects on shift side lane (#6252)
